#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from tools.accountability.soil._accountability_common import *

def main(argv=None):
 a=argparse.ArgumentParser()
 for n in ['assurance-root','registry-root','certification-root','archive-root','preservation-root','reconciliation-root','federation-root','discovery-root','published-root','ops-root','out-root','base-public-url']: a.add_argument('--'+n,required=True)
 a.add_argument('--assurance-id'); a.add_argument('--accountability-id'); x=a.parse_args(argv)
 aid=x.assurance_id or load_current_assurance(x.assurance_root)['active_assurance_id']; am=load_assurance_manifest(x.assurance_root,aid); ar=load_assurance_receipt(x.assurance_root,aid)
 if am.get('assurance_status')!='CONTINUOUS_ASSURANCE_READY': print(json.dumps({'accountability_allowed':False,'assurance_id':aid,'release_id':am.get('release_id'),'reasons':['assurance not ready']},sort_keys=True)); return 1
 entries=load_accountability_items(x.out_root,aid); ah=[stable_payload_hash(e) for e in sorted(entries,key=lambda z:stable_payload_hash(z))]
 acct=x.accountability_id or 'soil-accountability-'+stable_payload_hash({'a':aid,'h':ah})[:16]
 cyc=Path(x.out_root)/f'accountability/soil/cycles/{acct}'; cyc.mkdir(parents=True,exist_ok=True)
 m={'schema_version':'kfm.v1','object_type':'SoilPublicAccountabilityManifest','domain':'soil','accountability_id':acct,'assurance_id':aid,'registry_id':am['registry_id'],'certification_id':load_current_certification(x.certification_root)['active_certification_id'],'archive_package_id':load_current_archive_package(x.archive_root)['active_archive_package_id'],'preservation_id':load_current_preservation(x.preservation_root)['active_preservation_id'],'reconciliation_id':load_current_reconciliation(x.reconciliation_root)['active_reconciliation_id'],'federation_id':load_current_federation(x.federation_root)['active_federation_id'],'discovery_id':load_current_discovery(x.discovery_root)['active_discovery_id'],'release_id':am['release_id'],'publication_status':'PUBLISHED','trust_registry_status':'TRUST_REGISTRY_READY','assurance_status':'CONTINUOUS_ASSURANCE_READY','accountability_status':'PUBLIC_ACCOUNTABILITY_READY','accountability_state':'pass','certificate_status':'active','created':utc_now_iso(),'base_public_url':x.base_public_url,'accountability_scope':['KFM deterministic public accountability','Offline feedback, challenge, correction, and dispute intake','Public submissions are not truth sources'],'records':sorted(am.get('records',[]),key=lambda r:r.get('bundle_id','')),'truth_policy':{'observational_data_bound':True,'public_feedback_is_truth_source':False,'public_challenge_is_truth_source':False,'ai_interpretive_only':True,'model_output_is_truth_source':False}}
 write_json_atomic(cyc/'accountability_manifest.json',m)
 for fn,obj in [('public_feedback_registry.json',{'schema_version':'kfm.v1','object_type':'SoilPublicFeedbackRegistry','entries':[]}),('challenge_registry.json',{'schema_version':'kfm.v1','object_type':'SoilReproducibilityChallengeRegistry','entries':[]}),('correction_intake_registry.json',{'schema_version':'kfm.v1','object_type':'SoilCorrectionIntakeRegistry','entries':[],'immutable_artifacts_mutated':False,'correction_requests_are_not_truth_sources':True}),('dispute_ledger.json',{'schema_version':'kfm.v1','object_type':'SoilAccountabilityDisputeLedger','entries':[],'open_blocking_item_count':0,'unresolved_high_rights_or_security_count':0,'unresolved_critical_count':0})]: write_json_atomic(cyc/fn,{**obj,'domain':'soil','accountability_id':acct,'assurance_id':aid,'registry_id':am['registry_id'],'release_id':am['release_id']})
 t=build_feedback_transparency_log([]); write_json_atomic(cyc/'feedback_transparency_log.json',{'schema_version':'kfm.v1','object_type':'SoilFeedbackTransparencyLog','domain':'soil','accountability_id':acct,'assurance_id':aid,'registry_id':am['registry_id'],'release_id':am['release_id'],'log_mode':'offline_deterministic_hash_chain','live_public_form_submission_performed':False,'live_helpdesk_submission_performed':False,'entries':t['entries'],'log_root':t['log_root'],'created':utc_now_iso()})
 write_json_atomic(cyc/'public_accountability_report.json',{'schema_version':'kfm.v1','object_type':'SoilPublicAccountabilityReport','domain':'soil','accountability_id':acct,'assurance_id':aid,'registry_id':am['registry_id'],'certification_id':m['certification_id'],'release_id':am['release_id'],'accountability_status':'PUBLIC_ACCOUNTABILITY_READY','accountability_state':'pass','certificate_status':'active','public_advertising_allowed':True})
 gen={fn:'sha256:'+sha256_file(cyc/fn) for fn in ['accountability_manifest.json','public_feedback_registry.json','challenge_registry.json','correction_intake_registry.json','dispute_ledger.json','feedback_transparency_log.json','public_accountability_report.json']}
 write_json_atomic(cyc/'accountability_receipt.json',{'schema_version':'kfm.v1','receipt_type':'PublicAccountabilityReceipt','from_state':'CONTINUOUS_ASSURANCE_READY','to_state':'PUBLIC_ACCOUNTABILITY_READY','decision':'pass','domain':'soil','release_id':am['release_id'],'registry_id':am['registry_id'],'assurance_id':aid,'accountability_id':acct,'created':utc_now_iso(),'live_public_form_submission_performed':False,'live_helpdesk_submission_performed':False,'live_notification_performed':False,'source_assurance_receipt':{'ref':safe_rel_ref(Path(x.assurance_root)/f'assurance/soil/cycles/{aid}/assurance_receipt.json',x.assurance_root),'sha256':'sha256:'+sha256_bytes(json.dumps(ar,sort_keys=True).encode())},'generated_artifacts':gen,'feedback_transparency_log_root':t['log_root'],'policy_checks':{'assurance_checked':True,'registry_checked':True,'no_live_external_calls':True,'accountability_allowed':True},'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}})
 write_json_atomic(Path(x.out_root)/'accountability/soil/current_accountability.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentPublicAccountabilityPointer','domain':'soil','active_accountability_id':acct,'assurance_id':aid,'registry_id':am['registry_id'],'certification_id':m['certification_id'],'release_id':am['release_id'],'accountability_status':'PUBLIC_ACCOUNTABILITY_READY','accountability_state':'pass','certificate_status':'active','accountability_manifest_ref':safe_rel_ref(cyc/'accountability_manifest.json',x.out_root),'accountability_receipt_ref':safe_rel_ref(cyc/'accountability_receipt.json',x.out_root),'created':utc_now_iso()})
 print(json.dumps({'accountability_allowed':True,'accountability_id':acct,'assurance_id':aid,'registry_id':am['registry_id'],'release_id':am['release_id'],'state_transition':'CONTINUOUS_ASSURANCE_READY->PUBLIC_ACCOUNTABILITY_READY','accountability_state':'pass','outputs':{'root':str(cyc)}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
