"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { formatDownloadBytes as bytes, libraryRoleLabels } from "./local-download-client";
import type { useLocalDownloads } from "./use-local-downloads";
import type { useEarthEngineContext } from "./earth-engine-context-client";
import { earthEngineSetYear } from "./earth-engine-context";
import { EARTH_ENGINE_DATASETS } from "./earth-engine-data";
import type { ActivityItem } from "./download-activity";
import s from "./downloads/workspace.module.css";

const when = (stamp: string) => new Date(stamp).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
export default function DownloadLibrary({ downloads, reviewed, items = [] }: { items?: ActivityItem[]; downloads: ReturnType<typeof useLocalDownloads>; reviewed: ReturnType<typeof useEarthEngineContext> }) {
  const { library, connection } = downloads, connected = connection === "connected";
  const snapshot = library?.generatedAt ? library : null, scanning = library?.state === "scanning", stale = Boolean(downloads.libraryError || library?.state === "failed" || !connected);
  const [query, setQuery] = useState(""), [role, setRole] = useState("all"), [page, setPage] = useState(0);
  const collections = useMemo(() => (library?.entries ?? []).filter(entry => (role === "all" || entry.role === role) && `${entry.label} ${entry.lane} ${libraryRoleLabels[entry.role]}`.toLowerCase().includes(query.trim().toLowerCase())), [library, query, role]);
  const pages = Math.max(1, Math.ceil(collections.length / 10)), currentPage = Math.min(page, pages - 1);
  const retained = items.filter(item => item.bytes > 0 && ["downloaded", "cancelled", "failed", "interrupted"].includes(item.state));
  const [savedQuery, setSavedQuery] = useState(""), [savedPage, setSavedPage] = useState(0);
  const title = (item: ActivityItem) => item.kind === "earth-engine" ? `${EARTH_ENGINE_DATASETS.find(d => d.id === item.job.selection.dataset)?.title ?? item.job.selection.dataset} · ${item.job.selection.year ?? "fixed period"}` : item.title;
  const saved = retained.filter(item => title(item).toLowerCase().includes(savedQuery.trim().toLowerCase()));
  const savedPages = Math.max(1, Math.ceil(saved.length / 6)), savedCurrent = Math.min(savedPage, savedPages - 1);
  const approved = reviewed.manifests.flatMap(manifest => manifest.layers.filter(layer => layer.status === "approved").map(layer => ({ key: `${manifest.setId}/${layer.id}`, title: EARTH_ENGINE_DATASETS.find(source => source.id === layer.id)?.title ?? layer.id, year: layer.id === "ee-3dep" ? "Mixed dates" : earthEngineSetYear(manifest), period: layer.period })));
  return <section aria-labelledby="library-heading"><header className={s.sectionHeading}><div><p className={s.eyebrow}>YOUR STORED COLLECTIONS</p><h2 id="library-heading">My library</h2></div><button type="button" disabled={!connected || scanning || downloads.refreshingLibrary} aria-busy={scanning || downloads.refreshingLibrary} onClick={() => void downloads.refreshLibrary()}>{scanning ? "Scanning…" : downloads.refreshingLibrary ? "Starting scan…" : "Refresh library"}</button></header>
    <dl className={s.librarySummary}><div><dt>Stored on this computer</dt><dd>{snapshot ? bytes(snapshot.totalBytes) : "Unknown"}</dd><dd className={s.summaryNote}>{snapshot ? `${snapshot.totalFiles.toLocaleString()} files · ${snapshot.entries.length} collections` : scanning ? "First scan in progress" : "A completed scan is required"}</dd></div><div><dt>Ready on the map</dt><dd>{reviewed.loading ? "Checking…" : reviewed.error ? "Unavailable" : approved.length}</dd><dd className={s.summaryNote}>Approved display periods, checked separately</dd></div></dl>
    <p className={s.muted}>Source originals and working files. Downloads remain candidates until reviewed for map display.</p>
    {scanning && <div className={s.scan}><div><strong>Scanning in the background</strong><span>{library.scannedFiles.toLocaleString()} files inspected</span></div><progress aria-label="Library scan in progress; total file count unknown" /><p>{snapshot ? `Showing the previous completed scan from ${when(snapshot.generatedAt!)}.` : "Collection totals will appear when the first scan finishes."} You can keep browsing.</p></div>}
    {downloads.libraryError && <p className={s.alert}>{downloads.libraryError}</p>}
    {library?.state === "failed" && <p className={s.alert}>The scan could not finish{library.error === "LIBRARY_SCAN_LIMIT" ? " within its limit" : library.error === "LIBRARY_SCAN_CHANGED" ? " because files changed during inspection" : ""}. {snapshot ? "The previous snapshot remains visible." : "Current collection totals are unknown."}</p>}
    {snapshot && <p className={s.snapshot}>{scanning || stale ? "Previous completed scan" : "Completed scan"} · <time dateTime={snapshot.generatedAt!}>{when(snapshot.generatedAt!)}</time></p>}
    <section aria-labelledby="saved-downloads-heading"><h3 id="saved-downloads-heading">Downloaded files &amp; partial transfers</h3>
      <p>Recent transfers with retained bytes. Each entry identifies a completed download or a partial transfer; the scan above measures what is currently stored.</p>
      <label>Find a downloaded source<input type="search" value={savedQuery} placeholder="Map title, dataset or year" onChange={event => { setSavedQuery(event.target.value); setSavedPage(0); }} /></label>
      <ul className={s.collections}>{saved.slice(savedCurrent * 6, (savedCurrent + 1) * 6).map(item => <li key={item.key}><div><strong>{title(item)}</strong><small>{item.state === "downloaded" ? "Download completed" : "Partial download"} · {bytes(item.bytes)} · {when(item.createdAt)}</small><details><summary>Where it is stored</summary><code style={{ overflowWrap: "anywhere" }}>{item.job.destination}</code><p>Transfer record; files may have changed since this download. New downloads need review before map display.</p></details></div></li>)}</ul>
      {!saved.length && <p>{retained.length ? "No downloaded sources match this search." : "No recent transfers with retained bytes are recorded. Older stored collections appear below."}</p>}
      {savedPages > 1 && <nav className={s.pagination} aria-label="Downloaded file pages"><button type="button" disabled={savedCurrent === 0} onClick={() => setSavedPage(savedCurrent - 1)}>Previous downloads</button><span>Page {savedCurrent + 1} of {savedPages}</span><button type="button" disabled={savedCurrent + 1 >= savedPages} onClick={() => setSavedPage(savedCurrent + 1)}>Next downloads</button></nav>}
    </section>
    <h3>All stored collections</h3>
    <div className={s.filters}><label>Find a collection<input aria-label="Find a collection" type="search" placeholder="Source or collection name" value={query} onChange={event => { setQuery(event.target.value); setPage(0); }} /></label><label>Collection role<select value={role} onChange={event => { setRole(event.target.value); setPage(0); }}><option value="all">All roles</option>{Object.entries(libraryRoleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
    {snapshot ? <><div className={s.listHeading}><span>{collections.length} matching collections</span><span>Files / storage</span></div><ul className={s.collections} aria-label="Stored collections">{collections.slice(currentPage * 10, (currentPage + 1) * 10).map(entry => <li key={entry.id}><div><strong>{entry.dataset ? `${EARTH_ENGINE_DATASETS.find(d => d.id === entry.dataset)?.title ?? entry.dataset} · ${entry.period}` : entry.label}</strong><small>{libraryRoleLabels[entry.role]} · {entry.lane}</small></div><div><strong>{bytes(entry.bytes)}</strong><small>{entry.files.toLocaleString()} files</small></div></li>)}</ul>{!collections.length && <p className={s.empty}>{snapshot.entries.length ? "No collections match these filters." : "No eligible collection files were found."}</p>}<nav className={s.pagination} aria-label="Collection pages"><button type="button" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Previous</button><span>Page {currentPage + 1} of {pages}</span><button type="button" disabled={currentPage + 1 >= pages} onClick={() => setPage(currentPage + 1)}>Next</button></nav></> : <div className={s.empty}><strong>{scanning ? "Measuring the local library" : "The library has not been measured yet"}</strong><p>{connected ? "A completed scan will show source names, file counts and stored bytes." : "Connect this computer above to inspect stored collections."}</p></div>}
    <details className={s.readyDisclosure}><summary>Ready on the map <span>{reviewed.loading ? "Checking…" : reviewed.error ? "Unavailable" : `${approved.length} approved periods`}</span></summary><p>Approved display periods are independent of download status and stored bytes.</p>{reviewed.loading ? <p>Checking installed display sets…</p> : reviewed.error ? <p className={s.alert}>{reviewed.error}</p> : approved.length ? <ul>{approved.map(item => <li key={item.key}><strong>{item.title}</strong><span>{item.year ?? "Period not specified"}</span><small>{item.period}</small></li>)}</ul> : <p>No approved display periods are installed.</p>}<div className={s.linkActions}><button type="button" disabled={reviewed.loading} onClick={reviewed.reload}>Recheck periods</button><Link href="/earth-engine-context/install">Open map installer →</Link></div></details>
    <p className={s.libraryFoot}>Looking for provenance? <Link href="/acquisition">Inspect acquisition receipts →</Link></p>
  </section>;
}
