# .github/DEPENDABOT.yml
version: 2

updates:
  # ── GitHub Actions (workflows) ────────────────────────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:10"
    open-pull-requests-limit: 10
    labels: ["deps", "security", "ci"]
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]

  # ── NPM / Node (web client) ──────────────────────────────────────────────────
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:20"
    open-pull-requests-limit: 10
    labels: ["deps", "frontend", "security"]
    versioning-strategy: increase
    groups:
      web-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      # Example: hold back major MapLibre changes until manually tested
      - dependency-name: "maplibre-gl"
        update-types: ["version-update:semver-major"]

  # ── Python (pip / backend & tooling) ─────────────────────────────────────────
  # If you use Poetry or uv/requirements.in, adjust accordingly.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:30"
    open-pull-requests-limit: 10
    labels: ["deps", "python", "security"]
    # Dependabot scans common requirement files (requirements.txt, reqs/*.txt)
    groups:
      python-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      # Example: pin GDAL major jumps for reproducibility until CI images update
      - dependency-name: "GDAL"
        update-types: ["version-update:semver-major"]

  # ── Docker (container builds, if present) ─────────────────────────────────────
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:40"
    open-pull-requests-limit: 10
    labels: ["deps", "docker", "security"]
    groups:
      docker-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # ── Security updates (fast lane) ─────────────────────────────────────────────
  # Run a daily pass for any ecosystems above to raise security updates quickly.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["deps", "security", "priority"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "all"
    # Only open PRs when advisory-based updates exist
    commit-message:
      prefix: "chore(security)"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    labels: ["deps", "security", "priority"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "all"
    commit-message:
      prefix: "chore(security)"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["deps", "security", "priority"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "all"
    commit-message:
      prefix: "chore(security)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["deps", "security", "priority"]
    allow:
      - dependency-type: "direct"
      - dependency-type: "all"
    commit-message:
      prefix: "chore(security)"
