commitish: "main"
filter-by-commitish: true

pull-request-limit: 50
history-limit: 200

name-template: "v$RESOLVED_VERSION 🌾"
tag-template: "v$RESOLVED_VERSION"

change-template: "- $TITLE — [#$NUMBER]($URL) (@$AUTHOR)"
change-title-escapes: "\\<*_&@#`"
no-changes-template: "- No user-facing changes in this release."

sort-by: "merged_at"
sort-direction: "descending"

exclude-labels:
  - "skip-changelog"
  - "skip-release-notes"
  - "no-release-notes"
  - "meta"
  - "internal-only"
  - "status:wip"
  - "status:blocked"
  - "do-not-merge"

exclude-contributors:
  - "dependabot"
  - "dependabot[bot]"
  - "github-actions"
  - "github-actions[bot]"
  - "renovate"
  - "renovate[bot]"

version-resolver:
  major:
    labels:
      - "breaking-change"
      - "type:breaking"
      - "semver:major"
      - "major"
  minor:
    labels:
      - "type:feature"
      - "semver:minor"
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "type:bug"
      - "type:perf"
      - "type:security"
      - "type:docs"
      - "type:chore"
      - "semver:patch"
      - "patch"
      - "bug"
      - "fix"
      - "perf"
      - "refactor"
      - "docs"
      - "security"
      - "chore"
      - "dependencies"
      - "deps"
  default: "patch"

category-template: "### $TITLE"
categories:
  - title: "✨ Highlights"
    labels: ["release:highlight", "highlight"]

  - title: "💥 Breaking changes"
    labels: ["breaking-change", "type:breaking", "semver:major", "major"]

  - title: "🔐 Security, privacy & governance"
    labels:
      - "type:security"
      - "security"
      - "sec"
      - "vuln"
      - "cve"
      - "policy"
      - "policy-gate"
      - "governance:privacy"
      - "governance:sensitive-locations"
      - "governance:sovereignty"
      - "governance:license"
      - "governance:care"
      - "governance:fair"
      - "supply-chain"

  - title: "🧾 Receipts & promotion (run manifests, checksums, spec_hash)"
    labels:
      - "area:receipts"
      - "receipts"
      - "run-manifest"
      - "spec_hash"
      - "promotion"
      - "promotion-contract"

  - title: "🧾 Catalogs & provenance (DCAT/STAC/PROV)"
    labels:
      - "area:catalog"
      - "catalog"
      - "area:dcat"
      - "dcat"
      - "area:stac"
      - "stac"
      - "area:prov"
      - "prov"
      - "area:data"
      - "data"

  - title: "🧰 ETL & pipelines"
    labels:
      - "area:pipeline"
      - "pipeline"
      - "etl"
      - "ingest"

  - title: "🕸️ Graph & ontology"
    labels:
      - "area:graph"
      - "graph"
      - "neo4j"
      - "ontology"

  - title: "🔌 API boundary"
    labels:
      - "area:api"
      - "api"
      - "backend"
      - "server"

  - title: "🌐 Web / UI"
    labels:
      - "area:web"
      - "web"
      - "ui"
      - "frontend"
      - "map"
      - "maplibre"
      - "webgl"

  - title: "🎬 Story Nodes & narrative"
    labels:
      - "area:story"
      - "type:story"
      - "story"
      - "narrative"

  - title: "🧠 Focus Mode & analytics"
    labels:
      - "area:focus"
      - "focus"
      - "focus-mode"
      - "analysis"
      - "ml"
      - "ai"
      - "model"

  - title: "📈 Performance & reliability"
    labels:
      - "type:perf"
      - "perf"
      - "benchmark"
      - "observability"
      - "logging"
      - "metrics"

  - title: "⚠️ Ops, migrations & rollouts"
    labels:
      - "ops:migration"
      - "ops:rollback"
      - "risk:high"
      - "migration"
      - "db-migration"

  - title: "🧱 CI / infra / ops"
    labels:
      - "ci"
      - "infra"
      - "devops"
      - "docker"
      - "k8s"
      - "terraform"
      - "area:db"
      - "database"
      - "postgis"

  - title: "📚 Docs / SOPs"
    labels:
      - "area:docs"
      - "type:docs"
      - "docs"
      - "documentation"
      - "sop"

  - title: "⬆️ Dependencies"
    collapse-after: 8
    labels: ["dependencies", "deps"]

  - title: "🧹 Chores"
    labels:
      - "type:chore"
      - "chore"
      - "build"
      - "maintenance"

header: |
  ## 🌾 Kansas Frontier Matrix — Release Notes

  > Drafted from merged PRs (label-driven). Evidence-first • contract-first • governance-aware • fail-closed.
  >
  > 🧭 Truth Path: **Raw → Work → Processed → DCAT/STAC/PROV → Stores → API(+Policy) → UI/Stories → Focus Mode**

template: |
  ## ✅ Changes
  $CHANGES

  ## 🧪 Verification snapshot (release bar)
  - [ ] CI green (tests + lint)
  - [ ] Policy gates passed (OPA/Conftest) where applicable
  - [ ] Receipt gates passed (run_manifest + checksums + spec_hash semantics) where applicable
  - [ ] DCAT/STAC/PROV validated for any published data or evidence artifacts
  - [ ] Evidence resolver contract remains valid (refs resolve or deny safely)
  - [ ] Redaction + sovereignty review performed where required
  - [ ] SBOM / attestations present where applicable (release artifacts)

  ## 🧑‍🤝‍🧑 Contributors
  $CONTRIBUTORS

footer: |
  ## 🔎 Governance reminders
  - Promotion-critical outputs (data, catalogs, models, stories) must be traceable: **receipts + catalogs + checksums**.
  - Prefer digest-addressed pointers over payloads for large artifacts; attach proofs (SBOM/attestations) where enabled.
  - If a change affects privacy, sovereignty, sensitive locations, or licensing, treat it as high-scrutiny and ensure policy gates passed.

replacers:
  - search: "/CVE-(\\d{4})-(\\d+)/g"
    replace: "[CVE-$1-$2](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2)"

autolabeler:
  - label: "breaking-change"
    title:
      - "/BREAKING CHANGE/i"
      - "/^.+!:/"

  - label: "type:feature"
    title:
      - "/^feat(\\(.+\\))?:/i"
    branch:
      - "/^feat\\//"
      - "/^feature\\//"

  - label: "type:bug"
    title:
      - "/^fix(\\(.+\\))?:/i"
    branch:
      - "/^fix\\//"
      - "/^bug\\//"

  - label: "type:perf"
    title:
      - "/^perf(\\(.+\\))?:/i"
    branch:
      - "/^perf\\//"

  - label: "type:docs"
    title:
      - "/^docs(\\(.+\\))?:/i"
    branch:
      - "/^docs\\//"

  - label: "type:security"
    title:
      - "/^sec(\\(.+\\))?:/i"
      - "/\\bsecurity\\b/i"
      - "/CVE-\\d{4}-\\d+/i"
    branch:
      - "/^security\\//"
      - "/^sec\\//"

  - label: "type:chore"
    title:
      - "/^chore(\\(.+\\))?:/i"
    branch:
      - "/^chore\\//"

  - label: "area:web"
    files: ["web/**"]
  - label: "area:api"
    files: ["src/server/**", "api/**"]
  - label: "area:pipeline"
    files: ["src/pipelines/**", "pipelines/**", "scripts/**"]
  - label: "area:graph"
    files: ["src/graph/**", "data/graph/**", "docs/**/ontology/**"]
  - label: "area:data"
    files: ["data/**"]
  - label: "area:docs"
    files: ["docs/**", ".github/*.md", "README.md", "**/*.md", "**/*.mdx"]
  - label: "area:story"
    files: ["docs/**/story_nodes/**", "web/**/story_nodes/**"]
  - label: "area:focus"
    files: ["src/server/**/ai/**", "src/server/**/focus/**", "docs/**/focus/**"]

  - label: "area:receipts"
    files:
      [
        "data/work/**/runs/**/run_manifest.json",
        "data/work/**/runs/**/run_record.json",
        "contracts/**/receipts/**",
        "schemas/**/receipts/**",
      ]
  - label: "promotion-contract"
    files:
      [
        "contracts/**/promotion/**",
        "schemas/**/promotion/**",
        "data/work/**/runs/**/run_manifest.json",
      ]

  - label: "area:catalog"
    files: ["data/catalog/**", "data/**/catalog/**"]
  - label: "area:dcat"
    files: ["data/catalog/dcat/**", "data/**/dcat/**"]
  - label: "area:stac"
    files:
      ["data/catalog/stac/**", "data/**/stac/**", "**/collection.json", "**/catalog.json"]
  - label: "area:prov"
    files: ["data/catalog/prov/**", "data/prov/**", "data/provenance/**"]

  - label: "ops:migration"
    files:
      ["src/server/**/migrations/**", "src/server/**/alembic/**", "src/graph/migrations/**"]
  - label: "area:db"
    files: ["**/*.sql", "docker-compose.yml", "docker/**", "infra/**"]

  - label: "ci"
    files:
      [
        ".github/workflows/**",
        ".github/actions/**",
        ".github/dependabot.yml",
        ".pre-commit-config.yaml",
      ]
  - label: "devops"
    files: ["docker/**", "docker-compose.yml", "infra/**"]

  - label: "policy"
    files: ["policy/**", "tools/policy/**", "tools/**/policy/**", "docs/governance/**"]
  - label: "policy-gate"
    files: ["policy/**", "tools/**/policy/**"]

  - label: "governance:license"
    files:
      ["docs/standards/**", "policy/**/license**", "tools/**/license**", "data/catalog/dcat/**"]
  - label: "governance:sensitive-locations"
    files: ["policy/**/sensitive**", "tools/**/sensitive**", "docs/governance/**", "data/registry/**"]
  - label: "governance:sovereignty"
    files: ["docs/governance/**", "data/registry/**", "policy/**"]
  - label: "governance:privacy"
    files: ["policy/**/privacy/**", "tools/**/privacy/**", "docs/governance/**"]
  - label: "governance:care"
    files: ["docs/governance/**", "data/registry/**"]
  - label: "governance:fair"
    files: ["docs/standards/**", "schemas/**", "contracts/**"]

  - label: "supply-chain"
    files:
      [
        "releases/**",
        "tools/supply-chain/**",
        ".github/workflows/**sbom**",
        ".github/workflows/**attest**",
        ".github/actions/**sbom**",
        ".github/actions/**attest**",
      ]

  - label: "dependencies"
    files:
      [
        "**/package-lock.json",
        "**/pnpm-lock.yaml",
        "**/yarn.lock",
        "**/requirements*.txt",
        "**/poetry.lock",
        "**/Pipfile.lock",
        "**/Cargo.lock",
        "**/go.mod",
        "**/go.sum",
        "**/Gemfile.lock",
        "**/composer.lock",
        ".github/dependabot.yml",
      ]

  - label: "internal-only"
    files: ["docs/library/**"]
