# ===============================
# Kansas Geo Timeline — MkDocs
# ===============================
site_name: Kansas Geo Timeline
site_url: https://bartytime4life.github.io/Kansas-Frontier-Matrix/
repo_url: https://github.com/bartytime4life/Kansas-Frontier-Matrix
repo_name: Kansas-Frontier-Matrix
edit_uri: edit/main/docs/
docs_dir: docs
site_dir: _site_docs

use_directory_urls: true
strict: true  # fail on broken links

theme:
  name: material
  language: en
  features:
    # Navigation
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - toc.integrate
    # Content UX
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    # Search
    - search.highlight
    - search.suggest
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.png

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+'
      prebuild_index: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false

markdown_extensions:
  # Core
  - admonition
  - footnotes
  - tables
  - abbr
  - def_list
  - md_in_html
  - toc:
      permalink: true
  # Pymdownx / Material
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
      line_spans: __span
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams — rendered by mermaid.min.js (see extra_javascript)
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bartytime4life/Kansas-Frontier-Matrix
      name: GitHub
  analytics: {}
  generator: false
  consent:
    title: Cookie consent
    description: >
      We use local storage for search and navigation enhancements. No tracking.
  copyright:
    text: "© Kansas-Frontier-Matrix — MIT License"

extra_css:
  - assets/css/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/js/mermaid-init.js  # create with: mermaid.initialize({ startOnLoad: true });

# Optional: faster live-reload while editing outside docs/
watch:
  - web
  - stac
  - scripts

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Data Sources: data_sources.md
  - STAC: stac.md
  - CLI (kgt): cli.md
  - Web Viewer: viewer.md
  - Google Earth: earth.md
  - Reproducibility: reproducibility.md
  - Troubleshooting: troubleshooting.md
  - Roadmap: roadmap.md
  - Requirements: requirements.md
  - Status Snapshots: snapshots.md
