[build-system]
requires = [
  "setuptools>=68",
  "wheel",
  "setuptools_scm[toml]>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "kansas-geo-timeline"
dynamic = ["version"]  # managed by setuptools_scm
description = "Time · Terrain · History mapping system for Kansas (Earth + Web)"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "Andy Barta" }]
keywords = [
  "GIS", "Kansas", "Google Earth", "MapLibre", "COG", "STAC", "KML", "KMZ",
  "hillshade", "terrain", "historical-maps", "time-slider"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Education",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: GIS",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Internet :: WWW/HTTP :: Site Management",
  "Environment :: Console",
  "Operating System :: OS Independent"
]

# Core runtime — kept lean; heavy/vector stacks via extras.
# NOTE: NumPy <2.0 for rasterio 1.3.x ABI.
dependencies = [
  "numpy>=1.26.4,<2.0",
  "rasterio>=1.3.10,<1.4",
  "rio-cogeo>=5.3.3",
  "pyproj>=3.6.1",
  "shapely>=2.0.4",
  "pystac>=1.10.1",
  "pystac-client>=0.7.6",
  "jsonschema>=4.23.0",
  "Pillow>=10.4.0",
  "click>=8.1.7",
  "rich>=13.7.1",
  "typing-extensions>=4.12.2; python_version < '3.11'",
]

[project.optional-dependencies]
# Local dev / CI
dev = [
  "ruff>=0.6.9",
  "black>=24.8.0",
  "mypy>=1.11.2",
  "pytest>=8.3.2",
  "pytest-cov>=5.0.0",
  "pre-commit>=3.8.0",
  "types-PyYAML>=6.0.12.20240808",
]

# Security tooling (opt-in)
security = [
  "bandit>=1.7",
  "pip-audit>=2.7",
]

# STAC validator/tooling (optional to keep runtime slim)
stac = [
  "stac-validator>=3.3.1",
]

# Docs / handbook
docs = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.5.39",
  "mkdocstrings[python]>=0.25.1",
]

# Earth / KML helpers (optional – scripts generate most KML)
earth = [
  "simplekml>=1.3.6",
]

# Web build helpers (templating / tiny HTTP fetch)
web = [
  "jinja2>=3.1.4",
  "httpx>=0.27.2",
]

# Notebooks for demos / reproducibility capsules
notebooks = [
  "jupyter>=1.1.1",
  "ipykernel>=6.29.5",
]

# Optional heavy GIS/vector stack (opt-in to avoid unexpected GDAL/Fiona builds)
vector = [
  "pyogrio>=0.9.0",
  "geopandas>=1.0.0",
]

analysis = [
  "scipy>=1.13.1",
  "scikit-image>=0.24.0",
]

tiles = [
  "morecantile>=5.3.0",
  "rio-tiler>=6.6.1",
]

# Convenience meta-extras (expanded; no self-references)
# Install via: pip install "kansas-geo-timeline[all-dev]" or "[full]"
all-dev = [
  # dev
  "ruff>=0.6.9",
  "black>=24.8.0",
  "mypy>=1.11.2",
  "pytest>=8.3.2",
  "pytest-cov>=5.0.0",
  "pre-commit>=3.8.0",
  "types-PyYAML>=6.0.12.20240808",
  # docs
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.5.39",
  "mkdocstrings[python]>=0.25.1",
  # web
  "jinja2>=3.1.4",
  "httpx>=0.27.2",
  # notebooks
  "jupyter>=1.1.1",
  "ipykernel>=6.29.5",
  # stac tooling
  "stac-validator>=3.3.1",
  # security
  "bandit>=1.7",
  "pip-audit>=2.7",
]

full = [
  # earth/vector/tiles/analysis stacks
  "simplekml>=1.3.6",
  "pyogrio>=0.9.0",
  "geopandas>=1.0.0",
  "morecantile>=5.3.0",
  "rio-tiler>=6.6.1",
  "scipy>=1.13.1",
  "scikit-image>=0.24.0",
]

[project.scripts]
kgt = "kansas_geo_timeline.cli:main"

[project.urls]
Homepage = "https://github.com/bartytime4life/Kansas-Frontier-Matrix"
Repository = "https://github.com/bartytime4life/Kansas-Frontier-Matrix"
Issues = "https://github.com/bartytime4life/Kansas-Frontier-Matrix/issues"
Documentation = "https://bartytime4life.github.io/Kansas-Frontier-Matrix/"

# ---- setuptools layout -------------------------------------------------------
[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["kansas_geo_timeline*"]
exclude = ["tests*", "docs*"]

# Ship small schemas/templates with the wheel (avoid web/ or data/)
[tool.setuptools.package-data]
kansas_geo_timeline = [
  "schemas/**/*.json",
  "schemas/**/*.yaml",
  "templates/**/*.j2",
  "templates/**/*.jinja2",
  "templates/**/*.html",
]

# Ensure bulky local data never slips into wheels/sdists
[tool.setuptools.exclude-package-data]
"*" = ["data/**", "stac/**", "earth/**", "web/**"]

[tool.setuptools_scm]
write_to = "src/kansas_geo_timeline/_version.py"
fallback_version = "0.1.0"
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
# Typical lightweight tag pattern e.g. "v0.3.1" or "0.3.1"
tag_regex = "^(?:v)?(?P<version>\\d+\\.\\d+\\.\\d+(?:[A-Za-z0-9\\.\\-]+)?)$"

# ---- linters / formatters / typing ------------------------------------------
[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# Include security (S) and mccabe (C90) plus common correctness/upgrade rules.
select = ["E", "F", "I", "UP", "B", "W", "C90", "S"]
ignore = ["E203"]  # black-compat
fixable = ["ALL"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["kansas_geo_timeline"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]           # allow assert in tests
"src/**/__init__.py" = ["F401"] # allow re-export convenience imports

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
warn_unused_ignores = true
warn_redundant_casts = true
strict_optional = true
ignore_missing_imports = true
exclude = "(^build/|^dist/|^web/|^earth/|^stac/|^data/)"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q --cov=kansas_geo_timeline --cov-report=term-missing"
testpaths = ["tests"]

# ---- coverage (optional) -----------------------------------------------------
[tool.coverage.run]
branch = true
source = ["src/kansas_geo_timeline"]

[tool.coverage.report]
skip_empty = true
show_missing = true
# fail_under = 60

[tool.coverage.paths]
source = [
  "src/kansas_geo_timeline",
  "**/site-packages/kansas_geo_timeline"
]

# ---- security tools ----------------------------------------------------------
[tool.bandit]
targets = ["src"]
exclude_dirs = ["tests", "docs", "web", "data", "stac", "earth"]
skips = ["B101"]  # assert used (tests already allowed in Ruff)

# ---- project-specific defaults (consumed by scripts/ or CLI) -----------------
[tool.kansas_geo_timeline]
data_dir = "data"
processed_dir = "data/processed"
stac_dir = "stac"
web_dir = "web"
earth_dir = "earth"
default_crs = "EPSG:4326"
tile_size = 256
time_slider_min_year = 1850
time_slider_max_year = 2025
