[build-system]
requires = [
  "setuptools>=68",
  "wheel",
  "setuptools_scm[toml]>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "kansas-geo-timeline"
dynamic = ["version"]                  # managed by setuptools_scm
description = "Time · Terrain · History mapping system for Kansas (Earth + Web)"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Andy Barta" }]
keywords = [
  "GIS", "Kansas", "Google Earth", "MapLibre", "COG", "STAC", "KML", "KMZ",
  "hillshade", "terrain", "historical-maps", "time-slider"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Education",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: GIS",
  "Topic :: Internet :: WWW/HTTP :: Site Management"
]

# Core runtime deps (keep lean; heavy tools via extras below)
dependencies = [
  "rasterio>=1.3.9",
  "rio-cogeo>=5.1.0",
  "pyproj>=3.6.1",
  "shapely>=2.0.4",
  "pystac>=1.10.0",
  "pystac-client>=0.7.6",
  "jsonschema>=4.23.0",
  "Pillow>=10.4.0",
  "click>=8.1.7",
  "rich>=13.7.1",
  "numpy>=1.26.4"
]

[project.optional-dependencies]
# local dev / CI
dev = [
  "ruff>=0.6.8",
  "black>=24.8.0",
  "mypy>=1.11.2",
  "pytest>=8.3.2",
  "pytest-cov>=5.0.0",
  "pre-commit>=3.8.0",
  "types-PyYAML>=6.0.12.20240808"
]
# building docs / handbook
docs = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.5.39",
  "mkdocstrings[python]>=0.25.1",
]
# Earth / KML helpers (optional – most KML is generated by scripts)
earth = [
  "simplekml>=1.3.6"
]
# web build helpers (templating / tiny HTTP fetch when needed)
web = [
  "jinja2>=3.1.4",
  "httpx>=0.27.2"
]
# notebooks for demos / reproducibility capsules
notebooks = [
  "jupyter>=1.1.1",
  "ipykernel>=6.29.5"
]
# Optional heavy GIS/vector stack (opt-in to avoid unexpected GDAL/Fiona builds)
vector = [
  "pyogrio>=0.9.0",         # fast vector IO (GDAL-backed wheels on many platforms)
  "geopandas>=1.0.0"
]
analysis = [
  "scipy>=1.13.1",
  "scikit-image>=0.24.0"
]
tiles = [
  "morecantile>=5.3.0",
  "rio-tiler>=6.6.1"
]

[project.scripts]
kgt = "kansas_geo_timeline.cli:main"   # tiny CLI: fetch→cog→terrain→kml→site

[project.urls]
Homepage = "https://github.com/your-org/kansas-geo-timeline"
Repository = "https://github.com/your-org/kansas-geo-timeline"
Issues = "https://github.com/your-org/kansas-geo-timeline/issues"
Documentation = "https://your-org.github.io/kansas-geo-timeline/"

# ---- setuptools layout -------------------------------------------------------

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["kansas_geo_timeline*"]

[tool.setuptools.package-data]
# ship small schemas/templates/configs with the package (not big rasters)
kansas_geo_timeline = [
  "schemas/*.json",
  "templates/*"
]

[tool.setuptools_scm]
# automatic version from git tags; write version into the package at build time
write_to = "src/kansas_geo_timeline/_version.py"
fallback_version = "0.1.0"
local_scheme = "node-and-date"

# ---- linters / formatters / typing ------------------------------------------

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E","F","I","UP","B","W","C90"]
ignore = ["E203"]  # black-compat
fixable = ["ALL"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["kansas_geo_timeline"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
warn_unused_ignores = true
warn_redundant_casts = true
strict_optional = true
ignore_missing_imports = true
exclude = "(^build/|^dist/|^web/)"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q --cov=kansas_geo_timeline --cov-report=term-missing"
testpaths = ["tests"]

# ---- coverage (optional) -----------------------------------------------------

[tool.coverage.run]
branch = true
source = ["src/kansas_geo_timeline"]

[tool.coverage.report]
skip_empty = true
show_missing = true
# fail_under = 60

# ---- project-specific defaults (consumed by scripts/ or CLI) -----------------

[tool.kansas_geo_timeline]
data_dir = "data"
processed_dir = "data/processed"
stac_dir = "data/stac"
web_dir = "web"
earth_dir = "earth"
default_crs = "EPSG:4326"
tile_size = 512
time_slider_min_year = 1850
time_slider_max_year = 2025
