import Link from "next/link";
import { SOURCE_DOWNLOADS } from "../../source-downloads";
import { OFFICIAL_CONTEXT_SOURCES } from "../../live-context";

const refs = [
  ["Iowa Environmental Mesonet", "NEXRAD composites: construction, history and limitations", "https://mesonet.agron.iastate.edu/docs/nexrad_composites/", "Living documentation; accessed September 10, 2026"],
  ["Iowa Environmental Mesonet", "OGC web services", "https://mesonet.agron.iastate.edu/ogc/", "Live service documentation and capabilities"],
  ["NOAA NCEI", "Next Generation Weather Radar (NEXRAD)", "https://www.ncei.noaa.gov/products/radar/next-generation-weather-radar", "Official archive access"],
  ["NOAA NESDIS", "Hazard Mapping System smoke product", "https://www.ospo.noaa.gov/products/land/hms.html", "Product documentation"],
  ["NOAA NESDIS", "HMS smoke KML archive", "https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Smoke_Polygons/KML/", "Dated daily artifacts, verified 2005–2026"],
  ["NOAA / AWS Open Data", "High-Resolution Rapid Refresh archive", "https://registry.opendata.aws/noaa-hrrr-pds/", "GRIB2 model-run archive"],
  ["NASA GIBS", "Available visualizations", "https://nasa-gibs.github.io/gibs-api-docs/available-visualizations/", "Daily imagery and time-dimension documentation"],
  ["USGS", "Water Data APIs", "https://api.waterdata.usgs.gov/", "OGC API v1, accessed September 10, 2026"],
  ["Kansas Geological Survey", "Geology and mineral resources", "https://kgs.ku.edu/geology-and-mineral-resources", "Official mapped-geology source"],
  ["Kansas Geological Survey", "State Geology GeMS: Map Unit Polys (14)", "https://services2.arcgis.com/ZOdjAzAQ2B0f85zi/arcgis/rest/services/State_Geology_GeMS/FeatureServer/14", "M-118 (2008); GeMS conversion 2023–24"],
  ["USGS", "Topographic Mine Symbols: 1:24,000 points (8)", "https://services.arcgis.com/v01gqwM5QqNysAAi/arcgis/rest/services/USGS_Topographic_Mine_Symbols/FeatureServer/8", "Historical map-symbol compilation; not current mine operations"],
  ["USGS", "USMIN Mineral Deposit Database", "https://www.usgs.gov/centers/gggsc/science/usmin-mineral-deposit-database", "Latest compilation context and supersession"],
  ["GBIF", "Maps API v2", "https://techdocs.gbif.org/en/openapi/v2/maps", "Occurrence density tiles, time and taxonomy filters"],
  ["GBIF", "Best practices for generalizing sensitive species occurrence data", "https://docs.gbif.org/sensitive-species-best-practices/master/en/", "Privacy and generalization guidance"],
  ["KFM / Google Drive", "Living Atlas Interface, Default Views and Animation Design v0.1", "https://docs.google.com/document/d/1aivNyfMjQ8urQO6vjt4YvkT1ltF1t7fxCahEcnGV4Dw/edit", "Modified September 10, 2026; proposed design, access-controlled"],
  ["KFM / Google Drive", "Real-Data Resource Integration Manual", "https://drive.google.com/file/d/1WS6Z5E3bbgCdekQ-KA8mziFG0Wy6wgMX/view", "September 9, 2026; exploratory and non-activating, access-controlled"],
  ["KFM / Notion", "Real-Data Resource Integration — Research Manual & Delivery Hub", "https://app.notion.com/p/3d6a92021bf6816cae0ec1ccbd15e21e", "Edited September 10, 2026; coordination record, access-controlled"],
  ["KFM / GitHub", "Temporal View State contract", "https://github.com/bartytime4life/Kansas-Frontier-Matrix/blob/b44494c1cf0807ed28b606e8a41b255bebdf4ad7/contracts/common/temporal_view_state.md", "Current main checkpoint; proposed fixture-first contract"],
  ["KFM / GitHub", "Sites official-context alignment", "https://github.com/bartytime4life/Kansas-Frontier-Matrix/blob/b44494c1cf0807ed28b606e8a41b255bebdf4ad7/apps/kansas-frontier-matrix-explorer/docs/sites-v15-official-context-alignment.md", "Repository path records the unresolved Site/repository identity boundary"],
];
const Cite = ({ n }: { n: number }) => <a href={refs[n-1][2]} target="_blank" rel="noreferrer">[{n}]</a>;

export const metadata = { title: "Temporal Sources & Coverage · KFM Event Observatory" };
export default function SourcesPage() {
  return <article className="event-research">
    <Link href="/observatory">← Event Observatory</Link>
    <h1>Temporal environmental layers for Kansas</h1>
    <p>The Event Observatory connects dated environmental observations and independently dated context on one Kansas map. Historical radar replay is immediately feasible; smoke footprints, streamflow, satellite acquisitions, geology and occurrence records need different time rules. A universal date slider is useful only if it preserves those distinctions.</p>
    <nav aria-label="Research sections"><a href="#coverage">Coverage</a> · <a href="#time">Time model</a> · <a href="#atmosphere">Radar & smoke</a> · <a href="#earth">Earth & water</a> · <a href="#ecology">Flora & fauna</a> · <a href="#delivery">Delivery boundaries</a> · <a href="#references">References</a></nav>

    <h2 id="coverage">Source coverage and implemented carriers</h2>
    <p>The archive opens on today’s latest available frame and refreshes every five minutes while “Follow today” is active. Choosing a historical date pauses following. Source publication dates and Census editions remain separate.</p>
    <details className="source-download-directory"><summary>Download source data or propose an update</summary><p>Choose a source’s download or archive. Use <Link href="/data">Data commons</Link> to submit a file with its dates and reuse terms. Assigned stewards use the <Link href="/stewards">review desk</Link>; accepted submissions still require integration before appearing on the map.</p><table><thead><tr><th>Source</th><th>Data</th><th>Update</th></tr></thead><tbody>{OFFICIAL_CONTEXT_SOURCES.map((source) => <tr key={source.id}><td>{source.shortTitle}</td><td><a href={SOURCE_DOWNLOADS[source.id].href} target="_blank" rel="noreferrer">{SOURCE_DOWNLOADS[source.id].label} ↗</a></td><td><Link href={`/data?source=${source.id}`}>Propose data</Link></td></tr>)}<tr><td>NOAA daily weather</td><td><a href="https://www.ncei.noaa.gov/pub/data/ghcn/daily/" target="_blank" rel="noreferrer">GHCN-D station archives ↗</a></td><td><Link href="/data?source=noaa-daily-weather">Propose data</Link></td></tr></tbody></table></details>
    <p>Connections were checked on September 12, 2026. The calendar retains every day from 1800 onward, including gaps; the Explorer’s older deep-time axis remains available. Choose continuous river samples or daily means, discover a station’s earliest record, and step through full 24-hour days. A daily value does not create hourly observations.</p>
    <div className="research-table-wrap"><table><thead><tr><th>Layer</th><th>Temporal support</th><th>Representation</th><th>Important limit</th></tr></thead><tbody>
      <tr><td>NOAA-derived IEM radar</td><td>N0R from 1995; N0Q WMS from February 16, 2011; actual 5-minute artifacts</td><td>Time-bound reflectivity image over Kansas</td><td>Composite validity is not one simultaneous network scan. <Cite n={1} /><Cite n={2} /></td></tr>
      <tr><td>NOAA HMS smoke</td><td>Observed KML archive begins August 5, 2005, with gaps; per-polygon Start/End</td><td>Actual footprint and density-category changes</td><td>No observed transport vectors, height or surface concentration. <Cite n={4} /><Cite n={5} /></td></tr>
      <tr><td>USGS discharge</td><td>Provider-declared daily and continuous record spans, through latest available measurements</td><td>Continuous samples or separately selected daily means; oldest-record and latest controls</td><td>Topeka USGS-06889000 returned a daily record for June 12, 1917; its declared continuous span starts October 1, 1990. Other stations differ. Gaps remain. <Cite n={8} /></td></tr>
      <tr><td>NOAA GHCN daily weather</td><td>Exact-date station records; historical cooperative and current airport stations</td><td>Daily maximum/minimum temperature and precipitation at 19 selected Kansas stations</td><td>Verified records for May 19, 1900. Daily station summaries are not hourly or county-wide estimates. <a href="https://www.ncei.noaa.gov/products/land-based-station/global-historical-climatology-network-daily" target="_blank" rel="noreferrer">NOAA GHCN-D ↗</a></td></tr>
      <tr><td>County baselines</td><td>Independently selectable 2010 and 2020 Census editions</td><td>All 105 counties, population, housing, land and water area; click a county</td><td>Published Census map service replaces the API-key-dependent population request. The chosen edition stays labeled even when replaying an older event. <a href="https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb" target="_blank" rel="noreferrer">Census source ↗</a></td></tr>
      <tr><td>Raspberry Shake</td><td>FDSN station epochs overlapping the selected date</td><td>Historical and current station locations, with a provider waveform-viewer link</td><td>Waveforms are not rehosted. FDSN is delayed at least 30 minutes; real-time service and redistribution have separate provider terms. <a href="https://manual.raspberryshake.org/fdsn.html" target="_blank" rel="noreferrer">Provider documentation ↗</a></td></tr>
      <tr><td>USGS earthquake history</td><td>Catalog event times for the selected calendar day</td><td>Events appear at their recorded time and accumulate within that day</td><td>Historical catalog completeness varies. No earthquake observation is inferred from a Raspberry Shake station marker. <a href="https://earthquake.usgs.gov/fdsnws/event/1/" target="_blank" rel="noreferrer">USGS catalog ↗</a></td></tr>
      <tr><td>NASA Terra MODIS</td><td>Daily acquisition mosaics since February 24, 2000, with outages</td><td>Historical satellite background</td><td>Not intraday imagery, cloud-free coverage, or historical cartography. <Cite n={7} /></td></tr>
      <tr><td>KGS cached geology</td><td>Static carrier; exact cache edition not confirmed</td><td>Mapped surface unit colors</td><td>Not the newer GeMS service or a deep-time reconstruction. <Cite n={9} /><Cite n={10} /></td></tr>
      <tr><td>USGS resource-map symbols</td><td>Selected topographic edition year; Kansas editions 1934–1996 with gaps</td><td>County-aggregated historical map-symbol counts</td><td>Not reserves, unique mines, operating dates or current inventory. <Cite n={11} /><Cite n={12} /></td></tr>
      <tr><td>GBIF flora/fauna</td><td>Event-year occurrence records; source-dependent historical coverage</td><td>Coarse annual hexagon density, Plantae / Animalia</td><td>Not species abundance, migration, habitat, or absence. <Cite n={13} /></td></tr>
    </tbody></table></div>

    <h2 id="time">A shared cursor with explicit support intervals</h2>
    <p>The controlling axis is event time in UTC, also shown in Central time. The interface uses one playback scheduler for radar, smoke and river observations. Its sequence contains actual mosaic times, smoke interval boundaries and station sample times, not fabricated intermediate measurements. Radar is supported for its explicit five-minute display slot; smoke is shown only when Start ≤ cursor &lt; End. A river observation may be held for no more than thirty minutes, with its original timestamp and missing-value state intact.</p>
    <p>Publication, retrieval, acquisition and model initialization are not interchangeable. An annual occurrence layer stays an annual aggregate throughout an hourly event; a static geology layer remains static; a resource-map edition is explicitly pinned on its own control. These are analytical design decisions informed by KFM’s axis-aware temporal contract and the Living Atlas design, not evidence of causal relationships among displayed layers. <Cite n={15} /><Cite n={18} /></p>
    <p>Requested and displayed frames are separate. Changing a date cancels older requests. Temporal pixels are hidden while the next exact radar image is buffering, and the timestamp is committed after that image source is ready. Playback stops on failure, interaction, a hidden tab or Escape; reduced-motion users retain step and scrub controls. Loops start off. Layer opacity and drawing order affect presentation only, not measurements.</p>
    <p>Replay links preserve the selected interval, cursor, layers, opacity, order, background and resource-map edition. They reproduce a query, not immutable original bytes: external providers can revise or withdraw historical data. A future durable evidence archive must capture artifact hashes, retrieval and revision metadata, rights, policy decisions and release identity before claiming exact cross-session reproduction.</p>

    <h2 id="atmosphere">Radar archives and smoke dynamics</h2>
    <h3>Historical reflectivity</h3>
    <p>IEM provides practical browser-ready mosaics derived from NOAA/NWS radar. Its N0R and N0Q services have different history and reflectivity encoding; N0Q’s documented imagery history begins earlier than its current WMS capability minimum. The adapter conservatively uses N0R before February 16, 2011 and N0Q afterward. It does not calculate color differences across product eras or interpolate between them. <Cite n={1} /><Cite n={2} /></p>
    <p>Live endpoint probes exposed a material hazard: an out-of-range WMS TIME request could return the same successful PNG as a request with TIME omitted. Accordingly, the adapter admits only exact timestamped filenames found in the daily archive listing, validates cadence and range, and always sends TIME. A PNG response alone is insufficient proof. Directory and image responses are bounded, and a small cache plus two-frame look-ahead limits upstream load.</p>
    <p>Direct NOAA NCEI archives remain the stronger future path for preserving native Level-II scans and Level-III products. They require decoding, quality control, gridding and rendering before they become map animations. That additional processing is distinct from this Site’s IEM-derived display carrier and is not represented as already operational. <Cite n={3} /></p>
    <h3>Observed footprints versus modeled flow</h3>
    <p>HMS KML records contain actual polygons, categorical density and observation start/end fields. The accepted parser reads only those scalar fields and polygon coordinates; it ignores HTML, external links, icons and zero altitude. Unknown historical density values remain unknown. Neighboring archive days are inspected for intervals crossing midnight, while missing files remain distinguishable from valid files without a Kansas-intersecting footprint. <Cite n={5} /></p>
    <p>Moving polygon edges are not measured smoke transport. HMS is satellite-analyzed column context and does not establish a person’s surface PM2.5 exposure. A physically meaningful flow visualization needs a separately labeled modeled concentration field plus an identified wind field and height. Decorative particles, morphing footprints and extruded plumes would imply information that this product does not contain. <Cite n={4} /></p>
    <p>The NOAA HRRR archive offers the appropriate next data family. A verified June 7, 2023 index contains MASSDEN at eight metres above ground and COLMD for the full atmospheric column. A production adapter would perform bounded GRIB-message range reads, decode the grid and units, reproject Kansas, and cache derived tiles. Run initialization, forecast lead, valid time, variable, level and model version must remain fixed and inspectable. The archive’s 2014 start does not establish smoke-variable coverage for every year. HRRR flow is therefore researched but not activated in this version. <Cite n={6} /></p>

    <h2 id="earth">Hydrology, geology and historical maps</h2>
    <p>The USGS connection accepts an absolute historical UTC end time for a selected monitoring station, retaining its bounded 24-hour, seven-day, thirty-day and one-year service windows. The Observatory’s event view uses continuous discharge and displays only samples relevant to the chosen interval. The existing River Pulse view retains its longer series modes. Daily means, stage and instantaneous discharge remain separate products; the event marker is not a flood warning or an estimate at unmonitored reaches. <Cite n={8} /></p>
    <p>Kansas surface geology can be displayed immediately through the KGS cached map. That cache has less descriptive metadata than the newer State Geology GeMS service, so its edition is explicitly unconfirmed. The newer GeMS service documents M-118, 2008, at 1:500,000 and a 2023–24 conversion. It is the appropriate candidate for future inspectable unit attributes and stratigraphic legends, after source rights and representation are reviewed. Neither carrier reconstructs ancient plate positions or supplies subsurface volumes. <Cite n={9} /><Cite n={10} /></p>
    <p>Resource context uses a deliberately different representation: counts of historical USGS topographic mine symbols grouped upstream by county and map edition. Names are joined to modern Census counties without delivering exact site coordinates. The verified all-edition Kansas query produced 4,768 symbols; the 1984 edition query produced 26 in four counties. These sample totals describe the older compilation, not a complete current mine inventory. Multiple map representations can duplicate a physical site, and an omitted symbol does not prove no resource. <Cite n={11} /><Cite n={12} /></p>
    <p>Historical satellite imagery is connected through NASA GIBS daily Terra mosaics. Exact-date domain availability is checked before a layer is offered, and the tile adapter also verifies the returned actual-time header to reject nearest-date substitution. Clouds and missing swaths remain real gaps. Modern reference roads are labeled as modern and are not passed off as historical boundaries. <Cite n={7} /></p>
    <p>True historical cartography remains a separate next connection. USGS topoView and Library of Congress map editions are useful candidates, but each raster needs a scan identity, edition, rights, geographic extent and reviewed georeferencing transform/error. A printed publication year does not date every feature on the sheet. The relevant endpoints could not be runtime-verified in this environment, so no speculative historical map layer is presented as working.</p>

    <h2 id="ecology">Flora, fauna and ecological realism</h2>
    <p>GBIF Maps v2 supports taxonomy and year filters on occurrence-density tiles. The Site separates Plantae and Animalia and keeps the source tile zoom capped at six, so clients receive coarse hexagon images rather than exact occurrence coordinates. The layers include dated collection/specimen records as well as other occurrence bases and are labeled records, not exclusively contemporary sightings. Source-confirmed empty tiles are transparent and mean no returned records, not absent species. <Cite n={13} /></p>
    <p>Occurrence density reflects collection effort, mobilization and source coverage as well as ecological processes. It cannot by itself establish abundance, a population trend, habitat suitability or migration. No organism is animated moving between unrelated observations. The first responsible visual is annual record aggregation alongside independently timed environmental layers, with visibly different clocks. Authorized tracking datasets could support a future movement product, but require their own sampling, rights and privacy decisions.</p>
    <p>Generalization must occur before public delivery. Low opacity or hidden popups do not protect exact coordinates already sent to a browser. The coarse carrier avoids exact-point and sensitive-taxon drilldowns; it does not replace an independent source-admission and privacy assessment. Future exports, joins and small-cell analyses need additional protection against reconstructing sensitive localities. <Cite n={14} /></p>
    <p>Land cover, vegetation indices, range models and habitat maps should be added as separate named products with acquisition/reference years and methods. None should be used as a substitute for an observed species record. The Drive and Notion domain plans supply useful design ideas but describe candidate integrations and governance expectations, not proof of activated flora/fauna pipelines. <Cite n={16} /><Cite n={17} /></p>

    <h2 id="delivery">Authority, delivery boundaries and remaining work</h2>
    <p>GitHub’s independently checked main checkpoint was b44494c1cf0807ed28b606e8a41b255bebdf4ad7, merged by PR #4468. The repository and saved Site remain distinct source trees with a documented identity conflict, not interchangeable deployments. The Notion Hub is coordination evidence and Drive is design lineage; some implementation notes there still refer to older Site versions. No Notion or Drive write, GitHub source mutation, identity reconciliation or production deployment is implied by this Observatory implementation. <Cite n={17} /><Cite n={19} /></p>
    <p>Every new map carrier remains EXTERNAL_CONTEXT_ONLY. It is not automatically admitted to KFM EvidenceBundles, Qwen claim support, governed reports or evidence exports. Display co-presence indicates that records share a view and possibly temporal support, not that rainfall caused a river change, smoke caused an ecological change, or geology establishes an economic resource. Formal analysis needs lag assumptions, sampling support, spatial joins, uncertainty and a separately reviewed method.</p>
    <p>The supplied <em>KFM Full Atlas seed cards</em> describe proposed inspectable-claim objects and explicitly leave implementation maturity unresolved. The supplied <em>KFM Geology Natural Resources Architecture PDF Only Report</em>, sections 7–8, separates mapped geology, subsurface interpretation, resources and legal rights. The supplied <em>MapLibre 3D Features and KFM Implementation</em> is draft architecture, not deployment authority. These local attachments informed semantic boundaries; no inaccessible page or public link is invented for them.</p>
    <p>Recommended next delivery order: preserve exact source artifacts and revisions; implement a bounded HRRR smoke-field pipeline; qualify historical georeferenced map editions; add watershed/reach-aware hydrologic relationships; then introduce dated habitat and phenology products. A national “all GIS” archive is not a single connection and is not claimed here. Each new layer needs its own coverage, rights, precision, quality and current withdrawal rules.</p>

    <h2 id="references">Sources and references</h2>
    <ol>{refs.map(([publisher,title,url,date]) => <li key={url}><strong>{publisher}.</strong> <a href={url} target="_blank" rel="noreferrer">{title}</a>. {date}.</li>)}</ol>
    <p>Private project sources may require their original access permissions. Service documentation and source data can change after this research checkpoint; the map’s requested interval and retrieved timestamp remain visible.</p>
    <Link href="/observatory">Return to the Event Observatory →</Link>
  </article>;
}
