#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
import argparse, json, os, shutil, tempfile, xml.sax.saxutils as sx
from pathlib import Path
from tools.federation.soil._federation_common import *
TARGETS=['dcat','ckan','data_gov','stac','ogc_records','schemaorg','mirror','notifications']
def main(argv=None):
 a=argparse.ArgumentParser();
 for k in ['discovery-root','published-root','ops-root','out-root','base-public-url']: a.add_argument(f'--{k}',required=True)
 a.add_argument('--discovery-id');a.add_argument('--federation-id');a.add_argument('--targets',default='all');x=a.parse_args(argv)
 if not validate_base_public_url(x.base_public_url): print(json.dumps({'federation_allowed':False,'reasons':['invalid base_public_url']})); return 1
 ts=TARGETS if x.targets=='all' else [t.strip() for t in x.targets.split(',') if t.strip()]
 did=x.discovery_id or load_current_discovery(x.discovery_root)['active_discovery_id']
 reasons,d,dr,st,sr=validate_federation_inputs(x.discovery_root,x.published_root,x.ops_root,did); rid=d.get('release_id')
 if reasons: print(json.dumps({'federation_allowed':False,'discovery_id':did,'release_id':rid,'reasons':reasons},sort_keys=True)); return 1
 fid=sanitize_id(x.federation_id) if x.federation_id else deterministic_federation_id({'discovery_id':did,'release_id':rid,'targets':sorted(ts),'source_hashes':sorted([sha256_file(Path(x.discovery_root)/f'discovery/soil/releases/{did}/discovery_manifest.json'),sha256_file(Path(x.discovery_root)/f'discovery/soil/releases/{did}/discovery_receipt.json'),sha256_file(Path(x.ops_root)/'ops/soil/status/current_status.json'),sha256_file(Path(x.ops_root)/'ops/soil/status/status_receipt.json')])})
 final=Path(x.out_root)/'federation/soil/releases'/fid; tmp=Path(tempfile.mkdtemp(prefix='soilfe_'))/fid
 recs=sorted(d['records'],key=lambda z:z['bundle_id'])
 def w(rel,p): write_json_atomic(tmp/rel,p)
 if 'ckan' in ts: w('targets/ckan/package.json',{'name':fid,'title':'KFM Soil Federation','notes':'deterministic fixture','license_id':'cc-by' if is_public_rights(recs[0]['rights_status']) else 'other','owner_org':'kfm','tags':[{'name':'soil'}],'extras':[{'key':'release_id','value':rid},{'key':'discovery_id','value':did},{'key':'federation_id','value':fid},{'key':'evidence_bound','value':'true'}],'resources':[{'name':'api','url':public_url_join(x.base_public_url,'/soil/current')}],'kfm_live_submission':False})
 if 'dcat' in ts: w('targets/dcat/catalog.dataset.jsonld',{'@context':{'dcat':'http://www.w3.org/ns/dcat#','dct':'http://purl.org/dc/terms/'},'@type':'dcat:Dataset','dct:identifier':fid,'kfm:release_id':rid})
 if 'data_gov' in ts: w('targets/data_gov/dcat-us.json',{'identifier':fid,'title':'KFM Soil','accessLevel':'public','keyword':['soil'],'kfm:adapter_status':'PROPOSED_static_fixture_adapter'})
 if 'stac' in ts: w('targets/stac/catalog.json',{'type':'Catalog','id':fid,'links':[{'rel':'child','href':'collection.json'}]}); w('targets/stac/collection.json',{'type':'Collection','id':'soil','links':[{'rel':'self','href':public_url_join(x.base_public_url,f'/federation/soil/releases/{fid}/targets/stac/collection.json')}]})
 if 'ogc_records' in ts: w('targets/ogc_records/records.json',{'type':'FeatureCollection','features':[{'type':'Feature','id':sanitize_id(r['bundle_id']),'properties':{'title':r['title'],'release_id':rid,'discovery_id':did,'federation_id':fid,'evidence_bundle_ref':r['evidence_bundle_ref'],'rights_status':r['rights_status'],'policy_label':r['policy_label'],'sensitivity':r['sensitivity'],'metrics':r['metrics']}} for r in recs],'kfm:adapter_status':'PROPOSED_static_fixture_adapter'})
 if 'schemaorg' in ts: w('targets/schemaorg/catalog.jsonld',{'@context':'https://schema.org','@type':'DataCatalog','name':'KFM Soil Federation','dataset':[{'@type':'Dataset','identifier':r['bundle_id'],'name':r['title']} for r in recs]})
 w('notifications/change_notice.json',{'schema_version':'kfm.v1','object_type':'SoilFederationChangeNotice','domain':'soil','federation_id':fid,'discovery_id':did,'release_id':rid,'change_type':'new_federation_ready','public_message':'Federation package ready.','records_added':len(recs),'records_changed':0,'records_removed':0,'evidence_refs':[r['evidence_bundle_ref'] for r in recs],'created':utc_now_iso(),'public_urls':[],'truth_policy':{'observational_data_bound':True,'ai_interpretive_only':True,'model_output_is_truth_source':False}})
 w('notifications/feed_delta.json',{'version':'https://jsonfeed.org/version/1.1','items':[{'id':fid,'title':'new federation'}]})
 write_text_atomic(tmp/'notifications/feed_delta.atom.xml',f"<feed xmlns='http://www.w3.org/2005/Atom'><entry><id>{sx.escape(fid)}</id></entry></feed>\n")
 files=[]
 for p in sorted(tmp.rglob('*')):
  if p.is_file(): files.append({'logical_path':str(p.relative_to(tmp)),'public_url':public_url_join(x.base_public_url,'/federation/soil/releases/'+fid+'/'+str(p.relative_to(tmp))),'source_ref':str(p.relative_to(tmp)),'sha256':sha256_file(p),'media_type':'application/json' if p.suffix in {'.json','.jsonld'} else 'application/xml','required':True})
 w('mirror/public_snapshot_index.json',{'federation_id':fid,'files':[{'url':f['public_url'],'sha256':f['sha256']} for f in files]})
 w('mirror/mirror_manifest.json',{'schema_version':'kfm.v1','object_type':'SoilMirrorManifest','domain':'soil','federation_id':fid,'discovery_id':did,'release_id':rid,'mirror_status':'MIRROR_READY','live_mirror_sync_performed':False,'source_discovery_manifest_ref':f'discovery/soil/releases/{did}/discovery_manifest.json','source_discovery_receipt_ref':f'discovery/soil/releases/{did}/discovery_receipt.json','source_federation_receipt_ref':f'federation/soil/releases/{fid}/federation_receipt.json','public_snapshot_index_ref':'mirror/public_snapshot_index.json','files':sorted(files,key=lambda z:z['logical_path']),'policy_summary':{'public_only':True,'no_private_paths':True,'no_forbidden_terms':True,'hashes_checked':True,'live_sync_performed':False}})
 artifact_hashes={str(p.relative_to(tmp)):sha256_file(p) for p in sorted(tmp.rglob('*')) if p.is_file() and p.name!='federation_receipt.json'}
 manifest={'schema_version':'kfm.v1','object_type':'SoilFederationManifest','domain':'soil','federation_id':fid,'discovery_id':did,'release_id':rid,'publication_status':'PUBLISHED','discovery_status':'DISCOVERABLE','federation_status':'FEDERATION_READY','base_public_url':x.base_public_url,'created':utc_now_iso(),'target_count':len(ts),'targets':[{'target_name':t,'payload_ref':f'targets/{t}/'+({'dcat':'catalog.dataset.jsonld','ckan':'package.json','data_gov':'dcat-us.json','stac':'catalog.json','ogc_records':'records.json','schemaorg':'catalog.jsonld','mirror':'mirror_manifest.json','notifications':'change_notice.json'}[t] if t not in {'mirror','notifications'} else ('../mirror/mirror_manifest.json' if t=='mirror' else '../notifications/change_notice.json')),'payload_sha256':'','adapter_status':'PROPOSED_static_fixture_adapter','live_submission_performed':False,'public_url':''} for t in sorted(ts)],'source_refs':{'discovery_manifest_ref':f'discovery/soil/releases/{did}/discovery_manifest.json','discovery_receipt_ref':f'discovery/soil/releases/{did}/discovery_receipt.json','operational_status_ref':'ops/soil/status/current_status.json','status_receipt_ref':'ops/soil/status/status_receipt.json'},'records':recs,'artifact_hashes':artifact_hashes,'policy_summary':{'discovery_checked':True,'discovery_gate_checked':True,'status_checked':True,'latest_probe_checked':True,'retraction_checked':True,'rights_checked':True,'sensitivity_checked':True,'public_paths_checked':True,'forbidden_terms_checked':True,'live_submission_performed':False,'federation_allowed':True}}
 write_json_atomic(tmp/'federation_manifest.json',manifest)
 rc={'schema_version':'kfm.v1','receipt_type':'FederationReceipt','from_state':'DISCOVERABLE','to_state':'FEDERATION_READY','decision':'pass','domain':'soil','release_id':rid,'discovery_id':did,'federation_id':fid,'created':utc_now_iso(),'live_submission_performed':False,'source_discovery_receipt':{'ref':f'discovery/soil/releases/{did}/discovery_receipt.json','sha256':sha256_file(Path(x.discovery_root)/f'discovery/soil/releases/{did}/discovery_receipt.json')},'source_operational_status':{'ref':'ops/soil/status/current_status.json','sha256':sha256_file(Path(x.ops_root)/'ops/soil/status/current_status.json')},'source_status_receipt':{'ref':'ops/soil/status/status_receipt.json','sha256':sha256_file(Path(x.ops_root)/'ops/soil/status/status_receipt.json')},'generated_artifacts':artifact_hashes,'target_payloads':{t:{'sha256':'','adapter_status':'PROPOSED_static_fixture_adapter'} for t in ts},'policy_checks':{'discovery_checked':True,'discovery_gate_checked':True,'status_checked':True,'latest_probe_checked':True,'retraction_checked':True,'rights_checked':True,'sensitivity_checked':True,'public_paths_checked':True,'forbidden_terms_checked':True,'live_submission_performed_false':True,'federation_allowed':True},'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
 write_json_atomic(tmp/'federation_receipt.json',rc)
 if final.exists():
  old=load_json(final/'federation_manifest.json');
  if old.get('artifact_hashes')!=manifest.get('artifact_hashes'): print(json.dumps({'federation_allowed':False,'discovery_id':did,'release_id':rid,'reasons':['existing federation directory differs']})); return 1
 else: final.parent.mkdir(parents=True,exist_ok=True); os.replace(tmp,final)
 write_json_atomic(Path(x.out_root)/'federation/soil/current_federation.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentFederationPointer','domain':'soil','active_federation_id':fid,'discovery_id':did,'release_id':rid,'federation_status':'FEDERATION_READY','federation_manifest_ref':f'releases/{fid}/federation_manifest.json','federation_receipt_ref':f'releases/{fid}/federation_receipt.json','created':utc_now_iso()})
 print(json.dumps({'federation_allowed':True,'federation_id':fid,'discovery_id':did,'release_id':rid,'state_transition':'DISCOVERABLE->FEDERATION_READY','targets':ts,'outputs':{'release':str(final)}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
