from __future__ import annotations
import argparse,json,shutil,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT))
from tools.quality.flora.usda_common import canonical_hash,validate,write_json,sha256_file

def main():
 p=argparse.ArgumentParser();p.add_argument('--packaging-plan',type=Path,required=True);p.add_argument('--fixture-pmtiles',type=Path,required=True);p.add_argument('--fixture-mbtiles',type=Path);p.add_argument('--out-root',type=Path,required=True);p.add_argument('--snapshot-date',required=True);p.add_argument('--generated-at',required=True);a=p.parse_args()
 plan=json.loads(a.packaging_plan.read_text());snap=a.snapshot_date
 arch=a.out_root/f'published/flora/usda_plants/{snap}/archives';host=a.out_root/f'published/flora/usda_plants/{snap}/hosting';ctl=a.out_root/f'archives/flora/usda_plants/{snap}'
 arch.mkdir(parents=True,exist_ok=True);host.mkdir(parents=True,exist_ok=True);ctl.mkdir(parents=True,exist_ok=True)
 pm=arch/'county_presence.pmtiles';shutil.copyfile(a.fixture_pmtiles,pm)
 pm_manifest={"schema_version":"1.0.0","object_type":"usda_plants_pmtiles_package_manifest","pmtiles_package_id":f"kfm.pmtiles_package.flora.usda_plants.{snap}","domain":"flora","source_id":"usda_plants","snapshot_date":snap,"generated_at":a.generated_at,"packaging_plan_ref":f"archives/flora/usda_plants/{snap}/tile_archive_packaging_plan.json","source_tile_package_manifest_ref":f"published/flora/usda_plants/{snap}/tiles/tile_package_manifest.json","archive_ref":f"published/flora/usda_plants/{snap}/archives/county_presence.pmtiles","archive_format":"pmtiles","archive_engine":plan['archive_engine'],"size_bytes":pm.stat().st_size,"sha256":sha256_file(pm),"source_layer":"county_presence","minzoom":0,"maxzoom":8,"fixture_mode":True,"production_coverage_claim":False,"safety":{"contains_occurrence_coordinates":False,"contains_raw_refs":False,"contains_work_refs":False,"contains_quarantine_refs":False,"deploys_to_cdn":False},"status":"pass","reason_codes":["USDA_PLANTS_PMTILES_PACKAGE_CREATED"]}
 pm_manifest['manifest_hash']=canonical_hash(pm_manifest,'manifest_hash');write_json(arch/'pmtiles_package_manifest.json',pm_manifest)
 style={"schema_version":"1.0.0","object_type":"usda_plants_published_pmtiles_map_style","style_id":f"kfm.pmtiles_map_style.flora.usda_plants.{snap}","domain":"flora","source_id":"usda_plants","snapshot_date":snap,"generated_at":a.generated_at,"requires_protocol":"pmtiles","requires_maplibre_addProtocol":True,"pmtiles_ref":pm_manifest['archive_ref'],"maplibre_style":{"version":8,"name":"KFM USDA PLANTS County Presence PMTiles","metadata":{"kfm:domain":"flora","kfm:source_id":"usda_plants","kfm:snapshot_date":snap,"kfm:delivery":"pmtiles"},"sources":{"flora_usda_plants_county_presence_pmtiles":{"type":"vector","url":f"pmtiles://{pm_manifest['archive_ref']}","attribution":"USDA PLANTS Database; U.S. Census Bureau county boundaries."}},"layers":[{"id":"flora_usda_plants_county_presence_pmtiles_fill","type":"fill","source":"flora_usda_plants_county_presence_pmtiles","source-layer":"county_presence","paint":{"fill-opacity":0.55}}]},"safety":{"contains_occurrence_coordinates":False,"uses_pmtiles_protocol":True,"deploys_to_cdn":False}}
 style['style_hash']=canonical_hash(style,'style_hash');write_json(arch/'pmtiles_map_style.json',style)
 handoff={"schema_version":"1.0.0","object_type":"usda_plants_static_host_handoff","handoff_id":f"kfm.static_host_handoff.flora.usda_plants.{snap}","domain":"flora","source_id":"usda_plants","snapshot_date":snap,"generated_at":a.generated_at,"artifact_root":f"published/flora/usda_plants/{snap}/archives","hosting_root":f"published/flora/usda_plants/{snap}/hosting","deploys":False,"upload_target":None,"recommended_headers":[],"handoff_items":[{"role":"pmtiles","path":pm_manifest['archive_ref'],"sha256":pm_manifest['sha256'],"size_bytes":pm_manifest['size_bytes']}],"blocked_actions":["cdn_deploy","cloud_upload","auto_pr","auto_merge"],"status":"ready_for_future_deploy","reason_codes":["USDA_PLANTS_STATIC_HANDOFF_READY"]}; handoff['handoff_hash']=canonical_hash(handoff,'handoff_hash'); write_json(host/'static_host_handoff.json',handoff)
 integ={"schema_version":"1.0.0","object_type":"usda_plants_cache_integrity_manifest","integrity_manifest_id":f"kfm.cache_integrity.flora.usda_plants.{snap}","domain":"flora","source_id":"usda_plants","snapshot_date":snap,"generated_at":a.generated_at,"items":[{"path":pm_manifest['archive_ref'],"sha256":pm_manifest['sha256'],"size_bytes":pm_manifest['size_bytes'],"cache_control":"public, max-age=31536000, immutable","content_type":"application/octet-stream"}],"status":"pass","reason_codes":[]}; integ['integrity_hash']=canonical_hash(integ,'integrity_hash'); write_json(host/'cache_integrity_manifest.json',integ)
 receipt={"schema_version":"1.0.0","object_type":"usda_plants_tile_archive_publication_receipt","archive_publication_receipt_id":f"kfm.tile_archive_publication_receipt.flora.usda_plants.{snap}","domain":"flora","source_id":"usda_plants","snapshot_date":snap,"generated_at":a.generated_at,"packaging_plan_ref":f"archives/flora/usda_plants/{snap}/tile_archive_packaging_plan.json","pmtiles_package_manifest_ref":f"published/flora/usda_plants/{snap}/archives/pmtiles_package_manifest.json","static_host_handoff_ref":f"published/flora/usda_plants/{snap}/hosting/static_host_handoff.json","cache_integrity_manifest_ref":f"published/flora/usda_plants/{snap}/hosting/cache_integrity_manifest.json","pmtiles_map_style_ref":f"published/flora/usda_plants/{snap}/archives/pmtiles_map_style.json","published_items":[{"role":"pmtiles","target_ref":pm_manifest['archive_ref'],"sha256":pm_manifest['sha256'],"status":"published"}],"deploys":False,"publication_state":"published","status":"pass","reason_codes":[]}
 receipt['receipt_hash']=canonical_hash(receipt,'receipt_hash');write_json(ctl/'tile_archive_publication_receipt.json',receipt)
if __name__=='__main__':main()
