#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,os,tempfile
from pathlib import Path
from tools.preservation.soil._preservation_common import *

def main(argv=None):
 a=argparse.ArgumentParser()
 for k in ['reconciliation-root','federation-root','discovery-root','published-root','ops-root','out-root','base-public-url']: a.add_argument(f'--{k}',required=True)
 a.add_argument('--reconciliation-id');a.add_argument('--preservation-id');x=a.parse_args(argv)
 if not validate_base_public_url(x.base_public_url): print(json.dumps({'preservation_allowed':False,'reasons':['invalid base_public_url']})); return 1
 rid=x.reconciliation_id or load_current_reconciliation(x.reconciliation_root)['active_reconciliation_id']
 recm=load_reconciliation_manifest(x.reconciliation_root,rid);recr=load_reconciliation_receipt(x.reconciliation_root,rid);ext=load_external_status(x.reconciliation_root,rid)
 cf,cd,cp,ops=load_current_federation(x.federation_root),load_current_discovery(x.discovery_root),load_current_release(x.published_root),load_operational_status(x.ops_root)
 rs=validate_preservation_inputs(recm,recr,ext,cf,cd,cp,ops)
 if release_is_retracted(x.published_root,recm.get('release_id')) and not load_withdrawal_reconciliation(x.reconciliation_root,recm.get('release_id')): rs.append('retracted active release')
 if rs: print(json.dumps({'preservation_allowed':False,'reconciliation_id':rid,'release_id':recm.get('release_id'),'reasons':sorted(set(rs))},sort_keys=True)); return 1
 src=collect_public_source_artifacts(x.reconciliation_root,x.federation_root,x.discovery_root,x.published_root,x.ops_root,rid,recm['federation_id'],recm['discovery_id'],recm['release_id'])
 src_hash={k:'sha256:'+sha256_file(p) for k,p,_ in src}; seed=sha256_bytes((rid+''.join(sorted(src_hash.values()))).encode()); pid=sanitize_id(x.preservation_id) if x.preservation_id else f'soil-preservation-{seed[:16]}'
 out=Path(x.out_root)/f'preservation/soil/packages/{pid}';tmp=Path(tempfile.mkdtemp(prefix='soilpres_'))/pid; created=utc_now_iso()
 recs=sorted(recm.get('records',[]),key=lambda r:r.get('bundle_id',''))
 m={'schema_version':'kfm.v1','object_type':'SoilPreservationManifest','domain':'soil','preservation_id':pid,'reconciliation_id':rid,'federation_id':recm['federation_id'],'discovery_id':recm['discovery_id'],'release_id':recm['release_id'],'publication_status':'PUBLISHED','discovery_status':'DISCOVERABLE','federation_status':'FEDERATION_READY','reconciliation_status':'FEDERATION_RECONCILED','preservation_status':'PRESERVATION_READY','created':created,'base_public_url':x.base_public_url,'records':recs,'source_artifact_hashes':src_hash,'preserved_artifact_classes':['published_release','discovery_package','federation_package','reconciliation_package','operational_status','receipts','public_metadata','public_triplets'],'truth_policy':{'observational_data_bound':True,'ai_interpretive_only':True,'model_output_is_truth_source':False},'policy_summary':{'preservation_allowed':True}}
 write_json_atomic(tmp/'preservation_manifest.json',m); write_json_atomic(tmp/'public_preservation_index.json',{'schema_version':'kfm.v1','object_type':'SoilPublicPreservationIndex','domain':'soil','preservation_id':pid,'release_id':recm['release_id'],'preservation_status':'PRESERVATION_READY','citation':{'title':'Kansas Frontier Matrix Soil Moisture Public Release','version':recm['release_id'],'url':public_url_join(x.base_public_url,f'preservation/{pid}/'),'rights_status':'public'},'records':recs})
 cff='cff-version: "1.2.0"\ntitle: "Kansas Frontier Matrix Soil Moisture Public Release"\nmessage: "Please cite this dataset."\ntype: dataset\nversion: "'+recm['release_id']+'"\nauthors:\n  - family-names: "Kansas Frontier Matrix"\n    given-names: "Steward"\n'
 write_text_atomic(tmp/'citation.cff',cff)
 for fn,obj in [('datacite.json',{'schema_version':'kfm.v1','object_type':'SoilDataCiteReadyMetadata','identifier':{'identifierType':'URL','identifier':public_url_join(x.base_public_url,f'preservation/{pid}/')},'publisher':'Kansas Frontier Matrix','kfm':{'preservation_id':pid,'release_id':recm['release_id'],'live_doi_minting_performed':False}}),('codemeta.json',{'@context':'https://doi.org/10.5063/schema/codemeta-2.0','@type':'Dataset','name':'Kansas Frontier Matrix Soil Moisture Public Release','identifier':pid,'version':recm['release_id'],'isAccessibleForFree':True}),('ro-crate-metadata.json',{'@context':['https://w3id.org/ro/crate/1.1/context'],'@graph':[{'@id':'./','@type':'Dataset','name':'KFM Soil Preservation'}],'kfm:adapter_status':'PROPOSED_static_fixture_adapter'}),('reproducibility_capsule.json',{'schema_version':'kfm.v1','object_type':'SoilReproducibilityCapsule','domain':'soil','preservation_id':pid,'release_id':recm['release_id'],'canonical_units':{'soil_moisture':'m3/m3','ui_percent_conversion':'multiply_by_100_for_display_only'},'created':created}),('restoration_plan.json',{'schema_version':'kfm.v1','object_type':'SoilPreservationRestorationPlan','domain':'soil','preservation_id':pid,'release_id':recm['release_id'],'steps':[{'ordinal':1,'name':'load preservation_manifest'}],'created':created})]: write_json_atomic(tmp/fn,obj)
 write_text_atomic(tmp/'bagit/bag-info.txt',f'Bag-Software-Agent: KFM deterministic preservation builder\nBagging-Date: {created[:10]}\nKFM-Domain: soil\nKFM-Release-ID: {recm["release_id"]}\nKFM-Preservation-ID: {pid}\nKFM-Live-Archive-Upload-Performed: false\n')
 g=[]
 for p in sorted(tmp.rglob('*')):
  if p.is_file() and p.name!='preservation_receipt.json': g.append({'logical_path':str(p.relative_to(tmp)),'sha256':sha256_file(p),'media_type':'application/json' if p.suffix=='.json' else 'text/plain','required':True})
 fix={'schema_version':'kfm.v1','object_type':'SoilPreservationFixityManifest','domain':'soil','preservation_id':pid,'release_id':recm['release_id'],'algorithm':'sha256','generated_artifacts':sorted(g,key=lambda x:x['logical_path']),'source_artifacts':[{'logical_path':k,'source_ref':k,'sha256':v.replace('sha256:',''),'artifact_class':'source','required':True} for k,v in sorted(src_hash.items())],'created':created,'forbidden_terms_checked':True,'public_paths_checked':True}
 write_json_atomic(tmp/'fixity_manifest.json',fix)
 leaves=[{'logical_path':x['logical_path'],'sha256':x['sha256']} for x in fix['generated_artifacts']]; mt=build_merkle_tree(pid,leaves,created); write_json_atomic(tmp/'merkle_tree.json',mt)
 write_json_atomic(tmp/'fingerprint_ledger.json',{'schema_version':'kfm.v1','object_type':'SoilPreservationFingerprintLedger','domain':'soil','preservation_id':pid,'release_id':recm['release_id'],'fingerprints':[{'logical_path':x['logical_path'],'sha256':x['sha256'],'size_bytes':(tmp/x['logical_path']).stat().st_size,'artifact_class':'generated','media_type':x['media_type']} for x in fix['generated_artifacts']],'merkle_root':mt['merkle_root'],'created':created})
 write_text_atomic(tmp/'bagit/manifest-sha256.txt','\n'.join([f"{x['sha256']} {x['logical_path']}" for x in fix['generated_artifacts']])+'\n')
 rc={'schema_version':'kfm.v1','receipt_type':'PreservationReceipt','from_state':'FEDERATION_RECONCILED','to_state':'PRESERVATION_READY','decision':'pass','domain':'soil','release_id':recm['release_id'],'discovery_id':recm['discovery_id'],'federation_id':recm['federation_id'],'reconciliation_id':rid,'preservation_id':pid,'created':created,'live_archive_upload_performed':False,'live_doi_minting_performed':False,'generated_artifacts':{x['logical_path']:'sha256:'+x['sha256'] for x in fix['generated_artifacts']},'merkle_root':mt['merkle_root'],'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
 write_json_atomic(tmp/'preservation_receipt.json',rc)
 if out.exists():
  om=load_json(out/'preservation_manifest.json')
  if om.get('source_artifact_hashes')!=m.get('source_artifact_hashes'): print(json.dumps({'preservation_allowed':False,'reasons':['existing preservation directory differs']})); return 1
 else: out.parent.mkdir(parents=True,exist_ok=True); os.replace(tmp,out)
 write_json_atomic(Path(x.out_root)/'preservation/soil/current_preservation.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentPreservationPointer','domain':'soil','active_preservation_id':pid,'reconciliation_id':rid,'federation_id':recm['federation_id'],'discovery_id':recm['discovery_id'],'release_id':recm['release_id'],'preservation_status':'PRESERVATION_READY','preservation_manifest_ref':f'packages/{pid}/preservation_manifest.json','preservation_receipt_ref':f'packages/{pid}/preservation_receipt.json','created':created})
 print(json.dumps({'preservation_allowed':True,'preservation_id':pid,'reconciliation_id':rid,'federation_id':recm['federation_id'],'discovery_id':recm['discovery_id'],'release_id':recm['release_id'],'state_transition':'FEDERATION_RECONCILED->PRESERVATION_READY','outputs':{'package':str(out)}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
