#!/usr/bin/env python
import argparse,sys; from pathlib import Path; sys.path.append(str(Path(__file__).resolve().parent));from _candidate_reentry_common import *
p=argparse.ArgumentParser();p.add_argument('--rollforward-dir',action='append',default=[]);p.add_argument('--rollforward-ledger',required=True);p.add_argument('--rollforward-postcheck',required=True);p.add_argument('--rollforward-audit',required=True);p.add_argument('--out-dir',required=True);p.add_argument('--signature',default='fixture-signature');p.add_argument('--signature-type',default='fixture_signature');p.add_argument('--accepted-by',default='fixture-release-manager');p.add_argument('--role',default='release_manager');p.add_argument('--as-of');p.add_argument('--fixture-only',action='store_true');p.add_argument('--dry-run',action='store_true');a=p.parse_args();
post=j(a.rollforward_postcheck);aud=j(a.rollforward_audit);led=j(a.rollforward_ledger)
if post.get('result') in ('deny','blocked') or aud.get('result') in ('deny','blocked'): deny('rollforward checks denied')
if not led.get('chain_hash'): deny('invalid rollforward ledger')
if a.signature_type=='fixture_signature' and not a.fixture_only: deny('fixture signature non-production only')
o={"schema_version":"1.0.0","acceptance_id":"rfa-001","domain":"atmosphere.air","created_at":ts(a.as_of),"as_of":ts(a.as_of),"maintenance_closure_record_ref":"maintenance_closure_record.json","remediation_rollforward_plan_ref":"remediation_rollforward_plan.json","candidate_artifact_refresh_manifest_ref":"candidate_artifact_refresh_manifest.json","candidate_read_model_refresh_ref":"candidate_read_model_refresh.json","client_delivery_refresh_manifest_ref":"client_delivery_refresh_manifest.json","sunset_delta_candidate_ref":"sunset_delta_candidate.json","assurance_baseline_rotation_ref":"assurance_baseline_rotation.json","rollforward_ledger_manifest_ref":a.rollforward_ledger,"rollforward_postcheck_report_ref":a.rollforward_postcheck,"maintenance_rollforward_audit_report_ref":a.rollforward_audit,"acceptance_decision":"accept_fixture_rollforward","remaining_risks":[],"required_followups":[],"evidence_refs":[a.rollforward_postcheck,a.rollforward_audit,a.rollforward_ledger],"signature":a.signature,"signature_type":a.signature_type,"fixture_backed":True,"status":"fixture_accepted"}
if has_unsafe(o): deny('unsafe content')
out=Path(a.out_dir); out.mkdir(parents=True,exist_ok=True)
if not a.dry_run: w(out/'rollforward_acceptance_record.json',o); (out/'candidate_reentry_events.jsonl').write_text('{"event_type":"rollforward_acceptance_created","result":"pass"}\n')
print('PASS')
