#!/usr/bin/env python
import argparse,sys; from pathlib import Path; sys.path.append(str(Path(__file__).resolve().parent));from _candidate_reentry_common import *
p=argparse.ArgumentParser();p.add_argument('--rollforward-acceptance',required=True);p.add_argument('--candidate-artifact-refresh',required=True);p.add_argument('--candidate-read-model-refresh',required=True);p.add_argument('--client-delivery-refresh',required=True);p.add_argument('--assurance-baseline-rotation',required=True);p.add_argument('--out-dir',required=True);p.add_argument('--sunset-delta');p.add_argument('--as-of');p.add_argument('--fixture-only',action='store_true');p.add_argument('--dry-run',action='store_true');a=p.parse_args();
refs=[a.candidate_artifact_refresh,a.candidate_read_model_refresh,a.client_delivery_refresh,a.assurance_baseline_rotation]+([a.sunset_delta] if a.sunset_delta else [])
arts=[{"artifact_type":"candidate","path":r,"sha256":sha(r),"source_ref":r,"candidate_only":True} for r in refs]
o={"schema_version":"1.0.0","reentry_package_id":"crp-001","domain":"atmosphere.air","created_at":ts(a.as_of),"as_of":ts(a.as_of),"rollforward_acceptance_record_ref":a.rollforward_acceptance,"candidate_artifact_refresh_manifest_ref":a.candidate_artifact_refresh,"candidate_read_model_refresh_ref":a.candidate_read_model_refresh,"client_delivery_refresh_manifest_ref":a.client_delivery_refresh,"assurance_baseline_rotation_ref":a.assurance_baseline_rotation,"source_chain_refs":refs,"candidate_artifact_refs":arts,"candidate_catalog_refs":[],"candidate_delivery_refs":[a.client_delivery_refresh],"candidate_baseline_refs":[a.assurance_baseline_rotation],"reentry_objectives":["candidate_only_reentry"],"non_mutation_guarantees":["no_source_mutation","no_published_writes"],"safety_checks":["nowcast_operational_not_validated_truth"],"status":"fixture_reentry_package" if a.fixture_only else "candidate_reentry_package"}
if has_unsafe(o): deny('unsafe content')
out=Path(a.out_dir)
if not a.dry_run: w(out/'candidate_reentry_package.json',o); (out/'candidate_reentry_events.jsonl').write_text('{"event_type":"candidate_reentry_package_created","result":"pass"}\n')
print('PASS')
