#!/usr/bin/env python
import argparse,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]/'deployments'/'air'))
from cutover_common import J,TS,wj,h,etag,scan

def main():
 p=argparse.ArgumentParser(); p.add_argument('--cutover-refresh-dir',action='append',required=True); p.add_argument('--deployment-authorization-refresh-dir',action='append',required=True); p.add_argument('--deployment-readiness-refresh-dir',action='append',required=True); p.add_argument('--client-delivery-refresh-dir',action='append',required=True); p.add_argument('--out-dir',required=True); p.add_argument('--ops-dir',action='append',default=[]); p.add_argument('--as-of'); p.add_argument('--allow-fixture-handoff',action='store_true'); p.add_argument('--dry-run',action='store_true'); a=p.parse_args()
 cd=Path(a.cutover_refresh_dir[0]); od=Path(a.out_dir)
 req=['reentry_cutover_observation_refresh_record.json','reentry_post_deploy_gate_refresh_evaluation.json','reentry_release_ledger_refresh_manifest.json','reentry_operational_acceptance_refresh_record.json','reentry_rollback_decision_refresh_record.json']
 for r in req:
  if not (cd/r).exists(): print('DENY'); return 1
 out={"schema_version":"1.0.0","handoff_package_id":"reentry-handoff-refresh-"+h({"as_of":TS(a.as_of)})[:12],"domain":"atmosphere.air","created_at":TS(a.as_of),"as_of":TS(a.as_of),"cutover_observation_refresh_ref":str(cd/'reentry_cutover_observation_refresh_record.json'),"post_deploy_gate_refresh_evaluation_ref":str(cd/'reentry_post_deploy_gate_refresh_evaluation.json'),"release_ledger_refresh_manifest_ref":str(cd/'reentry_release_ledger_refresh_manifest.json'),"operational_acceptance_refresh_ref":str(cd/'reentry_operational_acceptance_refresh_record.json'),"rollback_decision_refresh_ref":str(cd/'reentry_rollback_decision_refresh_record.json'),"deployment_authorization_refresh_ref":str(Path(a.deployment_authorization_refresh_dir[0])/'reentry_deployment_authorization_refresh_manifest.json'),"client_delivery_refresh_manifest_ref":str(Path(a.client_delivery_refresh_dir[0])/'client_delivery_refresh_manifest.json'),"stakeholder_notice_refresh_draft_refs":[str(cd/'reentry_stakeholder_notice_refresh_draft.json')],"handoff_recipients":[{"label":"fixture-recipient-non-production"}],"responsibilities":["local-fixture-review-only"],"evidence_refs":[str(cd/'reentry_release_ledger_refresh_manifest.json')],"open_risks":[],"required_followups":[],"safety_checks":[{"name":"no_live_ops","pass":True}],"status":"fixture_handoff_refresh_candidate"}
 if scan(out): print('DENY'); return 1
 plan={"schema_version":"1.0.0","watch_plan_id":"watch-refresh-plan-"+h(out)[:12],"domain":"atmosphere.air","created_at":TS(a.as_of),"as_of":TS(a.as_of),"operational_handoff_refresh_package_ref":str(od/'reentry_operational_handoff_refresh_package.json'),"post_deploy_gate_refresh_evaluation_ref":out['post_deploy_gate_refresh_evaluation_ref'],"release_ledger_refresh_manifest_ref":out['release_ledger_refresh_manifest_ref'],"public_slo_objectives":["local fixture objective"],"watch_window":{"mode":"fixture","minutes":60},"local_checks":["hash","etag"],"incident_thresholds":["critical unresolved blocks"],"rollback_thresholds":["warnings require rollback record"],"evidence_refs":out['evidence_refs'],"forbidden_actions":["no live endpoint probes"],"safety_checks":[{"name":"local-only","pass":True}],"status":"fixture_watch_refresh_plan"}
 runbook={"schema_version":"1.0.0","runbook_activation_id":"runbook-refresh-"+h(plan)[:12],"domain":"atmosphere.air","created_at":TS(a.as_of),"as_of":TS(a.as_of),"operational_handoff_refresh_package_ref":str(od/'reentry_operational_handoff_refresh_package.json'),"watch_window_refresh_plan_ref":str(od/'reentry_watch_window_refresh_plan.json'),"release_ledger_refresh_manifest_ref":out['release_ledger_refresh_manifest_ref'],"deployment_authorization_refresh_ref":out['deployment_authorization_refresh_ref'],"runbook_sections":["local review"],"roles":["fixture-ops-non-production"],"local_procedures":["inspect generated json only"],"forbidden_actions":["kubectl","terraform apply","curl https://prod"],"evidence_refs":out['evidence_refs'],"safety_checks":[{"name":"non-executable","pass":True}],"status":"fixture_runbook_refresh_candidate"}
 evt={"schema_version":"1.0.0","event_id":"evt-"+h(runbook)[:12],"domain":"atmosphere.air","event_type":"operational_handoff_refresh_package_created","created_at":TS(a.as_of),"as_of":TS(a.as_of),"actor":"fixture-operator-non-production","subject_refs":[str(od/'reentry_operational_handoff_refresh_package.json')],"evidence_refs":out['evidence_refs'],"result":"pass","details":{"etag":etag(h(out))}}
 if not a.dry_run:
  od.mkdir(parents=True,exist_ok=True); wj(od/'reentry_operational_handoff_refresh_package.json',out); wj(od/'reentry_watch_window_refresh_plan.json',plan); wj(od/'reentry_runbook_activation_refresh_candidate.json',runbook); (od/'reentry_operational_handoff_refresh_events.jsonl').write_text(json.dumps(evt,sort_keys=True)+'\n')
 print('PASS'); return 0
if __name__=='__main__': raise SystemExit(main())
