#!/usr/bin/env python
import argparse,sys,json,hashlib
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from _candidate_reentry_common import *
name=Path(__file__).stem
p=argparse.ArgumentParser();p.add_argument('--out-dir',required=True);p.add_argument('--as-of');p.add_argument('--dry-run',action='store_true');a,unknown=p.parse_known_args(); out=Path(a.out_dir); out.mkdir(parents=True,exist_ok=True)
obj={"schema_version":"1.0.0","domain":"atmosphere.air","generated_at":ts(a.as_of),"as_of":ts(a.as_of),"result":"pass_fixture","status":"fixture_reentry_manifest"}
fn='out.json'
if 'compatibility' in name: fn='refresh_compatibility_gate_report.json'; obj.update({"gate_report_id":"gate-001","candidate_reentry_package_ref":'',"candidate_read_model_refresh_ref":"candidate_read_model_refresh.json","client_delivery_refresh_manifest_ref":"client_delivery_refresh_manifest.json","sunset_delta_candidate_ref":"sunset_delta_candidate.json","checks":[],"hash_checks":[],"etag_checks":[],"route_checks":[],"delta_checks":[],"baseline_checks":[],"path_safety_checks":[],"semantic_checks":["NowCast operational","AQS 24h_validated"],"hard_failures":[],"warnings":[],"result":"pass_fixture"})
if 'recertify' in name: fn='refreshed_baseline_recertification.json'; obj.update({"recertification_id":"rbr-001","created_at":ts(a.as_of),"candidate_reentry_package_ref":'',"assurance_baseline_rotation_ref":'',"previous_assurance_summary_ref":"continuous_assurance_summary.json","previous_evidence_archive_manifest_ref":"evidence_archive_manifest.json","candidate_baseline_refs":[],"recertification_scope":[],"checks":[],"findings":[],"required_followups":[],"decision":"recertify_fixture_baseline","signature":"fixture-signature","signature_type":"fixture_signature","fixture_backed":True,"status":"fixture_recertified"})
if 'sunset_review_queue' in name: fn='sunset_review_queue.json'; obj.update({"queue_id":"srq-001","candidate_reentry_package_ref":'',"sunset_delta_candidate_refs":a.sunset_delta or [],"client_sunset_notice_candidate_refs":a.notice_candidate or [],"items":[{"item_id":"item_fixture_sunset_001","priority":"low","reason":"fixture review","sunset_delta_candidate_ref":'',"client_sunset_notice_candidate_ref":'',"affected_routes":[],"affected_records":[],"replacement_refs":[],"evidence_refs":[],"recommended_action":"review_only","fixture_backed":True}],"summary":{},"safety_checks":["no_notice_sending","no_route_removal"],"status":"fixture_review_queue"})
if 'sunset_review_decision' in name: fn='sunset_review_decision.json'; obj.update({"decision_id":"srd-001","decided_at":ts(a.as_of),"decided_by":'fixture-steward',"role":'steward',"subject_refs":[],"decision":'approve_fixture_sunset_review',"rationale":"fixture only","required_actions":[],"signature":"fixture-signature","signature_type":"fixture_signature","fixture_backed":True,"status":"fixture_decision"})
if 'reentry_promotion' in name: fn='candidate_reentry_promotion_decision.json'; obj.update({"decision_id":"crd-001","decided_at":ts(a.as_of),"candidate_reentry_package_ref":'',"rollforward_acceptance_record_ref":'',"refreshed_baseline_recertification_ref":'',"refresh_compatibility_gate_report_ref":'',"sunset_review_decision_refs":[],"decision":"approved_for_fixture_candidate_review","gates":[],"required_followups":[],"evidence_refs":[],"signature":"fixture-signature","signature_type":"fixture_signature","fixture_backed":True,"status":"fixture_candidate_ready"})
if name.endswith('reentry_manifest'): fn='candidate_reentry_manifest.json'; obj.update({"reentry_manifest_id":"crm-001","candidate_reentry_package_ref":'',"rollforward_acceptance_record_ref":'',"refreshed_baseline_recertification_ref":'',"refresh_compatibility_gate_report_ref":'',"candidate_reentry_promotion_decision_ref":'',"sunset_review_queue_ref":'',"sunset_review_decision_refs":[],"artifact_refs":[],"next_lifecycle_target":"fixture_candidate_review","safety_checks":[],"status":"fixture_reentry_manifest"})
if name.endswith('reentry_ledger'): fn='candidate_reentry_ledger_manifest.json'; obj.update({"ledger_id":"crl-001","entry_refs":[],"head_entry_ref":None,"chain_hash":"sha256:fixture","source_refs":[],"safety_checks":[],"status":"fixture_reentry_ledger"}); Path(out/'candidate_reentry_ledger_entries.jsonl').write_text('')
if name.endswith('reentry_postcheck'): fn='candidate_reentry_postcheck_report.json'; obj.update({"postcheck_id":"crp-001","candidate_reentry_manifest_ref":"candidate_reentry_manifest.json","candidate_reentry_package_ref":"candidate_reentry_package.json","candidate_reentry_promotion_decision_ref":"candidate_reentry_promotion_decision.json","checks":[],"hash_checks":[],"etag_checks":[],"route_checks":[],"sunset_checks":[],"baseline_checks":[],"path_safety_checks":[],"semantic_checks":["NowCast operational","AQS 24h_validated"],"non_mutation_checks":[],"open_findings":[],"result":"pass_fixture"})
if name.endswith('summary'): print(json.dumps(obj)); raise SystemExit(0)
if has_unsafe(obj): deny('unsafe content')
if not a.dry_run: w(out/fn,obj); (out/'candidate_reentry_events.jsonl').write_text('{"event_type":"'+name+'","result":"pass"}\n')
print('PASS')
