name: 🐞 Bug Report
description: Report a reproducible defect in code, data, or metadata.
title: "[BUG] <short summary>"
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Please provide clear steps to reproduce the bug. Include provenance (paths, commit SHAs, STAC IDs), system info, and acceptance criteria.

  - type: input
    id: summary
    attributes:
      label: 🔢 Summary
      placeholder: "E.g. STAC validator fails for NOAA catalog.json"
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: ✈️ Steps to Reproduce
      placeholder: |
        1. Run `make stac-validate`
        2. Observe failure in `catalog.json`
        3. See error message
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: 🚫 Expected vs Actual
      placeholder: "Expected STAC validate to pass; it fails with ..."

  - type: input
    id: related-workflow
    attributes:
      label: 💼 Related CI Workflow or Path
      placeholder: "e.g., stac-validate.yml, data/stac/catalog.json"

  - type: textarea
    id: logs
    attributes:
      label: 🔍 Logs / Screenshots
      placeholder: "Attach log snippet, screenshot, traceback, or link to CI run"

  - type: input
    id: provenance
    attributes:
      label: 🌐 Provenance
      placeholder: "Path, STAC item ID, dataset SHA, commit SHA, etc."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 🔧 System Context
      placeholder: "Python 3.10, Ubuntu 22.04, actions/setup-node@v4"

  - type: dropdown
    id: semver
    attributes:
      label: 🔄 SemVer Impact
      options:
        - none
        - patch
        - minor
        - major
      default: 0

  - type: textarea
    id: acceptance
    attributes:
      label: 📄 Acceptance Criteria
      placeholder: "How will we know the bug is resolved? Include tests or output."
    validations:
      required: true
