name: "🐛 Bug Report"
description: "Report an error, failure, or unexpected behavior in the Kansas Frontier Matrix (KFM)."
title: "[BUG] <brief description>"
labels:
  - bug
  - validation
  - investigation-needed
assignees:
  - "@kfm-etl-ops"
  - "@bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Description
        Provide a clear and concise description of the issue.

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: "Explain what is wrong. Example: “Hazards ETL pipeline fails STAC validation for flood dataset (v9.5.0).”"
      placeholder: "What happened?"
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Affected Component(s)
      description: "Select all that apply."
      options:
        - label: "ETL / Data Pipeline"
        - label: "AI / Focus Mode"
        - label: "Frontend / MapLibre UI"
        - label: "Documentation / Metadata"
        - label: "Governance / FAIR+CARE"
        - label: "Other"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "List exact steps to reproduce the issue."
      placeholder: |
        1. run `make etl-hazards`
        2. observe console output or CI validation error
        3. attach logs or screenshots
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "Describe what should happen when the process runs successfully."
      placeholder: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "Describe what happened instead (include error text, tracebacks, or failed job links)."
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🧩 Environment"

  - type: input
    id: version_branch
    attributes:
      label: Version / Branch
      placeholder: "e.g., v9.5.0 / main"
    validations:
      required: true

  - type: input
    id: os_platform
    attributes:
      label: OS / Platform
      placeholder: "e.g., Ubuntu 22.04 / macOS 14"
    validations:
      required: true

  - type: input
    id: runtimes
    attributes:
      label: Python / Node Version
      placeholder: "e.g., Python 3.11 / Node 20"
    validations:
      required: false

  - type: input
    id: docker
    attributes:
      label: Docker / Compose Version
      placeholder: "e.g., Docker 24.0.7"
    validations:
      required: false

  - type: input
    id: workflow
    attributes:
      label: Workflow Affected
      placeholder: ".github/workflows/stac-validate.yml"
    validations:
      required: false

  - type: dropdown
    id: run_context
    attributes:
      label: Run Context
      options:
        - Local
        - CI
        - Containerized
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 📂 Logs & Evidence"

  - type: textarea
    id: logs
    attributes:
      label: Logs / Evidence
      description: "Paste relevant logs, errors, or JSON snippets. If logs exceed ~50 lines, attach a file or Gist."
      placeholder: |
        Example:
        Error: stac_validator.exceptions.STACValidationError: Missing 'license' field in item properties
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## 🧠 FAIR+CARE Impact Assessment"

  - type: dropdown
    id: fair_findable
    attributes:
      label: Findable
      description: "Impacts metadata indexing or STAC discoverability?"
      options: ["None", "Moderate", "High"]
    validations:
      required: true

  - type: dropdown
    id: fair_accessible
    attributes:
      label: Accessible
      description: "Reduces data/API accessibility or service availability?"
      options: ["None", "Moderate", "High"]
    validations:
      required: true

  - type: dropdown
    id: fair_interoperable
    attributes:
      label: Interoperable
      description: "Breaks schema or ontology compatibility?"
      options: ["None", "Moderate", "High"]
    validations:
      required: true

  - type: dropdown
    id: fair_reusable
    attributes:
      label: Reusable
      description: "Affects dataset, model, or workflow reusability?"
      options: ["None", "Moderate", "High"]
    validations:
      required: true

  - type: dropdown
    id: care_benefit
    attributes:
      label: Collective Benefit
      description: "Limits openness or public utility?"
      options: ["None", "Moderate", "High"]
    validations:
      required: true

  - type: dropdown
    id: care_ethics
    attributes:
      label: Ethical Oversight
      description: "Introduces governance or CARE concerns?"
      options: ["None", "Moderate", "High"]
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ⚙️ Governance Metadata"

  - type: textarea
    id: governance_refs
    attributes:
      label: Governance References
      description: "Confirm or update references relevant to the failing version."
      value: |
        Governance Ref: docs/standards/governance/ROOT-GOVERNANCE.md
        Manifest Ref: releases/v9.5.0/manifest.zip
        Telemetry Ref: releases/v9.5.0/focus-telemetry.json
        Data Contract: docs/contracts/data-contract-v3.json
        Ontology Alignment: ontologies/CIDOC_CRM-KFM.owl
        SBOM Ref: releases/v9.5.0/sbom.spdx.json
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## 🧾 Proposed Resolution / Next Steps"

  - type: textarea
    id: resolution
    attributes:
      label: Proposed Resolution
      description: "Provide suggestions, hypotheses, or immediate fixes."
      placeholder: "e.g., Update STAC `license` property in all flood dataset items and re-run validator."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: "Reproducible test case attached"
        - label: "FAIR+CARE impact documented"
        - label: "Governance references verified"
        - label: "Maintainers notified"

  - type: markdown
    attributes:
      value: |
        ## 🧭 Maintainer Routing
        - **Data Engineering Lead:** @kfm-etl-ops — Reproduce and verify ETL behavior  
        - **Architecture Lead:** @kfm-architecture — Evaluate workflow and CI/CD impact  
        - **AI/ML Governance:** @kfm-ai-lab — Validate AI/Focus Mode integrity  
        - **Repository Maintainer:** @bartytime4life — Approve and merge PR  

  - type: markdown
    attributes:
      value: |
        > ⚠️ **Automation Notice**  
        > Submitting this bug will trigger:
        > - FAIR+CARE validation (`.github/workflows/faircare-validate.yml`)
        > - STAC/DCAT metadata re-validation (`.github/workflows/stac-validate.yml`, `dcat-export.yml`)
        > - Provenance & hash updates in `reports/audit/ai_hazards_ledger.json`
        > - Telemetry sync to `releases/v9.5.0/focus-telemetry.json`
