---
name: "🐛 Bug Report"
about: "Report an error, failure, or unexpected behavior within the Kansas Frontier Matrix system."
title: "[BUG] <describe issue>"
labels: ["bug", "validation", "investigation-needed"]
assignees: ["@kfm-etl-ops", "@bartytime4life"]
---

## 🐛 Description

> _Provide a clear and concise description of the issue._  
> _Example: “Hazards ETL pipeline fails STAC validation for flood dataset (v9.3.2).”_

**Affected Component(s):**
- [ ] ETL / Data Pipeline  
- [ ] AI / Focus Mode  
- [ ] Frontend / MapLibre UI  
- [ ] Documentation / Metadata  
- [ ] Other  

---

## 🔍 Steps to Reproduce

1. Step one — _e.g., run `make hazards-etl`_  
2. Step two — _observe console output or validation error_  
3. Step three — _attach any error logs or screenshots below_

**Expected Behavior:**  
> _Describe what should happen when functioning correctly._

**Actual Behavior:**  
> _Describe what is happening instead (include logs or errors)._  

---

## 🧩 Environment

| Parameter | Value |
|------------|--------|
| **Version / Branch** | `<e.g., v9.3.2 / main>` |
| **OS / Platform** | `<e.g., Ubuntu 22.04 / macOS>` |
| **Python / Node Version** | `<e.g., Python 3.10 / Node 18>` |
| **Docker / Compose Version** | `<if applicable>` |
| **Workflow Affected** | `<e.g., .github/workflows/stac-validate.yml>` |

---

## 📂 Logs & Evidence

> _Attach logs, screenshots, or JSON snippets illustrating the issue._  
> _If logs exceed 50 lines, please upload as a file or GitHub Gist link._

```bash
# Example log snippet
Error: stac_validator.exceptions.STACValidationError: Missing 'license' field in item properties
```

---

## 🧠 FAIR+CARE Impact Assessment

| FAIR/CARE Category | Impact | Notes |
|--------------------|---------|-------|
| **Findable** | ☐ None ☐ Moderate ☐ High | _Does this issue affect metadata indexing or STAC discoverability?_ |
| **Accessible** | ☐ None ☐ Moderate ☐ High | _Does it limit data/API accessibility?_ |
| **Interoperable** | ☐ None ☐ Moderate ☐ High | _Does it break schema compatibility?_ |
| **Reusable** | ☐ None ☐ Moderate ☐ High | _Does it reduce dataset or model reusability?_ |
| **Collective Benefit** | ☐ None ☐ Moderate ☐ High | _Does this bug risk community utility or fairness?_ |

---

## ⚙️ Governance Metadata

| Field | Reference |
|--------|------------|
| **Governance Ref** | `docs/standards/governance/ROOT-GOVERNANCE.md` |
| **Manifest Ref** | `releases/v9.3.2/manifest.zip` |
| **Telemetry Ref** | `releases/v9.3.2/focus-telemetry.json` |
| **Data Contract** | `docs/contracts/data-contract-v3.json` |
| **Ontology Alignment** | `ontologies/CIDOC_CRM-KFM.owl` |

> _Ensure all referenced documents are up to date with the version that triggered the issue._

---

## 🧾 Proposed Resolution / Next Steps

> _Provide suggestions, hypotheses, or steps that may resolve the issue._  
> _Example: “Re-run STAC validator after updating schema property fields.”_

- [ ] Reproducible test case included  
- [ ] FAIR+CARE impact assessed  
- [ ] Governance metadata verified  
- [ ] Maintainers notified  

---

## 🧭 Maintainer Routing

| Role | Reviewer | Required Action |
|------|-----------|-----------------|
| **Data Engineering Lead** | @kfm-etl-ops | Reproduce ETL behavior |
| **Architecture Lead** | @kfm-architecture | Review workflow impact |
| **AI/ML Governance** | @kfm-ai-lab | Validate AI pipeline consistency |
| **Repository Maintainer** | @bartytime4life | Approve fix and merge PR |

---

> ⚠️ **Note:**  
> Filing this bug report automatically triggers:  
> - FAIR+CARE validation workflow (`.github/workflows/faircare-validate.yml`)  
> - STAC and schema re-validation pipeline (`.github/workflows/stac-validate.yml`)  
> - Provenance entry in `reports/audit/ai_hazards_ledger.json`  

---

**Kansas Frontier Matrix** · *Reproducibility × Transparency × Ethical AI*  
[🔗 Repository](https://github.com/bartytime4life/Kansas-Frontier-Matrix) • [🧭 Docs Portal](../../../docs/) • [⚖️ Governance Ledger](../../../docs/standards/governance/)