name: "💡 Feature Request"
description: "Propose a new feature, enhancement, or workflow — MCP-compliant & reproducible"
title: "[Feature]: <short summary>"
labels:

* enhancement
* needs-triage
  assignees:
* kfm-architecture
* kfm-data

# KFM header metadata (for humans)

# version: v2.3.0

# last_updated: 2025-10-15

# owners: @kfm-architecture @kfm-data

body:

* type: markdown
  attributes:
  value: |
  ## 💡 Summary
  *“Every Feature Builds the Future — Every Change is Reproducible.”*
  Please describe the requested enhancement and its purpose.
  > Example: Add slope classification to terrain pipeline outputs and enable gradient visualization in MapLibre.

* type: textarea
  id: summary
  attributes:
  label: Summary
  description: Describe the feature or enhancement and its purpose.
  placeholder: |
  - Add slope classification to terrain pipeline
  - Create new visualization layer in MapLibre for terrain gradients
  validations:
  required: true

* type: markdown
  attributes:
  value: "## 🧠 Context"

* type: input
  id: module
  attributes:
  label: Module / Workflow
  description: File or workflow impacted
  placeholder: terrain_pipeline.py | src/pipelines/hydro/flow_accumulation.py | web/config/layers.json
  validations:
  required: true

* type: dropdown
  id: domain
  attributes:
  label: Data Domain
  options:
  - Terrain
  - Hydrology
  - Hazards
  - Landcover
  - Climate
  - Knowledge Graph
  - Web / UI
  - API
  - Text / AI / NLP
  - Metadata / Governance
  - CI/CD
  - Other
  multiple: true
  validations:
  required: true

* type: input
  id: branch_commit
  attributes:
  label: Target Branch / Commit (if applicable)
  placeholder: main | feature/terrain-upgrade | 1a2b3c4
  validations:
  required: false

* type: input
  id: environment
  attributes:
  label: Environment
  description: OS, Python/Node versions, container image hash, runner type
  placeholder: Ubuntu 22.04 · Python 3.11 · Node 20.x · gh-runner=ubuntu-latest
  validations:
  required: false

* type: markdown
  attributes:
  value: "## 🧩 Problem Statement"

* type: textarea
  id: limitation
  attributes:
  label: Current Limitation
  placeholder: "Describe the limitation, gap, or inefficiency this feature resolves."
  validations:
  required: true

* type: markdown
  attributes:
  value: "## 🧩 Proposed Solution"

* type: textarea
  id: proposal
  attributes:
  label: Proposed Implementation
  description: Include technical details, architecture impacts, or data flow changes.
  placeholder: |
  - Extend terrain_pipeline.py with --add-slope-classification
  - Generate slope class COG and add STAC property slope_class_version
  - Update layers.json with new map style
  validations:
  required: true

* type: checkboxes
  id: change_types
  attributes:
  label: Change Type(s)
  options:
  - label: Add new data transformation module
  - label: Modify ETL pipeline step
  - label: Extend STAC metadata/schema
  - label: Create new visualization layer
  - label: Update documentation / SOP
  - label: Other (describe in proposal)

* type: markdown
  attributes:
  value: "## 🧮 Expected Outcome"

* type: textarea
  id: expected
  attributes:
  label: Expected Result / Metrics
  placeholder: |
  | Metric              | Target                                   |
  | :------------------ | :----------------------------------------|
  | Data Quality        | Slope class attribute added; STAC fields updated |
  | Reproducibility     | Deterministic outputs; SOP updated       |
  | Usability           | Map layer toggle + legend                |
  | Performance         | < +5% runtime impact                     |
  render: markdown
  validations:
  required: true

* type: markdown
  attributes:
  value: "## ⚙️ Implementation Plan"

* type: textarea
  id: plan
  attributes:
  label: Steps & Owners
  placeholder: |
  1) Draft ADR (docs/adr/ADR-XXXX-feature.md) — Owner …
  2) Implement code — Owner …
  3) Add unit/integration tests — Owner …
  4) Update STAC + documentation — Owner …
  5) Review + merge — Owner …
  validations:
  required: false

* type: markdown
  attributes:
  value: "## 🧭 Versioning Impact (SemVer / STAC)"

* type: textarea
  id: versioning
  attributes:
  label: Versioning Summary
  placeholder: |
  | Scope                 | Current | Proposed | Notes                |
  | :-------------------- | :------ | :------- | :------------------- |
  | Dataset / STAC Schema | v1.2.0  | v1.3.0   | Add slope metadata   |
  | Pipeline / Script     | v2.0.0  | v2.1.0   | Terrain ETL refactor |
  | Repo (SemVer)         | v1.4.0  | v1.5.0   | Minor feature add    |
  render: markdown
  validations:
  required: false

* type: markdown
  attributes:
  value: "## 🧾 Impact Assessment"

* type: dropdown
  id: impact
  attributes:
  label: Expected Impact
  options:
  - "🟩 Minor"
  - "🟨 Moderate"
  - "🟧 Major"
  - "🟥 Critical"
  validations:
  required: true

* type: textarea
  id: downstream
  attributes:
  label: Downstream Effects
  description: Describe affected modules, datasets, or users.
  placeholder: |
  - Web map layer updates required
  - New STAC schema affects validation workflow
  - Adds new CLI option for terrain processing
  validations:
  required: false

* type: markdown
  attributes:
  value: "## ✅ MCP Compliance Checklist"

* type: checkboxes
  id: mcp_checklist
  attributes:
  label: MCP Principles
  options:
  - label: Documentation-first — Clear summary + structured context
  required: true
  - label: Reproducibility — Deterministic steps + versioning impact
  required: true
  - label: Open Standards — STAC/JSON Schema alignment
  required: true
  - label: Provenance — STAC metadata and ADR references included
  required: true
  - label: Auditability — PR and issue linkage with reproducible steps
  required: true
  - label: Versioning — SemVer / STAC updated with change
  required: true

* type: markdown
  attributes:
  value: "## 🧩 Related Issues / References"

* type: textarea
  id: related
  attributes:
  label: Related Links
  description: Link PRs, similar issues, affected STAC items, ADRs, SOPs.
  placeholder: |
  - PR: #789
  - Similar: #456
  - STAC: data/stac/items/terrain_ks_2020.json
  - Docs: docs/sop/terrain_pipeline.md
  validations:
  required: false

* type: textarea
  id: notes
  attributes:
  label: Additional Notes
  description: Screenshots, mockups, or rationale for prioritization
  validations:
  required: false

---
