# üêû Kansas Frontier Matrix ‚Äî Bug Report Template
# File: .github/ISSUE_TEMPLATE/bug_report.yml
# Purpose: Governance-aware issue form for reporting software, data, or workflow defects.
# Alignment: MCP-DL v6.3 ¬∑ KFM-MDP v11.2.5 ¬∑ FAIR+CARE ¬∑ KFM-OP v11 ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©
# SPDX-License-Identifier: CC-BY-4.0

name: "üêû Bug Report"
description: "Report an error, malfunction, or unexpected behavior in the Kansas Frontier Matrix system."
title: "Bug: [Short Description]"
labels:
  - "bug"
  - "triage"
assignees:
  - "bartytime4life"

body:

  - type: markdown
    attributes:
      value: |
        ## üêû Bug Report

        Please describe the issue clearly and reproducibly. Reports should comply with **MCP-DL v6.3**, **KFM-MDP v11.2.5**, and **FAIR+CARE** governance.

        > ‚ö†Ô∏è **Security & Sovereignty**
        >
        > If this issue involves a potential **security vulnerability**, **sensitive locations**, or **Indigenous / CARE-governed data**, follow the guidance in `.github/SECURITY.md` and governance forms instead of sharing sensitive details publicly.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Short summary of the issue."
      placeholder: "Example: Treaty polygons fail to load on initial map render."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List all steps needed to consistently reproduce the issue."
      placeholder: |
        1. Open http://localhost:3000
        2. Enable 'Historical Treaties' layer
        3. Zoom into Kansas region
        4. Observe console error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "Example: Map should load and display all treaty polygons."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Example: Console shows `TypeError: Cannot read property 'coordinates' of undefined`."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs or Screenshots"
      description: "Console logs, stack traces, error objects, screenshots. Omit secrets, API keys, or sensitive coordinates."
      placeholder: |
        Traceback (most recent call last):
          File "src/api/routes/map.py", line 42, in get_layers
            raise ValueError("Missing STAC ID")
        ValueError: Missing STAC ID
      render: shell
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: "Environment Details"
      description: "Platform and version where this issue occurred."
      placeholder: "macOS 14 ¬∑ Chrome 120 ¬∑ Python 3.11 ¬∑ Node 18"
    validations:
      required: true

  - type: input
    id: kfm_versions
    attributes:
      label: "KFM Version / Branch"
      description: "Which KFM version, branch, or commit were you using?"
      placeholder: "v11.2.5 ¬∑ branch: main ¬∑ commit: abc1234"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity Level"
      description: "How severe is this issue?"
      options:
        - "üü• Critical ‚Äî System crash, data loss, or security impact"
        - "üüß High ‚Äî Major workflow or feature broken"
        - "üü® Medium ‚Äî Partial functionality broken"
        - "üü© Low ‚Äî Minor or cosmetic issue"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: pipeline_stage
    attributes:
      label: "Affected Pipeline Stage"
      description: "Where in the KFM pipeline is this issue occurring?"
      options:
        - "Deterministic ETL (data ingestion/validation)"
        - "Catalogs (STAC/DCAT/PROV metadata)"
        - "Knowledge Graph (Neo4j)"
        - "API Layer (FastAPI/GraphQL)"
        - "Web UI (React/MapLibre/Cesium)"
        - "Story Nodes / Focus Mode"
        - "CI/CD & Infra (.github workflows, deployment)"
        - "Other (explain in 'Related Files / IDs')"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: data_sensitivity
    attributes:
      label: "Data Sensitivity / Sovereignty"
      description: "Does this issue involve governed, sensitive, or Indigenous data?"
      options:
        - "Public / Non-sensitive data only"
        - "Potentially sensitive (location, personal, ecological)"
        - "Indigenous / CARE-governed data"
        - "Unknown / Not sure"
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: governance_flags
    attributes:
      label: "Security / Governance Flags"
      description: "Help us route this issue correctly."
      options:
        - label: "May be a security vulnerability (see `.github/SECURITY.md`)."
        - label: "May expose sensitive locations or Indigenous / CARE-governed data."
        - label: "Impacts AI-generated narratives (Story Nodes / Focus Mode)."
        - label: "Appears to be a data quality, lineage, or provenance issue."
    validations:
      required: false

  - type: textarea
    id: related_files
    attributes:
      label: "Related Files, IDs, or Directories"
      description: "Paths, IDs, or endpoints directly involved in this issue."
      placeholder: |
        e.g.
        - src/pipelines/etl/noaa_ingest.py
        - src/graph/migrations/2025_11_add_treaty_nodes.cypher
        - src/api/routes/map.py
        - web/src/components/TimelineView/index.tsx
        - data/stac/treaties/collection.json
        - Story Node IDs, STAC/DCAT IDs, PROV URNs, or API routes
    validations:
      required: false

  - type: checkboxes
    id: validation_steps
    attributes:
      label: "Pre-Submission Checklist"
      description: "Confirm the following before submitting:"
      options:
        - label: "I have reproduced the issue at least twice."
          required: true
        - label: "I verified the issue still occurs on the latest `main` branch."
          required: true
        - label: "I checked open issues to prevent duplicates."
          required: true
        - label: "I included complete reproduction steps and, where possible, logs/screenshots."
          required: true

  - type: markdown
    attributes:
      value: |
        ## üß© Validation, Governance & Telemetry

        Submitting this bug triggers automated CI/CD workflows, including:

        - **codeql.yml** ‚Äî Static analysis & security scanning  
        - **docs_validate.yml** ‚Äî KFM-MDP v11.2.5 doc & metadata validation  
        - **faircare_validate.yml** ‚Äî FAIR+CARE / sovereignty checks (where applicable)  
        - **security_audit.yml** ‚Äî Dependency & container scanning  
        - **telemetry_export.yml** ‚Äî CI/CD & sustainability telemetry logging  

        Governance & telemetry artifacts update automatically:

        - `docs/reports/audit/github-workflows-ledger.json`
        - `releases/*/focus-telemetry.json`

        Your report strengthens the KFM ecosystem by ensuring:

        - Reliability  
        - Ethical & sovereign-compliant behavior  
        - Reproducibility & transparent provenance  
        - Safety for users, communities, and environments  

        **¬© 2025 Kansas Frontier Matrix ‚Äî MIT / CC-BY 4.0**  
        FAIR+CARE Certified ¬∑ MCP-DL v6.3 ¬∑ KFM-MDP v11.2.5 ¬∑ KFM-OP v11.0  
        Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified