# üêû Kansas Frontier Matrix ‚Äî Bug Report Template  
# File: .github/ISSUE_TEMPLATE/bug_report.yaml  
# Purpose: Standardized issue form for reporting software, data, or workflow bugs.  
# Alignment: Master Coder Protocol (MCP v6.3) ¬∑ FAIR+CARE ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©  
# SPDX-License-Identifier: CC-BY-4.0  

name: "üêû Bug Report"
description: "Report an error, malfunction, or unexpected behavior in the Kansas Frontier Matrix system."
title: "Bug: [Short Description]"
labels:
  - "bug"
  - "triage"
assignees:
  - "bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## üêû Bug Report  
        Please use this form to describe the issue in detail.  
        Ensure your report is **clear, reproducible, and complete**.  
        This helps maintainers verify the problem quickly and preserve project stability under the **Master Coder Protocol (MCP v6.3)**.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a short summary of the issue."
      placeholder: "Example: Timeline map fails to render events on load."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List all necessary steps to reproduce the issue."
      placeholder: |
        1. Open http://localhost:3000
        2. Enable 'Historical Treaties' layer
        3. Zoom into Kansas region
        4. Observe console error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "Example: Map should load and display all treaty polygons without errors."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Example: Console displays `TypeError: Cannot read property 'coordinates' of undefined`."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs or Screenshots"
      description: "Attach console logs, stack traces, or screenshots to help reproduce the issue."
      placeholder: |
        ```bash
        Traceback (most recent call last):
          File "src/api/routes/map.py", line 42, in get_layers
            raise ValueError("Missing STAC ID")
        ValueError: Missing STAC ID
        ```
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: "Environment Details"
      description: "System or environment where this bug occurred."
      placeholder: "e.g. macOS 14.0, Chrome 120, Python 3.11, Node.js 18"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity Level"
      description: "Rate the impact of this issue."
      options:
        - "üü• Critical ‚Äî System crash or data loss"
        - "üüß High ‚Äî Major function broken"
        - "üü® Medium ‚Äî Minor function or visual defect"
        - "üü© Low ‚Äî Cosmetic or documentation issue"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "Affected Component"
      description: "Select the area of the system where the issue occurs."
      options:
        - "ETL Pipeline (data ingestion/validation)"
        - "AI/ML Components (Focus Mode, NER, summarization)"
        - "API Layer (FastAPI/GraphQL)"
        - "Frontend (React/MapLibre)"
        - "Docs/Workflows (.github actions)"
        - "Other (please describe below)"
      default: 0
    validations:
      required: true

  - type: textarea
    id: related_files
    attributes:
      label: "Related Files or Directories"
      description: "If applicable, specify file paths affected by this issue."
      placeholder: |
        Example:
        - src/pipelines/etl/noaa_ingest.py  
        - web/src/components/TimelineView/index.tsx
    validations:
      required: false

  - type: checkboxes
    id: validation_steps
    attributes:
      label: "Pre-Submission Checklist"
      description: "Please confirm you‚Äôve completed the following before submitting:"
      options:
        - label: "I have reproduced the issue at least twice."
          required: true
        - label: "I have confirmed the issue persists on the latest `main` branch."
          required: true
        - label: "I have reviewed open issues to ensure this bug has not been reported."
          required: true
        - label: "I have provided clear reproduction steps and relevant logs."
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### üß© Validation & Governance Workflow  
        Submitting this bug automatically triggers the following CI/CD pipelines:

        - **`codeql.yml`** ‚Üí Static code analysis & security scanning  
        - **`docs-lint.yml`** ‚Üí Documentation & metadata validation  
        - **`faircare-validate.yml`** ‚Üí Ethical/CARE compliance review  

        If relevant, this issue will also appear in the **Governance Ledger**:

        ```text
        reports/audit/github-workflows-ledger.json
        ```

        **Thank you for strengthening the Kansas Frontier Matrix.**  
        Your report helps maintain a secure, ethical, and reproducible platform aligned with **MCP v6.3** and **FAIR+CARE**.

        **¬© 2025 Kansas Frontier Matrix ‚Äî MIT / CC-BY 4.0**
