name: "🐞 Bug Report"
description: "Report a reproducible defect in code, data, or metadata."
title: "[BUG] <short summary>"
labels:
  - bug
  - needs-triage
assignees:
  - kfm-architecture

body:
  - type: markdown
    attributes:
      value: |
        ## 🔢 MCP-DL Bug Report Template
        Please provide **clear steps to reproduce**, **expected vs actual behavior**, and detailed **provenance** (paths, STAC IDs, commit SHAs, etc.). This ensures issues are **traceable**, **reproducible**, and **MCP-compliant**.

  - type: input
    id: summary
    attributes:
      label: 📅 Bug Summary
      description: Short description of the problem
      placeholder: "STAC validator fails for NOAA catalog.json"
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: ✈️ Steps to Reproduce
      description: Detailed reproducible steps
      placeholder: |
        1. Run `make stac-validate`
        2. Observe failure on `catalog.json`
        3. See: "Missing required field..."
    validations:
      required: true

  - type: textarea
    id: expected_actual
    attributes:
      label: 🚫 Expected vs Actual Behavior
      description: Contrast expected vs observed behavior
      placeholder: |
        **Expected:** Valid STAC returns status 0
        **Actual:** CLI exits with error `missing links`
    validations:
      required: true

  - type: dropdown
    id: semver
    attributes:
      label: 🔄 SemVer Impact
      description: What version scope does this bug impact?
      options:
        - none
        - patch (no breaking changes)
        - minor (non-breaking but visible)
        - major (breaking or schema-level)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 🔍 Logs or Evidence
      description: Paste log excerpts, errors, screenshots, or links
      placeholder: "Upload error trace, screenshots, or CI links"

  - type: input
    id: system
    attributes:
      label: 🔧 System Context
      description: Environment information (OS, container, runtime)
      placeholder: "Ubuntu 22.04 · Python 3.10 · actions/setup-node@v4"

  - type: input
    id: provenance
    attributes:
      label: 🌐 Provenance
      description: Affected paths, commit SHAs, dataset IDs, STAC items
      placeholder: "data/stac/catalog.json · commit abcd1234 · STAC: noaa_l4_sst.json"
    validations:
      required: true

  - type: textarea
    id: proposed_fix
    attributes:
      label: ✅ Proposed Fix (optional)
      description: Describe possible solution, workaround, or patch location
      placeholder: "Missing 'self' link — add to STAC Item under 'links' block"

  - type: textarea
    id: acceptance
    attributes:
      label: 📄 Acceptance Criteria
      description: Define what resolution looks like (test, output, command)
      placeholder: "`make stac-validate` returns code 0 with no errors"
    validations:
      required: true
