name: "📦 Data Submission"
description: "Submit a new dataset, metadata file, or update for integration into the Kansas Frontier Matrix (KFM)."
title: "[DATA SUBMISSION] <dataset title or identifier>"
labels: ["data-submission", "governance-review", "FAIR+CARE"]
assignees:
  - "@kfm-data-lab"
  - "@kfm-etl-ops"
  - "@bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## 📦 Dataset Overview
        Provide a concise summary of the dataset being submitted.
        Example: “Submitting 2025 Kansas drought severity index data from NOAA CPC.”

  - type: input
    id: dataset_name
    attributes:
      label: Dataset Name
      description: "Official dataset title or identifier"
      placeholder: "Kansas Hydrology Survey 2025"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose of Submission
      description: "Explain how this dataset contributes to KFM goals or FAIR+CARE ethics."
    validations:
      required: true

  - type: input
    id: source_url
    attributes:
      label: Access URL or API Endpoint
      description: "Provide a direct link or endpoint if available."
      placeholder: "https://data.noaa.gov/dataset/XXXX"
    validations:
      required: false

  - type: textarea
    id: license
    attributes:
      label: License / Usage Terms
      description: "Specify the license or data usage restrictions (e.g., CC-BY 4.0, Public Domain)."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Dataset Type
      options:
        - 🌍 Geospatial / Environmental
        - 🧭 Historical / Archival
        - 🧠 AI Training or Model Input
        - ⚡ Infrastructure / Energy
        - 📊 Tabular / Statistical
        - Other
    validations:
      required: true

  - type: textarea
    id: governance
    attributes:
      label: Governance Metadata
      description: "Include manifest, governance, and ontology references."
      value: |
        Governance Ref: docs/standards/governance/ROOT-GOVERNANCE.md  
        Manifest Ref: releases/v9.5.0/manifest.zip  
        Telemetry Ref: releases/v9.5.0/focus-telemetry.json  
        Data Contract: docs/contracts/data-contract-v3.json  
        Ontology Alignment: ontologies/CIDOC_CRM-KFM.owl

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Notes or Attachments
      description: "Upload metadata, sample files, or other supporting info."
