# üó∫Ô∏è Kansas Frontier Matrix ‚Äî Data Submission Template
# File: .github/ISSUE_TEMPLATE/data_submission.yml
# Purpose: Structured, governance-aware form for submitting new datasets or geospatial layers to KFM.
# Alignment: MCP-DL v6.3 ¬∑ KFM-MDP v11.0 ¬∑ FAIR+CARE ¬∑ KFM-OP v11.0 ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©
# SPDX-License-Identifier: CC-BY-4.0

name: "üó∫Ô∏è Data Submission"
description: "Submit a new dataset, STAC item, or geospatial layer for inclusion in the Kansas Frontier Matrix."
title: "Dataset Submission: [Dataset Name or ID]"
labels:
  - "data"
  - "stac"
  - "faircare"
assignees:
  - "bartytime4life"

body:

  - type: markdown
    attributes:
      value: |
        ## üó∫Ô∏è Kansas Frontier Matrix ‚Äî Data Submission Form
        Thank you for contributing a dataset to the **Kansas Frontier Matrix (KFM)**.
        All submissions undergo validation under:
        - **MCP-DL v6.3**
        - **KFM-MDP v11**
        - **FAIR+CARE governance**
        - **Sovereignty & ethics policies**
        - **Diamond‚Åπ Œ© / Crown‚àûŒ© safety protocols**

        Please complete each required section with accurate, verifiable metadata.

  - type: input
    id: dataset_id
    attributes:
      label: "Dataset ID"
      description: "Unique, lowercase identifier using underscores. This becomes the dataset‚Äôs KFM-STAC ID."
      placeholder: "e.g. noaa_storm_events_1950_2025"
    validations:
      required: true

  - type: input
    id: dataset_title
    attributes:
      label: "Dataset Title"
      description: "Human-readable descriptive title."
      placeholder: "e.g. NOAA Storm Events Archive (1950‚Äì2025)"
    validations:
      required: true

  - type: textarea
    id: dataset_description
    attributes:
      label: "Dataset Description"
      description: "Detailed description of the dataset‚Äôs purpose, contents, limitations, and relevant context."
      placeholder: |
        Example:
        This dataset includes recorded severe weather events across Kansas
        (tornadoes, hail, floods, thunderstorms) from 1950‚Äì2025, sourced from
        NOAA NCEI. Intended for historical analysis, climate visualization, and
        hazard trend modeling.
    validations:
      required: true

  - type: dropdown
    id: dataset_type
    attributes:
      label: "Dataset Type"
      description: "Select the dataset‚Äôs general category."
      options:
        - "Raster (GeoTIFF, COG)"
        - "Vector (GeoJSON, Shapefile)"
        - "Tabular (CSV, TSV, JSON)"
        - "Textual / Document (OCR, transcripts)"
        - "Other (specify below)"
      default: 0
    validations:
      required: true

  - type: textarea
    id: source_provenance
    attributes:
      label: "Source & Provenance"
      description: "Explain exactly where this data came from and who created it. Include URLs or citations."
      placeholder: |
        e.g.
        NOAA NCEI Storm Events Database
        https://www.ncei.noaa.gov/
    validations:
      required: true

  - type: input
    id: license
    attributes:
      label: "License"
      description: "Use an SPDX identifier, Creative Commons license, or public-domain designation."
      placeholder: "e.g. CC-BY-4.0, CC0-1.0, Public Domain (US Gov Works)"
    validations:
      required: true

  - type: input
    id: checksum
    attributes:
      label: "Checksum (SHA-256)"
      description: "Provide SHA-256 for at least one core file to ensure dataset integrity."
      placeholder: "sha256-012345abcdef..."
    validations:
      required: true

  - type: textarea
    id: spatial_extent
    attributes:
      label: "Spatial Coverage (Bounding Box in EPSG:4326)"
      description: "Provide WGS84 bounding box coordinates."
      placeholder: "[-102.05, 37.00, -94.60, 40.00]"
    validations:
      required: true

  - type: textarea
    id: temporal_extent
    attributes:
      label: "Temporal Coverage"
      description: "Specify start and end dates (ISO-8601)."
      placeholder: "{ start: '1950-01-01', end: '2025-05-01' }"
    validations:
      required: true

  - type: textarea
    id: keywords
    attributes:
      label: "Keywords / Tags"
      description: "Metadata tags to support FAIR discoverability."
      placeholder: "e.g. climate, tornado, hazards, noaa, kansas, historical"
    validations:
      required: true

  - type: textarea
    id: data_access
    attributes:
      label: "Data Access URL(s)"
      description: "Direct download links or API endpoints where the dataset can be retrieved."
      placeholder: |
        e.g.
        https://www.ncei.noaa.gov/access/search/storm-events
    validations:
      required: true

  - type: dropdown
    id: care_relevance
    attributes:
      label: "CARE Relevance"
      description: "Does this dataset relate to Indigenous, tribal, or culturally sensitive information?"
      options:
        - "No ‚Äî not applicable"
        - "Yes ‚Äî contains Indigenous-related or culturally sensitive information"
        - "Uncertain ‚Äî needs governance review"
      default: 0
    validations:
      required: true

  - type: textarea
    id: care_statement
    attributes:
      label: "CARE Statement (if applicable)"
      description: "Describe adherence to CARE principles for culturally sensitive datasets."
      placeholder: |
        Example:
        This dataset includes historical treaty boundaries validated through collaboration with tribal offices.
        Approved for publication with attribution.
    validations:
      required: false

  - type: checkboxes
    id: compliance_checklist
    attributes:
      label: "Contributor Checklist"
      description: "Confirm dataset meets FAIR+CARE governance requirements."
      options:
        - label: "Dataset complies with FAIR principles (F1¬∑A1¬∑I1¬∑R1)."
          required: true
        - label: "Dataset respects CARE principles where applicable."
          required: true
        - label: "Checksums, metadata, and provenance provided accurately."
          required: true
        - label: "I understand dataset will undergo STAC/DCAT + FAIR+CARE validation."
          required: true

  - type: markdown
    attributes:
      value: |
        ## üß™ Validation Workflows

        When this issue is submitted, the following CI/CD workflows automatically run:

        - **stac-validate.yml** ‚Üí STAC schema, bbox, license, checksum verification  
        - **dcat-validate.yml** ‚Üí DCAT dataset validation (if JSON-LD provided)  
        - **faircare-validate.yml** ‚Üí FAIR+CARE and Sovereignty governance review  
        - **docs-validate.yml** ‚Üí Markdown/YAML/JSON linting under KFM-MDP v11  
        - **security_audit.yml** ‚Üí Dependency + container vulnerability scanning  
        - **telemetry_export.yml** ‚Üí CI/CD + sustainability metrics logged to telemetry  

        Validation artifacts are saved under:

        ```
        reports/self-validation/stac/
        reports/fair/
        reports/self-validation/dcat/
        ```

        Telemetry & governance artifacts flow into:

        ```
        releases/v11.0.1/focus-telemetry.json
        docs/reports/audit/governance-ledger.json
        ```

        **Thank you for contributing open, ethical, FAIR+CARE-compliant data to the Kansas Frontier Matrix.**  
        Upholding reproducibility, transparency, and sovereign data stewardship.

        **¬© 2025 Kansas Frontier Matrix ‚Äî CC-BY 4.0**  
        FAIR+CARE Certified ¬∑ MCP-DL v6.3 ¬∑ KFM-MDP v11.0 ¬∑ KFM-OP v11.0  
        Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified
