name: "🗃️ Data Request"
description: "Propose a new dataset/integration — documented, provenanced, reproducible, and MCP-DL v6.3 compliant."
title: "[Data]: <dataset name> — <domain>"
labels:
  - data-request
  - needs-triage
assignees:
  - kfm-data
  - kfm-architecture

# ⛳ Kansas Frontier Matrix · Data Request Form (MCP-DL v6.3)
# This GitHub Issue Form captures everything needed to evaluate and integrate a new dataset:
# provenance, licensing, schema, ethics, format, STAC linkage, ETL targets, and CI validation.

# KFM metadata (informational)
# version: v2.3.0
# last_updated: 2025-10-18
# owners: @kfm-data @kfm-architecture

body:
  - type: markdown
    attributes:
      value: |
        ## 🧞 Dataset Overview
        *“Every Dataset Documented. Every Source Proven. Every Integration Reproducible.”*

  - type: input
    id: dataset_name
    attributes:
      label: Dataset Name
      placeholder: "USGS 3DEP LiDAR DEM (Kansas), NOAA Drought Monitor 1990–2024"
    validations:
      required: true

  - type: input
    id: source_org
    attributes:
      label: Primary Source / Organization
    validations:
      required: true

  - type: input
    id: program
    attributes:
      label: Program / Product Line (if applicable)
      placeholder: "USGS 3DEP; NOAA NCEI; Daymet v4; USDA SSURGO; FEMA FIRM; KGS DASC"

  - type: dropdown
    id: data_type
    attributes:
      label: Data Type
      options:
        - Raster
        - Vector
        - Tabular
        - Text
        - NetCDF
        - Mixed
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: License
      options:
        - Public Domain
        - CC-BY 4.0
        - CC0
        - CC-BY-SA
        - Government Works
        - Restricted
        - Other
    validations:
      required: true

  - type: input
    id: spatial_coverage
    attributes:
      label: Spatial Coverage
      placeholder: "Statewide Kansas; Flint Hills; Kansas River Basin; Multi-State"
    validations:
      required: true

  - type: input
    id: temporal_range
    attributes:
      label: Temporal Range
      placeholder: "1850–2025; 1991–2020 normals; daily (1980–present)"
    validations:
      required: true

  - type: dropdown
    id: update_frequency
    attributes:
      label: Update Frequency
      options:
        - Real-Time
        - Daily
        - Weekly
        - Monthly
        - Quarterly
        - Annual
        - Irregular/On-Demand
        - Static/Historical
    validations:
      required: true

  - type: input
    id: access_url
    attributes:
      label: Access URL / API Endpoint / Catalog
      placeholder: "Direct download, REST API base, STAC catalog URL"
    validations:
      required: true

  - type: input
    id: citation
    attributes:
      label: Citation / DOI / Reference
      placeholder: "DOI:10.5066/P9Z3D4AR or dataset page URL"

  - type: input
    id: steward
    attributes:
      label: Contact / Data Steward
      placeholder: "Maintainer email or org contact (if applicable)"

  - type: markdown
    attributes:
      value: "## 🌐 Data Source Provenance"

  - type: textarea
    id: provenance
    attributes:
      label: Source Provenance
      description: "Official source link(s), screenshots/quotes, reliability and QA/QC notes"
      placeholder: |
        - Official source URL(s)
        - Why trustworthy (QA/QC, peer review, agency standards)
        - Mirror locations (if any) + checksum references
    validations:
      required: true

  - type: dropdown
    id: access_method
    attributes:
      label: Access Method
      options:
        - REST API
        - HTTP/HTTPS
        - FTP
        - Open Data Portal
        - Bulk Download
        - STAC
    validations:
      required: true

  - type: textarea
    id: api_details
    attributes:
      label: API/Auth Details (if applicable)
      description: "Headers, auth, rate limits, pagination, throttling"
      placeholder: |
        - Auth: none | token | key | OIDC
        - Rate limits: 60 req/min
        - Pagination: ?page= / ?limit=
        - Example request/response

  - type: textarea
    id: formats
    attributes:
      label: Data Format(s)
      placeholder: "GeoTIFF (COG), Shapefile, GeoJSON, CSV, NetCDF, Parquet, TIFF+worldfile"
    validations:
      required: true

  - type: input
    id: crs
    attributes:
      label: Coordinate System / Projection (CRS)
      placeholder: "EPSG:4326 WGS84; EPSG:26914 NAD83 Kansas South; mixed → convert to 4326"
    validations:
      required: true

  - type: input
    id: resolution_scale
    attributes:
      label: Resolution / Scale (if applicable)
      placeholder: "10 m; 30 m; 1 km; 1:24,000"

  - type: textarea
    id: quality
    attributes:
      label: Quality Assurance / QA References
      placeholder: "Agency QA/QC docs, accuracy statements, peer-reviewed references"

  - type: markdown
    attributes:
      value: "## 🤩 Intended Integration"

  - type: input
    id: pipeline
    attributes:
      label: Pipeline Target
      placeholder: "hydrology_pipeline.py; climate_etl.py; src/pipelines/text/ocr_nlp.py"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Data Domain
      options:
        - Terrain
        - Hydrology
        - Hazards
        - Climate
        - Landcover
        - Text
        - Tabular
        - Other
    validations:
      required: true

  - type: dropdown
    id: stac_linkage
    attributes:
      label: STAC Linkage
      options:
        - "Yes — new Collection + Items"
        - "Yes — Items in existing Collection"
        - "No/Not applicable"
    validations:
      required: true

  - type: dropdown
    id: visualization
    attributes:
      label: Visualization Layer
      options:
        - Web Map
        - Timeline
        - Story Map
        - 3D Scene
        - API only
    validations:
      required: true

  - type: input
    id: ontology
    attributes:
      label: Semantic Ontology Tag(s)
      placeholder: "CIDOC CRM class (E73), OWL-Time interval, PeriodO ID"

  - type: markdown
    attributes:
      value: "## 🤝 Ethics & Usage"

  - type: dropdown
    id: data_ethics
    attributes:
      label: Data Ethics Classification
      description: "Sensitive/Indigenous/cultural usage constraints"
      options:
        - open
        - restricted-derivatives
        - no-public-artifacts
    validations:
      required: true

  - type: textarea
    id: usage_notes
    attributes:
      label: Usage Constraints / Fair Use Notes
      placeholder: "Attribution, downstream license, embargo notes, community guidelines"

  - type: markdown
    attributes:
      value: "## 🤠 Metadata & Schema"

  - type: textarea
    id: attributes_cols
    attributes:
      label: Attributes / Columns
      description: "List key attributes (e.g., elevation, slope, drought_index)"
    validations:
      required: true

  - type: textarea
    id: units
    attributes:
      label: Units
      placeholder: "m, °C, %, index, class code"
    validations:
      required: true

  - type: input
    id: schema_url
    attributes:
      label: Schema Source / URL
      placeholder: "Link to metadata XML/JSON, or documentation"

  - type: input
    id: encoding
    attributes:
      label: Encoding / Format
      placeholder: "UTF-8 / GeoTIFF / EPSG:4326"
    validations:
      required: true

  - type: textarea
    id: example_snippet
    attributes:
      label: Example Snippet
      description: "Small CSV/JSON/GeoJSON feature example"
      render: json

  - type: dropdown
    id: metadata_standard
    attributes:
      label: Metadata Standard
      options:
        - ISO 19115
        - FGDC
        - DCAT
        - STAC 1.0.x
        - Other/Unknown
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🧱 Validation Requirements"

  - type: checkboxes
    id: validation
    attributes:
      label: Pre-Integration Checklist
      options:
        - label: Verify license & usage rights
          required: true
        - label: Confirm accessibility (API reachable, files downloadable)
          required: true
        - label: Compute SHA-256 checksum(s) for all assets
          required: true
        - label: Validate CRS (convert to EPSG:4326 where needed)
          required: true
        - label: Inspect schema & attribute completeness
          required: true
        - label: Generate thumbnail/preview for docs
          required: true
        - label: Create STAC Item/Collection under `data/stac/`
          required: true
        - label: Validate STAC via `make stac-validate`
          required: true
        - label: Add/Update `data/sources/<domain>/<source>.json` manifest
          required: true
        - label: (If large) Track with LFS/DVC manifests and store pointers
          required: false
        - label: Include `license`, `providers`, `derived_from`, `created` STAC fields
          required: true

  - type: markdown
    attributes:
      value: "## ⚙️ Implementation Plan (Optional)"

  - type: textarea
    id: impl_plan
    attributes:
      label: Steps & Owners
      placeholder: |
        1) Review license/provenance — Owner …
        2) Fetch to data/raw/<domain>/ — Owner …
        3) Manifest in data/sources/<domain>/ — Owner …
        4) Checksums — Owner …
        5) Integrate (make <domain>) — Owner …
        6) STAC generation/validation — Owner …
        7) Web/timeline config — Owner …

  - type: markdown
    attributes:
      value: "## 🧭 Versioning & Governance"

  - type: textarea
    id: versioning
    attributes:
      label: Versioning Summary (SemVer + STAC)
      placeholder: |
        | Scope                  | Current | Proposed | Reason / Trigger    |
        | :---------------------- | :------ | :------- | :------------------ |
        | Dataset (STAC)          | v1.0.0  | v1.1.0   | new layer added     |
        | Domain Pipeline         | v2.1.0  | v2.2.0   | ETL updated         |
        | Repo Release (SemVer)   | v1.4.0  | v1.5.0   | dataset integration |
        | Data Source Manifest    | v1.0.0  | v1.0.1   | provenance update   |
      render: markdown

  - type: markdown
    attributes:
      value: "## ✅ MCP Compliance"

  - type: checkboxes
    id: mcp
    attributes:
      label: MCP Principles
      options:
        - label: Documentation-first — dataset fully described w/ provenance & metadata
          required: true
        - label: Reproducibility — deterministic retrieval & checksum validation defined
          required: true
        - label: Open Standards — interoperable formats (COG/CSV/GeoJSON/NetCDF)
          required: true
        - label: Provenance — manifest, STAC, and log lineage maintained
          required: true
        - label: Auditability — CI validation steps reproducible & archived
          required: true
        - label: Versioning — STAC `properties.version` & repo SemVer updated
          required: true
        - label: Ethics — `data_ethics` tag set; restrictions documented
          required: true

  - type: markdown
    attributes:
      value: "## 🤩 Related Datasets / Attachments"

  - type: textarea
    id: related
    attributes:
      label: Related Datasets & References
      placeholder: |
        - Linked Source: data/sources/hydro/usgs_nhd_flowlines.json
        - Complementary Layers: NLCD Landcover, NHD Waterbodies
        - Dependent Models: Flood Risk, Soil Erosion, Vegetation Index
        - External References: (studies, portals)

  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: "Small data samples, schema files, preview thumbnails"
      placeholder: |
        example.json — schema preview  (/data/sources/climate/example.json)
        preview.png  — docs thumbnail   (/docs/media/previews/climate_dataset.png)

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: "Visuals, sample maps, metadata screenshots, or priority rationale"
```