---
name: "🧭 Data Request"
about: "Request new datasets, sources, or geospatial layers for integration into the Kansas Frontier Matrix (KFM)."
title: "[DATA] <brief description of dataset request>"
labels: ["data", "enhancement", "governance-review"]
assignees: ["@kfm-data-lab", "@kfm-etl-ops", "@bartytime4life"]
---

## 🧭 Summary

> _Provide a concise overview of the dataset or data source you are requesting._  
> _Example: “Request integration of Kansas River discharge dataset from USGS NWIS API.”_

**Category:**
- [ ] 🌦️ Environmental / Climate
- [ ] 🗺️ Geospatial / Map Layer
- [ ] 📜 Historical / Archival
- [ ] ⚡ Energy / Infrastructure
- [ ] 🧠 AI Training Dataset
- [ ] Other (specify below)

**Purpose of Integration:**  
> _Explain why this dataset is relevant or valuable to the Kansas Frontier Matrix project._

---

## 🧩 Source Information

| Field | Description |
|--------|-------------|
| **Dataset Name** | `<official name or identifier>` |
| **Source Organization** | `<e.g., NOAA, USGS, FEMA, KHS, DASC>` |
| **Access URL / API Endpoint** | `<direct download or API link>` |
| **License / Terms of Use** | `<e.g., Public Domain, CC-BY 4.0, etc.>` |
| **Data Format(s)** | `<e.g., GeoJSON, GeoTIFF, CSV, NetCDF>` |
| **Temporal Coverage** | `<start-end dates>` |
| **Spatial Coverage** | `<statewide, county, watershed, etc.>` |
| **Update Frequency** | `<static / annual / monthly / real-time>` |
| **Data Volume (approx.)** | `<e.g., 1GB / 500MB>` |

---

## 🔍 FAIR Metadata (if available)

| Field | Description |
|--------|-------------|
| **DOI / Identifier** | `<if available>` |
| **Metadata File / Record** | `<link or upload>` |
| **Provenance / Citation** | `<reference to official documentation>` |
| **Data Steward / Contact** | `<organization or individual>` |

> _If metadata is missing, indicate whether it can be derived from the source._  

---

## ⚙️ Integration Requirements

> _Describe how you envision this dataset being used or displayed within KFM._  
> _Example: “To overlay flood hazard layers with county boundaries on the Focus Mode map.”_

**Preferred Integration Path:**
- [ ] ETL Pipeline (`/src/pipelines/etl/`)
- [ ] AI Model Input (`/src/pipelines/ai/`)
- [ ] Web Visualization (`/web/src/layers/`)
- [ ] Knowledge Graph / Neo4j Entity
- [ ] Documentation or Archive Only

---

## 🧠 FAIR+CARE Evaluation

| Category | Compliance | Notes |
|-----------|-------------|-------|
| **Findable** | ☐ Yes ☐ No | _Has clear metadata and identifiers?_ |
| **Accessible** | ☐ Yes ☐ No | _Freely available and machine-readable?_ |
| **Interoperable** | ☐ Yes ☐ No | _Uses open, standard formats?_ |
| **Reusable** | ☐ Yes ☐ No | _Includes clear license and provenance?_ |
| **Collective Benefit** | ☐ Yes ☐ No | _Provides social/scientific value?_ |
| **Authority to Control** | ☐ Yes ☐ No | _Respects ownership or community governance?_ |
| **Responsibility** | ☐ Yes ☐ No | _Handled ethically and securely?_ |
| **Ethics** | ☐ Yes ☐ No | _No harmful or biased data usage?_ |

---

## 🧾 Governance Metadata

| Field | Reference |
|--------|------------|
| **Governance Ref** | `docs/standards/governance/ROOT-GOVERNANCE.md` |
| **Manifest Ref** | `releases/v9.3.2/manifest.zip` |
| **Telemetry Ref** | `releases/v9.3.2/focus-telemetry.json` |
| **Data Contract** | `docs/contracts/data-contract-v3.json` |
| **Ontology Alignment** | `ontologies/CIDOC_CRM-KFM.owl` |

> _Ensure all linked governance and metadata references correspond to the current repository release._

---

## 📊 Suggested Output Layers or Products

> _Describe any derived datasets or visualizations expected after integration._  
> _Example: “Produce historical drought intensity maps per county (1900–present).”_

| Output Type | Description | Format |
|--------------|-------------|--------|
| ETL Output |  | GeoJSON / CSV |
| Visualization |  | MapLibre Tile Layer |
| AI Training Data |  | JSON / NetCDF |
| Validation Logs |  | JSON / Markdown |

---

## 🧩 Review Routing

| Role | Reviewer | Required Action |
|------|-----------|-----------------|
| **Data Engineering** | @kfm-etl-ops | Evaluate ingestion feasibility |
| **Metadata / FAIR Review** | @kfm-data-lab | Validate schema and metadata |
| **AI Governance** | @kfm-ai-lab | Assess ethical and technical use |
| **Architecture / Maintainer** | @bartytime4life | Approve inclusion in main branch |

---

## ✅ Submission Checklist

- [ ] Source license verified (Open Data / FAIR-compliant)
- [ ] Metadata file provided or retrievable
- [ ] FAIR+CARE compliance reviewed
- [ ] Governance metadata references included
- [ ] Notified maintainers for review and integration

---

> ⚠️ **Note:**  
> Submitting this data request automatically triggers:  
> - FAIR+CARE validation (`.github/workflows/faircare-validate.yml`)  
> - STAC ingestion test (`.github/workflows/stac-validate.yml`)  
> - Governance record entry (`reports/audit/hazards_archive_provenance.json`)  

---

**Kansas Frontier Matrix** · *Open Data × FAIR+CARE Ethics × Reproducible Science*  
[🔗 Repository](https://github.com/bartytime4life/Kansas-Frontier-Matrix) • [🧭 Docs Portal](../../../docs/) • [⚖️ Governance Ledger](../../../docs/standards/governance/)