---
name: "📦 Data Request"
description: "Request access to or integration of a new dataset into the Kansas Frontier Matrix (FAIR+CARE · MCP-DL v6.3 Compliant)"
title: "[DATA REQUEST] <brief description>"
labels: ["data-request", "faircare:review", "governance:pending"]
assignees:
  - "@kfm-data"
  - "@kfm-fair"
  - "@kfm-governance"
body:
  - type: markdown
    attributes:
      value: |
        ## 📦 Kansas Frontier Matrix — Data Request (FAIR+CARE Certified)
        Use this template to request the addition or access of a new dataset within the Kansas Frontier Matrix.
        Each request will be reviewed by the FAIR+CARE Council for ethical use, provenance, and schema compatibility.

  - type: input
    id: dataset_name
    attributes:
      label: "🧾 Dataset Name"
      description: "Provide the full name of the dataset or collection you are requesting."
      placeholder: "Example: NOAA Climate Data Record (CDR) – Daily Temperature Anomalies"
    validations:
      required: true

  - type: input
    id: dataset_source
    attributes:
      label: "🌍 Data Source or Provider"
      description: "Specify the organization, repository, or API that hosts the dataset."
      placeholder: "Example: NOAA National Centers for Environmental Information (NCEI)"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: "🏷️ KFM Domain"
      description: "Select the primary KFM domain relevant to this dataset."
      options:
        - Climate
        - Hydrology
        - Hazards
        - Landcover
        - Terrain
        - Tabular / Statistical
        - Text / Archival
        - Metadata / Governance
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📚 Dataset Description"
      description: "Provide a short description of the dataset content and purpose."
      placeholder: "Describe what this dataset contains, its temporal range, and why it’s important for KFM."
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: "💡 Research or Operational Justification"
      description: "Explain why this dataset should be added to the Kansas Frontier Matrix."
      placeholder: "Explain how this dataset supports open research, governance, or FAIR+CARE alignment."
    validations:
      required: true

  - type: textarea
    id: format
    attributes:
      label: "🧩 File Formats and Access Details"
      description: "List the formats, API endpoints, or download links for accessing the data."
      placeholder: "Example: CSV, GeoTIFF, JSON, or REST API endpoint URL"
    validations:
      required: true

  - type: checkboxes
    id: licenses
    attributes:
      label: "📜 License and Usage Terms"
      description: "Select the applicable license(s) for this dataset."
      options:
        - label: "CC-BY 4.0 (Attribution Required)"
        - label: "CC0 (Public Domain)"
        - label: "Open Government Data License"
        - label: "MIT / BSD License"
        - label: "Other (please specify below)"
    validations:
      required: true

  - type: textarea
    id: other_license
    attributes:
      label: "🔖 Other License or Usage Notes"
      description: "If the dataset uses a different license or access restriction, specify it here."
      placeholder: "Example: Data available under institutional agreement, non-commercial clause, etc."
    validations:
      required: false

  - type: dropdown
    id: sensitivity
    attributes:
      label: "⚠️ Sensitivity Level"
      description: "Classify the ethical or access sensitivity of the dataset."
      options:
        - Open Access (public, unrestricted)
        - Limited Access (requires attribution or controlled use)
        - Restricted (requires governance review before ingestion)
    validations:
      required: true

  - type: textarea
    id: provenance
    attributes:
      label: "⚖️ Provenance and Lineage Information"
      description: "Provide information on data origin, processing history, and versioning."
      placeholder: "Include citations, URLs, or links to data documentation or prior use."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🧠 FAIR+CARE Compliance Review
        Please complete this section to confirm FAIR+CARE alignment before review.

  - type: checkboxes
    id: faircare_alignment
    attributes:
      label: "FAIR+CARE Compliance Checklist"
      options:
        - label: "Findable — Dataset includes persistent identifiers or catalog entries"
        - label: "Accessible — Data publicly available or through transparent licensing"
        - label: "Interoperable — Schema or metadata aligned with FAIR+CARE / DCAT / STAC"
        - label: "Reusable — Data properly documented and versioned for reproducibility"
        - label: "Ethical — Dataset respects cultural, environmental, and privacy guidelines"
    validations:
      required: true

  - type: textarea
    id: governance_links
    attributes:
      label: "📘 Governance References"
      description: "Provide links or references to governance, ethics, or metadata documentation."
      placeholder: "Example: https://data.noaa.gov/documents/ethics-and-metadata"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🧾 Sign-Off
        Please confirm the integrity and ethical compliance of this dataset request.

  - type: input
    id: contributor
    attributes:
      label: "👤 Contributor"
      description: "Your GitHub handle or full name."
      placeholder: "@username"
    validations:
      required: true

  - type: input
    id: affiliation
    attributes:
      label: "🏢 Affiliation"
      description: "Your organization, institution, or project."
      placeholder: "Kansas Frontier Matrix / Open FAIR+CARE Network"
    validations:
      required: true

  - type: textarea
    id: certification
    attributes:
      label: "🪶 FAIR+CARE Certification Statement"
      description: "By submitting this data request, you affirm compliance with FAIR+CARE and open governance standards."
      value: |
        I confirm that this dataset:
        - Complies with FAIR+CARE ethical standards for open science.
        - Contains no sensitive or restricted personal information.
        - Supports transparent, reproducible, and inclusive research practices.
    validations:
      required: true
