# üó∫Ô∏è Kansas Frontier Matrix ‚Äî Data Submission Template  
# File: .github/ISSUE_TEMPLATE/data_submission.yml  
# Purpose: Structured form for submitting new datasets or geospatial layers to KFM.  
# Aligned with Master Coder Protocol (MCP v6.3) ¬∑ FAIR+CARE ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©  
# SPDX-License-Identifier: CC-BY-4.0  

name: "üó∫Ô∏è Data Submission"
description: "Submit a new dataset, STAC item, or data layer for inclusion in the Kansas Frontier Matrix."
title: "Dataset Submission: [Dataset Name or ID]"
labels:
  - "data"
  - "stac"
  - "faircare"
assignees:
  - "bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## üó∫Ô∏è Kansas Frontier Matrix ‚Äî Data Submission Form  
        Thank you for contributing a new dataset to the **Kansas Frontier Matrix (KFM)**.  
        Please fill out all fields carefully to ensure proper ingestion and validation.  
        All submissions are evaluated under the **Master Coder Protocol (MCP v6.3)** and must meet **FAIR+CARE** compliance.

  - type: input
    id: dataset_id
    attributes:
      label: "Dataset ID"
      description: "A short, unique, lowercase identifier for this dataset (use underscores instead of spaces)."
      placeholder: "e.g. noaa_storm_events_1950_2025"
    validations:
      required: true

  - type: input
    id: dataset_title
    attributes:
      label: "Dataset Title"
      description: "Full descriptive title of the dataset."
      placeholder: "e.g. NOAA Storm Events Archive (1950‚Äì2025)"
    validations:
      required: true

  - type: textarea
    id: dataset_description
    attributes:
      label: "Dataset Description"
      description: "Provide a detailed summary of the dataset content, scope, and intended use."
      placeholder: |
        Example:
        This dataset includes recorded severe weather events (tornadoes, floods, hail, etc.) across Kansas
        from 1950‚Äì2025 as collected by NOAA‚Äôs National Centers for Environmental Information (NCEI).
    validations:
      required: true

  - type: dropdown
    id: dataset_type
    attributes:
      label: "Dataset Type"
      description: "Select the general type of dataset."
      options:
        - "raster (GeoTIFF, COG, imagery)"
        - "vector (GeoJSON, shapefile, boundaries)"
        - "tabular (CSV, TSV, JSON)"
        - "text (OCR, transcripts, documents)"
        - "other (specify below)"
      default: 0
    validations:
      required: true

  - type: textarea
    id: source_provenance
    attributes:
      label: "Source & Provenance"
      description: "Provide the original data source, repository link, or publication reference."
      placeholder: "e.g. NOAA NCEI, USGS National Map, Kansas Geological Survey (KGS), etc."
    validations:
      required: true

  - type: input
    id: license
    attributes:
      label: "License"
      description: "Provide the SPDX or Creative Commons license for the dataset (e.g. CC-BY-4.0, Public Domain)."
      placeholder: "e.g. Public Domain (US Government Works)"
    validations:
      required: true

  - type: input
    id: checksum
    attributes:
      label: "Checksum (SHA-256)"
      description: "Provide a checksum hash for file integrity verification."
      placeholder: "e.g. sha256-abcdef123456..."
    validations:
      required: true

  - type: textarea
    id: spatial_extent
    attributes:
      label: "Spatial Coverage (Bounding Box)"
      description: "Provide bounding box coordinates in WGS84 (EPSG:4326)."
      placeholder: "Example: [-102.05, 37.00, -94.60, 40.00]"
    validations:
      required: true

  - type: textarea
    id: temporal_extent
    attributes:
      label: "Temporal Coverage (Start and End Dates)"
      description: "Specify the date range covered by this dataset."
      placeholder: "Example: { start: '1950-01-01', end: '2025-05-01' }"
    validations:
      required: true

  - type: textarea
    id: keywords
    attributes:
      label: "Keywords / Tags"
      description: "List relevant topics, themes, or metadata tags for discoverability."
      placeholder: "e.g. climate, tornado, hazards, historical-data, kansas, NOAA"
    validations:
      required: true

  - type: textarea
    id: data_access
    attributes:
      label: "Data Access URL(s)"
      description: "Provide the direct download link(s) or API endpoint(s) for the dataset."
      placeholder: "e.g. https://www.ncei.noaa.gov/access/search/storm-events"
    validations:
      required: true

  - type: dropdown
    id: care_relevance
    attributes:
      label: "CARE Relevance"
      description: "Does this dataset contain or relate to Indigenous, tribal, or culturally sensitive data?"
      options:
        - "No ‚Äî not applicable"
        - "Yes ‚Äî includes Indigenous-related content"
        - "Uncertain ‚Äî requires governance review"
      default: 0
    validations:
      required: true

  - type: textarea
    id: care_statement
    attributes:
      label: "CARE Statement (if applicable)"
      description: "If your dataset relates to Indigenous lands, heritage, or cultural knowledge, describe how CARE principles are respected."
      placeholder: |
        Example:
        This dataset includes digitized treaty boundaries verified with tribal partners.
        It has been reviewed and approved for open publication with attribution.
    validations:
      required: false

  - type: checkboxes
    id: compliance_checklist
    attributes:
      label: "Contributor Checklist"
      description: "Confirm all required compliance steps before submission."
      options:
        - label: "I confirm this dataset complies with FAIR principles (Findable, Accessible, Interoperable, Reusable)."
          required: true
        - label: "I confirm this dataset respects CARE principles where applicable."
          required: true
        - label: "I have verified all file checksums and metadata accuracy."
          required: true
        - label: "I understand this dataset will undergo validation via `stac-validate.yml` and `faircare-validate.yml` workflows."
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### üß™ Validation Workflows  
        Upon submission, your dataset will automatically be validated by:
        - **`stac-validate.yml`** ‚Üí Schema and link validation  
        - **`faircare-validate.yml`** ‚Üí FAIR+CARE and license checks  
        - **`docs-lint.yml`** ‚Üí Markdown, YAML, and JSON front-matter validation  

        Validation results will be stored under:
        ```
        reports/self-validation/stac/
        reports/fair/
        ```
        and referenced in the system telemetry at:
        ```
        releases/v9.7.0/focus-telemetry.json
        ```

        **Thank you for contributing open, ethical, and verifiable data to the Kansas Frontier Matrix.**  
        Built under **Master Coder Protocol v6.3** ¬∑ FAIR+CARE Certified ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified  
        **¬© 2025 Kansas Frontier Matrix ‚Äî CC-BY 4.0**
