name: "🧭 Data Request"
description: "Request new datasets, sources, or geospatial layers for integration into the Kansas Frontier Matrix (KFM)."
title: "[DATA] <brief description of dataset request>"
labels:
  - data
  - enhancement
  - governance-review
assignees:
  - "@kfm-data-lab"
  - "@kfm-etl-ops"
  - "@bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## 🧭 Summary
        Provide a concise overview of the dataset or data source you are requesting.
        Example: “Request integration of Kansas River discharge dataset from USGS NWIS API.”

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Select the appropriate category for this dataset."
      options:
        - "🌦️ Environmental / Climate"
        - "🗺️ Geospatial / Map Layer"
        - "📜 Historical / Archival"
        - "⚡ Energy / Infrastructure"
        - "🧠 AI / ML Training Dataset"
        - "Other (specify below)"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose of Integration
      description: "Explain why this dataset benefits KFM and supports FAIR+CARE-aligned open science."
      placeholder: "Describe how this data contributes to the KFM mission."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🧩 Source Information"

  - type: textarea
    id: source_info
    attributes:
      label: Source Information
      description: "Provide dataset name, organization, URL, license, formats, temporal and spatial coverage."
      value: |
        Dataset Name:  
        Source Organization:  
        Access URL / API Endpoint:  
        License / Terms of Use:  
        Data Format(s):  
        Temporal Coverage:  
        Spatial Coverage:  
        Update Frequency:  
        Approx. Data Volume:  
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🔍 FAIR Metadata (if available)"

  - type: textarea
    id: metadata
    attributes:
      label: FAIR Metadata
      description: "Provide DOI, metadata record links, provenance, or data steward contact info if available."
      value: |
        DOI / Persistent ID:  
        Metadata Record / File:  
        Provenance / Citation:  
        Data Steward / Contact:  
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## ⚙️ Integration Requirements"

  - type: textarea
    id: integration
    attributes:
      label: Integration Requirements
      description: "Describe technical requirements, pipelines, or transformations needed (e.g., EPSG:4326 reprojection)."
      placeholder: "Describe how this dataset should be integrated or displayed in KFM."
    validations:
      required: false

  - type: checkboxes
    id: integration_path
    attributes:
      label: Preferred Integration Path
      options:
        - label: "ETL Pipeline (/src/pipelines/etl/)"
        - label: "AI Model Input (/src/pipelines/ai/)"
        - label: "Web Visualization (/web/src/layers/)"
        - label: "Knowledge Graph / Neo4j Entity"
        - label: "Documentation / Reference Archive Only"

  - type: markdown
    attributes:
      value: "## 🧠 FAIR+CARE Evaluation"

  - type: checkboxes
    id: faircare
    attributes:
      label: FAIR+CARE Compliance Self-Assessment
      description: "Mark applicable compliance categories."
      options:
        - label: "Findable — Metadata or DOI present"
        - label: "Accessible — Open license and machine-readable format"
        - label: "Interoperable — Uses open standards (e.g., GeoJSON, CSV)"
        - label: "Reusable — Clear citation and documentation"
        - label: "Collective Benefit — Serves community or research purpose"
        - label: "Authority to Control — Respects community rights"
        - label: "Responsibility — Data handled ethically"
        - label: "Ethics — No harmful or biased use"

  - type: markdown
    attributes:
      value: "## 🧾 Governance Metadata"

  - type: textarea
    id: governance_refs
    attributes:
      label: Governance References
      description: "Confirm or update governance metadata for the dataset."
      value: |
        Governance Ref: docs/standards/governance/ROOT-GOVERNANCE.md  
        Manifest Ref: releases/v9.5.0/manifest.zip  
        Telemetry Ref: releases/v9.5.0/focus-telemetry.json  
        SBOM Ref: releases/v9.5.0/sbom.spdx.json  
        Data Contract: docs/contracts/data-contract-v3.json  
        Ontology Alignment: ontologies/CIDOC_CRM-KFM.owl  

  - type: markdown
    attributes:
      value: "## 📊 Suggested Output Layers or Products"

  - type: textarea
    id: output
    attributes:
      label: Expected Outputs
      description: "List expected outputs or derived visualizations after integration."
      value: |
        ETL Output:  
        Visualization:  
        AI Training Data:  
        Validation Logs:  

  - type: markdown
    attributes:
      value: "## 🧩 Review Routing"

  - type: markdown
    attributes:
      value: |
        | Role | Reviewer | Required Action |
        |------|-----------|-----------------|
        | **Data Engineering** | @kfm-etl-ops | Evaluate ingestion feasibility & format compatibility |
        | **Metadata / FAIR Review** | @kfm-data-lab | Validate metadata schema & FAIR compliance |
        | **AI Governance** | @kfm-ai-lab | Assess ethical alignment & potential AI use |
        | **Architecture / Maintainer** | @bartytime4life | Approve inclusion & merge to main branch |

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: "License verified (Open / FAIR-compliant)"
        - label: "Metadata provided or retrievable"
        - label: "FAIR+CARE self-assessment completed"
        - label: "Governance metadata validated"
        - label: "Maintainers notified for review"

  - type: markdown
    attributes:
      value: |
        > ⚠️ **Automation Notice:**  
        > Submitting this issue triggers:  
        > - FAIR+CARE validation (`.github/workflows/faircare-validate.yml`)  
        > - STAC/DCAT schema testing (`.github/workflows/stac-validate.yml`, `dcat-export.yml`)  
        > - Governance ledger update (`reports/audit/ai_hazards_ledger.json`)  
        > - Telemetry update (`releases/v9.5.0/focus-telemetry.json`)
