# GitHub Issue Form: Data Pipeline Change (KFM)
# Place this file under .github/ISSUE_TEMPLATE/data_pipeline_change.yml
#
# NOTE: GitHub Issue Forms only allow specific top-level keys (name/description/title/labels/assignees/projects/body).
# Any KFM-specific structure must live inside `body` fields.

name: "Data pipeline change"
description: "Governed request to change a data pipeline (schema/transforms/orchestration). Captures provenance, QA gates, and policy considerations."
title: "[Data pipeline change]: "
labels:
  - "data-pipeline"
  - "change-request"
  - "governance"

body:
  - type: markdown
    attributes:
      value: |
        ## KFM Data Pipeline Change (Governed)

        Use this form to request or record a change that affects one or more of:
        - data pipelines / orchestration,
        - dataset schemas,
        - promotion between **Raw → Work → Processed → Published**,
        - governed APIs or user-facing claims.

        Wherever possible, **link to evidence** (PRs, design docs/ADRs, run logs, validation reports, dashboards).

  - type: input
    id: change_id
    attributes:
      label: Change ID
      description: Optional if you don't have one yet. Prefer a UUID (or a kfm://change/<uuid> identifier).
      placeholder: "kfm://change/<uuid>  (or just <uuid>)"
    validations:
      required: false

  - type: dropdown
    id: change_type
    attributes:
      label: Change type
      options:
        - pipeline
        - dataset
        - infra
        - policy
        - docs
    validations:
      required: true

  - type: dropdown
    id: target_envs
    attributes:
      label: Target environments
      multiple: true
      options:
        - dev
        - staging
        - prod
    validations:
      required: true

  - type: input
    id: requested_by
    attributes:
      label: Requested by
      description: Name / team / contact handle.
      placeholder: "Jane Doe — Data Platform — @jdoe"
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem statement
      description: What is broken/missing/risky today? Include symptoms, incidents, examples, and impacted users/systems.
      placeholder: |
        - What is happening?
        - Impact and blast radius
        - When it started / how often
        - Links to incidents/tickets (if any)
    validations:
      required: true

  - type: textarea
    id: goals_metrics
    attributes:
      label: Goals, non-goals, and success metrics
      description: Define what "done" looks like and what is explicitly out of scope.
      placeholder: |
        Goals:
        - ...

        Non-goals:
        - ...

        Success metrics:
        - metric: ...
          target: ...
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope (affected pipelines & datasets)
      description: List pipelines/datasets affected. Include zone/sensitivity/license where known.
      placeholder: |
        Affected pipelines:
        - pipeline_id: 
          name: 
          orchestrator: airflow|dagster|prefect|argo|other
          schedule: "cron/event/manual"
          owner: 

        Affected datasets:
        - dataset_id: 
          name: 
          zone: raw|work|processed|published
          sensitivity: public|restricted|confidential|cultural-restricted
          license: 
          consumers:
            - ...
    validations:
      required: true

  - type: textarea
    id: change_summary
    attributes:
      label: Proposed change summary
      description: One paragraph summary + compatibility expectations.
      placeholder: |
        Summary:
        
        Backwards compatibility:
        - breaking_change: false
        - mitigation (if breaking): ...
    validations:
      required: true

  - type: textarea
    id: schema_changes
    attributes:
      label: Schema changes
      description: Provide before/after schema references (paths/URIs) and a brief diff.
      placeholder: |
        - dataset_id: 
          change: none|add_columns|remove_columns|rename|type_change|other
          before_schema_ref: 
          after_schema_ref: 
          notes: 
    validations:
      required: false

  - type: textarea
    id: transforms
    attributes:
      label: Transforms, code paths, and dependencies
      description: Where is the change implemented? Include container image digests when applicable.
      placeholder: |
        Code paths:
        - pipelines/...
        - dbt/models/...

        Container images:
        - name: 
          digest: "sha256:..."

        Dependencies / integrations:
        - ...
    validations:
      required: true

  - type: textarea
    id: data_lineage
    attributes:
      label: Data lineage (inputs → outputs)
      description: Provide URIs and checksums/snapshots when available. Avoid exact coordinates for sensitive sites.
      placeholder: |
        Inputs:
        - name: 
          uri: 
          classification: 
          checksum: 
          time_extent: "YYYY-MM-DD..YYYY-MM-DD"
          spatial_extent: "coarse geography only if sensitive"

        Outputs:
        - name: 
          uri: 
          zone: raw|work|processed|published
          checksum: 
    validations:
      required: true

  - type: textarea
    id: quality_gates
    attributes:
      label: Quality gates and evidence
      description: List required checks, thresholds, and links to evidence (CI logs, reports, dashboards).
      placeholder: |
        Required checks:
        - name: schema_validation
          tool: 
          threshold: 
          evidence_uri: 
        - name: row_count_sanity
          tool: 
          threshold: 
          evidence_uri: 
        - name: null_rate
          tool: 
          threshold: 
          evidence_uri: 

        Promotion gate notes (Raw→Work / Work→Processed / Processed→Published):
        - ...
    validations:
      required: true

  - type: textarea
    id: security_policy
    attributes:
      label: Security and policy review
      description: Access control model, sensitive fields, redaction/retention, and any community constraints.
      placeholder: |
        Access control:
        - authz_model: RBAC|ABAC|policy-engine
        - roles/permissions: 

        PII/sensitive fields:
        - present: false
        - fields: []
        - handling: redaction|hashing|tokenization|...

        Retention:
        - raw_days: 
        - published_days: 

        Community constraints:
        - present: false
        - notes: 
    validations:
      required: true

  - type: textarea
    id: deployment
    attributes:
      label: Deployment, monitoring, and rollback plan
      description: How will this roll out? What will you watch? How do you roll back quickly?
      placeholder: |
        Rollout strategy: canary|blue_green|full

        Steps:
        - ...

        Monitoring:
        - dashboards:
          - ...
        - alerts:
          - name: ...
            condition: ...
            paging: false

        Rollback:
        - steps:
          - ...
        - max_rollback_time_minutes: 30
    validations:
      required: true

  - type: textarea
    id: audit
    attributes:
      label: Audit / traceability
      description: Link PR, design doc/ADR, runbook; include git refs and run IDs.
      placeholder: |
        Links:
        - pr: 
        - design_doc: 
        - runbook: 
        - incident_postmortem: 

        Repo refs:
        - git_remote: 
        - base_ref: 
        - head_ref: 

        Execution:
        - ci_run_id: 
        - pipeline_run_id: 
        - executed_by: 
        - executed_at: 
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Confirm baseline governance requirements.
      options:
        - label: "I linked or attached evidence for required quality checks (or explained what is pending)."
        - label: "I verified license and sensitivity classification for affected datasets."
        - label: "I included a rollout + rollback plan and monitoring/alerting plan."
        - label: "If culturally restricted or sensitive locations are involved, I did not include exact coordinates."
