# üí° Kansas Frontier Matrix ‚Äî Feature Request Template  
# File: .github/ISSUE_TEMPLATE/feature_request.yaml  
# Purpose: Collect structured requests for new features, enhancements, or improvements to the KFM system.  
# Aligned with Master Coder Protocol (MCP v6.3) ¬∑ FAIR+CARE ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©  
# SPDX-License-Identifier: CC-BY-4.0  

name: "üí° Feature Request"
description: "Propose a new feature, enhancement, or improvement to the Kansas Frontier Matrix project."
title: "Feature Request: [Short Title]"
labels:
  - "enhancement"
  - "feature"
assignees:
  - "bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## üí° Kansas Frontier Matrix ‚Äî Feature Request Form  
        Use this form to suggest new functionality, UI improvements, pipeline features, or AI/ETL enhancements.  
        All feature proposals are reviewed during the **MCP Quarterly Architecture Review Cycle** and must include clear rationale and implementation details.

  - type: input
    id: feature_title
    attributes:
      label: "Feature Title"
      description: "Provide a short and descriptive title for the requested feature."
      placeholder: "e.g. Add AI-assisted entity linking for treaty documents"
    validations:
      required: true

  - type: textarea
    id: feature_summary
    attributes:
      label: "Summary"
      description: "Briefly summarize the purpose and scope of this feature."
      placeholder: |
        Example:
        This feature adds an NLP-based entity linking module that automatically connects people, places, and treaties
        within the Kansas Frontier Matrix knowledge graph.
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem or Opportunity"
      description: "Describe the problem this feature solves or the opportunity it creates."
      placeholder: |
        Example:
        Manual linking of historical entities is time-consuming and inconsistent.
        Automating entity relationships improves accuracy and discoverability across datasets.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Explain your proposed implementation, including technologies, algorithms, or UI concepts."
      placeholder: |
        Example:
        Implement a `focus_transformer_v2` model in `src/ai/models/` that uses transformer embeddings
        to detect and link semantic entities. Integrate with Neo4j graph database via Cypher query templates.
    validations:
      required: true

  - type: dropdown
    id: component_area
    attributes:
      label: "Affected Component Area"
      description: "Select which part of the system the proposed feature affects."
      options:
        - "ETL / Data Pipelines"
        - "AI / NLP Models"
        - "API Layer (FastAPI / GraphQL)"
        - "Frontend (React / MapLibre)"
        - "Documentation / Governance"
        - "Infrastructure / CI-CD"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: impact_level
    attributes:
      label: "Estimated Impact Level"
      description: "Select the overall impact of this feature."
      options:
        - "High ‚Äî Core functionality enhancement"
        - "Medium ‚Äî Improves usability or automation"
        - "Low ‚Äî Minor improvement or refactor"
      default: 1
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies or Related Work"
      description: "List any related datasets, models, or workflows that may be affected or required."
      placeholder: |
        Example:
        - Dependent on `src/graph/queries/link_entities.cypher`
        - Builds on `focus_transformer_v1`
        - Requires new STAC metadata for linked documents
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: "Potential Risks or Considerations"
      description: "Identify any challenges, data sensitivity, or technical limitations to consider."
      placeholder: |
        Example:
        - Model bias must be tested before production
        - New dependencies increase container image size
        - Requires additional FAIR+CARE governance review
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define what success looks like. What measurable outcomes or deliverables should this feature achieve?"
      placeholder: |
        Example:
        - Entity linking achieves 90% accuracy on test corpus.
        - Users can filter by linked entities in the Focus Mode UI.
        - Documentation updated under `docs/ai/focus_transformer.md`.
    validations:
      required: true

  - type: checkboxes
    id: compliance_checklist
    attributes:
      label: "Governance & Compliance Checklist"
      description: "Confirm these before submitting your feature request."
      options:
        - label: "I confirm this proposal follows Master Coder Protocol v6.3 (documentation-first design)."
          required: true
        - label: "I confirm this feature will comply with FAIR+CARE data governance principles."
          required: true
        - label: "I will update or create relevant documentation in `docs/` and `src/` upon implementation."
          required: true
        - label: "I understand this feature request may require approval during the next architecture review cycle."
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### üß≠ Architecture Review & Validation Workflow  
        Submitted feature requests automatically enter KFM‚Äôs governance workflow:
        - **`docs-lint.yml`** ‚Üí Validates proposal format and Markdown consistency  
        - **`stac-validate.yml`** ‚Üí Checks metadata interoperability (if applicable)  
        - **`faircare-validate.yml`** ‚Üí Confirms ethical compliance for any new datasets  
        - **`build-and-deploy.yml`** ‚Üí (Triggered post-approval) integrates into development build  

        Approved proposals are tracked in:
        ```
        reports/audit/github-workflows-ledger.json
        ```
        and referenced in:
        ```
        releases/v9.7.0/focus-telemetry.json
        ```

        **Thank you for helping shape the future of the Kansas Frontier Matrix.**  
        Governed under **Master Coder Protocol v6.3** ¬∑ FAIR+CARE Certified ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified  
        **¬© 2025 Kansas Frontier Matrix ‚Äî MIT / CC-BY 4.0**
