name: "💡 Feature Request"
description: "Propose a new feature or enhancement — documented, versioned, reproducible, and MCP-DL v6.3 compliant."
title: "[Feature]: <feature name> — <component/domain>"
labels:
  - enhancement
  - needs-triage
assignees:
  - kfm-architecture
  - kfm-data

# ⛳ Kansas Frontier Matrix · Feature Request Form (MCP-DL v6.3)
# Captures all details to design, review, and integrate a feature:
# problem, rationale, implementation, KPIs, governance, security, data ethics, and versioning.

# KFM metadata (informational)
# version: v2.4.0
# last_updated: 2025-10-18
# owners: @kfm-architecture @kfm-data

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Overview
        *"Every feature builds the future — every change is reproducible."*

  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      placeholder: "Slope Classification Enhancement for Terrain Pipeline"
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Target Module / Component
      placeholder: "terrain_pipeline.py | web/config/layers.json | src/graph/schema.cypher | src/api/routes.py"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain / Area of Impact
      options:
        - Terrain
        - Hydrology
        - Climate
        - Hazards
        - Landcover
        - Knowledge Graph
        - Web UI
        - API
        - Text / AI / NLP
        - Metadata / Governance
        - CI/CD
      multiple: true
    validations:
      required: true

  - type: input
    id: stakeholder
    attributes:
      label: Feature Owner / Stakeholder
      placeholder: "@kfm-data · @kfm-web · project-leads"
    validations:
      required: true

  - type: dropdown
    id: impact_level
    attributes:
      label: Expected Impact Level
      options:
        - "🟩 Minor"
        - "🟨 Moderate"
        - "🟧 Major"
        - "🔴 Critical"
    validations:
      required: true

  - type: dropdown
    id: semver
    attributes:
      label: SemVer Impact
      options:
        - patch (no breaking changes)
        - minor (non-breaking but visible)
        - major (breaking or schema-level)
        - unknown
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🔍 Problem & Rationale"

  - type: textarea
    id: problem
    attributes:
      label: Current Limitation or Problem
      placeholder: "Describe the current limitation or user need driving this feature."
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Motivation & Rationale
      placeholder: |
        - Aligns with roadmap milestone
        - Fills UI accessibility gap
        - Enhances knowledge graph linking
        - Supports Focus Mode / AI summaries
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🧠 Proposed Implementation"

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Implementation Details
      description: "Describe logic, workflow changes, files affected, dependencies."
      placeholder: |
        - Add CLI flag to terrain_pipeline.py
        - Modify layers.json with slope_class layer
        - Update ADR + add unit tests + e2e test fixture
        - Adjust STAC properties + thumbnails
    validations:
      required: true

  - type: checkboxes
    id: change_types
    attributes:
      label: Type of Change
      options:
        - label: New ETL pipeline/module
        - label: Graph schema/API expansion
        - label: Web/timeline interaction enhancement
        - label: Visualization config/UI component
        - label: Docs/ADR/SOP updates
        - label: CI/CD workflow change
        - label: AI/Model pipeline change
        - label: Other

  - type: textarea
    id: toggles_rollout
    attributes:
      label: Rollout & Toggle Strategy
      description: "How to deploy safely and roll back if needed."
      placeholder: |
        - Feature flag: `feature.slope_class`
        - Canary / partial rollout
        - Rollback plan: revert config + data migration
        - Migration notes: cache rebuild, index refresh

  - type: markdown
    attributes:
      value: |
        ## 📐 Metrics / Expected Outcome
        Use this template (copy/paste into the field below):
        ```
        | Metric          | Target                                      |
        |-----------------|----------------------------------------------|
        | Data Quality    | `slope_class` populated; STAC updated        |
        | Reproducibility | Deterministic outputs; SOP updated           |
        | Usability       | Map layer toggle + legend + doc link         |
        | Performance     | ≤ +5% runtime impact                         |
        | Accessibility   | Meets WCAG 2.1 AA; keyboard-only operable    |
        | Observability   | New logs/metrics in CI and runtime dashboards|
        ```
  - type: textarea
    id: outcomes
    attributes:
      label: Expected Behavior / KPIs
      description: "Enter the KPI table or bullet list. Markdown is rendered."
      placeholder: "Paste the KPI table template (see above) and adjust targets."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: downstream
    attributes:
      label: Downstream Effects
      description: "Describe expected effects on STAC, pipelines, UI, tests, model cards, etc."
      placeholder: |
        - STAC schema version bump (properties.version)
        - New test fixtures + screenshots
        - Update `docs/` usage & ADR
        - Affect model card? (if AI surfaces/dossiers change)

  - type: markdown
    attributes:
      value: "## 🔒 Security, Supply Chain & Ethics"

  - type: checkboxes
    id: security_ethics
    attributes:
      label: Security & Data Ethics Checklist
      options:
        - label: CodeQL/Trivy clean or mitigations documented
        - label: Actions pinned (SHA/tag); least-privilege tokens
        - label: SBOM re-generated (if deps changed)
        - label: Policy-as-Code checks pass (OPA/Conftest)
        - label: Data ethics reviewed; STAC `data_ethics` set if applicable

  - type: markdown
    attributes:
      value: "## 📜 Governance / Versioning"

  - type: textarea
    id: versioning_summary
    attributes:
      label: Versioning Summary (SemVer + STAC)
      description: "Enter a table of proposed version increments."
      placeholder: |
        | Component            | Current | Proposed | Reason             |
        |----------------------|---------|----------|--------------------|
        | ETL Script           | v1.3.0  | v1.4.0   | logic addition     |
        | Graph/API Schema     | v1.0.0  | v1.1.0   | field added        |
        | Web Config           | v1.2.1  | v1.2.2   | toggle added       |
        | Repo Release (SemVer)| v2.4.0  | v2.5.0   | feature bump       |
        | Dataset (STAC)       | v1.0.0  | v1.1.0   | collection update  |
      render: markdown

  - type: markdown
    attributes:
      value: "## 🔗 References & Notes"

  - type: textarea
    id: references
    attributes:
      label: Links / Related PRs / Docs
      placeholder: |
        - Related Issue: #456
        - ADR: docs/adr/ADR-####.md
        - SOP: docs/sop/terrain_pipeline.md
        - PRs: #789

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: |
        - Diagrams, screenshots, mockups
        - Risk flags, review blockers, etc.
```