# üí° Kansas Frontier Matrix ‚Äî Feature Request Template
# File: .github/ISSUE_TEMPLATE/feature_request.yaml
# Purpose: Collect structured requests for new features, enhancements, or improvements to the KFM system.
# Alignment: MCP-DL v6.3 ¬∑ KFM-MDP v11.0 ¬∑ FAIR+CARE ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©
# SPDX-License-Identifier: CC-BY-4.0

name: "üí° Feature Request"
description: "Propose a new feature, enhancement, or improvement to the Kansas Frontier Matrix project."
title: "Feature Request: [Short Title]"
labels:
  - "enhancement"
  - "feature"
assignees:
  - "bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## üí° Kansas Frontier Matrix ‚Äî Feature Request Form
        Use this form to suggest new functionality, UI improvements, data/ETL features, or AI/graph enhancements.
        All feature proposals are reviewed under **MCP-DL v6.3**, **KFM-MDP v11**, and **FAIR+CARE** governance.

  - type: input
    id: feature_title
    attributes:
      label: "Feature Title"
      description: "Short, descriptive title for the requested feature."
      placeholder: "e.g. Add AI-assisted entity linking for treaty documents"
    validations:
      required: true

  - type: textarea
    id: feature_summary
    attributes:
      label: "Summary"
      description: "Summarize the purpose and scope of this feature."
      placeholder: |
        Example:
        This feature adds an NLP-based entity linking module that automatically connects
        people, places, and treaties within the Kansas Frontier Matrix knowledge graph.
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem or Opportunity"
      description: "Describe the problem this feature solves or the opportunity it enables."
      placeholder: |
        Example:
        Manual linking of historical entities is time-consuming and inconsistent.
        Automating these relationships improves accuracy and discoverability across datasets.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Outline the proposed implementation (conceptual design, algorithms, UI ideas, or system changes)."
      placeholder: |
        Example:
        Implement an entity-linking module under `src/ai/models/` that uses transformer-based embeddings
        to detect and link semantic entities (people, places, events). Expose results via a GraphQL endpoint
        and integrate with Focus Mode v3 and Neo4j through Cypher query templates.
    validations:
      required: true

  - type: dropdown
    id: component_area
    attributes:
      label: "Affected Component Area"
      description: "Select where this feature will primarily apply."
      options:
        - "ETL / Data Pipelines"
        - "AI / NLP / Focus Mode"
        - "API Layer (FastAPI / GraphQL)"
        - "Frontend (React / MapLibre / Cesium)"
        - "Documentation / Governance / Story Nodes"
        - "Infrastructure / CI-CD / GitHub Workflows"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: impact_level
    attributes:
      label: "Estimated Impact Level"
      description: "How impactful is this feature to the system or users?"
      options:
        - "High ‚Äî Core functionality or major architecture impact"
        - "Medium ‚Äî Significant usability or automation improvement"
        - "Low ‚Äî Minor enhancement, refactor, or convenience"
      default: 1
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies or Related Work"
      description: "List related datasets, models, workflows, or components this feature depends on or affects."
      placeholder: |
        Examples:
        - Depends on `src/graph/queries/link_entities.cypher`
        - Builds on `focus_transformer_v2`
        - Requires new STAC metadata fields for linked documents
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: "Potential Risks or Considerations"
      description: "Identify data sensitivity, bias, performance, or technical risks."
      placeholder: |
        Examples:
        - New model may introduce or amplify bias; requires FAIR+CARE review.
        - Increased compute or memory requirements for Focus Mode v3.
        - Needs additional consent review for cultural/Indigenous data usage.
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define measurable success criteria and done-conditions."
      placeholder: |
        Examples:
        - Entity linking achieves ‚â• 90% accuracy on evaluation corpus.
        - Users can filter by linked entities in the Focus Mode UI.
        - Documentation added under `docs/ai/` and `docs/graph/`.
        - New telemetry fields added and visible in governance dashboards.
    validations:
      required: true

  - type: checkboxes
    id: compliance_checklist
    attributes:
      label: "Governance & Compliance Checklist"
      description: "Confirm you understand governance and documentation expectations."
      options:
        - label: "This proposal will be documented following Master Coder Protocol v6.3 (documentation-first)."
          required: true
        - label: "This feature will comply with FAIR+CARE principles and sovereignty policies."
          required: true
        - label: "I will update or create all relevant docs in `docs/` and `src/` upon implementation."
          required: true
        - label: "I understand this request may require approval during an architecture/governance review cycle."
          required: true

  - type: markdown
    attributes:
      value: |
        ## üß≠ Architecture Review & Validation Workflow

        Feature requests help guide roadmap and architecture decisions. After submission, automation may:

        - Run **docs_validate.yml** to ensure the proposal and follow-up docs conform to **KFM-MDP v11**.  
        - Run **stac_validate.yml** / **dcat_validate.yml** if new metadata patterns or catalogs are proposed.  
        - Run **faircare_validate.yml** to flag FAIR+CARE implications, especially for data- or AI-related features.  
        - Feed into **telemetry_export.yml** for governance and roadmap telemetry (e.g., feature backlog, complexity).  

        Architecture and governance decisions are recorded in:

        ```
        docs/reports/audit/github-workflows-ledger.json
        ```

        and may be reflected in telemetry snapshots:

        ```
        releases/v11.0.1/focus-telemetry.json
        ```

        Thank you for helping shape the **Kansas Frontier Matrix**.
        Your proposal contributes to a transparent, ethical, and reproducible system.

        **¬© 2025 Kansas Frontier Matrix ‚Äî MIT / CC-BY-4.0**  
        FAIR+CARE Certified ¬∑ MCP-DL v6.3 ¬∑ KFM-MDP v11.0 ¬∑ KFM-OP v11.0  
        Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified
