name: "💡 Feature Request"
description: "Propose a feature or enhancement — documented, versioned, and reproducible"
title: "[Feature]: <short title> — <component or domain>"
labels:
  - enhancement
  - needs-triage
assignees:
  - kfm-architecture
  - kfm-data

# KFM metadata
# version: v2.3.0
# last_updated: 2025-10-15
# owners: @kfm-architecture @kfm-data

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Overview
        *“Every Feature Builds the Future · Every Change is Reproducible.”*

  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      placeholder: "Slope Classification Enhancement for Terrain Pipeline"
    validations:
      required: true

  - type: input
    id: related_component
    attributes:
      label: Related Component / Module
      placeholder: "terrain_pipeline.py | graph_ingest.py | stac-validate.yml | web/config/layers.json"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain / Area of Impact
      options:
        - Terrain
        - Hydrology
        - Climate
        - Hazards
        - Landcover
        - Knowledge Graph
        - Web UI
        - API
        - Text / AI / NLP
        - Metadata / Governance
        - CI/CD
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🎯 Motivation & Limitation"

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      placeholder: "Explain the problem this feature solves and who benefits."
    validations:
      required: true

  - type: textarea
    id: limitation
    attributes:
      label: Current Limitation
      placeholder: "Describe the current limitation or gap this enhancement resolves."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ⚙️ Proposed Implementation"

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Implementation
      description: "Include technical specifics, workflow changes, and architecture impacts."
      placeholder: |
        - Extend terrain_pipeline.py with --add-slope-classification
        - Generate slope class COG and add STAC property slope_class_version
        - Add layers.json entry with gradient style
    validations:
      required: true

  - type: checkboxes
    id: change_type
    attributes:
      label: Change Type(s)
      options:
        - label: Add new module or component
        - label: Modify ETL pipeline step
        - label: Extend STAC metadata/schema
        - label: Create new visualization layer
        - label: Update documentation / SOP
        - label: Other (describe in proposal)

  - type: markdown
    attributes:
      value: "## 🧮 Expected Outcome / Metrics"

  - type: textarea
    id: expected_outcome
    attributes:
      label: Expected Outcome / Metrics
      placeholder: |
        | Metric          | Target                                        |
        | :-------------- | :---------------------------------------------|
        | Data Quality    | slope_class attribute present; STAC fields updated |
        | Reproducibility | Deterministic outputs; SOP updated            |
        | Usability       | Map layer toggle + legend                     |
        | Performance     | < +5% runtime impact                          |
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🧩 Integration Context"

  - type: dropdown
    id: integration_scope
    attributes:
      label: Integration Scope
      options:
        - Backend (ETL / AI / Graph)
        - Frontend (Map / Timeline / UI)
        - Cross-Layer (Full-stack)
        - Infrastructure (CI/CD / Deployment)
        - Documentation / SOP
    validations:
      required: true

  - type: dropdown
    id: semver
    attributes:
      label: Repo SemVer Impact
      description: "Patch = fix; Minor = new feature; Major = breaking change."
      options:
        - semver:none
        - semver:patch
        - semver:minor
        - semver:major
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🧠 Dependencies & Linkages"

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Related Components
      placeholder: |
        - Depends on: data/sources/terrain/usgs_dem.json
        - Related workflows: src/pipelines/terrain_pipeline.py
        - Requires STAC validation workflow update
        - Potential impact on Web Map layer rendering
      description: "List affected components, upstream/downstream dependencies, or required data."

  - type: textarea
    id: related_docs
    attributes:
      label: Related Documentation / SOP
      placeholder: "/docs/architecture/etl.md · /docs/sop/terrain_pipeline.md"
      description: "Link to associated documentation or operational procedures."

  - type: markdown
    attributes:
      value: "## 🧩 Implementation Plan"

  - type: textarea
    id: impl_plan
    attributes:
      label: Steps & Owners
      placeholder: |
        1) Design review — Owner …
        2) Implement ETL change — Owner …
        3) Add unit tests — Owner …
        4) Update documentation & versioning — Owner …
        5) Validate & merge — Owner …
      description: "Break down key steps, assignments, and validation points."

  - type: markdown
    attributes:
      value: "## 🧭 Versioning & Governance"

  - type: textarea
    id: versioning
    attributes:
      label: Versioning Summary
      placeholder: |
        | Scope             | Current | Proposed | Reason / Trigger          |
        | :---------------- | :------ | :-------- | :------------------------ |
        | Component Module  | v2.3.0  | v2.4.0    | Feature enhancement added |
        | CI Workflow       | v1.7.1  | v1.8.0    | STAC validation expanded  |
        | Docs / SOP        | v1.2.0  | v1.3.0    | Process updated           |
      render: markdown

  - type: markdown
    attributes:
      value: "## ✅ Pre-Merge Validation"

  - type: checkboxes
    id: validation
    attributes:
      label: Pre-Merge Checklist
      options:
        - label: Unit tests added and passing
          required: true
        - label: STAC schema validated (make stac-validate)
          required: true
        - label: ETL reproducibility confirmed
          required: true
        - label: License & data compliance verified
          required: true
        - label: Docs updated under /docs/sop/ or /docs/adr/
          required: true
        - label: Version bump recorded in CHANGELOG.md
          required: true

  - type: markdown
    attributes:
      value: "## 🧭 MCP Compliance"

  - type: checkboxes
    id: mcp
    attributes:
      label: MCP Principles
      options:
        - label: Documentation-first — feature documented and versioned
          required: true
        - label: Reproducibility — deterministic implementation steps defined
          required: true
        - label: Provenance — source modules and changes traceable
          required: true
        - label: Open Standards — compatible with STAC, DCAT, CIDOC CRM, OWL-Time
          required: true
        - label: Auditability — CI/CD and code review enforce compliance
          required: true
        - label: Versioning — feature tracked in repo and SemVer updates applied
          required: true

  - type: markdown
    attributes:
      value: "## 🧩 Related Issues / Attachments"

  - type: textarea
    id: related
    attributes:
      label: Related Issues or PRs
      placeholder: |
        - Related: #45 (ETL refactor)
        - Dependent: #102 (web map overlay support)
        - Supersedes: #37 (legacy pipeline flag)
        - Linked Data Request: #201 (terrain COG integration)
  
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: "Optional diagrams, screenshots, or proof-of-concept links"
      placeholder: |
        architecture_diagram.png — overview of workflow impact
        feature_diff.json — config patch example
        prototype.mp4 — UI demo of enhancement
  
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: "Discussion points, risk notes, or follow-up tasks."
```
