# üí° Kansas Frontier Matrix ‚Äî Feature Request Template
# File: .github/ISSUE_TEMPLATE/feature_request.yml
# Purpose: Collect structured requests for new features, enhancements, or improvements to the KFM system.
# Alignment: MCP-DL v6.3 ¬∑ KFM-MDP v11.2.5 ¬∑ KFM-OP v11.0 ¬∑ KFM-STAC v11 ¬∑ KFM-DCAT v11 ¬∑ KFM-PROV v11 ¬∑ FAIR+CARE ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©
# SPDX-License-Identifier: CC-BY-4.0

name: "üí° Feature Request"
description: "Propose a new feature, enhancement, or improvement to the Kansas Frontier Matrix project."
title: "Feature Request: [Short Title]"
labels:
  - "enhancement"
  - "feature"
  - "governance"
assignees:
  - "bartytime4life"

body:
  - type: markdown
    attributes:
      value: |
        ## üí° Kansas Frontier Matrix ‚Äî Feature Request Form
        Use this form to suggest new functionality, UI improvements, data/ETL features, or AI/graph enhancements.
        All feature proposals are reviewed under **MCP-DL v6.3**, **KFM-MDP v11.2.5**, **FAIR+CARE**, and KFM governance.

        This template is part of the deterministic KFM pipeline:

        `Deterministic ETL ‚Üí STAC/DCAT/PROV catalogs ‚Üí Neo4j knowledge graph ‚Üí API layer ‚Üí React/MapLibre/Cesium frontend ‚Üí Story Nodes ‚Üí Focus Mode`.

  - type: input
    id: feature_title
    attributes:
      label: "Feature Title"
      description: "Short, descriptive title for the requested feature."
      placeholder: "e.g. Add AI-assisted entity linking for treaty documents"
    validations:
      required: true

  - type: textarea
    id: feature_summary
    attributes:
      label: "Summary"
      description: "Summarize the purpose and scope of this feature."
      placeholder: |
        Example:
        This feature adds an NLP-based entity linking module that automatically connects
        people, places, and treaties within the Kansas Frontier Matrix knowledge graph.
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem or Opportunity"
      description: "Describe the problem this feature solves or the opportunity it enables."
      placeholder: |
        Example:
        Manual linking of historical entities is time-consuming and inconsistent.
        Automating these relationships improves accuracy and discoverability across datasets.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution"
      description: "Outline the proposed implementation (conceptual design, algorithms, UI ideas, or system changes)."
      placeholder: |
        Example:
        Implement an entity-linking module under `src/ai/models/` that uses transformer-based embeddings
        to detect and link semantic entities (people, places, events). Expose results via an API endpoint
        and integrate with Focus Mode and Neo4j through Cypher query templates.
    validations:
      required: true

  - type: dropdown
    id: component_area
    attributes:
      label: "Affected Component Area"
      description: "Select where this feature will primarily apply."
      options:
        - "ETL / Data Pipelines"
        - "AI / NLP / Focus Mode"
        - "API Layer (FastAPI / GraphQL)"
        - "Frontend (React / MapLibre / Cesium)"
        - "Documentation / Governance / Story Nodes"
        - "Infrastructure / CI-CD / GitHub Workflows"
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: pipeline_layers
    attributes:
      label: "Pipeline Layers Touched"
      description: "Select all parts of the KFM pipeline this feature will touch."
      options:
        - label: "Deterministic ETL / data ingestion"
        - label: "STAC / DCAT / PROV catalogs"
        - label: "Neo4j knowledge graph / ontologies"
        - label: "API layer (REST / GraphQL / tiles)"
        - label: "Frontend (React / MapLibre / Cesium / 3D)"
        - label: "Story Nodes / Focus Mode"
        - label: "CI/CD, security, or governance automation"
    validations:
      required: false

  - type: dropdown
    id: impact_level
    attributes:
      label: "Estimated Impact Level"
      description: "How impactful is this feature to the system or users?"
      options:
        - "High ‚Äî Core functionality or major architecture impact"
        - "Medium ‚Äî Significant usability or automation improvement"
        - "Low ‚Äî Minor enhancement, refactor, or convenience"
      default: 1
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies or Related Work"
      description: "List related datasets, models, workflows, or components this feature depends on or affects."
      placeholder: |
        Examples:
        - Depends on `src/graph/queries/link_entities.cypher`
        - Builds on `src/ai/models/focus_transformer_v2/`
        - Requires new STAC or DCAT metadata fields
    validations:
      required: false

  - type: textarea
    id: governance_and_risks
    attributes:
      label: "Governance, FAIR+CARE & Risk Considerations"
      description: "Identify data sensitivity, bias, sovereignty, performance, and security considerations."
      placeholder: |
        Examples:
        - Uses Indigenous or culturally sensitive data ‚Üí requires sovereignty / CARE review.
        - New ML model may introduce or amplify bias; needs evaluation and documentation.
        - Increased compute or storage footprint with sustainability implications.
        - Touches authentication, authorization, or security-sensitive paths.
    validations:
      required: false

  - type: textarea
    id: docs_and_catalog_impacts
    attributes:
      label: "Docs, Catalog & Knowledge Graph Impacts"
      description: "Describe which docs, catalogs, or graph schemas must be created or updated."
      placeholder: |
        Examples:
        - New architecture doc under `docs/architecture/feature_xyz.md`.
        - STAC Collection or Item changes under `data/stac/`.
        - DCAT dataset entry under `docs/data/catalog/`.
        - New node/edge types in Neo4j (KFM-OP v11 alignment).
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define measurable success criteria and done-conditions."
      placeholder: |
        Examples:
        - Entity linking achieves ‚â• 90% precision/recall on evaluation corpus.
        - Users can filter and explore new entities in Focus Mode.
        - Documentation added under `docs/ai/`, `docs/graph/`, and `docs/architecture/`.
        - Telemetry fields added and visible in governance dashboards.
    validations:
      required: true

  - type: checkboxes
    id: compliance_checklist
    attributes:
      label: "Governance & Compliance Checklist"
      description: "Confirm you understand governance and documentation expectations."
      options:
        - label: "This proposal will be documented following Master Coder Protocol (MCP-DL v6.3), documentation-first."
          required: true
        - label: "This feature will comply with FAIR+CARE principles and sovereignty policies, including Indigenous data protections where applicable."
          required: true
        - label: "I will update or create all relevant docs in `docs/` and keep configs, schemas, and examples in sync."
          required: true
        - label: "I understand this request may require architecture and governance review before implementation."
          required: true

  - type: markdown
    attributes:
      value: |
        ## üß≠ Architecture Review & Validation Workflow

        Feature requests help guide roadmap and architecture decisions. After submission, automation may:

        - Run **docs-validate.yml** to ensure the proposal and follow-up docs conform to **KFM-MDP v11.2.5**.  
        - Run **stac-validate.yml** / **dcat-validate.yml** if new metadata patterns, catalogs, or datasets are proposed.  
        - Run **faircare-validate.yml** to flag FAIR+CARE and sovereignty implications, especially for data- or AI-related features.  
        - Run **security_audit.yml** if the feature touches authentication, authorization, or supply-chain sensitive components.  
        - Feed into **telemetry_export.yml** for governance and roadmap telemetry (e.g., feature backlog, complexity, sustainability metrics).  

        Architecture and governance decisions are recorded in:

        `docs/reports/audit/github-workflows-ledger.json`

        Telemetry snapshots are typically stored in:

        `releases/<version>/focus-telemetry.json`  
        `docs/reports/telemetry/`

        Thank you for helping shape the **Kansas Frontier Matrix**.
        Your proposal contributes to a transparent, ethical, reproducible, and sovereign-aware system.

        **¬© 2025 Kansas Frontier Matrix ‚Äî CC-BY 4.0**  
        FAIR+CARE Certified ¬∑ MCP-DL v6.3 ¬∑ KFM-MDP v11.2.5 ¬∑ KFM-STAC v11 ¬∑ KFM-DCAT v11 ¬∑ KFM-PROV v11 ¬∑ KFM-OP v11.0  
        Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified
