name: "💡 Feature Request"
description: "Propose a feature or enhancement — documented, versioned, and reproducible"
title: "[Feature]: <feature name> — <component/domain>"
labels:
  - enhancement
  - needs-triage
assignees:
  - kfm-architecture
  - kfm-data

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Overview
        *“Every Feature Builds the Future · Every Change is Reproducible.”*

  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      placeholder: "Slope Classification Enhancement for Terrain Pipeline"
    validations:
      required: true

  - type: input
    id: related_component
    attributes:
      label: Primary Component / Module
      placeholder: "terrain_pipeline.py | graph_ingest.py | stac-validate.yml | web/config/layers.json"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain / Area of Impact
      options:
        - Terrain
        - Hydrology
        - Climate
        - Hazards
        - Landcover
        - Knowledge Graph
        - Web UI
        - API
        - Text / AI / NLP
        - Metadata / Governance
        - CI/CD
        - Other
    validations:
      required: true

  - type: input
    id: owner_team
    attributes:
      label: Primary Owner / Team
      placeholder: "@kfm-architecture, @kfm-data, @kfm-web"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🌐 Design Provenance"

  - type: textarea
    id: provenance
    attributes:
      label: Design References & Rationale
      description: "Link ADRs/SOPs/specs, cite standards, include brief rationale with quotes/screens if applicable"
      placeholder: |
        - ADR: /docs/adr/0007-slope-classification.md (summary: why/alternatives/decision)
        - SOP: /docs/sop/terrain_pipeline.md#slope
        - Standards: STAC 1.0.x extension property, OWL-Time, CIDOC CRM tag(s)
        - Rationale: why this change now, rejected options, alignment with roadmap
    validations:
      required: true
