---
name: "⚖️ Governance Review Request"
description: "Request a FAIR+CARE governance or ethics review for a dataset, pipeline, or documentation change (MCP-DL v6.3 Certified)"
title: "[GOVERNANCE REVIEW] <brief description>"
labels: ["governance:review", "faircare:review", "ethics:audit"]
assignees:
  - "@kfm-governance"
  - "@kfm-fair"
  - "@kfm-ethics"
body:
  - type: markdown
    attributes:
      value: |
        ## ⚖️ Kansas Frontier Matrix — Governance Review Form (FAIR+CARE Certified)
        Use this form to request a governance, ethics, or FAIR+CARE compliance review.  
        Reviews ensure transparency, ethical oversight, and MCP-DL documentation completeness before publication or release.

  - type: input
    id: review_subject
    attributes:
      label: "🧾 Subject of Review"
      description: "Provide the dataset, workflow, or documentation that requires governance or ethics evaluation."
      placeholder: "Example: data/work/processed/hazards/flood_extents.geojson"
    validations:
      required: true

  - type: dropdown
    id: review_type
    attributes:
      label: "🏷️ Type of Governance Review"
      description: "Select the type of governance review required."
      options:
        - FAIR+CARE Certification
        - Ethical Data Use Review
        - Provenance or Ledger Audit
        - Release or Publication Approval
        - Policy or Documentation Update
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📚 Description and Context"
      description: "Explain why this review is needed and summarize the context."
      placeholder: "Example: This dataset involves public hazard information and needs FAIR+CARE recertification before publication."
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: "⏱️ Review Priority"
      description: "Select the urgency level for this review."
      options:
        - Critical (Immediate release or compliance impact)
        - High (Release planned this week)
        - Normal (Next scheduled review cycle)
        - Low (Documentation or minor update)
    validations:
      required: true

  - type: textarea
    id: governance_references
    attributes:
      label: "🔗 Relevant Governance Records or Ledger Entries"
      description: "Provide any references to governance, FAIR+CARE, or ethics documentation."
      placeholder: "Example: reports/audit/data_provenance_ledger.json#record_1345 or releases/v9.6.0/manifest.zip"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🧠 FAIR+CARE Governance Review — Ethical Considerations
        Please confirm compliance across all eight FAIR+CARE principles.

  - type: checkboxes
    id: faircare_checklist
    attributes:
      label: "FAIR+CARE Principles Checklist"
      options:
        - label: "Findable — Records traceable with identifiers and metadata references"
        - label: "Accessible — Data and documentation open under appropriate licensing"
        - label: "Interoperable — Metadata aligns with STAC/DCAT/ISO standards"
        - label: "Reusable — Content properly versioned and reproducible"
        - label: "Collective Benefit — Promotes equitable, public, or environmental good"
        - label: "Authority to Control — FAIR+CARE Council approval required for release"
        - label: "Responsibility — Proper stewardship and ethics documentation provided"
        - label: "Ethics — Reviewed for inclusion, transparency, and sustainability"
    validations:
      required: true

  - type: textarea
    id: potential_risks
    attributes:
      label: "⚠️ Ethical, Legal, or Cultural Risks"
      description: "Identify any potential privacy, sensitivity, or ethical issues related to this material."
      placeholder: "Example: Contains Indigenous territorial data — requires cultural sensitivity review."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🔍 Review Outcomes & Certification (To be completed by Governance Council)
        The FAIR+CARE Governance Council will review and document decisions in ledger records.
        Certification results are automatically linked to `reports/audit/data_provenance_ledger.json`.

  - type: dropdown
    id: expected_outcome
    attributes:
      label: "🧾 Expected Review Outcome"
      description: "Select the anticipated governance result."
      options:
        - Certification Approval
        - Conditional Approval (pending revision)
        - Rejection (non-compliance)
        - Further Review Required
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: "🗒️ Additional Notes or Comments"
      description: "Provide any context or background relevant to the review."
      placeholder: "Optional additional remarks for Council consideration."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🧾 Sign-Off
        Confirm the integrity of this governance review request and your compliance with KFM's ethical and MCP-DL v6.3 documentation framework.

  - type: input
    id: requester
    attributes:
      label: "👤 Requester"
      description: "Your GitHub username or full name."
      placeholder: "@username"
    validations:
      required: true

  - type: input
    id: affiliation
    attributes:
      label: "🏢 Affiliation"
      description: "Your organization or institutional affiliation."
      placeholder: "Kansas Frontier Matrix / Open FAIR+CARE Network"
    validations:
      required: true

  - type: textarea
    id: certification
    attributes:
      label: "🪶 FAIR+CARE Certification Statement"
      description: "By submitting this review request, you affirm compliance with KFM’s ethical governance framework."
      value: |
        I confirm that this request:
        - Adheres to FAIR+CARE and MCP-DL v6.3 governance protocols.
        - Contains no sensitive or restricted private information.
        - Seeks transparent, ethical, and reproducible certification review.
    validations:
      required: true
