name: "Governance request"
description: "Request governed review/approval for Story publishing, dataset promotion, policy changes, or incidents."
title: "[GOV] <summary>"
labels:
  - governance
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Kansas Frontier Matrix (KFM) — Governance request

        Use this form to request a governed decision (publish/promote/change policy/handle an incident).

        **Safety + governance notes**
        - Do **not** include secrets, credentials, private keys, or sensitive personal data in this issue.
        - If you are uncertain about sensitivity, check the relevant trigger(s) below and explain. Review will **fail closed** if needed.

  - type: dropdown
    id: request_type
    attributes:
      label: Request type
      description: What kind of governance decision are you requesting?
      options:
        - story_publish
        - dataset_promotion
        - policy_change
        - incident
    validations:
      required: true

  - type: dropdown
    id: queue
    attributes:
      label: Governance queue
      description: Where should this request be routed?
      options:
        - story_review_queue
        - promotion_queue
        - incident_queue
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: One-line summary
      description: Keep it short and action-oriented.
      placeholder: "Publish kfm://story/<uuid>@v1 with generalized geometry"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What is changing and what decision is needed?
      description: Include background, rationale, and the explicit decision you want reviewers to make.
      placeholder: |
        - Current state:
        - Proposed state:
        - Decision requested:
        - Why now:
    validations:
      required: true

  - type: dropdown
    id: target_kind
    attributes:
      label: Target kind
      options:
        - story
        - dataset
        - policy_bundle
        - incident
        - other
    validations:
      required: true

  - type: input
    id: target_id
    attributes:
      label: Target ID
      description: Prefer canonical identifiers (kfm://... ids) or repo paths.
      placeholder: "kfm://story/<uuid>@v1"
    validations:
      required: true

  - type: dropdown
    id: current_status
    attributes:
      label: Current status
      options:
        - draft
        - review
        - published
        - unknown
    validations:
      required: true

  - type: dropdown
    id: proposed_status
    attributes:
      label: Proposed status
      options:
        - draft
        - review
        - published
        - unknown
    validations:
      required: true

  - type: input
    id: current_policy_label
    attributes:
      label: Current policy label (if known)
      description: "Use your repo's controlled vocabulary (e.g., restricted, public_generalized, public)."
      placeholder: "restricted"
    validations:
      required: false

  - type: input
    id: proposed_policy_label
    attributes:
      label: Proposed policy label (if known)
      description: Use your repo's controlled vocabulary.
      placeholder: "public_generalized"
    validations:
      required: false

  - type: textarea
    id: artifacts
    attributes:
      label: Relevant artifacts (paths/links)
      description: Provide repo paths/links to Story Node markdown + sidecar, dataset manifests, policy diffs, run receipts, etc.
      placeholder: |
        - path: <relative/path/to/story.md>
        - path: <relative/path/to/story.sidecar.json>
        - path: <relative/path/to/promotion_manifest.json>
        - link: <url or issue/PR link>
      render: markdown
    validations:
      required: false

  - type: textarea
    id: evidence_refs
    attributes:
      label: Evidence / provenance references
      description: "Paste as a YAML list (e.g., dcat://..., stac://..., prov://run/<id>, doc://...)."
      value: |
        - kind: dcat
          ref: dcat://<dataset_id>@<dataset_version_id>
        - kind: prov
          ref: prov://run/<run_id>
        - kind: doc
          ref: doc://<doc_id>
      render: yaml
    validations:
      required: false

  - type: textarea
    id: requested_actions
    attributes:
      label: Requested action(s) and constraints
      description: Include any obligations (e.g., coordinate generalization, redactions, UI notice text).
      placeholder: |
        - action: approve_publish
          notes: "Publish only generalized geometry (>=10km)"
      render: yaml
    validations:
      required: false

  - type: checkboxes
    id: sensitive_topic_flags
    attributes:
      label: Sensitive topic triggers
      description: Check any that apply (if uncertain, check the closest match and explain below).
      options:
        - label: Indigenous communities or culturally restricted knowledge involved
        - label: Archaeological site locations or sensitive ecological locations involved
        - label: Could enable harm if published (targeting, exploitation, etc.)
        - label: Contains PII or personal data

  - type: textarea
    id: sensitivity_notes
    attributes:
      label: Sensitivity details and mitigation
      description: If any trigger is checked (or uncertainty exists), describe the risk and the mitigation (redaction/generalization/etc.).
      placeholder: |
        - What is sensitive:
        - Mitigation applied/planned:
        - Residual risk:
        - Recommended policy label (if known):
    validations:
      required: false

  - type: dropdown
    id: pii_risk
    attributes:
      label: PII risk
      options:
        - unknown
        - low
        - medium
        - high
    validations:
      required: true

  - type: dropdown
    id: sensitive_location_risk
    attributes:
      label: Sensitive location risk
      options:
        - unknown
        - low
        - medium
        - high
    validations:
      required: true

  - type: dropdown
    id: rights_risk
    attributes:
      label: Rights / licensing risk
      options:
        - unknown
        - low
        - medium
        - high
    validations:
      required: true

  - type: dropdown
    id: security_risk
    attributes:
      label: Security risk
      options:
        - unknown
        - low
        - medium
        - high
    validations:
      required: true

  - type: textarea
    id: risk_notes
    attributes:
      label: Risk notes
      description: Add any additional risk context + mitigations.
      placeholder: "Coordinate generalization transform recorded in provenance; media rights verified; etc."
    validations:
      required: false

  - type: checkboxes
    id: gate_checks
    attributes:
      label: Publish / promotion gates
      description: Check what you have already verified (leave unchecked if unknown and explain in notes).
      options:
        - label: Citations/evidence refs resolve and are reproducible
        - label: Map/story does not reveal restricted coordinates or identifiers
        - label: Rights metadata exists for all embedded media
        - label: Map state references promoted dataset versions only
        - label: Policy label + review state set correctly for proposed release
        - label: Changelog / release notes updated

  - type: textarea
    id: rollback_plan
    attributes:
      label: Rollback / reversibility plan
      description: How to revert safely if issues are found after approval/publish.
      placeholder: |
        - Revert commit(s):
        - Deprecate story/dataset version:
        - Backout plan:
    validations:
      required: false

  - type: textarea
    id: approvers
    attributes:
      label: Requested reviewers / approvers
      description: List individuals or groups (use @mentions where applicable).
      placeholder: |
        - steward: @team-stewards
        - governance_council: @team-governance
    validations:
      required: false

  - type: textarea
    id: incident_details
    attributes:
      label: Incident details (only if request_type == incident)
      description: Incident type, detection signals, containment, remediation, and related run/log references.
      placeholder: |
        incident_type: <restricted_data_leakage|licensing_violation_risk|corrupted_catalogs|nondeterministic_pipeline_outputs|other>
        detected_at: YYYY-MM-DDTHH:MM:SSZ
        detection_signals: []
        containment_steps: []
        remediation_steps: []
        related_run_ids: []
      render: yaml
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I did not include secrets, credentials, or private keys in this issue.
          required: true
        - label: If there is any uncertainty about sensitivity, I am requesting review and accept a fail-closed (restricted) outcome.
          required: true
        - label: I understand this request and its decision will be recorded for audit/provenance.
          required: true
