# ‚öñÔ∏è Kansas Frontier Matrix ‚Äî Governance Review Form
# File: .github/ISSUE_TEMPLATE/governance_form.yml
# Purpose: Enable FAIR+CARE, sovereignty, cultural, and ethics-aligned governance reviews.
# Alignment: MCP-DL v6.3 ¬∑ KFM-MDP v11.2.2 ¬∑ KFM-OP v11.0 ¬∑ KFM-PDC v11.0 ¬∑ FAIR+CARE ¬∑ Indigenous Data Sovereignty ¬∑ Diamond‚Åπ Œ© / Crown‚àûŒ©
# SPDX-License-Identifier: CC-BY-4.0

name: "‚öñÔ∏è Governance or FAIR+CARE Review"
description: "Submit a governance, ethics, sovereignty, or FAIR+CARE compliance review for datasets or workflows."
title: "Governance Review: [Dataset or Layer Name]"
labels:
  - "governance"
  - "faircare"
  - "ethics"
  - "sovereignty"
assignees:
  - "bartytime4life"

body:

  - type: markdown
    attributes:
      value: |
        ## ‚öñÔ∏è Kansas Frontier Matrix ‚Äî Governance & Ethical Review

        This form ensures datasets, workflows, Story Nodes, and models align with:

        - **FAIR principles** ‚Äî Findable ¬∑ Accessible ¬∑ Interoperable ¬∑ Reusable  
        - **CARE principles** ‚Äî Collective Benefit ¬∑ Authority to Control ¬∑ Responsibility ¬∑ Ethics  
        - **Indigenous Data Sovereignty Requirements**  
        - **Master Coder Protocol v6.3**  
        - **KFM-MDP v11.2.2 governance rules**  

        Governance reviews protect communities, ensure ethical practice, and maintain transparency in the Kansas Frontier Matrix.

  - type: input
    id: reviewer_name
    attributes:
      label: "Reviewer Name(s)"
      description: "Full name(s) of reviewer(s)."
      placeholder: "e.g. Dr. Jane Doe, Tribal Cultural Office Reviewer"
    validations:
      required: true

  - type: input
    id: reviewer_affiliation
    attributes:
      label: "Affiliation / Organization"
      description: "Institution, tribal council, working group, or FAIR+CARE delegation membership."
      placeholder: "e.g. Prairie Band Potawatomi Nation ¬∑ FAIR+CARE Council"
    validations:
      required: true

  - type: dropdown
    id: review_type
    attributes:
      label: "Review Type"
      description: "Select the category that best describes this governance review."
      options:
        - "FAIR+CARE Compliance Review"
        - "Ethical or Cultural Sensitivity Review"
        - "Data Governance Audit"
        - "Indigenous Data Sovereignty Review"
        - "General Governance or Policy Feedback"
      default: 0
    validations:
      required: true

  - type: textarea
    id: dataset_reference
    attributes:
      label: "Dataset(s) / Workflow(s) Reviewed"
      description: "Provide dataset IDs, file paths, STAC/DCAT identifiers, or workflow references."
      placeholder: |
        e.g.
        - data/sources/usgs_hydro_1890.json
        - datasets/stac/tribal_boundaries_1840.item.json
        - .github/workflows/data_pipeline.yml
    validations:
      required: true

  - type: dropdown
    id: indigenous_data_flag
    attributes:
      label: "Indigenous / Tribal / Community-Governed Data"
      description: "Does this dataset or workflow involve Indigenous, Tribal, or otherwise community-governed data or knowledge?"
      options:
        - "No"
        - "Yes ‚Äî with documented approvals and conditions"
        - "Yes ‚Äî approvals pending / in progress"
        - "Unsure ‚Äî requires further sovereignty review"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: data_sensitivity
    attributes:
      label: "Proposed Sensitivity Classification"
      description: "Proposed sensitivity level for this dataset/workflow under KFM governance."
      options:
        - "Public ¬∑ Low-Risk"
        - "Limited ¬∑ Medium-Risk"
        - "Restricted ¬∑ High-Risk"
        - "Critical ¬∑ Very High-Risk"
        - "Needs Classification by FAIR+CARE Council"
      default: 0
    validations:
      required: true

  - type: textarea
    id: care_analysis
    attributes:
      label: "CARE Evaluation"
      description: |
        Assess compliance with CARE principles:
        - **Collective Benefit**
        - **Authority to Control**
        - **Responsibility**
        - **Ethics**
      placeholder: |
        Example:
        - Collective Benefit: Supports educational and community-led research.
        - Authority to Control: Dataset reviewed with sovereignty office; conditions attached.
        - Responsibility: Full provenance, licensing, and context included.
        - Ethics: No restricted or sensitive cultural materials present.
    validations:
      required: true

  - type: dropdown
    id: fair_compliance
    attributes:
      label: "FAIR Compliance Assessment"
      description: "Evaluate FAIR compliance level."
      options:
        - "Fully Compliant"
        - "Partially Compliant"
        - "Non-Compliant"
        - "Needs Additional Review"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: care_compliance
    attributes:
      label: "CARE Compliance Assessment"
      description: "Evaluate CARE compliance level."
      options:
        - "Fully Compliant"
        - "Partially Compliant"
        - "Non-Compliant"
        - "Needs Additional Review"
      default: 1
    validations:
      required: true

  - type: textarea
    id: reviewer_notes
    attributes:
      label: "Reviewer Notes & Recommendations"
      description: "Summaries, findings, remediation steps, or conditions for approval."
      placeholder: |
        Example:
        - Sovereignty office requests masking to H3 r7 for culturally sensitive features.
        - Requires corrected attribution for Indigenous knowledge sources.
        - Add contextual metadata for community impact description.
    validations:
      required: true

  - type: dropdown
    id: governance_decision
    attributes:
      label: "Governance Decision"
      description: "Proposed disposition for the reviewed dataset/workflow."
      options:
        - "Approved"
        - "Approved with Conditions"
        - "Requires Revision"
        - "Rejected"
        - "Escalate to FAIR+CARE Council"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: ai_training_inclusion
    attributes:
      label: "AI Training Inclusion"
      description: "Is this dataset/workflow approved for inclusion in AI training/fine-tuning datasets?"
      options:
        - "Not permitted for AI training"
        - "Permitted with restrictions (FAIR+CARE / sovereignty conditions)"
        - "Permitted for general AI training"
        - "Needs additional review by FAIR+CARE Council"
      default: 1
    validations:
      required: true

  - type: textarea
    id: ai_transform_notes
    attributes:
      label: "AI / Automation Notes"
      description: "Any constraints on AI transforms (e.g., allow summaries/a11y, prohibit speculative narratives), Focus Mode usage, or tool-specific conditions."
      placeholder: |
        Example:
        - Allowed transforms: summaries, a11y adaptations, semantic highlighting.
        - Prohibited: speculative historical reconstructions, decontextualized narrative generation.
        - Focus Mode: allowed only with explicit context and source citation.
    validations:
      required: false

  - type: textarea
    id: supporting_evidence
    attributes:
      label: "Supporting Documents or Evidence"
      description: "Provide links to governance notes, FAIR+CARE reports, provenance logs, or external reviews."
      placeholder: |
        e.g.
        - reports/fair/faircare_summary.json
        - docs/reports/audit/governance-ledger.json
        - https://doi.org/10.xxxx/kfm.review.2025-001
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: "Reviewer Acknowledgements"
      description: "Confirm adherence to governance requirements."
      options:
        - label: "I confirm this review aligns with Master Coder Protocol v6.3."
          required: true
        - label: "I verify all referenced data is ethically and legally shareable under the described conditions."
          required: true
        - label: "I understand this review will be logged in the governance ledger and may inform future FAIR+CARE decisions."
          required: true

  - type: markdown
    attributes:
      value: |
        ## üßæ Governance Ledger & Audit Trail

        This governance review will be permanently logged in:

        ```text
        docs/reports/audit/governance-ledger.json
        ```

        Telemetry & sustainability metrics will also be updated:

        ```text
        releases/v11.2.2/focus-telemetry.json
        docs/reports/telemetry/
        ```

        Governance reviews ensure:
        - Ethical stewardship  
        - Sovereignty protection  
        - Transparent decision-making  
        - Sustainable and responsible data practice  

        Thank you for upholding the ethical and cultural framework of the **Kansas Frontier Matrix**.

        **¬© 2025 Kansas Frontier Matrix ‚Äî CC-BY 4.0**  
        FAIR+CARE Certified ¬∑ MCP-DL v6.3 ¬∑ KFM-MDP v11.2.2 ¬∑ KFM-OP v11.0 ¬∑ KFM-PDC v11.0  
        Diamond‚Åπ Œ© / Crown‚àûŒ© Ultimate Certified
