name: "🛡️ Security Vulnerability"
description: "Report a suspected security vulnerability in the Kansas Frontier Matrix (KFM) project following responsible disclosure guidelines."
title: "[SECURITY] <short description of the vulnerability>"
labels:
  - security
  - vulnerability
  - triage-needed
assignees:
  - "@kfm-architecture"
  - "@bartytime4life"
  - "@kfm-etl-ops"

body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Responsible Disclosure
        Please **do not include secrets, private keys, access tokens, or PII** in this issue.  
        For confidential details or embargoed disclosures, follow `SECURITY.md` contact and email instructions.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Provide a concise overview of the security issue."
      placeholder: "Brief description of affected area and potential impact."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity (Reporter Assessment)
      description: "Initial assessment; the security team may adjust during triage."
      options:
        - Critical
        - High
        - Medium
        - Low
        - Informational
        - Unknown
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Affected Component(s)
      description: "Select all that apply."
      options:
        - label: "/src/ — ETL / AI / Graph"
        - label: "/web/ — Frontend (React / MapLibre)"
        - label: "/.github/workflows/ — CI/CD"
        - label: "/data/** — Datasets / Metadata"
        - label: "/docs/** — Documentation"
        - label: "Container / Dockerfile / Image"
        - label: "Other (describe below)"
    validations:
      required: true

  - type: textarea
    id: affected_versions
    attributes:
      label: Affected Versions / Branches
      description: "List specific tags, branches, or commit SHAs affected."
      placeholder: "e.g., v9.5.0, main@<sha>, feature/etl-refactor"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Runtime details that help reproduce or understand the issue."
      value: |
        OS/Platform:  
        Python/Node:  
        Docker/Compose:  
        Deployment Context (Local/CI/Containerized):  
    validations:
      required: false

  - type: dropdown
    id: exploit_status
    attributes:
      label: Exploitation Status (Reporter Knowledge)
      options:
        - Unproven
        - Proof-of-Concept Available
        - Active Exploitation Suspected
        - Confirmed Exploitation
        - Unknown
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Steps to Reproduce / PoC
      description: "Provide safe, redacted steps or a minimal PoC demonstrating the issue (omit secrets)."
      placeholder: |
        1. Step one
        2. Step two
        3. Observed vulnerable behavior
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Analysis
      description: "Describe security impact and potential downstream effects."
      placeholder: "What an attacker could do, escalation possibilities, data affected, etc."
    validations:
      required: true

  - type: dropdown
    id: confidentiality_impact
    attributes:
      label: Confidentiality Impact
      options:
        - No Impact
        - Low
        - Medium
        - High
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: integrity_impact
    attributes:
      label: Integrity Impact
      options:
        - No Impact
        - Low
        - Medium
        - High
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: availability_impact
    attributes:
      label: Availability Impact
      options:
        - No Impact
        - Low
        - Medium
        - High
        - Unknown
    validations:
      required: true

  - type: input
    id: cve
    attributes:
      label: CVE (if assigned)
      placeholder: "e.g., CVE-2025-XXXX"
    validations:
      required: false

  - type: input
    id: cwe
    attributes:
      label: CWE Category (if known)
      placeholder: "e.g., CWE-79 (XSS), CWE-89 (SQL Injection)"
    validations:
      required: false

  - type: input
    id: sbom
    attributes:
      label: SBOM Reference
      description: "Link to current SPDX SBOM for impacted release."
      placeholder: "releases/v9.5.0/sbom.spdx.json"
      value: "releases/v9.5.0/sbom.spdx.json"
    validations:
      required: false

  - type: textarea
    id: governance_refs
    attributes:
      label: Governance & References
      description: "Confirm governance documents and telemetry references."
      value: |
        Governance Ref: docs/standards/governance/ROOT-GOVERNANCE.md  
        Manifest Ref: releases/v9.5.0/manifest.zip  
        Telemetry Ref: releases/v9.5.0/focus-telemetry.json  
        FAIR+CARE Validation: docs/standards/faircare-validation.md  
        AI Ledger / Audit: reports/audit/ai_hazards_ledger.json  
        Ontology Alignment: ontologies/CIDOC_CRM-KFM.owl
    validations:
      required: false

  - type: textarea
    id: remediation
    attributes:
      label: Suggested Remediation / Mitigations
      description: "Provide recommendations (patch, config change, dependency update, compensating controls)."
      placeholder: "Proposed fix, affected files, rollback plan, test strategy"
    validations:
      required: false

  - type: input
    id: disclosure_contact
    attributes:
      label: Contact for Coordinated Disclosure
      description: "Preferred email/keybase or follow SECURITY.md instructions."
      placeholder: "security@example.org"
    validations:
      required: false

  - type: input
    id: embargo
    attributes:
      label: Requested Embargo Until (optional)
      description: "YYYY-MM-DD — For coordinated disclosure, if applicable."
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: "I have removed secrets/PII and followed SECURITY.md disclosure guidance."
        - label: "I provided a safe, minimal PoC or clear reproduction steps."
        - label: "I verified affected versions/branches."
        - label: "I included governance references and SBOM link (if applicable)."

  - type: markdown
    attributes:
      value: |
        ## 🔁 Triage & Routing (Internal)
        - **Security Triage:** @kfm-architecture · @bartytime4life  
        - **Data/ETL Verification:** @kfm-etl-ops  
        - **AI/Model Review (if relevant):** @kfm-ai-lab  

        > ⚠️ **Automation Notice**  
        > Submitting this report triggers:
        > - Code/dep scans (`.github/workflows/codeql.yml`, `.github/workflows/trivy.yml`)  
        > - Governance ledger sync (`.github/workflows/governance-ledger.yml`)  
        > - Optional docs & schema checks (`.github/workflows/docs-validate.yml`)

