from .classifier import classify
from .ids import stable_id

def build_tasks(manifest, remediation_items, evidence_records, created_at):
    tasks=[]
    for item in remediation_items:
        cat,pri,st=classify(item.get("remediation_code"),item.get("severity","REQUIRED"),"FAIL")
        tid=stable_id("kfm:air_quality:airnow:remediation_task:v1",[manifest["manifest_id"],item.get("remediation_id"),item.get("remediation_code")])
        tasks.append({"object_type":"AirNowRemediationTask","schema_version":"v1","task_id":tid,"source_id":"airnow","manifest_id":manifest["manifest_id"],"workflow_name":manifest.get("workflow_name"),"lifecycle_stage":"remediation_task_not_applied_not_published","preliminary_data":True,"publication_allowed":False,"public_dashboard_allowed":False,"tiles_allowed":False,"public_api_allowed":False,"emergency_alert":False,"regulatory_claim":False,"auto_apply_allowed":False,"github_issue_creation_allowed":False,"task_status":st,"task_category":cat,"task_priority":pri,"task_source":{"layer":"layer7","source_object_type":"AirNowRemediationPlan","source_id":item.get("remediation_id"),"source_gate_check":item.get("affected_gate_check"),"source_remediation_code":item.get("remediation_code")},"title":item.get("title","Remediation task"),"problem_statement":"Layer 7 detected evidence requiring remediation.","required_action":item.get("required_action","Fix input and rerun Layer 7 gate."),"non_goals":["Do not publish.","Do not call AirNow APIs."],"blocked_capabilities":["publication","public_dashboard","tiles","public_api","emergency_alerts","regulatory_claims"],"blocks_internal_review":bool(item.get("blocks_internal_review",False)),"blocks_publication":True,"public_release_allowed_after_fix":False,"suggested_owner_role":"data_governance_reviewer","requires_manual_review":True,"requires_source_verification":False,"requires_test_update":True,"requires_docs_update":True,"requires_fixture_update":False,"acceptance_criteria":["Rerun Layer 7 and confirm blocker resolved."],"validation_commands":["python tools/air_quality/airnow_layer7_release_gate.py --manifest tests/fixtures/air_quality/airnow/layer7/manifests/gate_valid_internal_review_manifest.json --out-dir /tmp/airnow_layer7_gate --created-at 2026-01-01T00:00:00Z"],"evidence_required":["Updated Layer 7 release_gate_receipt.json"],"created_at":created_at})
    for ev in evidence_records:
        if ev.get("status") in ("WARN","INFO"):
            cat,pri,st=classify(ev.get("remediation_code"),ev.get("severity"),ev.get("status"))
            tid=stable_id("kfm:air_quality:airnow:remediation_task:v1",[manifest["manifest_id"],ev.get("evidence_record_id")])
            tasks.append({"object_type":"AirNowRemediationTask","schema_version":"v1","task_id":tid,"source_id":"airnow","manifest_id":manifest["manifest_id"],"workflow_name":manifest.get("workflow_name"),"lifecycle_stage":"remediation_task_not_applied_not_published","preliminary_data":True,"publication_allowed":False,"public_dashboard_allowed":False,"tiles_allowed":False,"public_api_allowed":False,"emergency_alert":False,"regulatory_claim":False,"auto_apply_allowed":False,"github_issue_creation_allowed":False,"task_status":st,"task_category":cat,"task_priority":pri,"task_source":{"layer":"layer7","source_object_type":"AirNowReleaseGateEvidenceRecord","source_id":ev.get("evidence_record_id"),"source_gate_check":ev.get("gate_check"),"source_remediation_code":ev.get("remediation_code")},"title":f"Follow up {ev.get('gate_check')}","problem_statement":"Layer 7 non-pass evidence follow-up.","required_action":"Manual review and verification.","non_goals":["Do not publish."],"blocked_capabilities":["publication"],"blocks_internal_review":False,"blocks_publication":True,"public_release_allowed_after_fix":False,"suggested_owner_role":"data_governance_reviewer","requires_manual_review":True,"requires_source_verification":True,"requires_test_update":False,"requires_docs_update":True,"requires_fixture_update":False,"acceptance_criteria":["Document review result."],"validation_commands":[],"evidence_required":["Manual verification note"],"created_at":created_at})
    return sorted(tasks,key=lambda t:(t["task_priority"],t["task_category"],t["task_id"]))
