import type { MapViewProfile } from "./map-interface";

export type LivingAtlasViewStatus = "REAL_BASELINE" | "SITE_DEMO" | "DESIGN_HOLD";

export type LivingAtlasView = Readonly<{
  id: string;
  title: string;
  question: string;
  scope: string;
  domains: readonly string[];
  display: "2D" | "Terrain 3D" | "Globe" | "Story";
  time: string;
  sourcePosture: string;
  motion: string;
  report: string;
  status: LivingAtlasViewStatus;
  profileId?: MapViewProfile["id"];
  story?: boolean;
  camera?: Readonly<{
    center: readonly [number, number];
    zoom: number;
    bearing: number;
    pitch: number;
  }>;
  note: string;
}>;

const camera = (
  center: readonly [number, number],
  zoom: number,
  bearing = 0,
  pitch = 0,
) => Object.freeze({ center, zoom, bearing, pitch });

/**
 * The design inventory stays honest about the boundary between a useful
 * interface and an admitted production data package. SITE_DEMO entries map to
 * the existing local profiles; DESIGN_HOLD entries remain visible as planned
 * investigations but cannot pretend to have released data behind them.
 */
export const LIVING_ATLAS_VIEWS: readonly LivingAtlasView[] = Object.freeze([
  Object.freeze({
    id: "kansas-overview",
    title: "Kansas Overview",
    question: "Where should I begin?",
    scope: "Kansas statewide",
    domains: ["places", "water", "movement"],
    display: "2D",
    time: "Today’s observations + pinned Census edition",
    sourcePosture: "Census county baseline + USGS water sources",
    motion: "Paused; camera only",
    report: "Statewide orientation + report starter",
    status: "REAL_BASELINE",
    profileId: "overview",
    camera: camera([-98.38, 38.48], 5.45),
    note: "Opens on all 105 real county boundaries, decennial population/housing counts, stream observations and mapped hydrography. No synthetic overlay starts enabled.",
  }),
  Object.freeze({
    id: "county-atlas",
    title: "County Atlas",
    question: "What is present, changing, or missing here?",
    scope: "Choose a county; Ellsworth is the pilot focus",
    domains: ["places", "water", "coverage"],
    display: "2D",
    time: "2020 Census baseline; 2010 comparison available",
    sourcePosture: "105 Census county boundaries and counts",
    motion: "Step declared catalog time",
    report: "County dossier + coverage table",
    status: "REAL_BASELINE",
    profileId: "overview",
    camera: camera([-98.45, 38.56], 8.1),
    note: "Click a real county boundary to inspect its population, housing and land/water area. Use the archive for independently dated 2010 and 2020 baseline editions.",
  }),
  Object.freeze({
    id: "terrain-landforms",
    title: "Terrain & Landforms",
    question: "How does the land rise and shape a route?",
    scope: "Kansas landform regions",
    domains: ["geology", "hydrology"],
    display: "Terrain 3D",
    time: "Provider-published elevation mosaic",
    sourcePosture: "USGS 3DEP hillshade and reference terrain",
    motion: "Optional orbit; no data clock",
    report: "Elevation concept + limitations",
    status: "REAL_BASELINE",
    profileId: "elevation",
    camera: camera([-96.55, 38.55], 7.85, -22, 48),
    note: "Shows actual published elevation-derived terrain context. The layer retains its source limitations and makes no acquisition-date or accuracy claim for an individual pixel.",
  }),
  Object.freeze({
    id: "living-waters",
    title: "Living Waters",
    question: "What connects this river, basin, and place?",
    scope: "Kansas river corridors",
    domains: ["hydrology", "habitat"],
    display: "2D",
    time: "Exact USGS samples + provider-current GIS",
    sourcePosture: "USGS observations, hydrography and NOAA context",
    motion: "Exact gauge frames; gaps break paths",
    report: "Hydrology context + separate source clocks",
    status: "REAL_BASELINE",
    profileId: "water",
    camera: camera([-96.75, 39.0], 7.35, 12, 42),
    note: "Start with real observations and mapped waterways. Explore each station’s declared record span and daily or continuous samples in the archive. No gauge value is generalized to a reach or basin.",
  }),
  Object.freeze({
    id: "weather-window",
    title: "Weather Window",
    question: "What is available at this declared time?",
    scope: "Kansas atmosphere context",
    domains: ["atmosphere", "time"],
    display: "2D",
    time: "2022 / 2024 / 2026 steps",
    sourcePosture: "Synthetic temporal observations",
    motion: "Step frames; no interpolation",
    report: "Time-sliced catalog report",
    status: "SITE_DEMO",
    profileId: "time",
    camera: camera([-98.4, 38.5], 5.8),
    note: "The timeline makes gaps and exact fixture years visible without calling them weather observations.",
  }),
  Object.freeze({
    id: "smoke-transport",
    title: "Smoke Transport",
    question: "How should smoke context be inspected without overclaiming it?",
    scope: "Kansas plus regional context",
    domains: ["smoke", "fire", "hazards"],
    display: "2D",
    time: "NOAA analysis intervals and observed radar times",
    sourcePosture: "NOAA HMS polygons and radar images",
    motion: "Presentation effect; no forecast",
    report: "Smoke context + boundary notes",
    status: "REAL_BASELINE",
    profileId: "smoke",
    camera: camera([-99.0, 38.7], 6.4, 8, 18),
    note: "Actual smoke footprints and observed radar frames retain their provider times. This layer does not infer smoke movement, surface concentration, or exposure.",
  }),
  Object.freeze({
    id: "air-quality",
    title: "Air Quality",
    question: "What do monitors and reporting areas support?",
    scope: "Kansas monitors and reporting areas",
    domains: ["atmosphere", "health context"],
    display: "2D",
    time: "Monitor averaging periods required",
    sourcePosture: "No admitted AQI or concentration source",
    motion: "Unavailable until source closure",
    report: "Unavailable with reason",
    status: "DESIGN_HOLD",
    note: "Monitor values, AQI, reporting areas, units and averaging periods need a governed source package before loading.",
  }),
  Object.freeze({
    id: "soil-moisture",
    title: "Soil & Moisture",
    question: "What is mapped soil, and what is actually measured?",
    scope: "County, watershed, or declared analysis area",
    domains: ["soil", "water"],
    display: "2D",
    time: "Survey edition + observation intervals",
    sourcePosture: "No admitted soil package",
    motion: "Depth-aware frames required",
    report: "Unavailable with reason",
    status: "DESIGN_HOLD",
    note: "Survey units, station depths and satellite support must stay separate; a colored surface cannot substitute for measurements.",
  }),
  Object.freeze({
    id: "rail-through-time",
    title: "Rail Through Time",
    question: "How did documented rail connections change?",
    scope: "Kansas corridors and public depots",
    domains: ["rail", "history", "places"],
    display: "2D",
    time: "1885 / 1910 fixture vintages",
    sourcePosture: "Generalized movement context",
    motion: "Reveal supported editions",
    report: "Dated corridor comparison",
    status: "SITE_DEMO",
    profileId: "history",
    camera: camera([-97.0, 38.9], 7.3, 12, 18),
    note: "Network geometry is not a train, schedule, active-line status, or freight-volume feed.",
  }),
  Object.freeze({
    id: "roads-access",
    title: "Roads & Access",
    question: "How do generalized corridors connect places?",
    scope: "Kansas roads, rail and settlements",
    domains: ["roads", "rail", "places"],
    display: "2D",
    time: "Current site snapshot",
    sourcePosture: "Generalized corridors; not routable",
    motion: "Camera traversal only",
    report: "Corridor context report",
    status: "SITE_DEMO",
    profileId: "people-movement",
    camera: camera([-97.4, 38.1], 6.8, -10, 24),
    note: "Routing, traffic, closures, crossings, ownership and operational infrastructure remain outside the fixture.",
  }),
  Object.freeze({
    id: "cities-growth",
    title: "Cities & Growth",
    question: "What public place context is available here?",
    scope: "Kansas places and settlement classes",
    domains: ["cities", "settlements"],
    display: "2D",
    time: "Current site snapshot",
    sourcePosture: "Public place points; no population claim",
    motion: "Camera focus only",
    report: "Place context + selected record",
    status: "SITE_DEMO",
    profileId: "people-movement",
    camera: camera([-97.33, 37.69], 9.15, -8, 30),
    note: "City growth needs dated editions, imagery, footprints and qualified heights before it becomes a real-data view.",
  }),
  Object.freeze({
    id: "archaeology-cultural-landscapes",
    title: "Archaeology & Cultural Landscapes",
    question: "What can be responsibly explained about this landscape's past?",
    scope: "Public-approved cultural context",
    domains: ["archaeology", "history", "culture"],
    display: "Story",
    time: "Documented periods and intervals",
    sourcePosture: "Public-safe review and release required",
    motion: "Chapters with transcript",
    report: "Cited story only after review",
    status: "DESIGN_HOLD",
    note: "Protected sites, sacred places, human remains and sensitive camera or asset metadata never become public defaults.",
  }),
  Object.freeze({
    id: "geology-resources",
    title: "Geology & Resources",
    question: "Which mapped units support this explanation?",
    scope: "Public Kansas geology context",
    domains: ["geology", "resources"],
    display: "Terrain 3D",
    time: "Map vintage + geologic time",
    sourcePosture: "Generalized landform fixture",
    motion: "Edition step; no subsurface simulation",
    report: "Unit context + interpretation boundary",
    status: "SITE_DEMO",
    profileId: "elevation",
    camera: camera([-98.55, 38.85], 7.55, 24, 45),
    note: "The site can demonstrate the question and its limits; a measured subsurface volume remains a separate release.",
  }),
  Object.freeze({
    id: "agriculture-land-cover",
    title: "Agriculture & Land Cover",
    question: "How do public land-cover patterns relate to water and soil?",
    scope: "Declared county, basin, or public grid",
    domains: ["agriculture", "land cover", "water"],
    display: "2D",
    time: "Annual classifications required",
    sourcePosture: "No admitted classification package",
    motion: "Step actual editions",
    report: "Unavailable with reason",
    status: "DESIGN_HOLD",
    note: "Green pixels are not yield, ownership, management behavior, or crop certainty.",
  }),
  Object.freeze({
    id: "habitat-flora-fauna",
    title: "Habitat, Flora & Fauna",
    question: "What public-safe seasonal evidence is available?",
    scope: "Ecoregions, wetlands and generalized observations",
    domains: ["habitat", "flora", "fauna"],
    display: "2D",
    time: "Seasonal context",
    sourcePosture: "Generalized guild and community fixtures",
    motion: "Phenology concept only",
    report: "Uncertainty-aware habitat context",
    status: "SITE_DEMO",
    profileId: "ecosystems",
    camera: camera([-96.65, 38.45], 7.5, -16, 36),
    note: "The site keeps rare-species locations, nests, dens and precise movement evidence out of the public fixture.",
  }),
  Object.freeze({
    id: "hazards-resilience",
    title: "Hazards & Resilience",
    question: "Which hazard contexts are documented, and what remains unknown?",
    scope: "Kansas public-safe regional context",
    domains: ["hazards", "fire", "smoke"],
    display: "2D",
    time: "Synthetic 2022 / 2024 / 2026 steps",
    sourcePosture: "Synthetic envelopes; not emergency data",
    motion: "Paused by default",
    report: "Boundary-aware hazard context",
    status: "SITE_DEMO",
    profileId: "hazards",
    camera: camera([-98.2, 38.4], 6.3, 0, 18),
    note: "No warning, forecast, evacuation, fire perimeter, floodplain or life-safety decision is produced.",
  }),
  Object.freeze({
    id: "people-places",
    title: "People & Places",
    question: "What public place and aggregate governance context is available?",
    scope: "Kansas settlements and policy-safe aggregates",
    domains: ["people", "places", "governance"],
    display: "2D",
    time: "Current site snapshot",
    sourcePosture: "Aggregate-only policy fixtures",
    motion: "Camera transitions only",
    report: "Public-safe context report",
    status: "SITE_DEMO",
    profileId: "people-movement",
    camera: camera([-98.0, 38.5], 5.9, 0, 0),
    note: "There is no individual, household, genealogy, tribal-affiliation, genomic, or living-person tracking data.",
  }),
  Object.freeze({
    id: "story-atlas",
    title: "Story Atlas",
    question: "Can a reviewed chapter guide an evidence inspection?",
    scope: "Four-step site-local trust story",
    domains: ["story", "evidence", "history"],
    display: "Story",
    time: "Step-specific fixture years",
    sourcePosture: "Site-local guided story",
    motion: "Pause, inspect, exit",
    report: "Add selected evidence to report",
    status: "SITE_DEMO",
    profileId: "overview",
    story: true,
    camera: camera([-98.38, 38.48], 5.45),
    note: "The story is a navigation and trust exercise; it cannot elevate a fixture into an admitted release.",
  }),
]);

export const livingAtlasStatusLabel = (status: LivingAtlasViewStatus) => (
  status === "REAL_BASELINE" ? "REAL SOURCE BASELINE" : status === "SITE_DEMO" ? "LEGACY EXAMPLE" : "DESIGN / DATA HOLD"
);
