#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
import argparse, json, shutil, tempfile, os, xml.etree.ElementTree as ET
from pathlib import Path
from tools.discovery.soil._discovery_common import *

def main(argv=None):
 a=argparse.ArgumentParser();a.add_argument('--published-root',required=True);a.add_argument('--ops-root',required=True);a.add_argument('--out-root',required=True);a.add_argument('--base-public-url',required=True);a.add_argument('--release-id');a.add_argument('--discovery-id');x=a.parse_args(argv)
 rid=x.release_id or load_current_release(x.published_root); reasons=validate_discovery_inputs(x.published_root,x.ops_root,rid,x.base_public_url)
 if reasons: print(json.dumps({'discovery_allowed':False,'release_id':rid,'reasons':reasons},sort_keys=True)); return 1
 idx=load_published_index(x.published_root,rid); man=load_published_manifest(x.published_root,rid)
 source_hashes=sorted([sha256_file(Path(x.published_root)/f'published/soil/releases/{rid}/manifest.json'),sha256_file(Path(x.published_root)/f'published/soil/releases/{rid}/index.json'),sha256_file(Path(x.published_root)/f'published/soil/releases/{rid}/publication_receipt.json'),sha256_file(Path(x.ops_root)/'ops/soil/status/current_status.json'),sha256_file(Path(x.ops_root)/'ops/soil/status/status_receipt.json')])
 did=sanitize_id(x.discovery_id) if x.discovery_id else f"soil-discovery-{sha256_bytes((rid+''.join(source_hashes)).encode())[:16]}"
 out=Path(x.out_root)/'discovery/soil/releases'/did; tmp=Path(tempfile.mkdtemp(prefix='soildisc_'))/did
 (tmp/'ogcapi/collections/soil-moisture').mkdir(parents=True); (tmp/'feeds').mkdir(parents=True)
 recs=[]
 for r in sorted(idx['records'],key=lambda z:z['bundle_id']):
  sid=sanitize_id(r['bundle_id']); recs.append({'bundle_id':r['bundle_id'],'safe_bundle_id':sid,'title':f"Soil Moisture {r['bundle_id']}",'source':r.get('source'),'aggregation':r.get('aggregation'),'time_window':r.get('time_window'),'bbox':r.get('bbox'),'metrics':r.get('metrics'),'evidence_bundle_ref':r['evidence_bundle_ref'],'stac_ref':r['stac_ref'],'dcat_ref':r['dcat_ref'],'prov_ref':r['prov_ref'],'triplet_ref':r['triplet_ref'],'focus_card_ref':f"focus_cards/{sid}.json",'public_record_url':public_url_join(x.base_public_url,f"/soil/records/{sid}"),'public_focus_card_url':public_url_join(x.base_public_url,f"/soil/focus-cards/{sid}"),'public_triplet_url':public_url_join(x.base_public_url,f"/soil/triplets/{sid}.nt"),'rights_status':r['rights_status'],'policy_label':r['policy_label'],'sensitivity':r['sensitivity'],'publication_status':'PUBLISHED'})
 urls={k:public_url_join(x.base_public_url,v) for k,v in {'landing':f'/discovery/soil/releases/{did}/landing.html','schemaorg':f'/discovery/soil/releases/{did}/landing.schemaorg.jsonld','dcat':f'/discovery/soil/releases/{did}/dcat.dataset.jsonld','stac_collection':f'/discovery/soil/releases/{did}/stac_collection.json','ogcapi_landing':f'/discovery/soil/releases/{did}/ogcapi/landing.json','json_feed':f'/discovery/soil/releases/{did}/feeds/soil.json','atom_feed':f'/discovery/soil/releases/{did}/feeds/soil.atom.xml','sitemap':f'/discovery/soil/releases/{did}/sitemap.xml','robots':f'/discovery/soil/releases/{did}/robots.txt','search_index':f'/discovery/soil/releases/{did}/search_index.json'}.items()}
 schemaorg={"@context":"https://schema.org","@type":"Dataset","name":"KFM Soil Moisture Public Release","identifier":rid,"description":"Governed public soil moisture release","keywords":["soil moisture","SMAP","Mesonet","Kansas","volumetric water content"],"license":recs[0]['rights_status'],"isAccessibleForFree":True,"measurementTechnique":"SMAP L4 and Kansas Mesonet","variableMeasured":[{"name":"masked_pct"},{"name":"zscore_30d_max"},{"name":"station_grid_residual_max"}],"sameAs":list(urls.values()),"additionalProperty":[{"name":"canonical units","value":"m3/m3"},{"name":"UI percent conversion","value":"multiply_by_100_for_display_only"},{"name":"evidence bound","value":True},{"name":"model output is truth source","value":False}]}
 write_json_atomic(tmp/'landing.schemaorg.jsonld',schemaorg)
 write_text_atomic(tmp/'landing.html',f"<html><head><title>KFM Soil Discovery</title></head><body><h1>KFM Soil Moisture Public Release</h1><p>release_id={rid}</p><p>discovery_id={did}</p><a href='landing.schemaorg.jsonld'>schema</a></body></html>\n")
 write_json_atomic(tmp/'dcat.dataset.jsonld',{"@type":"dcat:Dataset","dct:identifier":did,"dcat:distribution":[{"@id":urls['json_feed']}]})
 write_json_atomic(tmp/'stac_collection.json',{"stac_version":"1.0.0","type":"Collection","id":"soil-moisture","license":"CC-BY-4.0","links":[{"rel":"self","href":urls['stac_collection']},{"rel":"items","href":public_url_join(x.base_public_url,f'/discovery/soil/releases/{did}/ogcapi/collections/soil-moisture/items.json')}]})
 write_json_atomic(tmp/'ogcapi/landing.json',{"title":"KFM Soil OGC API","links":[{"rel":"self","href":urls['ogcapi_landing']}]} )
 write_json_atomic(tmp/'ogcapi/conformance.json',{"conformsTo":["http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core"],"kfm:adapter_status":"PROPOSED_static_fixture_adapter"})
 write_json_atomic(tmp/'ogcapi/collections.json',{"collections":[{"id":"soil-moisture","links":[{"rel":"items","href":public_url_join(x.base_public_url,f'/discovery/soil/releases/{did}/ogcapi/collections/soil-moisture/items.json')}]}]})
 feats=[{"type":"Feature","id":r['safe_bundle_id'],"bbox":r['bbox'],"geometry":{"type":"Polygon","coordinates":[[[r['bbox'][0],r['bbox'][1]],[r['bbox'][2],r['bbox'][1]],[r['bbox'][2],r['bbox'][3]],[r['bbox'][0],r['bbox'][3]],[r['bbox'][0],r['bbox'][1]]]]},"properties":{k:r[k] for k in ['bundle_id','source','aggregation','time_window','metrics','rights_status','policy_label','sensitivity','evidence_bundle_ref']}|{'release_id':rid,'publication_status':'PUBLISHED','canonical_units':'m3/m3'}} for r in recs]
 write_json_atomic(tmp/'ogcapi/collections/soil-moisture/items.json',{"type":"FeatureCollection","features":feats})
 write_json_atomic(tmp/'feeds/soil.json',{"version":"https://jsonfeed.org/version/1.1","title":"KFM Soil Feed","home_page_url":urls['landing'],"feed_url":urls['json_feed'],"items":[{"id":r['safe_bundle_id'],"url":r['public_record_url'],"title":r['title'],"content_text":r['title'],"tags":["soil"],"_kfm":{"evidence_bundle_ref":r['evidence_bundle_ref'],"metrics":r['metrics']}} for r in recs]})
 atom="<feed xmlns='http://www.w3.org/2005/Atom'><title>KFM Soil Feed</title>"+''.join([f"<entry><id>{r['safe_bundle_id']}</id><title>{r['title']}</title></entry>" for r in recs])+"</feed>\n"; write_text_atomic(tmp/'feeds/soil.atom.xml',atom)
 write_json_atomic(tmp/'search_index.json',{"schema_version":"kfm.v1","object_type":"SoilPublicDiscoverySearchIndex","domain":"soil","discovery_id":did,"release_id":rid,"records":[{'bundle_id':r['bundle_id'],'safe_bundle_id':r['safe_bundle_id'],'title':r['title'],'summary':r['title'],'keywords':['soil moisture'],'source':r['source'],'aggregation':r['aggregation'],'time_window':r['time_window'],'bbox':r['bbox'],'metrics':r['metrics'],'public_urls':{'record':r['public_record_url']},'evidence_bundle_ref':r['evidence_bundle_ref'],'rights_status':r['rights_status'],'policy_label':r['policy_label'],'sensitivity':r['sensitivity']} for r in recs]})
 su=[urls['landing'],urls['schemaorg'],urls['dcat'],urls['stac_collection'],urls['ogcapi_landing'],urls['json_feed'],urls['atom_feed']]+[r['public_record_url'] for r in recs]+[r['public_focus_card_url'] for r in recs]
 sm=ET.Element('urlset',xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'); [ET.SubElement(ET.SubElement(sm,'url'),'loc').__setattr__('text',u) for u in su]; write_text_atomic(tmp/'sitemap.xml',ET.tostring(sm,encoding='unicode'))
 write_text_atomic(tmp/'robots.txt',f"User-agent: *\nAllow: /\nSitemap: {urls['sitemap']}\n")
 manifest={'schema_version':'kfm.v1','object_type':'SoilDiscoveryManifest','domain':'soil','discovery_id':did,'release_id':rid,'publication_status':'PUBLISHED','discovery_status':'DISCOVERABLE','base_public_url':x.base_public_url,'created':utc_now_iso(),'source_release':{'published_manifest_ref':f'published/soil/releases/{rid}/manifest.json','publication_receipt_ref':f'published/soil/releases/{rid}/publication_receipt.json','operational_status_ref':'ops/soil/status/current_status.json','status_receipt_ref':'ops/soil/status/status_receipt.json'},'bundle_count':len(recs),'records':recs,'public_discovery_urls':urls,'artifact_hashes':{},'policy_summary':{'release_audited':True,'service_status_checked':True,'latest_probe_checked':True,'retraction_checked':True,'rights_checked':True,'sensitivity_checked':True,'public_paths_checked':True,'forbidden_terms_checked':True,'discovery_allowed':True}}
 for f in sorted(tmp.rglob('*')):
  if f.is_file() and f.name!='discovery_receipt.json': manifest['artifact_hashes'][str(f.relative_to(tmp))]=sha256_file(f)
 write_json_atomic(tmp/'discovery_manifest.json',manifest)
 receipt={'schema_version':'kfm.v1','receipt_type':'DiscoveryReceipt','from_state':'PUBLISHED','to_state':'DISCOVERABLE','decision':'pass','domain':'soil','release_id':rid,'discovery_id':did,'created':utc_now_iso(),'source_publication_receipt':{'ref':manifest['source_release']['publication_receipt_ref'],'sha256':source_hashes[2]},'source_operational_status':{'ref':manifest['source_release']['operational_status_ref'],'sha256':source_hashes[3]},'source_status_receipt':{'ref':manifest['source_release']['status_receipt_ref'],'sha256':source_hashes[4]},'generated_artifacts':manifest['artifact_hashes'],'policy_checks':{'release_audited':True,'status_checked':True,'latest_probe_checked':True,'retraction_checked':True,'rights_checked':True,'sensitivity_checked':True,'public_paths_checked':True,'forbidden_terms_checked':True,'discovery_allowed':True},'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
 write_json_atomic(tmp/'discovery_receipt.json',receipt)
 if out.exists():
  old=load_json(out/'discovery_manifest.json')
  if old.get('artifact_hashes')!=manifest.get('artifact_hashes'): print(json.dumps({'discovery_allowed':False,'release_id':rid,'reasons':['existing discovery directory differs']},sort_keys=True)); return 1
 else:
  out.parent.mkdir(parents=True,exist_ok=True); os.replace(tmp,out)
 write_json_atomic(Path(x.out_root)/'discovery/soil/current_discovery.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentDiscoveryPointer','domain':'soil','active_discovery_id':did,'release_id':rid,'discovery_status':'DISCOVERABLE','discovery_manifest_ref':f'releases/{did}/discovery_manifest.json','discovery_receipt_ref':f'releases/{did}/discovery_receipt.json','created':utc_now_iso()})
 print(json.dumps({'discovery_allowed':True,'discovery_id':did,'release_id':rid,'state_transition':'PUBLISHED->DISCOVERABLE','outputs':{'release':str(out)}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
