#!/usr/bin/env python3
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.recommissioning.soil._recommissioning_common import *

def main(argv=None):
 p=argparse.ArgumentParser()
 for a in ['resilience_root','closure_root','incident_root','observability_root','delivery_root','routing_root','active_root','lineage_root','outcome_root','remediation_root','corrective_root','resolution_root','accountability_root','assurance_root','registry_root','certification_root','archive_root','preservation_root','reconciliation_root','federation_root','discovery_root','published_root','ops_root','recommissioning_root','out_root','base_public_url']: p.add_argument('--'+a.replace('_','-'),required=True)
 p.add_argument('--resilience-id'); p.add_argument('--recommissioning-id'); a=p.parse_args(argv)
 cur=load_current_public_resilience(a.resilience_root); rid=a.resilience_id or cur['active_resilience_id']; rm=load_public_resilience_manifest(a.resilience_root,rid)
 if rm.get('public_resilience_status')!='PUBLIC_DELIVERY_RESILIENCE_READY': print(json.dumps({'delivery_recommissioning_allowed':False,'reasons':['bad resilience']})); return 1
 recid=sanitize_id(a.recommissioning_id or ('soil-recommissioning-'+stable_payload_hash(rm).split(':')[1][:16]))
 outdir=Path(a.out_root)/f'recommissioning/soil/cycles/{recid}'; outdir.mkdir(parents=True,exist_ok=True)
 manifest={'schema_version':'kfm.v1','object_type':'SoilDeliveryRecommissioningManifest','domain':'soil','recommissioning_id':recid,'resilience_id':rid,'closure_id':rm.get('closure_id'),'incident_response_id':rm.get('incident_response_id'),'observability_id':rm.get('observability_id'),'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'publication_status':'PUBLISHED','public_resilience_status':'PUBLIC_DELIVERY_RESILIENCE_READY','delivery_recommissioning_status':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':'recommissioned_governance_only','active_public_delivery_ready':False,'created':utc_now_iso(),'base_public_url':a.base_public_url}
 write_json_atomic(outdir/'delivery_recommissioning_manifest.json',manifest)
 for n,o in [('resilience_followup_completion_registry.json','SoilResilienceFollowupCompletionRegistry'),('monitoring_baseline_revalidation_registry.json','SoilMonitoringBaselineRevalidationRegistry'),('slo_error_budget_revalidation_report.json','SoilSloErrorBudgetRevalidationReport'),('safe_mode_exit_verification_registry.json','SoilSafeModeExitVerificationRegistry'),('active_delivery_recommissioning_readiness_packet.json','SoilActiveDeliveryRecommissioningReadinessPacket'),('public_recommissioning_status_report.json','SoilPublicRecommissioningStatusReport')]: write_json_atomic(outdir/n,{'schema_version':'kfm.v1','object_type':o,'domain':'soil','recommissioning_id':recid,'resilience_id':rid})
 ents,root=build_recommissioning_transparency_log([{'event_type':'build','object_type':'SoilDeliveryRecommissioningManifest','item_id':recid,'ref':'delivery_recommissioning_manifest.json','sha256':sha256_file(outdir/'delivery_recommissioning_manifest.json'),'created':utc_now_iso()}]); write_json_atomic(outdir/'recommissioning_transparency_log.json',{'schema_version':'kfm.v1','object_type':'SoilRecommissioningTransparencyLog','domain':'soil','recommissioning_id':recid,'entries':ents,'log_root':root,'created':utc_now_iso()})
 hashes={f.name:sha256_file(f) for f in outdir.glob('*.json') if f.name!='delivery_recommissioning_receipt.json'}
 write_json_atomic(outdir/'delivery_recommissioning_receipt.json',{'schema_version':'kfm.v1','receipt_type':'DeliveryRecommissioningReceipt','from_state':'PUBLIC_DELIVERY_RESILIENCE_READY','to_state':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','decision':'governance_only','domain':'soil','recommissioning_id':recid,'resilience_id':rid,'generated_artifacts':hashes,'signatures':[{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}],'created':utc_now_iso()})
 write_json_atomic(Path(a.out_root)/'recommissioning/soil/current_delivery_recommissioning.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentDeliveryRecommissioningPointer','domain':'soil','active_recommissioning_id':recid,'resilience_id':rid,'delivery_recommissioning_status':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':'recommissioned_governance_only','active_public_delivery_ready':False,'delivery_recommissioning_manifest_ref':str(outdir/'delivery_recommissioning_manifest.json'),'delivery_recommissioning_receipt_ref':str(outdir/'delivery_recommissioning_receipt.json'),'created':utc_now_iso()})
 print(json.dumps({'delivery_recommissioning_allowed':True,'recommissioning_id':recid,'resilience_id':rid,'state_transition':'PUBLIC_DELIVERY_RESILIENCE_READY->PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':'recommissioned_governance_only','outputs':{'root':str(outdir)}})); return 0
if __name__=='__main__': raise SystemExit(main())
