#!/usr/bin/env python3
import argparse,json,hashlib,shutil,os
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.recommissioning.soil._recommissioning_common import *
def main(argv=None):
 p=argparse.ArgumentParser()
 for n in ['resilience','closure','incident','observability','delivery','routing','active','lineage','outcome','remediation','corrective','resolution','accountability','assurance','registry','certification','archive','preservation','reconciliation','federation','discovery','published','ops','recommissioning','out']:
  p.add_argument(f'--{n}-root',required=True)
 p.add_argument('--resilience-id'); p.add_argument('--recommissioning-id'); p.add_argument('--base-public-url',required=True); ns=p.parse_args(argv)
 if not validate_base_public_url(ns.base_public_url): print(json.dumps({'delivery_recommissioning_allowed':False,'reasons':['invalid base url']})); return 1
 rid=ns.resilience_id or load_current_public_resilience(ns.resilience_root)['active_resilience_id']; rm=load_public_resilience_manifest(ns.resilience_root,rid)
 fups=list((Path(ns.recommissioning_root)/f'recommissioning/soil/followup_completions/{rid}').glob('*.followup_completion.json'))
 mons=list((Path(ns.recommissioning_root)/f'recommissioning/soil/revalidation_monitors/{rid}').glob('*.revalidation_monitor.json'))
 smvs=list((Path(ns.recommissioning_root)/f'recommissioning/soil/safe_mode_verifications/{rid}').glob('*.safe_mode_exit_verification.json'))
 h=hashlib.sha256((rid+''.join(sorted([p.name for p in fups+mons+smvs]))).encode()).hexdigest()[:16]; rcid=ns.recommissioning_id or f'soil-recommissioning-{h}'
 out=Path(ns.out_root)/f'recommissioning/soil/cycles/{rcid}'; tmp=Path(str(out)+'.tmp'); shutil.rmtree(tmp,ignore_errors=True); tmp.mkdir(parents=True)
 state='recommissioned_governance_only'; active_ready=False
 if mons and smvs and rm.get('resilience_state')=='ready': state='recommissioned_active'; active_ready=True
 mani={'schema_version':'kfm.v1','object_type':'SoilDeliveryRecommissioningManifest','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'closure_id':rm.get('closure_id'),'incident_response_id':rm.get('incident_response_id'),'observability_id':rm.get('observability_id'),'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'pointer_transition_id':None,'lineage_id':None,'outcome_cycle_id':None,'remediation_id':None,'corrective_id':None,'resolution_id':None,'accountability_id':None,'assurance_id':None,'registry_id':None,'certification_id':None,'archive_package_id':None,'preservation_id':None,'reconciliation_id':None,'federation_id':None,'discovery_id':None,'prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'publication_status':'PUBLISHED','public_resilience_status':'PUBLIC_DELIVERY_RESILIENCE_READY','delivery_recommissioning_status':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':state,'certificate_status':rm.get('certificate_status','active'),'active_public_routes_enabled':bool(rm.get('active_public_routes_enabled',False)),'active_public_delivery_ready':active_ready,'created':utc_now_iso(),'base_public_url':ns.base_public_url,'artifact_hashes':{}}
 names=['delivery_recommissioning_manifest.json','resilience_followup_completion_registry.json','monitoring_baseline_revalidation_registry.json','slo_error_budget_revalidation_report.json','safe_mode_exit_verification_registry.json','active_delivery_recommissioning_readiness_packet.json','public_recommissioning_status_report.json','recommissioning_transparency_log.json']
 payloads=[mani,{'schema_version':'kfm.v1','object_type':'SoilResilienceFollowupCompletionRegistry','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'active_release_id':rm.get('active_release_id'),'completions':[load_json(x) for x in sorted(fups)]},{'schema_version':'kfm.v1','object_type':'SoilMonitoringBaselineRevalidationRegistry','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'revalidations':[load_json(x) for x in sorted(mons)]},{'schema_version':'kfm.v1','object_type':'SoilSloErrorBudgetRevalidationReport','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'revalidation_status':'pass' if state=='recommissioned_active' else 'governance_only','slo_rechecks':[]},{'schema_version':'kfm.v1','object_type':'SoilSafeModeExitVerificationRegistry','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'closure_id':rm.get('closure_id'),'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'verifications':[load_json(x) for x in sorted(smvs)],'safe_mode_exit_verified':bool(smvs),'active_public_delivery_ready':active_ready},{'schema_version':'kfm.v1','object_type':'SoilActiveDeliveryRecommissioningReadinessPacket','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'active_release_id':rm.get('active_release_id'),'readiness_state':'ready_for_active_delivery' if active_ready else 'ready_governance_only','active_public_delivery_ready':active_ready,'active_public_delivery_recommended':active_ready},{'schema_version':'kfm.v1','object_type':'SoilPublicRecommissioningStatusReport','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'delivery_recommissioning_status':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':state,'active_public_delivery_ready':active_ready},{'schema_version':'kfm.v1','object_type':'SoilRecommissioningTransparencyLog','domain':'soil','recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'entries':[],'log_root':None}]
 for n,pd in zip(names,payloads): write_json_atomic(tmp/n,pd)
 hashes={n:sha256_file(tmp/n) for n in names}; mani['artifact_hashes']=hashes; write_json_atomic(tmp/'delivery_recommissioning_manifest.json',mani)
 write_json_atomic(tmp/'delivery_recommissioning_receipt.json',{'schema_version':'kfm.v1','receipt_type':'DeliveryRecommissioningReceipt','from_state':'PUBLIC_DELIVERY_RESILIENCE_READY','to_state':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','decision':'pass' if active_ready else 'governance_only','domain':'soil','resilience_id':rid,'recommissioning_id':rcid,'created':utc_now_iso(),'generated_artifacts':hashes,'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}})
 if out.exists():
  if sha256_file(out/'delivery_recommissioning_manifest.json')!=sha256_file(tmp/'delivery_recommissioning_manifest.json'): print(json.dumps({'delivery_recommissioning_allowed':False,'reasons':['existing different content']})); return 1
 else: os.replace(tmp,out)
 write_json_atomic(Path(ns.out_root)/'recommissioning/soil/current_delivery_recommissioning.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentDeliveryRecommissioningPointer','domain':'soil','active_recommissioning_id':rcid,'resilience_id':rid,'delivery_recommissioning_status':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':state,'active_public_delivery_ready':active_ready,'delivery_recommissioning_manifest_ref':str(out/'delivery_recommissioning_manifest.json'),'delivery_recommissioning_receipt_ref':str(out/'delivery_recommissioning_receipt.json'),'created':utc_now_iso()})
 print(json.dumps({'delivery_recommissioning_allowed':True,'recommissioning_id':rcid,'resilience_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'state_transition':'PUBLIC_DELIVERY_RESILIENCE_READY->PUBLIC_DELIVERY_RECOMMISSIONING_READY','recommissioning_state':state,'outputs':{n:str(out/n) for n in names+['delivery_recommissioning_receipt.json']}})); return 0
if __name__=='__main__': raise SystemExit(main())
