#!/usr/bin/env python3
import argparse, json, shutil
from pathlib import Path
from tools.restoration.soil._delivery_restoration_common import *

def main(argv=None):
 p=argparse.ArgumentParser()
 for n in ['recommissioning','resilience','closure','incident','observability','delivery','routing','active','lineage','outcome','remediation','corrective','resolution','accountability','assurance','registry','certification','archive','preservation','reconciliation','federation','discovery','published','ops','restoration','out']: p.add_argument(f'--{n}-root',required=True)
 p.add_argument('--recommissioning-id'); p.add_argument('--restoration-id'); p.add_argument('--base-public-url',required=True)
 ns=p.parse_args(argv)
 rid=ns.recommissioning_id or load_current_delivery_recommissioning(ns.recommissioning_root)['active_recommissioning_id']; rm=load_delivery_recommissioning_manifest(ns.recommissioning_root,rid)
 adir=Path(ns.restoration_root)/f'restoration/soil/approvals/{rid}'; pdir=Path(ns.restoration_root)/f'restoration/soil/probes/{rid}'
 approvals=sorted(adir.glob('*.restoration_approval.json')); probes=sorted(pdir.glob('*.restoration_probe_receipt.json'))
 state=rm.get('recommissioning_state','blocked'); active=state=='recommissioned_active'
 if not approvals or (active and (not probes or load_json(probes[-1]).get('decision')!='pass')):
  print(json.dumps({'delivery_restoration_allowed':False,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'reasons':['missing approval/probe']})); return 1
 rest_id=sanitize_id(ns.restoration_id or ('soil-restoration-'+stable_payload_hash({'rid':rid,'a':[sha256_file(x) for x in approvals],'p':[sha256_file(x) for x in probes]})[:16]))
 out=Path(ns.out_root)/f'restoration/soil/cycles/{rest_id}'; tmp=out.with_name(out.name+'.tmp'); shutil.rmtree(tmp,ignore_errors=True); tmp.mkdir(parents=True)
 rst='restored_active' if active else ('restored_governance_only' if state=='recommissioned_governance_only' else state)
 manifest={'schema_version':'kfm.v1','object_type':'SoilDeliveryRestorationManifest','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'publication_status':'PUBLISHED','delivery_recommissioning_status':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','delivery_restoration_status':'PUBLIC_DELIVERY_RESTORATION_READY','restoration_state':rst,'certificate_status':rm.get('certificate_status','active'),'active_public_routes_enabled':active,'active_public_delivery_restored':active,'created':utc_now_iso(),'base_public_url':ns.base_public_url,'records':[]}
 files={
 'delivery_restoration_manifest.json':manifest,
 'restoration_approval_registry.json':{'schema_version':'kfm.v1','object_type':'SoilDeliveryRestorationApprovalRegistry','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'approvals':[load_json(x) for x in approvals]},
 'restored_active_delivery_overlay.json':{'schema_version':'kfm.v1','object_type':'SoilRestoredActiveDeliveryOverlay','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'restoration_state':rst,'active_public_delivery_restored':active,'active_public_routes_enabled':active,'overlay_mode':'active_overlay' if active else 'governance_only_overlay','published_current_pointer_mutated':False,'immutable_artifacts_mutated':False,'live_external_route_update_performed':False,'created':utc_now_iso()},
 'restored_endpoint_routing_table.json':{'schema_version':'kfm.v1','object_type':'SoilRestoredEndpointRoutingTable','domain':'soil','restoration_id':rest_id,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'active_release_id':rm.get('active_release_id'),'active_public_delivery_restored':active,'routes':[]},
 'restored_active_read_model_projection.json':{'schema_version':'kfm.v1','object_type':'SoilRestoredActiveReadModelProjection','domain':'soil','restoration_id':rest_id,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'active_release_id':rm.get('active_release_id'),'projection_state':'restored_active' if active else 'governance_only','units':{'canonical_soil_moisture':'m3/m3','ui_percent_conversion':'multiply_by_100_for_display_only'},'records':[]},
 'restoration_probe_registry.json':{'schema_version':'kfm.v1','object_type':'SoilRestorationProbeRegistry','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'latest_probe_decision':'pass' if active else 'not_required','probes':[load_json(x) for x in probes]},
 'post_restoration_verification_report.json':{'schema_version':'kfm.v1','object_type':'SoilPostRestorationVerificationReport','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'active_release_id':rm.get('active_release_id'),'verification_status':'pass' if active else 'governance_only','verification_passed':True},
 'public_restoration_status_report.json':{'schema_version':'kfm.v1','object_type':'SoilPublicRestorationStatusReport','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'delivery_restoration_status':'PUBLIC_DELIVERY_RESTORATION_READY','restoration_state':rst,'active_public_routes_enabled':active,'active_public_delivery_restored':active},
 }
 entries=[]
 for n,payload in files.items(): write_json_atomic(tmp/n,payload); entries.append({'event_type':'artifact','object_type':payload.get('object_type','artifact'),'item_id':n,'ref':n,'sha256':sha256_file(tmp/n),'created':utc_now_iso()})
 log,root=build_restoration_transparency_log(entries)
 write_json_atomic(tmp/'restoration_transparency_log.json',{'schema_version':'kfm.v1','object_type':'SoilRestorationTransparencyLog','domain':'soil','restoration_id':rest_id,'recommissioning_id':rid,'log_mode':'offline_deterministic_hash_chain','entries':log,'log_root':root,'created':utc_now_iso()})
 hashes={n:sha256_file(tmp/n) for n in [*files.keys(),'restoration_transparency_log.json']}; manifest['artifact_hashes']=hashes; write_json_atomic(tmp/'delivery_restoration_manifest.json',manifest)
 write_json_atomic(tmp/'delivery_restoration_receipt.json',{'schema_version':'kfm.v1','receipt_type':'DeliveryRestorationReceipt','from_state':'PUBLIC_DELIVERY_RECOMMISSIONING_READY','to_state':'PUBLIC_DELIVERY_RESTORATION_READY','decision':'pass' if active else 'governance_only','domain':'soil','prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'routing_id':rm.get('routing_id'),'delivery_id':rm.get('delivery_id'),'recommissioning_id':rid,'restoration_id':rest_id,'created':utc_now_iso(),'generated_artifacts':hashes,'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'},'published_current_pointer_mutated':False,'immutable_artifacts_mutated':False,'live_workflow_invoked_by_this_layer':False,'live_policy_mutation_performed':False,'live_external_route_update_performed':False,'live_external_monitoring_update_performed':False,'live_dns_update_performed':False,'live_cdn_update_performed':False,'live_helpdesk_submission_performed':False,'live_notification_performed':False,'raw_access_logs_publicly_exposed':False})
 if out.exists(): shutil.rmtree(tmp); print(json.dumps({'delivery_restoration_allowed':False,'reasons':['existing directory']})); return 1
 os.replace(tmp,out)
 write_json_atomic(Path(ns.out_root)/'restoration/soil/current_delivery_restoration.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentDeliveryRestorationPointer','domain':'soil','active_restoration_id':rest_id,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'delivery_restoration_status':'PUBLIC_DELIVERY_RESTORATION_READY','restoration_state':rst,'active_public_delivery_restored':active,'delivery_restoration_manifest_ref':str(out/'delivery_restoration_manifest.json'),'delivery_restoration_receipt_ref':str(out/'delivery_restoration_receipt.json'),'created':utc_now_iso()})
 print(json.dumps({'delivery_restoration_allowed':True,'restoration_id':rest_id,'recommissioning_id':rid,'delivery_id':rm.get('delivery_id'),'routing_id':rm.get('routing_id'),'prior_release_id':rm.get('prior_release_id'),'active_release_id':rm.get('active_release_id'),'state_transition':'PUBLIC_DELIVERY_RECOMMISSIONING_READY->PUBLIC_DELIVERY_RESTORATION_READY','restoration_state':rst,'outputs':{k:str(out/k) for k in list(files.keys())+['restoration_transparency_log.json','delivery_restoration_receipt.json']}})); return 0
if __name__=='__main__': raise SystemExit(main())
