import hashlib, io, json, re, tarfile
from pathlib import Path

FORBIDDEN_SCHEMES=("http://","https://","ftp://","s3://","gs://","file://")
DENIED_KEYS=("api_key","token","secret","password","bearer","credential","authorization","client_secret","access_key","refresh_token","private_key","session","deploy_key","webhook","publish_url","github_token","git_remote","ssh_key","signing_key","remote_url","callback_url","bucket","s3_bucket","storage_account","connection_string","legal_hold_id")
DENIED_FLAGS=["publication_requested","public_dashboard_requested","tiles_requested","public_api_requested","emergency_alert_requested","regulatory_claims_requested","exact_sensitive_overlay_requested","command_execution_requested","auto_execute_requested","auto_apply_requested","task_closure_requested","github_issue_creation_requested","github_pr_creation_requested","git_push_requested","file_deletion_requested","destruction_execution_requested","archive_transfer_requested","external_storage_requested","chmod_or_chattr_requested","legal_hold_creation_requested","official_archive_certification_requested","legal_advice_requested"]
REQ13=["retention_receipt_json","archival_accession_register_json","retention_schedule_json","fixity_manifest_json","retention_policy_attestation_json","retention_caveat_register_json"]

def cjson(v): return json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False)
def sh(v): return hashlib.sha256((v if isinstance(v,str) else cjson(v)).encode()).hexdigest()
def sid(prefix,v): return f"{prefix}:{sh(v)}"
def loadj(p): return json.loads(Path(p).read_text())
def wj(p,o): Path(p).write_text(json.dumps(o,indent=2,sort_keys=True)+"\n")
def wjl(p,rows): Path(p).write_text("".join(cjson(r)+"\n" for r in rows))

def _bad_path(s):
 s=str(s)
 return any(s.startswith(x) for x in FORBIDDEN_SCHEMES) or "://" in s or ".." in Path(s).parts

def _find_denied(v):
 if isinstance(v,dict):
  for k,x in v.items():
   if any(t in str(k).lower() for t in DENIED_KEYS): return True
   if _find_denied(x): return True
 if isinstance(v,list): return any(_find_denied(x) for x in v)
 return isinstance(v,str) and any(t in v.lower() for t in DENIED_KEYS)

FORBIDDEN_TEXT=["delete","destroy","archive transfer","legal hold","legal advice","official archive certification","chmod","chattr","upload","publish","deploy","execute command"]
COORD_RE=re.compile(r"\b-?\d{1,2}\.\d{4,}\s*,\s*-?\d{1,3}\.\d{4,}\b")

def run_retention_review(manifest_path,out_dir,created_at):
 m=loadj(manifest_path); out=Path(out_dir); out.mkdir(parents=True,exist_ok=True)
 errs=[]; warns=[]
 if _find_denied(m): errs.append("SECRET_FIELD_DENIED")
 if m.get("local_file_only") is not True or m.get("no_network") is not True: errs.append("NETWORK_INTENT_DENIED")
 if m.get("bulk_web_service_loop") is not False: errs.append("BULK_LOOP_DENIED")
 for k in DENIED_FLAGS:
  if m.get(k) is True: errs.append("DENIED_CAPABILITY_REQUESTED")
 l13=m.get("layer13_inputs",{})
 for p in list(l13.values()):
  if _bad_path(p): errs.append("UNSAFE_PATH")
 for e in m.get("manual_review_evidence",[]):
  if _bad_path(e.get("path","")): errs.append("UNSAFE_PATH")
 missing=[]
 for k in REQ13:
  p=l13.get(k)
  if not p or not Path(p).exists(): missing.append(k)
 if missing: errs.append("MISSING_REQUIRED_LAYER13")
 l13r=loadj(l13["retention_receipt_json"]) if l13.get("retention_receipt_json") and Path(l13["retention_receipt_json"]).exists() else {}
 if l13r.get("object_type")!="AirNowRetentionReceipt": errs.append("INVALID_LAYER13_RECEIPT")
 if l13r.get("public_release_allowed") is True: errs.append("LAYER13_PUBLIC_RELEASE_DENIED")

 inv=[]; assessments=[]; validations=[]; blockers=[]
 for e in sorted(m.get("manual_review_evidence",[]),key=lambda x:(x.get("evidence_type",""),x.get("evidence_id",""),x.get("path",""))):
  p=Path(e.get("path","")); ex=p.exists(); txt=p.read_text() if ex else ""
  b=p.read_bytes() if ex else b""
  med="application/json" if p.suffix==".json" else "text/markdown" if p.suffix==".md" else "text/plain"
  status="PASS" if ex else ("FAIL" if e.get("required") else "WARN")
  forbidden_found=any(t in txt.lower() for t in FORBIDDEN_TEXT)
  coord=bool(COORD_RE.search(txt)) if e.get("human_readable") else False
  secret=any(t in txt.lower() for t in ["api_key","token","secret","password","bearer"]) 
  if e.get("required") and not ex: blockers.append(("MISSING_REQUIRED_REVIEW_EVIDENCE",e))
  if forbidden_found: status="FAIL"; blockers.append(("FORBIDDEN_EXECUTION_AUTHORIZATION",e))
  if coord: status="FAIL"; blockers.append(("HUMAN_DOC_COORDINATE_LEAK",e))
  if secret: status="FAIL"; blockers.append(("SECRET_FIELD_DENIED",e))
  inv.append({"object_type":"AirNowRetentionReviewEvidenceInventoryRecord","schema_version":"v1","retention_review_evidence_inventory_record_id":sid("kfm:air_quality:airnow:retention_review_evidence_inventory_record:v1",[m.get("manifest_id"),e.get("evidence_id")]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"evidence_id":e.get("evidence_id"),"evidence_type":e.get("evidence_type"),"path_original":e.get("path"),"required":e.get("required",False),"exists":ex,"media_type":med,"format":"json" if p.suffix==".json" else "markdown","object_type_detected":(loadj(p).get("object_type") if ex and p.suffix==".json" else None),"expected_object_type":e.get("expected_object_type"),"related_layer13_record_id":e.get("related_layer13_record_id"),"related_artifact_id":e.get("related_artifact_id"),"byte_size":len(b),"sha256":hashlib.sha256(b).hexdigest() if ex else None,"contains_exact_coordinates_declared":e.get("contains_exact_coordinates",False),"contains_exact_coordinates_detected":coord,"human_readable":e.get("human_readable",False),"sensitivity":"internal","inventory_status":status,"warnings":[],"errors":[] if status=="PASS" else [status],"created_at":created_at})
  ast="ACCEPTED" if status=="PASS" else "NEEDS_MORE_INPUT" if status=="WARN" else "DENIED"
  reason="MANUAL_RETENTION_ATTESTATION_VALID" if e.get("evidence_type")=="MANUAL_RETENTION_ATTESTATION" and status=="PASS" else "ACCESSION_REVIEW_ACCEPTED" if status=="PASS" else "MISSING_REQUIRED_EVIDENCE" if not ex else "FORBIDDEN_EXECUTION_AUTHORIZATION"
  assessments.append({"object_type":"AirNowRetentionReviewAssessmentRecord","schema_version":"v1","retention_review_assessment_id":sid("kfm:air_quality:airnow:retention_review_assessment:v1",[m.get("manifest_id"),e.get("evidence_id")]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"evidence_id":e.get("evidence_id"),"evidence_type":e.get("evidence_type"),"related_layer13_record_id":e.get("related_layer13_record_id"),"related_artifact_id":e.get("related_artifact_id"),"assessment_status":ast,"assessment_reason_code":reason,"assessment_detail":"Manual evidence assessed for internal archival review intake.","required":e.get("required",False),"manual_attestation_required":e.get("manual_attestation_required",False),"manual_attestation_verified":status=="PASS","required_disclaimers_present":True,"forbidden_language_found":forbidden_found,"exact_coordinates_found_in_human_doc":coord,"execution_authorization_detected":forbidden_found,"legal_advice_detected":"legal advice" in txt.lower(),"blocks_archival_review_acceptance":ast in {"DENIED","REJECTED"},"public_release_allowed":False,"archive_transfer_allowed":False,"file_deletion_allowed":False,"legal_hold_creation_allowed":False,"created_at":created_at})
  validations.append({"object_type":"AirNowRetentionReviewValidationResult","schema_version":"v1","retention_review_validation_result_id":sid("kfm:air_quality:airnow:retention_review_validation_result:v1",[m.get("manifest_id"),e.get("evidence_id"),"FILE_EXISTS"]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"validation_type":"FILE_EXISTS","related_evidence_id":e.get("evidence_id"),"related_layer13_record_id":e.get("related_layer13_record_id"),"validation_status":"PASS" if ex else "FAIL","expected_condition":"evidence file exists","observed_summary":"exists" if ex else "missing","command_executed":False,"retention_action_executed":False,"manual_review_required":True,"public_release_allowed":False,"created_at":created_at})
 sat=[]
 for a in assessments:
  sat.append({"object_type":"AirNowRetentionItemSatisfactionRecord","schema_version":"v1","retention_item_satisfaction_id":sid("kfm:air_quality:airnow:retention_item_satisfaction:v1",[m.get("manifest_id"),a["evidence_id"]]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"layer13_record_id":a.get("related_layer13_record_id"),"layer13_record_type":"AirNowLayer13Record","artifact_id":a.get("related_artifact_id"),"retention_item_category":"accession","satisfaction_status":"SATISFIED_CANDIDATE" if a["assessment_status"]=="ACCEPTED" else "UNSATISFIED","satisfaction_basis":"Based on evidence assessment.","accepted_assessment_ids":[a["retention_review_assessment_id"]] if a["assessment_status"]=="ACCEPTED" else [],"rejected_assessment_ids":[] if a["assessment_status"]=="ACCEPTED" else [a["retention_review_assessment_id"]],"missing_evidence_ids":[],"validation_result_ids":[],"acceptance_candidate_created":a["assessment_status"]=="ACCEPTED","execution_performed":False,"archive_transfer_executed":False,"file_deletion_executed":False,"legal_hold_created":False,"requires_manual_review":True,"blocks_internal_archival_review_after_evidence":a["assessment_status"]!="ACCEPTED","blocks_publication_after_evidence":True,"public_release_allowed_after_evidence":False,"created_at":created_at})
 cands=[{"object_type":"AirNowRetentionAcceptanceCandidate","schema_version":"v1","retention_acceptance_candidate_id":sid("kfm:air_quality:airnow:retention_acceptance_candidate:v1",s["retention_item_satisfaction_id"]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"candidate_status":"READY_FOR_INTERNAL_ARCHIVAL_REVIEW","candidate_category":"accession","related_layer13_record_id":s.get("layer13_record_id"),"related_artifact_id":s.get("artifact_id"),"candidate_basis":"Accepted manual evidence supports internal archival review.","requires_manual_review":True,"acceptance_not_performed":True,"retention_action_executed":False,"archive_transfer_executed":False,"file_deletion_executed":False,"destruction_executed":False,"legal_hold_created":False,"official_archive_certified":False,"public_release_allowed":False,"recommended_next_action":"Manual reviewer may inspect Layer 14 report.","created_at":created_at} for s in sat if s["satisfaction_status"]=="SATISFIED_CANDIDATE"]
 b_recs=[{"object_type":"AirNowResidualRetentionBlocker","schema_version":"v1","residual_retention_blocker_id":sid("kfm:air_quality:airnow:residual_retention_blocker:v1",[b[0],b[1].get("evidence_id")]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"blocker_type":b[0],"severity":"BLOCKER","related_layer13_record_id":b[1].get("related_layer13_record_id"),"related_artifact_id":b[1].get("related_artifact_id"),"reason_code":b[0],"reason_detail":"Blocked by evidence validation.","recommended_action":"Provide compliant local evidence and rerun Layer 14.","public_release_allowed":False,"archive_transfer_allowed":False,"file_deletion_allowed":False,"legal_hold_creation_allowed":False,"created_at":created_at} for b in blockers]

 outcome="RETENTION_REVIEW_ACCEPTED_FOR_INTERNAL_ARCHIVAL_REVIEW"; val="PASS"; finite="ANSWER"
 if errs: outcome="RETENTION_REVIEW_DENIED_REQUESTED_CAPABILITY"; val="FAIL"; finite="DENY"
 elif b_recs: outcome="RETENTION_REVIEW_REJECTED"; val="FAIL"; finite="DENY"

 wj(out/'retention_review_manifest.resolved.json',{"object_type":"AirNowResolvedRetentionReviewManifest","schema_version":"v1","resolved_retention_review_manifest_id":sid("kfm:air_quality:airnow:resolved_retention_review_manifest:v1",m.get("manifest_id")),"source_id":"airnow","manifest_id":m.get("manifest_id"),"workflow_name":m.get("workflow_name"),"workflow_version":"v1","lifecycle_stage":"retention_review_intake_internal_only_not_executed_not_published","maximum_positive_outcome":"RETENTION_REVIEW_ACCEPTED_FOR_INTERNAL_ARCHIVAL_REVIEW","preliminary_data":True,"publication_allowed":False,"public_dashboard_allowed":False,"tiles_allowed":False,"public_api_allowed":False,"emergency_alert":False,"regulatory_claim":False,"legal_advice":False,"command_execution_allowed":False,"auto_execute_allowed":False,"auto_apply_allowed":False,"task_closure_allowed":False,"github_issue_creation_allowed":False,"github_pr_creation_allowed":False,"git_push_allowed":False,"file_deletion_allowed":False,"destruction_execution_allowed":False,"archive_transfer_allowed":False,"external_storage_allowed":False,"chmod_or_chattr_allowed":False,"legal_hold_creation_allowed":False,"official_archive_certification_allowed":False,"layer13_input_count":len(l13),"manual_review_evidence_count":len(inv),"required_manual_review_evidence_count":sum(1 for x in m.get('manual_review_evidence',[]) if x.get('required')),"detected_layer13_workflow_outcome":l13r.get("workflow_outcome"),"source_doc_refs":m.get("source_doc_refs",[]),"created_at":created_at})
 wj(out/'retention_review_evidence_inventory.json',{"object_type":"AirNowRetentionReviewEvidenceInventory","schema_version":"v1","retention_review_evidence_inventory_id":sid("kfm:air_quality:airnow:retention_review_evidence_inventory:v1",m.get("manifest_id")),"source_id":"airnow","manifest_id":m.get("manifest_id"),"evidence_count":len(inv),"evidence_counts_by_type":{},"inventory_status_counts":{"PASS":sum(1 for r in inv if r['inventory_status']=='PASS'),"WARN":sum(1 for r in inv if r['inventory_status']=='WARN'),"FAIL":sum(1 for r in inv if r['inventory_status']=='FAIL')},"records":inv,"created_at":created_at}); wjl(out/'retention_review_evidence_inventory.jsonl',inv)
 wj(out/'retention_review_assessment_matrix.json',{"object_type":"AirNowRetentionReviewAssessmentMatrix","schema_version":"v1","records":assessments,"created_at":created_at}); wjl(out/'retention_review_assessment_matrix.jsonl',sorted(assessments,key=lambda x:(x['assessment_status'],x['evidence_type'],x['retention_review_assessment_id'])))
 wj(out/'retention_item_satisfaction_matrix.json',{"object_type":"AirNowRetentionItemSatisfactionMatrix","schema_version":"v1","records":sat,"created_at":created_at}); wjl(out/'retention_item_satisfaction_matrix.jsonl',sorted(sat,key=lambda x:(x['retention_item_category'],x['satisfaction_status'],x['retention_item_satisfaction_id'])))
 wjl(out/'retention_acceptance_candidates.jsonl',sorted(cands,key=lambda x:(x['candidate_status'],x['candidate_category'],x['retention_acceptance_candidate_id'])))
 wjl(out/'residual_retention_blockers.jsonl',sorted(b_recs,key=lambda x:(x['severity'],x['blocker_type'],x['residual_retention_blocker_id'])))
 wj(out/'retention_review_validation_results.json',{"object_type":"AirNowRetentionReviewValidationResults","schema_version":"v1","records":validations,"created_at":created_at}); wjl(out/'retention_review_validation_results.jsonl',sorted(validations,key=lambda x:(x['validation_status'],x['retention_review_validation_result_id'])))
 wj(out/'archival_review_readiness_summary.json',{"object_type":"AirNowArchivalReviewReadinessSummary","schema_version":"v1","archival_review_readiness_summary_id":sid("kfm:air_quality:airnow:archival_review_readiness_summary:v1",m.get("manifest_id")),"source_id":"airnow","manifest_id":m.get("manifest_id"),"workflow_name":m.get("workflow_name"),"readiness_status":"READY_FOR_INTERNAL_ARCHIVAL_REVIEW" if not b_recs and not errs else "BLOCKED","positive_outcome_ceiling":"RETENTION_REVIEW_ACCEPTED_FOR_INTERNAL_ARCHIVAL_REVIEW","accepted_candidate_count":len(cands),"partial_candidate_count":0,"residual_blocker_count":len(b_recs),"blocker_counts_by_severity":{"INFO":0,"WARNING":0,"BLOCKER":len(b_recs)},"retention_actions_executed":False,"file_deletion_executed":False,"archive_transfer_executed":False,"legal_hold_created":False,"official_archive_certified":False,"public_release_allowed":False,"recommended_next_step":"Internal archival review may proceed manually outside Layer 14. Public release remains denied.","created_at":created_at})
 wj(out/'retention_review_rerun_plan.json',{"object_type":"AirNowRetentionReviewRerunPlan","schema_version":"v1","retention_review_rerun_plan_id":sid("kfm:air_quality:airnow:retention_review_rerun_plan:v1",m.get("manifest_id")),"source_id":"airnow","manifest_id":m.get("manifest_id"),"rerun_recommendation":"RERUN_LAYER14_ONLY" if not errs else "DO_NOT_RERUN_POLICY_DENIED","rerun_allowed":not bool(errs),"public_release_allowed":False,"recommended_local_commands":[],"blocked_commands":["curl","wget","gh issue create","gh pr create","git push","rm","chmod","chattr"],"created_at":created_at})
 wj(out/'retention_review_policy_attestation.json',{"object_type":"AirNowRetentionReviewPolicyAttestation","schema_version":"v1","retention_review_policy_attestation_id":sid("kfm:air_quality:airnow:retention_review_policy_attestation:v1",m.get("manifest_id")),"source_id":"airnow","manifest_id":m.get("manifest_id"),"workflow_name":m.get("workflow_name"),"policy_status":"DENY" if errs else "PASS","checks":[{"check":"review_intake_only","status":"PASS"}],"denied_capabilities":["publication","public_dashboard","tiles","public_api","emergency_alerts","regulatory_claims","command_execution","auto_execute","auto_apply","task_closure","github_issue_creation","github_pr_creation","git_push","file_deletion","destruction_execution","archive_transfer_execution","external_storage","chmod_or_chattr","legal_hold_creation","official_archive_certification","legal_advice"],"created_at":created_at})
 wj(out/'retention_review_caveat_register.json',{"object_type":"AirNowRetentionReviewCaveatRegister","schema_version":"v1","retention_review_caveat_register_id":sid("kfm:air_quality:airnow:retention_review_caveat_register:v1",m.get("manifest_id")),"source_id":"airnow","manifest_id":m.get("manifest_id"),"caveats":[{"caveat_code":"RETENTION_REVIEW_NOT_LEGAL_ADVICE","status":"PRESENT","text":"Layer 14 retention-review intake is not legal advice.","source_doc_refs":[]},{"caveat_code":"RETENTION_REVIEW_NOT_DESTRUCTION_AUTHORIZATION","status":"PRESENT","text":"Layer 14 does not authorize or execute destruction.","source_doc_refs":[]},{"caveat_code":"RETENTION_REVIEW_NOT_ARCHIVE_CERTIFICATION","status":"PRESENT","text":"Layer 14 does not certify official archive status.","source_doc_refs":[]},{"caveat_code":"RETENTION_REVIEW_NOT_ARCHIVE_TRANSFER","status":"PRESENT","text":"Layer 14 does not transfer artifacts to archive storage.","source_doc_refs":[]},{"caveat_code":"AIRNOW_PRELIMINARY_DATA","status":"PRESENT","text":"AirNow data are preliminary and subject to change.","source_doc_refs":["https://www.airnow.gov/about-the-data"]},{"caveat_code":"AIRNOW_NOT_AQS_REGULATORY_DATA","status":"PRESENT","text":"Official regulatory air-quality data must come from EPA AQS/AirData.","source_doc_refs":["https://www.epa.gov/outdoor-air-quality-data/download-daily-data"]}],"registry_status":"PASS","created_at":created_at})
 wj(out/'retention_review_status_board.json',{"object_type":"AirNowRetentionReviewStatusBoard","schema_version":"v1","retention_review_status_board_id":sid("kfm:air_quality:airnow:retention_review_status_board:v1",[m.get("manifest_id"),outcome]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"workflow_name":m.get("workflow_name"),"board_status":outcome,"columns":[{"column":"EVIDENCE_ACCEPTED","record_ids":[a['retention_review_assessment_id'] for a in assessments if a['assessment_status']=='ACCEPTED']},{"column":"ITEMS_SATISFIED_CANDIDATE","record_ids":[s['retention_item_satisfaction_id'] for s in sat if s['satisfaction_status']=='SATISFIED_CANDIDATE']},{"column":"ACCEPTANCE_CANDIDATES","record_ids":[c['retention_acceptance_candidate_id'] for c in cands]},{"column":"NEEDS_MORE_INPUT","record_ids":[]},{"column":"RESIDUAL_BLOCKERS","record_ids":[b['residual_retention_blocker_id'] for b in b_recs]},{"column":"POLICY_DENIED_CAPABILITIES","record_ids":[]}],"public_release_allowed":False,"commands_executed":False,"retention_actions_executed":False,"file_deletion_executed":False,"archive_transfer_executed":False,"legal_hold_created":False,"created_at":created_at})
 (out/'retention_review_status_board.md').write_text(f"# AirNow Layer 14 Retention Review Status Board\n\nInternal retention-review intake only.\n\nWorkflow outcome: {outcome}\n")
 (out/'retention_review_report.md').write_text("# AirNow Layer 14 Retention Review Report\n\nInternal retention-review intake only.\nLayer 14 does not execute retention actions.\nLayer 14 does not delete files.\nLayer 14 does not transfer artifacts to external storage.\nLayer 14 does not set immutable filesystem flags.\nLayer 14 does not create legal holds.\nLayer 14 does not certify official archive status.\nLayer 14 does not provide legal advice.\nLayer 14 does not execute commands.\nLayer 14 does not apply fixes automatically.\nLayer 14 does not close tasks.\nLayer 14 does not create GitHub issues or pull requests.\nNot publication output.\nNot a public dashboard.\nNot a public API.\nNot a map tile product.\nNot an emergency alert product.\nNot regulatory analysis.\nNot legal advice.\nAirNow data are preliminary and subject to change.\nOfficial regulatory air-quality data must come from EPA AQS/AirData.\nPublic release remains denied by policy.\nRetention-review acceptance is not destruction authorization.\nRetention-review acceptance is not archive-transfer execution.\n")
 packet_hash=None
 if m.get('review_policy',{}).get('include_packet',True):
  packet=out/'retention_review_packet.tar.gz'; members=sorted([p.name for p in out.iterdir() if p.is_file() and p.name!=packet.name])
  with tarfile.open(packet,'w:gz') as tf:
   for nm in members:
    d=(out/nm).read_bytes(); ti=tarfile.TarInfo(nm); ti.size=len(d); ti.mtime=0; tf.addfile(ti,io.BytesIO(d))
  packet_hash=hashlib.sha256(packet.read_bytes()).hexdigest()
 receipt={"object_type":"AirNowRetentionReviewReceipt","schema_version":"v1","receipt_id":sid("kfm:air_quality:airnow:retention_review_receipt:v1",[m.get("manifest_id"),outcome,created_at]),"source_id":"airnow","manifest_id":m.get("manifest_id"),"workflow_name":m.get("workflow_name"),"workflow_version":"v1","workflow_runner":"airnow_layer14_retention_review","workflow_runner_version":"v1","workflow_outcome":outcome,"validation_outcome":val,"finite_outcome":finite,"commands_executed":False,"review_actions_executed":False,"retention_actions_executed":False,"fixity_checks_executed":False,"file_deletion_executed":False,"destruction_executed":False,"archive_transfer_executed":False,"external_storage_used":False,"legal_hold_created":False,"official_archive_certified":False,"legal_advice_provided":False,"publication_allowed":False,"public_release_allowed":False,"task_closure_performed":False,"warnings":warns,"errors":sorted(set(errs)),"output_hashes":{"retention_review_packet_hash":packet_hash},"created_at":created_at}
 wj(out/'retention_review_receipt.json',receipt)
 return receipt
