#!/usr/bin/env python3
import argparse, json, sys, os, tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
sys.path.insert(0,str(ROOT)) if str(ROOT) not in sys.path else None
from tools.observability.soil._delivery_observability_common import *

def main(argv=None):
 ap=argparse.ArgumentParser()
 for k in ['delivery-root','routing-root','active-root','lineage-root','outcome-root','remediation-root','corrective-root','resolution-root','accountability-root','assurance-root','registry-root','certification-root','archive-root','preservation-root','reconciliation-root','federation-root','discovery-root','published-root','ops-root','observability-root','out-root','base-public-url']:
  ap.add_argument('--'+k,required=True)
 ap.add_argument('--delivery-id');ap.add_argument('--observability-id');x=ap.parse_args(argv)
 ok,reasons=validate_observability_inputs(x.base_public_url)
 did=x.delivery_id or load_current_public_delivery(x.delivery_root)['active_delivery_id']
 dm=load_public_delivery_manifest(x.delivery_root,did); dr=load_public_delivery_receipt(x.delivery_root,did)
 mdir=Path(x.observability_root)/f'observability/soil/monitors/{did}'; ms=sorted(mdir.glob('*.delivery_monitor_receipt.json'))
 if not ms: reasons.append('missing monitor receipt')
 mon=load_json(ms[-1]) if ms else {}
 if dm.get('public_delivery_status')!='PUBLIC_DELIVERY_VERIFIED': reasons.append('delivery status invalid')
 if mon.get('decision')!='pass': reasons.append('failed monitor')
 if not dr.get('signatures'): reasons.append('missing delivery signature')
 if reasons: print(json.dumps({'public_observability_allowed':False,'delivery_id':did,'reasons':reasons})); return 1
 oid=sanitize_id(x.observability_id or ('soil-observability-'+stable_payload_hash({'delivery':did,'monitor':sha256_file(ms[-1])}).split(':')[1][:16]))
 out=Path(x.out_root)/f'observability/soil/cycles/{oid}'
 if out.exists(): print(json.dumps({'public_observability_allowed':False,'delivery_id':did,'reasons':['observability dir exists']})); return 1
 tmp=Path(tempfile.mkdtemp(prefix='obs-'))/oid; tmp.mkdir(parents=True)
 manifest={'schema_version':'kfm.v1','object_type':'SoilPublicDeliveryObservabilityManifest','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'pointer_transition_id':dm.get('pointer_transition_id'),'lineage_id':dm.get('lineage_id'),'outcome_cycle_id':dm.get('outcome_cycle_id'),'remediation_id':dm.get('remediation_id'),'corrective_id':dm.get('corrective_id'),'resolution_id':dm.get('resolution_id'),'accountability_id':dm.get('accountability_id'),'assurance_id':dm.get('assurance_id'),'registry_id':dm.get('registry_id'),'certification_id':dm.get('certification_id'),'archive_package_id':dm.get('archive_package_id'),'preservation_id':dm.get('preservation_id'),'reconciliation_id':dm.get('reconciliation_id'),'federation_id':dm.get('federation_id'),'discovery_id':dm.get('discovery_id'),'prior_release_id':dm.get('prior_release_id'),'active_release_id':dm.get('active_release_id'),'publication_status':'PUBLISHED','public_delivery_status':'PUBLIC_DELIVERY_VERIFIED','public_observability_status':'PUBLIC_DELIVERY_OBSERVABILITY_READY','observability_state':'active' if dm.get('active_public_routes_enabled') else 'governance_only','certificate_status':'active','active_public_routes_enabled':bool(dm.get('active_public_routes_enabled')),'latest_monitor_decision':'pass','created':utc_now_iso(),'base_public_url':x.base_public_url,'records':sorted(dm.get('records',[]),key=lambda r:r.get('bundle_id','')) if dm.get('active_public_routes_enabled') else []}
 write_json_atomic(tmp/'public_delivery_observability_manifest.json',manifest)
 write_json_atomic(tmp/'delivery_monitor_registry.json',{'schema_version':'kfm.v1','object_type':'SoilDeliveryMonitorRegistry','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'active_release_id':dm.get('active_release_id'),'latest_monitor_id':mon.get('monitor_id'),'latest_monitor_decision':'pass','monitors':[{'monitor_id':mon.get('monitor_id'),'ref':str(ms[-1]),'sha256':sha256_file(ms[-1]),'decision':'pass','active_public_routes_enabled':mon.get('active_public_routes_enabled'),'endpoint_count':len(mon.get('endpoint_results',[])),'failed_endpoint_count':0,'failure_reasons':[],'created':mon.get('created')}],'required_monitor_present':True})
 write_json_atomic(tmp/'access_log_snapshot_registry.json',{'schema_version':'kfm.v1','object_type':'SoilPublicSafeAccessLogSnapshotRegistry','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'active_release_id':dm.get('active_release_id'),'snapshots':[],'aggregated_routes':[],'raw_logs_publicly_exposed':False,'ip_addresses_logged':False,'authorization_headers_logged':False,'cookies_logged':False,'raw_user_agents_logged':False})
 slo=[{'slo_id':f'KFM-SLO-{i:03d}','endpoint_pattern':'*','objective_name':'req','target':'all_required_probes_pass','observed':'pass','status':'pass','evidence_refs':[str(ms[-1])],'failure_reason':None} for i in range(1,13)]
 write_json_atomic(tmp/'endpoint_slo_matrix.json',{'schema_version':'kfm.v1','object_type':'SoilEndpointSloMatrix','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'slo_mode':'offline_deterministic_fixture','slos':slo})
 write_json_atomic(tmp/'route_error_budget_report.json',{'schema_version':'kfm.v1','object_type':'SoilRouteErrorBudgetReport','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'error_budget_mode':'offline_deterministic_fixture','error_budget_state':'healthy','required_probe_failures':0,'unsafe_log_entries':0,'route_errors':[],'public_advertising_allowed':dm.get('active_public_routes_enabled',False),'incident_trigger_recommended':False})
 write_json_atomic(tmp/'endpoint_response_drift_report.json',{'schema_version':'kfm.v1','object_type':'SoilEndpointResponseDriftReport','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'drift_detected':False,'comparisons':[],'variable_fields_ignored':['created','uptime','request_id'],'failure_reasons':[]})
 write_json_atomic(tmp/'consumer_contract_drift_report.json',{'schema_version':'kfm.v1','object_type':'SoilConsumerContractDriftReport','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'consumer_contract_drift_detected':False,'checks':[],'breaking_change_detected':False,'public_safe_fields_preserved':True,'prohibited_fields_absent':True})
 write_json_atomic(tmp/'incident_trigger_recommendations.json',{'schema_version':'kfm.v1','object_type':'SoilObservabilityIncidentTriggerRecommendations','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'incident_triggered':False,'recommended_incident_type':None,'recommended_severity':None,'recommended_action':'none','triggers':[],'trigger_workflow_refs':{'record_incident':'tools/ops/soil/record_incident.py','route_reprobe':'tools/observability/soil/run_delivery_monitor.py'}})
 write_json_atomic(tmp/'public_observability_status_report.json',{'schema_version':'kfm.v1','object_type':'SoilPublicObservabilityStatusReport','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'pointer_transition_id':dm.get('pointer_transition_id'),'prior_release_id':dm.get('prior_release_id'),'active_release_id':dm.get('active_release_id'),'public_observability_status':'PUBLIC_DELIVERY_OBSERVABILITY_READY','observability_state':manifest['observability_state'],'certificate_status':'active','active_public_routes_enabled':manifest['active_public_routes_enabled'],'latest_monitor_decision':'pass','endpoint_slo_state':'pass','error_budget_state':'healthy','response_drift_detected':False,'consumer_contract_drift_detected':False,'incident_triggered':False,'public_advertising_allowed':dm.get('active_public_routes_enabled',False),'public_summary':'deterministic'})
 tlog=build_observability_transparency_log([{'event_type':'monitor','object_type':'DeliveryMonitorReceipt','item_id':mon.get('monitor_id'),'ref':str(ms[-1]),'sha256':sha256_file(ms[-1]),'created':utc_now_iso()}])
 write_json_atomic(tmp/'observability_transparency_log.json',{'schema_version':'kfm.v1','object_type':'SoilPublicObservabilityTransparencyLog','domain':'soil','observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'pointer_transition_id':dm.get('pointer_transition_id'),'prior_release_id':dm.get('prior_release_id'),'active_release_id':dm.get('active_release_id'),'log_mode':'offline_deterministic_hash_chain','live_notification_performed':False,'live_external_observability_export_performed':False,'live_external_route_update_performed':False,'live_dns_update_performed':False,'live_cdn_update_performed':False,'published_current_pointer_mutated':False,'entries':tlog['entries'],'log_root':tlog['log_root'],'created':utc_now_iso()})
 hashes={f.name:sha256_file(f) for f in tmp.iterdir() if f.name!='public_observability_receipt.json'}
 write_json_atomic(tmp/'public_observability_receipt.json',{'schema_version':'kfm.v1','receipt_type':'PublicObservabilityReceipt','from_state':'PUBLIC_DELIVERY_VERIFIED','to_state':'PUBLIC_DELIVERY_OBSERVABILITY_READY','decision':'pass' if dm.get('active_public_routes_enabled') else 'governance_only','domain':'soil','prior_release_id':dm.get('prior_release_id'),'active_release_id':dm.get('active_release_id'),'successor_release_id':dm.get('successor_release_id'),'registry_id':dm.get('registry_id'),'assurance_id':dm.get('assurance_id'),'accountability_id':dm.get('accountability_id'),'resolution_id':dm.get('resolution_id'),'corrective_id':dm.get('corrective_id'),'remediation_id':dm.get('remediation_id'),'outcome_cycle_id':dm.get('outcome_cycle_id'),'lineage_id':dm.get('lineage_id'),'pointer_transition_id':dm.get('pointer_transition_id'),'routing_id':dm.get('routing_id'),'delivery_id':did,'observability_id':oid,'created':utc_now_iso(),'live_notification_performed':False,'live_external_observability_export_performed':False,'live_external_route_update_performed':False,'live_dns_update_performed':False,'live_cdn_update_performed':False,'raw_access_logs_publicly_exposed':False,'published_current_pointer_mutated':False,'immutable_artifacts_mutated':False,'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'},'generated_artifacts':hashes,'observability_transparency_log_root':tlog['log_root']})
 out.parent.mkdir(parents=True,exist_ok=True); os.replace(tmp,out)
 write_json_atomic(Path(x.out_root)/'observability/soil/current_public_observability.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentPublicObservabilityPointer','domain':'soil','active_observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'pointer_transition_id':dm.get('pointer_transition_id'),'lineage_id':dm.get('lineage_id'),'prior_release_id':dm.get('prior_release_id'),'active_release_id':dm.get('active_release_id'),'public_observability_status':'PUBLIC_DELIVERY_OBSERVABILITY_READY','observability_state':manifest['observability_state'],'latest_monitor_decision':'pass','public_delivery_observability_manifest_ref':str(out/'public_delivery_observability_manifest.json'),'public_observability_receipt_ref':str(out/'public_observability_receipt.json'),'created':utc_now_iso()})
 print(json.dumps({'public_observability_allowed':True,'observability_id':oid,'delivery_id':did,'routing_id':dm.get('routing_id'),'prior_release_id':dm.get('prior_release_id'),'active_release_id':dm.get('active_release_id'),'state_transition':'PUBLIC_DELIVERY_VERIFIED->PUBLIC_DELIVERY_OBSERVABILITY_READY','observability_state':manifest['observability_state'],'outputs':{'root':str(out)}})); return 0
if __name__=='__main__': raise SystemExit(main())
