# ==============================================================================
# Kansas-Frontier-Matrix — Declarative Roadmap (→ Issues & Milestones)
# Consumed by .github/workflows/roadmap.yml to sync labels, milestones, issues.
# Colors are 6-hex (no '#'), as GitHub's API expects.
# ==============================================================================

version: 1
project: "Kansas Geo Timeline"
owner: "bartytime4life"

enums:
  priorities: [P1, P2, P3]
  estimates:  [XS, S, M, L, XL]

defaults:
  create_missing_labels: true
  create_missing_milestones: true
  close_missing_issues: false
  dry_run: false
  issue:
    state: open
    assignees: []
    labels: []
    priority: P2
    estimate: M

# ------------------------------------------------------------------------------
# Labels (idempotent) — will be created/updated by name/color/description
# ------------------------------------------------------------------------------

labels:
  # scope / domain
  - name: data            ; color: "1f77b4" ; description: "Datasets, ingestion, sources"
  - name: hydrology       ; color: "17becf" ; description: "Water, flood, irrigation, aquifer"
  - name: paleoclimate    ; color: "bcbd22" ; description: "Tree rings, pollen, charcoal, proxies"
  - name: ai              ; color: "9467bd" ; description: "NLP, CV, geospatial ML, modeling"
  - name: uncertainty     ; color: "7f7f7f" ; description: "UQ, calibration, confidence, error bars"
  - name: ontology        ; color: "8c564b" ; description: "CIDOC-CRM, GeoSciML, KG, RDF/OWL"
  - name: fractals        ; color: "e377c2" ; description: "Fractals, scaling laws, clustering"
  - name: storytelling    ; color: "ff7f0e" ; description: "Narrative modules, timeline, glossary"
  - name: crowdsourcing   ; color: "2ca02c" ; description: "Submission portal, contributor flow"
  - name: 3d              ; color: "d62728" ; description: "CesiumJS, KML/KMZ, time-dynamic"
  - name: api             ; color: "00b5ad" ; description: "REST/GraphQL, downloads"
  - name: architecture    ; color: "111111" ; description: "Modularity, plugins, extension points"
  - name: reproducibility ; color: "9edae5" ; description: "STAC validation, CI/CD"
  - name: MCP             ; color: "6e6ef7" ; description: "Master Coder Protocol artifacts"
  - name: education       ; color: "c49c94" ; description: "UI literacy, public comms"
  # viewer / infra
  - name: stac            ; color: "0a7bbb" ; description: "STAC catalog, collections, items"
  - name: web             ; color: "1f6feb" ; description: "MapLibre viewer, web/config pack"
  - name: ci              ; color: "6a737d" ; description: "GitHub Actions, pipelines"
  - name: docker          ; color: "2496ed" ; description: "Dockerfiles, compose, images"
  - name: python          ; color: "3776ab" ; description: "Python packages, CLI, scripts"
  - name: security        ; color: "b60205" ; description: "Vulns, CodeQL, secrets, supply chain"
  # triage / defaults used by templates
  - name: bug             ; color: "d73a4a" ; description: "Something isn’t working"
  - name: enhancement     ; color: "a2eeef" ; description: "Feature request / improvement"
  - name: triage          ; color: "fbca04" ; description: "Needs review / classification"

# ------------------------------------------------------------------------------
# Milestones → GitHub Milestones (with issues that create/update GH Issues).
# Each milestone and issue includes a stable 'key' for idempotent sync.
# ------------------------------------------------------------------------------

milestones:
  - key: m1-data
    title: "Milestone 1 — Enrich Data Sources"
    state: open
    due_on: "2025-10-31"
    description: >
      Expand coverage: oral histories, paleoclimate proxies, hydrology & water management.
      Document sources and provenance in the STAC catalog; wire key layers to the viewer.
    issues:
      - key: oral-histories
        title: "Oral Histories & Indigenous Narratives"
        labels: [data, storytelling, MCP]
        priority: P2
        estimate: S
        body: |
          ### Goal
          Integrate oral history archives with geocoded map links and contextual popups.

          ### Tasks
          - [ ] Identify oral history archives (tribal, local historical societies, KHRI)
          - [ ] Digitize + geocode transcripts (MCP experiment template)
          - [ ] Link narratives to features with glossary tooltips
          - [ ] Document sources in `data/sources/oral_histories.json`

          ### Deliverables
          - `data/sources/oral_histories.json` (license, contact, update cadence)
          - Initial story map tie-ins (timeline + glossary)
        files:
          - data/sources/oral_histories.json

      - key: paleo-fire
        title: "Paleoclimate & Fire Regimes"
        labels: [data, paleoclimate]
        priority: P2
        estimate: M
        body: |
          ### Goal
          Bring in drought indices, pollen cores, and charcoal/fire records for environmental context.

          ### Tasks
          - [ ] Integrate NOAA/USDM drought indices and station normals
          - [ ] Add pollen/charcoal/fire records (Neotoma, state archives)
          - [ ] Cross-link KGS/Neotoma paleo records
          - [ ] Create `data/sources/paleoclimate.json` with provenance

          ### Deliverables
          - `data/sources/paleoclimate.json` + STAC registration
        files:
          - data/sources/paleoclimate.json

      - key: hydro-expansion
        title: "Hydrology & Water Management Expansion"
        labels: [data, hydrology]
        priority: P2
        estimate: M
        body: |
          ### Goal
          Enrich water datasets and prototype flood scenarios.

          ### Tasks
          - [ ] Add flood event datasets (NOAA Storm Events, FEMA declarations)
          - [ ] Add irrigation/management layers (canals/diversions where public)
          - [ ] Prototype HEC-RAS historical flood scenarios (MCP modeling SOP)
          - [ ] STAC registration for hydrology items/collections
          - [ ] Wire Makefile + viewer to load layers (`make site`, `make site-config`)

          ### Deliverables
          - `data/sources/hydrology.json` endpoints + licenses
          - FEMA + SPC + USDM entries in `data/sources/` as needed
          - Hydrology STAC Items/Collections and web layers
        files:
          - data/sources/hydrology.json

      - key: kgs-kansas-river
        title: "Kansas River (KGS) Integration — Source → STAC → Viewer"
        labels: [data, hydrology, reproducibility, stac, web]
        priority: P1
        estimate: S
        body: |
          ### Goal
          Incorporate KGS Kansas River as a first-class hydrology layer:
          source descriptor, STAC collection/items, fetch/export, and viewer overlays.

          ### Tasks
          - [ ] Source: `data/sources/ks_kansas_river.json` (ArcGIS REST + metadata)
          - [ ] STAC: `stac/collections/ks_kansas_river.json`
                (+ link under `stac/collections/vectors.json` if used)
          - [ ] Items: `stac/items/ks_kansas_river/channels.json`,
                `stac/items/ks_kansas_river/floodplains.json`,
                `stac/items/ks_kansas_river/gauges.json`
          - [ ] Makefile: `hydrology-fetch` (ogr2ogr), `hydrology-stac`
                (href patch), plus `site`/`site-config` for preview
          - [ ] Web: `ksriv_*` layers present in `web/layers.json` (fallback)
                and `web/app.config.json` (STAC-rendered)
          - [ ] CI: (optional) dry-run job to exercise `make hydrology-fetch`

          ### Acceptance
          - End-to-end path visible in preview: source → export (GeoJSON)
            → STAC-wired → rendered in viewer (with attribution)
        files:
          - data/sources/ks_kansas_river.json
          - stac/collections/ks_kansas_river.json
          - stac/items/ks_kansas_river/channels.json
          - stac/items/ks_kansas_river/floodplains.json
          - stac/items/ks_kansas_river/gauges.json
          - data/processed/hydrology/kansas_river/channels.geojson
          - data/processed/hydrology/kansas_river/floodplains.geojson
          - data/processed/hydrology/kansas_river/gauges.geojson
          - web/layers.json
          - web/app.config.json
          - Makefile

  - key: m2-analytics
    title: "Milestone 2 — Analytical Enhancements"
    state: open
    due_on: "2025-11-30"
    description: >
      Predictive modeling, uncertainty, symbolic reasoning, fractal/pattern analytics.
    issues:
      - key: predictive-modeling
        title: "Predictive Modeling"
        labels: [ai]
        priority: P2
        estimate: L
        body: |
          ### Goal
          Predict likely settlement sites using environmental drivers.

          ### Tasks
          - [ ] Train on DEM, hydrology, soils, land cover + known sites
          - [ ] Log in `mcp/experiments/EXP-SETTLE-PRED.md`
          - [ ] Explore Bayesian + hybrid ABM/GIS variants

          ### Deliverables
          - Reproducible notebook + MCP experiment log
        files:
          - mcp/experiments/EXP-SETTLE-PRED.md

      - key: uncertainty-quant
        title: "Uncertainty Quantification"
        labels: [uncertainty]
        priority: P1
        estimate: M
        body: |
          ### Goal
          Make uncertainty first-class in georeferencing, NLP, and map rectification.

          ### Tasks
          - [ ] Confidence scores for NLP toponyms
          - [ ] Georeferencing RMS/error reporting, rectification logs
          - [ ] UI display: opacity/error bars/CI shading

      - key: symbolic-reasoning
        title: "Symbolic & Knowledge-Based Reasoning"
        labels: [ontology, ai]
        priority: P2
        estimate: M
        body: |
          ### Goal
          Add CIDOC-CRM + GeoSciML ontologies and treaty/legal inference rules.

          ### Tasks
          - [ ] Define core ontology schema and identity strategy (Wikidata)
          - [ ] Implement rules for treaty/legal land transfers
          - [ ] Export RDF/OWL snapshots

      - key: fractal-patterns
        title: "Fractal & Pattern Analysis"
        labels: [fractals, ai]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Quantify scaling and self-similarity in rivers, fires, and settlement clusters.

          ### Tasks
          - [ ] Meander fractal dimension and sinuosity metrics
          - [ ] Power-law analysis on event/migration frequencies
          - [ ] Cluster scaling vs hydro-geomorphology

  - key: m3-story
    title: "Milestone 3 — Storytelling & Education"
    state: open
    due_on: "2025-12-31"
    description: >
      Public-facing narrative modules, educational overlays, glossary tooltips, and submission portal.
    issues:
      - key: sft-storymap
        title: "Interactive Story Maps — Santa Fe Trail"
        labels: [storytelling, education]
        priority: P2
        estimate: M
        body: |
          ### Goal
          Build narrative module for the Santa Fe Trail with timeline & sources.

          ### Tasks
          - [ ] Assemble trail route layers + primary sources
          - [ ] Timeline UI + step-through views
          - [ ] Educator notes + glossary links

      - key: dustbowl-timeline
        title: "Dust Bowl Timeline Prototype"
        labels: [storytelling, education]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Blend 1930s climate, newspaper archives, soils, and land use.

          ### Tasks
          - [ ] Collect climate + newspaper datasets
          - [ ] Compose time-series map overlays
          - [ ] Add uncertainty annotations

      - key: glossary-annotations
        title: "Glossary & Educational Annotations"
        labels: [education, MCP]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Link MCP glossary into tooltips and overlays.

          ### Tasks
          - [ ] Embed glossary lookups in popups
          - [ ] Author overlays for railroads, treaties, forts, migration

      - key: crowdsourcing-portal
        title: "Crowdsourcing Submission Portal"
        labels: [crowdsourcing]
        priority: P3
        estimate: M
        body: |
          ### Goal
          Lower barrier for community contributions (web form → GitHub PR).

          ### Tasks
          - [ ] Build web form with metadata/consent checks
          - [ ] PR bot to format submissions
          - [ ] `docs/CONTRIBUTING.md` contributor guide

  - key: m4-tech
    title: "Milestone 4 — Technical Enhancements"
    state: open
    description: >
      3D/temporal, semantic web, modular plugins, APIs, and download endpoints.
    issues:
      - key: time-3d
        title: "3D Time Animation"
        labels: [3d]
        priority: P3
        estimate: M
        body: |
          ### Goal
          CesiumJS prototype and regionated KML/KMZ export for Google Earth.

          ### Tasks
          - [ ] CesiumJS time-dynamic scene (1850–present)
          - [ ] Regionated KML/KMZ exports

      - key: semantic-web
        title: "Semantic Web Integration"
        labels: [ontology, api]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Publish an internal knowledge graph with entity linking.

          ### Tasks
          - [ ] Map entities to Wikidata; export RDF
          - [ ] SPARQL/GraphQL access (if feasible)

      - key: modularity
        title: "Modularity & Extensibility"
        labels: [architecture]
        priority: P2
        estimate: M
        body: |
          ### Goal
          Refactor ingestion/AI/UI into plugins, document extension points.

          ### Tasks
          - [ ] Define plugin API boundaries
          - [ ] `docs/architecture.md` extension sections

      - key: apis-downloads
        title: "APIs & External Tools"
        labels: [api]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Provide REST/GraphQL endpoints and GeoJSON/CSV downloads.

          ### Tasks
          - [ ] Dataset catalog endpoints
          - [ ] Download endpoints (GeoJSON/CSV)

  - key: m5-mcp
    title: "Milestone 5 — MCP Integration"
    state: open
    description: >
      Experiments, SOPs, model cards, and CI/STAC validation for mission-grade reproducibility.
    issues:
      - key: experiments-first-3
        title: "Experiment Reports (First Three)"
        labels: [MCP, reproducibility]
        priority: P2
        estimate: S
        body: |
          ### Goal
          Adopt MCP experiment template and log three initial experiments.

          ### Tasks
          - [ ] `mcp/experiments/experiment_template.md` in use
          - [ ] Georeferencing experiment
          - [ ] NLP placename extraction experiment
          - [ ] Predictive settlement modeling experiment

      - key: sop-docs
        title: "SOP Documentation"
        labels: [MCP]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Create MCP SOPs for repeatability.

          ### Tasks
          - [ ] `mcp/sops/georeference_map.md`
          - [ ] `mcp/sops/add_dataset.md`

      - key: model-cards
        title: "Model Cards"
        labels: [MCP, ai]
        priority: P3
        estimate: S
        body: |
          ### Goal
          Transparent model documentation.

          ### Tasks
          - [ ] `mcp/model_cards/nlp_placename.md`
          - [ ] `mcp/model_cards/change_detection.md`

      - key: ci-repro
        title: "CI/CD Reproducibility"
        labels: [reproducibility, ci]
        priority: P2
        estimate: S
        body: |
          ### Goal
          Automated STAC validation and reproducibility checks.

          ### Tasks
          - [ ] GitHub Actions job to validate STAC JSON
          - [ ] `make prebuild` target documented in README
