import Link from "next/link";
export const metadata={title:"Connect KFM downloads"};
export default function Page(){return <main style={{maxWidth:780,margin:"40px auto",padding:24,lineHeight:1.7}}>
  <Link href="/downloads">← Data &amp; downloads</Link><h1>Connect KFM downloads</h1>
  <h2>Download free public files without Google sign-in</h2><p>Open <Link href="/downloads#public-climate">Kansas crops &amp; climate</Link> or <Link href="/downloads#public-maps">Maps &amp; geology</Link>. Select a dataset and file, press <strong>Connect downloads · no login</strong>, review the maximum size, then press <strong>Download to this computer</strong>. Connecting alone never starts a transfer.</p>
  <p>If this hosted page cannot connect, <a href="http://127.0.0.1:4173/downloads">open the installed KFM workspace on this computer</a>. Its connection starts automatically. The browser and download service must run on the same computer.</p>
  <h2>Optional Earth Engine exports require Google access</h2>
  <p>Download a chosen dataset and year directly to your computer. KFM uses a small local download service to keep Google credentials and downloaded files on your computer.</p>
  <ol><li>Start the KFM Earth Engine download service. On this configured workstation it runs automatically as <code>kfm-earth-engine-downloads.service</code>.</li><li>Open <Link href="/earth-engine">Earth Engine advanced recipes</Link> and press <strong>Sign in with Google</strong>. You do not need a project ID to sign in.</li><li>Choose your Google account and complete Google’s consent screen. If the new tab did not open, press <strong>Continue with Google</strong>.</li><li>Return to KFM; your account appears automatically. Choose an existing project from the list or enter its ID, then press <strong>Check download access</strong>. Once access is verified, select a maximum download size and press <strong>Download to KFM</strong>. Your browser may first ask to allow local-network access.</li></ol>
  <h2>See your downloaded data</h2><p>Open <Link href="/downloads#library">My library</Link> for stored collections, dataset periods, completed downloads, partial transfers, sizes and storage locations. Refresh library to measure files added outside KFM. Transfer history and current storage are checked separately.</p>
  <h2>Where the files go</h2><p>The download panel shows the exact destination under your KFM data root, grouped by dataset, year and download job. Downloads include source IDs, processing details and file hashes. A cancelled or interrupted job keeps its partial files.</p>
  <p>Downloaded files need coverage and processing review before a map display set can be prepared. The map installer keeps that step separate from account sign-in and capture. MSS and ERA5 selections currently download source inventories; their raster products still need variable and processing choices.</p>
  <h2>If connection fails</h2><p>Check that the local service is running on the same computer as this browser, then press <strong>Connect local downloads</strong>. Sign-in also requires a project registered for Earth Engine and permission to use it. KFM does not enable billing or create paid storage.</p>
  <details><summary>Set up another computer</summary><p>Use the KFM repository runbook <code>docs/runbooks/earth-engine-downloads.md</code> to install the local operator with Python 3.11 or newer. The operator listens only on <code>127.0.0.1:8769</code> and writes into your existing private KFM data store. It supports the local KFM Site on port 4173 and this private hosted Site.</p></details>
  <p><a href="https://developers.google.com/earth-engine/guides/auth" target="_blank" rel="noreferrer">Google’s account and project setup guide ↗</a></p>
</main>;}
