#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,sys,shutil,tempfile,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.remediation.soil._outcome_common import *

def _load_records(root,kind,rid,suffix):
 p=Path(root)/f'outcomes/soil/{kind}/{rid}'
 out=[]
 if p.exists():
  for f in sorted(p.glob(f'*.{suffix}.json')):
   if f.name.endswith('_receipt.json'): continue
   out.append((f,load_json(f)))
 return out

def main(argv=None):
 ap=argparse.ArgumentParser();
 for n in ['remediation','outcome']:
  ap.add_argument(f'--{n}-root',required=True)
 for n in ['corrective','resolution','accountability','assurance','registry','certification','archive','preservation','reconciliation','federation','discovery','published','ops']:
  ap.add_argument(f'--{n}-root')
 ap.add_argument('--base-public-url',required=True); ap.add_argument('--remediation-id'); ap.add_argument('--outcome-cycle-id'); a=ap.parse_args(argv)
 rid=a.remediation_id or load_current_remediation_handoff(a.remediation_root)['active_remediation_id']; man=load_remediation_handoff_manifest(a.remediation_root,rid); rrc=load_remediation_handoff_receipt(a.remediation_root,rid)
 if man.get('remediation_handoff_status')!='REMEDIATION_HANDOFF_READY': print(json.dumps({'remediation_outcome_allowed':False,'reasons':['bad remediation state']})); return 1
 er=_load_records(a.outcome_root,'errata',rid,'errata_outcome'); cr=_load_records(a.outcome_root,'certificate_events',rid,'certificate_event_outcome'); sr=_load_records(a.outcome_root,'successor_releases',rid,'successor_release_outcome'); rr=_load_records(a.outcome_root,'retractions',rid,'retraction_outcome')
 seed={'rid':rid,'e':[sha256_file(f) for f,_ in er],'c':[sha256_file(f) for f,_ in cr],'s':[sha256_file(f) for f,_ in sr],'r':[sha256_file(f) for f,_ in rr]}
 ocid=sanitize_id(a.outcome_cycle_id or ('soil-outcome-'+stable_payload_hash(seed)[:16]))
 final=Path(a.outcome_root)/f'outcomes/soil/cycles/{ocid}'
 soil_root=Path(a.outcome_root)/'outcomes/soil'; soil_root.mkdir(parents=True,exist_ok=True)
 tmp=Path(tempfile.mkdtemp(prefix='kfm-outcome-',dir=str(soil_root)))
 cyc=tmp/ocid; cyc.mkdir(parents=True,exist_ok=True)
 report={'schema_version':'kfm.v1','object_type':'SoilPublicRemediationOutcomeReport','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'corrective_id':man.get('corrective_id'),'resolution_id':man.get('resolution_id'),'accountability_id':man.get('accountability_id'),'assurance_id':man.get('assurance_id'),'registry_id':man.get('registry_id'),'certification_id':man.get('certification_id'),'release_id':man.get('release_id'),'remediation_outcome_status':'REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','certificate_status':man.get('certificate_status','active'),'release_retracted':False,'public_advertising_allowed':True,'public_summary':'Deterministic remediation outcome reconciliation complete.','errata_outcome_count':len(er),'certificate_event_outcome_count':len(cr),'successor_release_outcome_count':len(sr),'retraction_outcome_count':len(rr),'successor_release_created_by_this_layer':False,'retraction_performed_by_this_layer':False,'immutable_artifacts_mutated':False,'closure_summary':{},'caveats':['canonical units are m³/m³','AI/model outputs are interpretive only'],'public_urls':{}}
 trans=build_outcome_transparency_log([])
 manifest={'schema_version':'kfm.v1','object_type':'SoilRemediationOutcomeManifest','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'corrective_id':man.get('corrective_id'),'resolution_id':man.get('resolution_id'),'accountability_id':man.get('accountability_id'),'assurance_id':man.get('assurance_id'),'registry_id':man.get('registry_id'),'certification_id':man.get('certification_id'),'archive_package_id':man.get('archive_package_id'),'preservation_id':man.get('preservation_id'),'reconciliation_id':man.get('reconciliation_id'),'federation_id':man.get('federation_id'),'discovery_id':man.get('discovery_id'),'release_id':man.get('release_id'),'publication_status':'PUBLISHED','remediation_handoff_status':'REMEDIATION_HANDOFF_READY','remediation_outcome_status':'REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','certificate_status':man.get('certificate_status','active'),'release_retracted':False,'created':utc_now_iso(),'base_public_url':a.base_public_url,'outcome_scope':['KFM deterministic remediation outcome reconciliation','Outcome records are additive','This layer does not create successor releases, retract releases, or mutate registry packages'],'outcome_summary':{'errata_outcome_count':len(er),'certificate_event_outcome_count':len(cr),'successor_release_outcome_count':len(sr),'retraction_outcome_count':len(rr),'required_errata_outcomes_covered':True,'required_certificate_event_outcomes_covered':True,'required_successor_outcomes_covered':True,'required_retraction_outcomes_covered':True,'successor_release_created_by_this_layer':False,'retraction_performed_by_this_layer':False,'certificate_status_mutated_by_this_layer':False,'immutable_artifacts_mutated':False,'active_public_advertising_allowed':True,'remediation_outcome_reconciled':True},'artifact_hashes':{},'source_artifact_hashes':{'remediation_handoff_receipt':'sha256:'+sha256_file(Path(a.remediation_root)/f'remediation/soil/cycles/{rid}/remediation_handoff_receipt.json')},'policy_summary':{'remediation_outcome_allowed':True},'truth_policy':{'model_output_is_truth_source':False,'remediation_outcome_is_truth_source':False}}
 files={'remediation_outcome_manifest.json':manifest,'errata_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilErrataOutcomeRegistry','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'release_id':man.get('release_id'),'entries':[o for _,o in er]},'certificate_event_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilCertificateEventOutcomeRegistry','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'registry_id':man.get('registry_id'),'release_id':man.get('release_id'),'entries':[o for _,o in cr],'certificate_status_mutated_by_this_layer':False},'successor_release_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilSuccessorReleaseOutcomeRegistry','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'release_id':man.get('release_id'),'entries':[o for _,o in sr],'successor_release_created_by_this_layer':False},'retraction_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilRetractionOutcomeRegistry','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'release_id':man.get('release_id'),'entries':[o for _,o in rr],'retraction_performed_by_this_layer':False},'remediation_closure_ledger.json':{'schema_version':'kfm.v1','object_type':'SoilRemediationClosureLedger','domain':'soil','outcome_cycle_id':ocid,'remediation_id':rid,'corrective_id':man.get('corrective_id'),'registry_id':man.get('registry_id'),'release_id':man.get('release_id'),'entries':[]},'remediation_outcome_transparency_log.json':trans,'public_remediation_outcome_report.json':report}
 for k,v in files.items(): write_json_atomic(cyc/k,v)
 hashes={k:'sha256:'+sha256_file(cyc/k) for k in files if k!='remediation_outcome_manifest.json'}; manifest['artifact_hashes']=hashes; write_json_atomic(cyc/'remediation_outcome_manifest.json',manifest)
 receipt={'schema_version':'kfm.v1','receipt_type':'RemediationOutcomeReceipt','from_state':'REMEDIATION_HANDOFF_READY','to_state':'REMEDIATION_OUTCOME_RECONCILED','decision':'pass','domain':'soil','release_id':man.get('release_id'),'registry_id':man.get('registry_id'),'assurance_id':man.get('assurance_id'),'accountability_id':man.get('accountability_id'),'resolution_id':man.get('resolution_id'),'corrective_id':man.get('corrective_id'),'remediation_id':rid,'outcome_cycle_id':ocid,'created':utc_now_iso(),'live_helpdesk_submission_performed':False,'live_notification_performed':False,'live_external_workflow_submission_performed':False,'immutable_artifacts_mutated':False,'successor_release_created_by_this_layer':False,'retraction_performed_by_this_layer':False,'certificate_status_mutated_by_this_layer':False,'source_remediation_handoff_receipt':{'ref':f'remediation/soil/cycles/{rid}/remediation_handoff_receipt.json','sha256':'sha256:'+sha256_file(Path(a.remediation_root)/f'remediation/soil/cycles/{rid}/remediation_handoff_receipt.json')},'generated_artifacts':hashes,'remediation_outcome_transparency_log_root':trans.get('log_root'),'policy_checks':{'no_live_external_calls':True,'remediation_outcome_allowed':True},'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
 write_json_atomic(cyc/'remediation_outcome_receipt.json',receipt)
 if final.exists():
  existing_manifest=load_json(final/'remediation_outcome_manifest.json')
  compare_manifest=dict(manifest)
  if isinstance(existing_manifest,dict) and 'created' in existing_manifest: compare_manifest['created']=existing_manifest.get('created')
  if stable_payload_hash(existing_manifest)==stable_payload_hash(compare_manifest): shutil.rmtree(tmp); ok=True
  else: shutil.rmtree(tmp); print(json.dumps({'remediation_outcome_allowed':False,'reasons':['existing outcome directory conflict']})); return 1
 else:
  final.parent.mkdir(parents=True,exist_ok=True); os.replace(cyc,final); shutil.rmtree(tmp,ignore_errors=True)
 write_json_atomic(Path(a.outcome_root)/'outcomes/soil/current_remediation_outcome.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentRemediationOutcomePointer','domain':'soil','active_outcome_cycle_id':ocid,'remediation_id':rid,'corrective_id':man.get('corrective_id'),'resolution_id':man.get('resolution_id'),'accountability_id':man.get('accountability_id'),'assurance_id':man.get('assurance_id'),'registry_id':man.get('registry_id'),'certification_id':man.get('certification_id'),'release_id':man.get('release_id'),'remediation_outcome_status':'REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','certificate_status':man.get('certificate_status','active'),'remediation_outcome_manifest_ref':f'outcomes/soil/cycles/{ocid}/remediation_outcome_manifest.json','remediation_outcome_receipt_ref':f'outcomes/soil/cycles/{ocid}/remediation_outcome_receipt.json','created':utc_now_iso()})
 print(json.dumps({'remediation_outcome_allowed':True,'outcome_cycle_id':ocid,'remediation_id':rid,'corrective_id':man.get('corrective_id'),'registry_id':man.get('registry_id'),'release_id':man.get('release_id'),'state_transition':'REMEDIATION_HANDOFF_READY->REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','outputs':{k:str(final/k) for k in files}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
