#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,sys,tempfile,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.remediation.soil._outcome_common import *

def main(argv=None):
 ap=argparse.ArgumentParser();
 for n in ['remediation','corrective','resolution','accountability','assurance','registry','certification','archive','preservation','reconciliation','federation','discovery','published','ops','outcome']:
  ap.add_argument(f'--{n}-root',required=True)
 ap.add_argument('--remediation-id'); ap.add_argument('--outcome-cycle-id'); ap.add_argument('--base-public-url',required=True)
 a=ap.parse_args(argv)
 rid=a.remediation_id or load_current_remediation_handoff(a.remediation_root)['active_remediation_id']
 m=load_remediation_handoff_manifest(a.remediation_root,rid); rr=load_remediation_handoff_receipt(a.remediation_root,rid)
 if m.get('remediation_handoff_status')!='REMEDIATION_HANDOFF_READY': print(json.dumps({'remediation_outcome_allowed':False,'reasons':['bad remediation status']})); return 1
 if rr.get('decision') not in {'pass','degraded','governance_only'}: print(json.dumps({'remediation_outcome_allowed':False,'reasons':['bad remediation receipt']})); return 1
 oid=a.outcome_cycle_id or ('soil-outcome-'+stable_payload_hash({'r':rid})[:16])
 out=Path(a.outcome_root)/f'outcomes/soil/cycles/{sanitize_id(oid)}'; out.parent.mkdir(parents=True,exist_ok=True); tmp=Path(tempfile.mkdtemp(prefix='outcome.',dir=str(out.parent)))
 man={'schema_version':'kfm.v1','object_type':'SoilRemediationOutcomeManifest','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'corrective_id':m.get('corrective_id'),'resolution_id':m.get('resolution_id'),'accountability_id':m.get('accountability_id'),'assurance_id':m.get('assurance_id'),'registry_id':m.get('registry_id'),'certification_id':m.get('certification_id'),'archive_package_id':m.get('archive_package_id'),'preservation_id':m.get('preservation_id'),'reconciliation_id':m.get('reconciliation_id'),'federation_id':m.get('federation_id'),'discovery_id':m.get('discovery_id'),'release_id':m.get('release_id'),'publication_status':'PUBLISHED','remediation_handoff_status':'REMEDIATION_HANDOFF_READY','remediation_outcome_status':'REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','certificate_status':m.get('certificate_status','active'),'release_retracted':False,'created':utc_now_iso(),'base_public_url':a.base_public_url,'outcome_scope':['KFM deterministic remediation outcome reconciliation'],'artifact_hashes':{},'source_artifact_hashes':{},'policy_summary':{'remediation_outcome_allowed':True},'truth_policy':{'remediation_outcome_is_truth_source':False,'ai_interpretive_only':True,'model_output_is_truth_source':False}}
 files={'remediation_outcome_manifest.json':man,'errata_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilErrataOutcomeRegistry','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'release_id':m.get('release_id'),'entries':[]},'certificate_event_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilCertificateEventOutcomeRegistry','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'registry_id':m.get('registry_id'),'release_id':m.get('release_id'),'entries':[]},'successor_release_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilSuccessorReleaseOutcomeRegistry','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'release_id':m.get('release_id'),'entries':[]},'retraction_outcome_registry.json':{'schema_version':'kfm.v1','object_type':'SoilRetractionOutcomeRegistry','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'release_id':m.get('release_id'),'entries':[]},'remediation_closure_ledger.json':{'schema_version':'kfm.v1','object_type':'SoilRemediationClosureLedger','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'entries':[],'closure_summary':{'closed_count':0,'pending_count':0,'blocked_count':0,'governance_only_count':0,'active_public_advertising_allowed':True}},'remediation_outcome_transparency_log.json':build_outcome_transparency_log([]),'public_remediation_outcome_report.json':{'schema_version':'kfm.v1','object_type':'SoilPublicRemediationOutcomeReport','domain':'soil','outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'registry_id':m.get('registry_id'),'release_id':m.get('release_id'),'remediation_outcome_status':'REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','certificate_status':m.get('certificate_status','active'),'release_retracted':False,'public_advertising_allowed':True,'public_summary':'deterministic outcome reconciliation'}}
 for k,v in files.items(): write_json_atomic(tmp/k,v)
 hashes={k:'sha256:'+sha256_file(tmp/k) for k in files}; man['artifact_hashes']=hashes; write_json_atomic(tmp/'remediation_outcome_manifest.json',man)
 rc={'schema_version':'kfm.v1','receipt_type':'RemediationOutcomeReceipt','from_state':'REMEDIATION_HANDOFF_READY','to_state':'REMEDIATION_OUTCOME_RECONCILED','decision':'pass','domain':'soil','release_id':m.get('release_id'),'registry_id':m.get('registry_id'),'assurance_id':m.get('assurance_id'),'accountability_id':m.get('accountability_id'),'resolution_id':m.get('resolution_id'),'corrective_id':m.get('corrective_id'),'remediation_id':rid,'outcome_cycle_id':sanitize_id(oid),'created':utc_now_iso(),'live_helpdesk_submission_performed':False,'live_notification_performed':False,'live_external_workflow_submission_performed':False,'immutable_artifacts_mutated':False,'successor_release_created_by_this_layer':False,'retraction_performed_by_this_layer':False,'certificate_status_mutated_by_this_layer':False,'generated_artifacts':hashes,'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
 write_json_atomic(tmp/'remediation_outcome_receipt.json',rc)
 out.parent.mkdir(parents=True,exist_ok=True)
 if out.exists(): return 1
 os.replace(tmp,out)
 cur={'schema_version':'kfm.v1','object_type':'SoilCurrentRemediationOutcomePointer','domain':'soil','active_outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'corrective_id':m.get('corrective_id'),'resolution_id':m.get('resolution_id'),'accountability_id':m.get('accountability_id'),'assurance_id':m.get('assurance_id'),'registry_id':m.get('registry_id'),'certification_id':m.get('certification_id'),'release_id':m.get('release_id'),'remediation_outcome_status':'REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','certificate_status':m.get('certificate_status','active'),'remediation_outcome_manifest_ref':f'outcomes/soil/cycles/{sanitize_id(oid)}/remediation_outcome_manifest.json','remediation_outcome_receipt_ref':f'outcomes/soil/cycles/{sanitize_id(oid)}/remediation_outcome_receipt.json','created':utc_now_iso()}
 write_json_atomic(Path(a.outcome_root)/'outcomes/soil/current_remediation_outcome.json',cur)
 print(json.dumps({'remediation_outcome_allowed':True,'outcome_cycle_id':sanitize_id(oid),'remediation_id':rid,'corrective_id':m.get('corrective_id'),'registry_id':m.get('registry_id'),'release_id':m.get('release_id'),'state_transition':'REMEDIATION_HANDOFF_READY->REMEDIATION_OUTCOME_RECONCILED','outcome_state':'pass','outputs':{k:str(out/k) for k in files}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
