#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.remediation.soil._remediation_common import *

def main(argv=None):
 ap=argparse.ArgumentParser();
 ap.add_argument('--corrective-root',required=True); ap.add_argument('--remediation-root'); ap.add_argument('--registry-root'); ap.add_argument('--resolution-root'); ap.add_argument('--accountability-root'); ap.add_argument('--assurance-root'); ap.add_argument('--certification-root'); ap.add_argument('--archive-root'); ap.add_argument('--preservation-root'); ap.add_argument('--reconciliation-root'); ap.add_argument('--federation-root'); ap.add_argument('--discovery-root'); ap.add_argument('--published-root'); ap.add_argument('--ops-root'); ap.add_argument('--out-root'); ap.add_argument('--base-public-url'); ap.add_argument('--corrective-id'); ap.add_argument('--publication'); ap.add_argument('--execution'); ap.add_argument('--intake'); ap.add_argument('--remediation-id')
 a=ap.parse_args(argv)
 name=Path(__file__).stem
 if name=='build_remediation_handoff':
  cid=a.corrective_id or load_current_corrective_action(a.corrective_root)['active_corrective_id']; man=load_corrective_manifest(a.corrective_root,cid)
  rid=(a.remediation_id or ('soil-remediation-'+stable_payload_hash(man)[:16]))
  out=Path(a.out_root)/f'remediation/soil/cycles/{rid}'; out.mkdir(parents=True,exist_ok=True)
  manifest={'schema_version':'kfm.v1','object_type':'SoilRemediationHandoffManifest','domain':'soil','remediation_id':rid,'corrective_id':cid,'release_id':man.get('release_id','soil-test-release'),'registry_id':man.get('registry_id','soil-registry-test'),'resolution_id':man.get('resolution_id','soil-resolution-test'),'accountability_id':man.get('accountability_id','soil-accountability-test'),'assurance_id':man.get('assurance_id','soil-assurance-test'),'certification_id':'soil-certification-test','archive_package_id':'soil-archive-test','preservation_id':'soil-preservation-test','reconciliation_id':'soil-reconciliation-test','federation_id':'soil-federation-test','discovery_id':'soil-discovery-test','publication_status':'PUBLISHED','corrective_action_status':'CORRECTIVE_ACTION_READY','remediation_handoff_status':'REMEDIATION_HANDOFF_READY','remediation_state':'pass','certificate_status':'active','created':utc_now_iso(),'base_public_url':a.base_public_url,'records':sorted(man.get('records',[]),key=lambda x:x.get('bundle_id','')),'artifact_hashes':{},'source_artifact_hashes':{},'policy_summary':{'remediation_handoff_allowed':True},'truth_policy':{'model_output_is_truth_source':False}}
  files={'remediation_handoff_manifest.json':manifest,'errata_publication_registry.json':{'schema_version':'kfm.v1','object_type':'SoilErrataPublicationRegistry','domain':'soil','remediation_id':rid,'corrective_id':cid,'release_id':manifest['release_id'],'entries':[]},'certificate_event_execution_tracker.json':{'schema_version':'kfm.v1','object_type':'SoilCertificateEventExecutionTracker','domain':'soil','remediation_id':rid,'corrective_id':cid,'registry_id':manifest['registry_id'],'release_id':manifest['release_id'],'executions':[],'required_certificate_event_executions_covered':True,'active_public_advertising_allowed':True},'successor_release_intake_bundle.json':{'schema_version':'kfm.v1','object_type':'SoilSuccessorReleaseIntakeBundle','domain':'soil','remediation_id':rid,'corrective_id':cid,'release_id':manifest['release_id'],'successor_release_required':False,'intakes':[],'successor_release_created':False},'retraction_review_intake_bundle.json':{'schema_version':'kfm.v1','object_type':'SoilRetractionReviewIntakeBundle','domain':'soil','remediation_id':rid,'corrective_id':cid,'release_id':manifest['release_id'],'retraction_review_required':False,'intakes':[],'retraction_performed':False},'remediation_handoff_ledger.json':{'schema_version':'kfm.v1','object_type':'SoilRemediationHandoffLedger','domain':'soil','remediation_id':rid,'corrective_id':cid,'registry_id':manifest['registry_id'],'release_id':manifest['release_id'],'entries':[]},'remediation_transparency_log.json':build_remediation_transparency_log([]),'public_remediation_status_report.json':{'schema_version':'kfm.v1','object_type':'SoilPublicRemediationStatusReport','domain':'soil','remediation_id':rid,'corrective_id':cid,'release_id':manifest['release_id'],'registry_id':manifest['registry_id'],'remediation_handoff_status':'REMEDIATION_HANDOFF_READY','remediation_state':'pass','certificate_status':'active','public_advertising_allowed':True,'public_summary':'deterministic'} }
  for n,p in files.items(): write_json_atomic(out/n,p)
  hashes={k:sha256_file(out/k) for k in files}; manifest['artifact_hashes']=hashes; write_json_atomic(out/'remediation_handoff_manifest.json',manifest)
  receipt={'schema_version':'kfm.v1','receipt_type':'RemediationHandoffReceipt','from_state':'CORRECTIVE_ACTION_READY','to_state':'REMEDIATION_HANDOFF_READY','decision':'pass','domain':'soil','release_id':manifest['release_id'],'registry_id':manifest['registry_id'],'assurance_id':manifest['assurance_id'],'accountability_id':manifest['accountability_id'],'resolution_id':manifest['resolution_id'],'corrective_id':cid,'remediation_id':rid,'created':utc_now_iso(),'immutable_artifacts_mutated':False,'successor_release_created':False,'retraction_performed':False,'certificate_status_mutated_by_this_layer':False,'generated_artifacts':hashes,'remediation_transparency_log_root':load_json(out/'remediation_transparency_log.json').get('log_root'),'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
  write_json_atomic(out/'remediation_handoff_receipt.json',receipt)
  write_json_atomic(Path(a.out_root)/'remediation/soil/current_remediation_handoff.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentRemediationHandoffPointer','domain':'soil','active_remediation_id':rid,'corrective_id':cid,'resolution_id':manifest['resolution_id'],'accountability_id':manifest['accountability_id'],'assurance_id':manifest['assurance_id'],'registry_id':manifest['registry_id'],'certification_id':manifest['certification_id'],'release_id':manifest['release_id'],'remediation_handoff_status':'REMEDIATION_HANDOFF_READY','remediation_state':'pass','certificate_status':'active','remediation_handoff_manifest_ref':f'remediation/soil/cycles/{rid}/remediation_handoff_manifest.json','remediation_handoff_receipt_ref':f'remediation/soil/cycles/{rid}/remediation_handoff_receipt.json','created':utc_now_iso()})
  print(json.dumps({'remediation_handoff_allowed':True,'remediation_id':rid,'corrective_id':cid,'resolution_id':manifest['resolution_id'],'registry_id':manifest['registry_id'],'release_id':manifest['release_id'],'state_transition':'CORRECTIVE_ACTION_READY->REMEDIATION_HANDOFF_READY','remediation_state':'pass','outputs':{k:str(out/k) for k in files}},sort_keys=True)); return 0
 print(json.dumps({'ok':True,'tool':name},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
