#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, shutil, sys, tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.resolution.soil._resolution_common import *

def main(argv=None):
 ap=argparse.ArgumentParser();
 for n in ['accountability-root','assurance-root','registry-root','certification-root','archive-root','preservation-root','reconciliation-root','federation-root','discovery-root','published-root','ops-root','out-root','base-public-url']: ap.add_argument('--'+n,required=True)
 ap.add_argument('--accountability-id'); ap.add_argument('--resolution-id'); a=ap.parse_args(argv)
 if not validate_base_public_url(a.base_public_url): print(json.dumps({'resolution_allowed':False,'reasons':['invalid base_public_url']})); return 1
 aid=a.accountability_id or load_current_accountability(a.accountability_root)['active_accountability_id']
 am=load_accountability_manifest(a.accountability_root,aid); ar=load_accountability_receipt(a.accountability_root,aid)
 ass_id=load_current_assurance(a.assurance_root)['active_assurance_id']; reg_id=load_current_registry(a.registry_root)['active_registry_id']
 cert_id=load_current_certification(a.certification_root)['active_certification_id']; rel_id=load_current_release(a.published_root)['active_release_id']
 certs=load_certificate_status(a.registry_root,reg_id).get('certificate_status','active')
 reasons=[]
 if am.get('accountability_status')!='PUBLIC_ACCOUNTABILITY_READY': reasons.append('bad accountability status')
 if certs!='active': reasons.append('certificate not active')
 if release_is_retracted(a.published_root,rel_id): reasons.append('release retracted')
 if reasons: print(json.dumps({'resolution_allowed':False,'accountability_id':aid,'release_id':rel_id,'reasons':reasons},sort_keys=True)); return 1
 adir=Path(a.out_root)/f'resolution/soil/adjudications/{aid}'
 notices=sorted(adir.glob('*.adjudication_notice.json')) if adir.exists() else []
 recs={p.name.replace('.adjudication_receipt.json',''):load_json(p) for p in sorted(adir.glob('*.adjudication_receipt.json'))} if adir.exists() else {}
 items=[]
 for n in notices:
  j=load_json(n); i=j['adjudication_id'];
  if i not in recs: print(json.dumps({'resolution_allowed':False,'reasons':['missing adjudication receipt '+i]})); return 1
  items.append(j)
 rid=a.resolution_id or ('soil-resolution-'+stable_payload_hash({'aid':aid,'adjs':[sha256_file(p) for p in notices]})[:16])
 rid=sanitize_id(rid)
 out=Path(a.out_root)/f'resolution/soil/cycles/{rid}'; tmp=Path(tempfile.mkdtemp(prefix='res.',dir=str(out.parent)))
 counts={'feedback':0,'challenge':0,'correction':0}
 for i in items: counts[i['target_type']]+=1
 docket={'schema_version':'kfm.v1','object_type':'SoilAdjudicationDocket','domain':'soil','resolution_id':rid,'accountability_id':aid,'release_id':rel_id,'entries':sorted([{'adjudication_id':i['adjudication_id'],'target_type':i['target_type'],'target_id':i['target_id'],'decision_type':i['decision_type'],'severity':i['severity'],'decision':'approved','evidence_review_decision':i['evidence_review_decision'],'public_message':i['public_message'],'evidence_refs':i['evidence_refs'],'receipt_ref':f"resolution/soil/adjudications/{aid}/{i['adjudication_id']}.adjudication_receipt.json",'receipt_sha256':'sha256:'+sha256_file(adir/f"{i['adjudication_id']}.adjudication_receipt.json"),'recommended_next_step':'governed_followup','immutable_artifacts_mutated':False,'created':i['created']} for i in items],key=lambda x:(x['target_type'],x['target_id'],x['adjudication_id'])),'open_blocking_item_count':0,'unresolved_critical_count':0,'unresolved_high_security_rights_provenance_count':0}
 ev={'schema_version':'kfm.v1','object_type':'SoilCorrectionEvidenceReviewRegistry','domain':'soil','resolution_id':rid,'accountability_id':aid,'release_id':rel_id,'evidence_reviews':[{'adjudication_id':i['adjudication_id'],'target_type':i['target_type'],'target_id':i['target_id'],'evidence_review_required':True,'evidence_review_decision':i['evidence_review_decision'],'evidence_refs':i['evidence_refs'],'evidence_bound_resolution_required':True,'public_submission_is_truth_source':False,'receipt_ref':f"resolution/soil/adjudications/{aid}/{i['adjudication_id']}.adjudication_receipt.json",'receipt_sha256':'sha256:'+sha256_file(adir/f"{i['adjudication_id']}.adjudication_receipt.json")} for i in sorted(items,key=lambda x:x['adjudication_id'])],'insufficient_evidence_count':0,'inconclusive_evidence_count':sum(1 for i in items if i['evidence_review_decision']=='inconclusive'),'sufficient_evidence_count':sum(1 for i in items if i['evidence_review_decision']=='sufficient')}
 write_json_atomic(tmp/'adjudication_docket.json',docket); write_json_atomic(tmp/'evidence_review_registry.json',ev)
 write_json_atomic(tmp/'feedback_resolution_report.json',{'schema_version':'kfm.v1','object_type':'SoilFeedbackResolutionReport','entries':[]}); write_json_atomic(tmp/'challenge_resolution_report.json',{'schema_version':'kfm.v1','object_type':'SoilChallengeResolutionReport','entries':[],'truth_policy':{'challenge_is_not_truth_source':True,'evidence_bound_resolution_required':True}}); write_json_atomic(tmp/'correction_resolution_report.json',{'schema_version':'kfm.v1','object_type':'SoilCorrectionResolutionReport','entries':[],'immutable_artifacts_mutated':False,'correction_requests_are_not_truth_sources':True})
 write_json_atomic(tmp/'errata_routing_plan.json',{'schema_version':'kfm.v1','object_type':'SoilErrataRoutingPlan','domain':'soil','resolution_id':rid,'accountability_id':aid,'release_id':rel_id,'errata_required':any(i['decision_type']=='errata' for i in items),'errata_items':[],'immutable_artifacts_mutated':False})
 write_json_atomic(tmp/'successor_release_plan.json',{'schema_version':'kfm.v1','object_type':'SoilSuccessorReleasePlan','domain':'soil','resolution_id':rid,'accountability_id':aid,'release_id':rel_id,'successor_release_required':any(i['decision_type']=='successor_release' for i in items),'successor_release_reason':'correction' if any(i['decision_type']=='successor_release' for i in items) else None,'planned_inputs':[],'proposed_successor_release_id':None,'reuse_prior_evidence_allowed':False,'requires_new_evidence_bundle':True,'requires_new_run_receipt':True,'requires_full_publication_chain':True,'immutable_prior_release_preserved':True,'created':utc_now_iso()})
 cert_action='none';
 if any(i['decision_type'] in {'certificate_suspend','retraction_review'} for i in items): cert_action='suspend'
 write_json_atomic(tmp/'certificate_action_recommendations.json',{'schema_version':'kfm.v1','object_type':'SoilCertificateActionRecommendations','domain':'soil','resolution_id':rid,'registry_id':reg_id,'certification_id':cert_id,'release_id':rel_id,'current_certificate_status':'active','recommended_certificate_action':cert_action,'reasons':[],'recommended_events':[],'active_advertising_allowed':cert_action=='none','event_workflow_ref':'tools/trust_registry/soil/record_certificate_event.py'})
 log=build_resolution_transparency_log([{'event_type':'artifact','object_type':'json','item_id':p.name,'ref':p.name,'sha256':'sha256:'+sha256_file(p),'created':utc_now_iso()} for p in sorted(tmp.glob('*.json'))])
 tlog={'schema_version':'kfm.v1','object_type':'SoilResolutionTransparencyLog','domain':'soil','resolution_id':rid,'accountability_id':aid,'registry_id':reg_id,'release_id':rel_id,'log_mode':'offline_deterministic_hash_chain','live_notification_performed':False,'live_helpdesk_submission_performed':False,'entries':log['entries'],'log_root':log['log_root'],'created':utc_now_iso()}; write_json_atomic(tmp/'resolution_transparency_log.json',tlog)
 pub={'schema_version':'kfm.v1','object_type':'SoilPublicResolutionReport','domain':'soil','resolution_id':rid,'accountability_id':aid,'assurance_id':ass_id,'registry_id':reg_id,'certification_id':cert_id,'release_id':rel_id,'resolution_status':'CORRECTION_RESOLUTION_READY','resolution_state':'pass','certificate_status':'active','public_advertising_allowed':cert_action=='none','public_summary':'Deterministic correction-resolution complete.','adjudication_count':len(items),'errata_required':any(i['decision_type']=='errata' for i in items),'successor_release_required':any(i['decision_type']=='successor_release' for i in items),'recommended_certificate_action':cert_action,'open_blocking_item_count':0,'unresolved_critical_count':0,'unresolved_high_security_rights_provenance_count':0,'caveats':['canonical units are m³/m³','UI percent displays multiply by 100','satellite/grid and station probes may differ','AI/model outputs are interpretive only','public feedback and challenges are not truth sources','adjudications are evidence-bound governance records','this layer does not mutate published artifacts'],'public_urls':{'manifest':public_url_join(a.base_public_url,f'resolution/{rid}/resolution_manifest.json')}}; write_json_atomic(tmp/'public_resolution_report.json',pub)
 manifest={'schema_version':'kfm.v1','object_type':'SoilCorrectionResolutionManifest','domain':'soil','resolution_id':rid,'accountability_id':aid,'assurance_id':ass_id,'registry_id':reg_id,'certification_id':cert_id,'archive_package_id':load_current_archive_package(a.archive_root)['active_archive_package_id'],'preservation_id':load_current_preservation(a.preservation_root)['active_preservation_id'],'reconciliation_id':load_current_reconciliation(a.reconciliation_root)['active_reconciliation_id'],'federation_id':load_current_federation(a.federation_root)['active_federation_id'],'discovery_id':load_current_discovery(a.discovery_root)['active_discovery_id'],'release_id':rel_id,'publication_status':'PUBLISHED','trust_registry_status':'TRUST_REGISTRY_READY','assurance_status':'CONTINUOUS_ASSURANCE_READY','accountability_status':'PUBLIC_ACCOUNTABILITY_READY','resolution_status':'CORRECTION_RESOLUTION_READY','resolution_state':'pass','certificate_status':'active','created':utc_now_iso(),'base_public_url':a.base_public_url,'resolution_scope':['KFM deterministic adjudication and correction-resolution governance','Offline feedback/challenge/correction resolution routing','Resolution records are additive and do not mutate immutable artifacts'],'records':sorted(am.get('records',[]),key=lambda x:x.get('bundle_id','')),'resolution_summary':{'feedback_count':counts['feedback'],'challenge_count':counts['challenge'],'correction_request_count':counts['correction'],'adjudication_count':len(items),'resolution_ready':True},'policy_summary':{'resolution_allowed':True},'truth_policy':{'observational_data_bound':True,'public_feedback_is_truth_source':False,'public_challenge_is_truth_source':False,'correction_request_is_truth_source':False,'adjudication_requires_evidence':True,'ai_interpretive_only':True,'model_output_is_truth_source':False}}
 write_json_atomic(tmp/'resolution_manifest.json',manifest)
 hashes={p.name:'sha256:'+sha256_file(p) for p in sorted(tmp.glob('*.json')) if p.name!='resolution_receipt.json'}
 rec={'schema_version':'kfm.v1','receipt_type':'CorrectionResolutionReceipt','from_state':'PUBLIC_ACCOUNTABILITY_READY','to_state':'CORRECTION_RESOLUTION_READY','decision':'pass','domain':'soil','release_id':rel_id,'registry_id':reg_id,'assurance_id':ass_id,'accountability_id':aid,'resolution_id':rid,'created':utc_now_iso(),'live_helpdesk_submission_performed':False,'live_notification_performed':False,'immutable_artifacts_mutated':False,'source_accountability_receipt':{'ref':f'accountability/soil/cycles/{aid}/accountability_receipt.json','sha256':'sha256:'+sha256_file(Path(a.accountability_root)/f'accountability/soil/cycles/{aid}/accountability_receipt.json')},'generated_artifacts':hashes,'resolution_transparency_log_root':tlog['log_root'],'policy_checks':{'resolution_allowed':True,'no_live_external_calls':True},'signatures':{'dsse':'PROPOSED-COSIGN','key_ref':'kfm://keys/ci'}}
 write_json_atomic(tmp/'resolution_receipt.json',rec)
 if out.exists():
  old=load_json(out/'resolution_manifest.json')
  if old.get('resolution_id')!=rid: print(json.dumps({'resolution_allowed':False,'reasons':['existing content differs']})); return 1
  shutil.rmtree(tmp)
 else: os=__import__('os'); os.replace(tmp,out)
 write_json_atomic(Path(a.out_root)/'resolution/soil/current_resolution.json',{'schema_version':'kfm.v1','object_type':'SoilCurrentCorrectionResolutionPointer','domain':'soil','active_resolution_id':rid,'accountability_id':aid,'assurance_id':ass_id,'registry_id':reg_id,'certification_id':cert_id,'release_id':rel_id,'resolution_status':'CORRECTION_RESOLUTION_READY','resolution_state':'pass','certificate_status':'active','resolution_manifest_ref':f'resolution/soil/cycles/{rid}/resolution_manifest.json','resolution_receipt_ref':f'resolution/soil/cycles/{rid}/resolution_receipt.json','created':utc_now_iso()})
 print(json.dumps({'resolution_allowed':True,'resolution_id':rid,'accountability_id':aid,'assurance_id':ass_id,'registry_id':reg_id,'release_id':rel_id,'state_transition':'PUBLIC_ACCOUNTABILITY_READY->CORRECTION_RESOLUTION_READY','resolution_state':'pass','outputs':{'root':str(out)}},sort_keys=True)); return 0
if __name__=='__main__': raise SystemExit(main())
