from __future__ import annotations

import argparse
import json
import math
import shutil
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlparse
from typing import Any

from . import RUNNER_VERSION
from .event_queue import JsonlQueue
from .http_client import download_to_file
from .models import ChangeEvent, RunnerSettings, SourceSpec, load_config
from .signer import env_overlay, sign_and_verify
from .token_bucket import TokenBucketStore
from .utils import atomic_write_json, canonical_dumps, read_json, safe_id, sha256_file, sha256_prefixed_bytes, utc_now


def _date_parts(now: datetime | None = None) -> tuple[str, str, str]:
    now = now or datetime.now(timezone.utc)
    return f"{now.year:04d}", f"{now.month:02d}", f"{now.day:02d}"


def _artifact_name(spec: SourceSpec) -> str:
    if spec.artifact_name:
        return spec.artifact_name
    basename = Path(urlparse(spec.url).path).name
    return basename or "artifact.bin"


def _run_id(spec: SourceSpec, event: ChangeEvent) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    short_hash = event.next_spec_hash.replace("sha256-", "")[:12]
    return f"{timestamp}-{safe_id(spec.source_id)}-{short_hash}-{uuid.uuid4().hex[:8]}"


def _backoff_seconds(settings: RunnerSettings, attempt_count: int) -> int:
    raw = settings.backoff_base_seconds * (2 ** max(0, attempt_count - 1))
    return min(settings.backoff_max_seconds, raw)


def _available_at_after(seconds: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(seconds=seconds)).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _error_fingerprint(text: str) -> str:
    return sha256_prefixed_bytes(text.encode("utf-8"))


def write_dlq(settings: RunnerSettings, event: ChangeEvent, cause: str, stage: str, detail: str = "") -> dict[str, Any]:
    record = {
        "source_id": event.source_id,
        "event": event.to_dict(),
        "cause": cause,
        "stage": stage,
        "attempt_count": event.attempt_count,
        "last_error_fingerprint": _error_fingerprint(cause + "|" + detail),
        "detail": detail[:2000],
        "failed_at": utc_now(),
    }
    JsonlQueue(settings.dlq_path).append(record)
    return record


def _load_meta(settings: RunnerSettings, source_id: str) -> dict[str, Any]:
    return read_json(Path(settings.meta_dir) / f"{safe_id(source_id)}.json", default={}) or {}


def _bundle_payload(
    spec: SourceSpec,
    event: ChangeEvent,
    meta: dict[str, Any],
    artifact_rel_path: str,
    artifact_info: dict[str, Any],
    bundle_id: str,
) -> dict[str, Any]:
    return {
        "schema_version": "v1",
        "object_type": "EvidenceBundle",
        "bundle_id": bundle_id,
        "domain": spec.domain,
        "policy_label": spec.policy_label,
        "rights_status": spec.rights_status,
        "spec_hash": event.next_spec_hash,
        "source_refs": [
            {
                "uri": spec.url,
                "download_key": spec.download_key,
                "etag": meta.get("etag") or artifact_info.get("etag"),
                "last_modified": meta.get("last_modified") or artifact_info.get("last_modified"),
                "http_status": artifact_info.get("status"),
                "source_version": spec.source_version,
            }
        ],
        "evidence_refs": [
            {
                "path": artifact_rel_path,
                "sha256": artifact_info["sha256"],
                "bytes": artifact_info["bytes"],
                "content_type": artifact_info.get("content_type"),
            }
        ],
        "validators": spec.validators,
        "created_at": utc_now(),
        "runner_version": RUNNER_VERSION,
        "notes": ["Generated by KFM evented watcher POC"],
    }


def _decision_log_payload(
    spec: SourceSpec,
    event: ChangeEvent,
    bundle_id: str,
    bundle_path: str,
    artifact_info: dict[str, Any],
    signing_required: bool,
) -> dict[str, Any]:
    return {
        "schema_version": "v1",
        "object_type": "DecisionLog",
        "decision_id": f"dl-{bundle_id}",
        "bundle_id": bundle_id,
        "source_id": spec.source_id,
        "change": {
            "prev_spec_hash": event.prev_spec_hash,
            "next_spec_hash": event.next_spec_hash,
            "reason": event.reason,
            "material": event.material,
        },
        "artifact": {
            "sha256": artifact_info["sha256"],
            "bytes": artifact_info["bytes"],
        },
        "validator_set": spec.validators,
        "preconditions": [
            "evidence_bundle_shape_valid",
            "rights_status_resolved",
            "policy_label_resolved",
            "signature_required" if signing_required else "signature_pending_or_disabled_for_local_demo",
        ],
        "promotion_decision": "BLOCKED_PENDING_SIGNATURE" if not signing_required else "BLOCKED_PENDING_SIGNATURE_VERIFICATION",
        "bundle_path": bundle_path,
        "created_at": utc_now(),
    }


def _receipt_payload(
    spec: SourceSpec,
    event: ChangeEvent,
    bundle_id: str,
    bundle_path: Path,
    decision_log_path: Path,
    signing_required: bool,
    signing_status: dict[str, Any],
) -> dict[str, Any]:
    fingerprint = sha256_file(bundle_path)
    result = "PENDING_PROMOTION" if signing_required and signing_status.get("all_verified") else "PENDING_SIGNATURE"
    return {
        "schema_version": "v1",
        "object_type": "RunReceipt",
        "bundle_id": bundle_id,
        "source_id": spec.source_id,
        "fingerprint": fingerprint,
        "spec_hash": event.next_spec_hash,
        "policy_label": spec.policy_label,
        "rights_status": spec.rights_status,
        "validators": spec.validators,
        "runner_version": RUNNER_VERSION,
        "result": result,
        "artifacts": {
            "evidence_bundle_path": str(bundle_path),
            "decision_log_path": str(decision_log_path),
        },
        "signing": signing_status,
        "timestamps": {"built": utc_now()},
    }


def _copy_to_receipts(work_file: Path, receipt_dir: Path) -> Path:
    receipt_dir.mkdir(parents=True, exist_ok=True)
    dest = receipt_dir / work_file.name
    shutil.copy2(work_file, dest)
    return dest


def _sign_artifacts(paths: list[Path], settings: RunnerSettings, *, force_enabled: bool | None = None) -> dict[str, Any]:
    signing = env_overlay(settings.signing)
    if force_enabled is not None:
        signing.enabled = force_enabled
    status: dict[str, Any] = {
        "required": bool(signing.enabled),
        "tool": "cosign",
        "mode": signing.mode,
        "all_signed": False,
        "all_verified": False,
        "artifacts": [],
    }
    if not signing.enabled:
        return status

    all_signed = True
    all_verified = True
    for path in paths:
        bundle_path = Path(str(path) + ".sigstore.json")
        signed, verified = sign_and_verify(path, bundle_path, signing)
        entry = {
            "path": str(path),
            "bundle_path": str(bundle_path),
            "signed": signed.ok,
            "verified": bool(verified and verified.ok),
            "sign_stderr": signed.stderr[-1000:],
            "verify_stderr": (verified.stderr[-1000:] if verified else ""),
        }
        status["artifacts"].append(entry)
        all_signed = all_signed and signed.ok
        all_verified = all_verified and bool(verified and verified.ok)
    status["all_signed"] = all_signed
    status["all_verified"] = all_verified
    return status


def process_event(
    event_dict: dict[str, Any],
    settings: RunnerSettings,
    sources_by_id: dict[str, SourceSpec],
    token_store: TokenBucketStore,
    *,
    sign_override: bool | None = None,
) -> dict[str, Any]:
    event = ChangeEvent.from_mapping(event_dict)
    spec = sources_by_id.get(event.source_id)
    if spec is None:
        write_dlq(settings, event, "unknown_source_id", "preflight", event.source_id)
        return {"source_id": event.source_id, "status": "DLQ", "cause": "unknown_source_id"}
    if not event.material:
        return {"source_id": event.source_id, "status": "NOOP"}
    if event.high_risk and settings.fail_on_missing_http_validators:
        write_dlq(settings, event, "fail_closed_missing_http_validators", "preflight", event.reason)
        return {"source_id": event.source_id, "status": "DLQ", "cause": "fail_closed_missing_http_validators"}
    if not token_store.try_consume(spec.source_id, settings.token_rate_per_minute, settings.token_burst):
        return {"source_id": event.source_id, "status": "DEFERRED", "event": event.to_dict(), "cause": "token_bucket_empty"}

    run_id = _run_id(spec, event)
    work_dir = Path(settings.work_dir) / safe_id(spec.source_id) / run_id
    artifact_path = work_dir / _artifact_name(spec)
    try:
        artifact_info = download_to_file(spec.url, spec.headers, artifact_path, settings.max_download_bytes)
        meta = _load_meta(settings, spec.source_id)
        bundle_id = f"eb-{datetime.now(timezone.utc).strftime('%Y%m%d')}-{safe_id(spec.source_id)}-{event.next_spec_hash.replace('sha256-', '')[:12]}"
        artifact_rel = str(artifact_path)

        bundle = _bundle_payload(spec, event, meta, artifact_rel, artifact_info, bundle_id)
        bundle_path = work_dir / "evidence_bundle.json"
        atomic_write_json(bundle_path, bundle)

        effective_signing_enabled = env_overlay(settings.signing).enabled if sign_override is None else sign_override
        decision_log = _decision_log_payload(spec, event, bundle_id, str(bundle_path), artifact_info, effective_signing_enabled)
        decision_log_path = work_dir / "decision_log.json"
        atomic_write_json(decision_log_path, decision_log)

        y, m, d = _date_parts()
        receipt_dir = Path(settings.receipts_dir) / y / m / d / safe_id(spec.source_id) / run_id
        receipt_bundle_path = _copy_to_receipts(bundle_path, receipt_dir)
        receipt_decision_path = _copy_to_receipts(decision_log_path, receipt_dir)

        signing_status = _sign_artifacts([receipt_bundle_path, receipt_decision_path], settings, force_enabled=effective_signing_enabled)
        if effective_signing_enabled and not signing_status.get("all_verified"):
            detail = canonical_dumps(signing_status)
            write_dlq(settings, event, "fail_closed_signature_verification", "signing", detail)
            return {"source_id": event.source_id, "status": "DLQ", "cause": "fail_closed_signature_verification", "detail": signing_status}

        receipt = _receipt_payload(spec, event, bundle_id, receipt_bundle_path, receipt_decision_path, effective_signing_enabled, signing_status)
        receipt_path = receipt_dir / "run_receipt.json"
        atomic_write_json(receipt_path, receipt)
        if effective_signing_enabled:
            receipt_signing = _sign_artifacts([receipt_path], settings, force_enabled=effective_signing_enabled)
            if not receipt_signing.get("all_verified"):
                write_dlq(settings, event, "fail_closed_receipt_signature_verification", "signing", canonical_dumps(receipt_signing))
                return {"source_id": event.source_id, "status": "DLQ", "cause": "fail_closed_receipt_signature_verification", "detail": receipt_signing}
        return {
            "source_id": event.source_id,
            "status": "BUILT",
            "bundle_id": bundle_id,
            "receipt_path": str(receipt_path),
            "result": receipt["result"],
        }
    except Exception as exc:  # deliberate broad catch: runner must route failures, not crash the batch
        event.attempt_count += 1
        if event.attempt_count > settings.max_retries:
            write_dlq(settings, event, "max_retries_exceeded", "download_or_build", repr(exc))
            return {"source_id": event.source_id, "status": "DLQ", "cause": "max_retries_exceeded", "detail": repr(exc)}
        delay = _backoff_seconds(settings, event.attempt_count)
        event.available_at = _available_at_after(delay)
        return {"source_id": event.source_id, "status": "RETRY", "event": event.to_dict(), "delay_seconds": delay, "detail": repr(exc)}


def run_once(config_path: str | Path, *, sign_override: bool | None = None) -> dict[str, Any]:
    settings, sources_by_id = load_config(config_path)
    queue = JsonlQueue(settings.queue_path)
    events = queue.drain_ready(settings.max_changes_per_run)
    token_store = TokenBucketStore(Path(settings.state_dir) / "token_buckets.json")
    if not events:
        return {"dequeued": 0, "results": []}

    results: list[dict[str, Any]] = []
    requeue: list[dict[str, Any]] = []
    batches = [events[i : i + settings.batch_size] for i in range(0, len(events), settings.batch_size)]
    for batch in batches:
        with ThreadPoolExecutor(max_workers=settings.max_workers) as pool:
            futures = [pool.submit(process_event, item, settings, sources_by_id, token_store, sign_override=sign_override) for item in batch]
            for future in as_completed(futures):
                result = future.result()
                results.append(result)
                if result.get("status") in {"DEFERRED", "RETRY"} and result.get("event"):
                    requeue.append(result["event"])
    if requeue:
        queue.append_many(requeue)
    return {"dequeued": len(events), "requeued": len(requeue), "results": results}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="KFM batched micro-runner")
    parser.add_argument("--config", required=True, help="Path to config JSON")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--sign", action="store_true", help="Force cosign signing for this run")
    group.add_argument("--no-sign", action="store_true", help="Force signing off for this run")
    args = parser.parse_args(argv)
    sign_override = True if args.sign else False if args.no_sign else None
    result = run_once(args.config, sign_override=sign_override)
    print(json.dumps(result, sort_keys=True, indent=2))
    # Fail CI if any item went to DLQ during this run.
    return 1 if any(item.get("status") == "DLQ" for item in result.get("results", [])) else 0


if __name__ == "__main__":
    raise SystemExit(main())
