export type FunctionGroup = "PUBLIC_INTERFACE" | "OPERATIONAL_HANDOFF";
export type FunctionState = "ACTIVE" | "BOUNDED" | "DOCUMENTED" | "GATED";
export type FunctionAuthority = "REPOSITORY PROOF" | "SITE PROOF" | "DOCUMENTED" | "PROPOSED";
export type FunctionMaturity = "IMPLEMENTED" | "PARTIAL" | "HANDOFF ONLY" | "NOT IMPLEMENTED";
export type FunctionInventory = "MAP FUNCTION MATRIX" | "SITE EXTENSION" | "OPERATIONAL RUNBOOK";
export type FunctionAction =
  | "OPEN_MAP"
  | "OPEN_LAYERS"
  | "OPEN_DOSSIER"
  | "OPEN_TIMELINE"
  | "OPEN_FOCUS"
  | "OPEN_EXPORT"
  | "OPEN_DIAGNOSTICS"
  | "OPEN_SOURCES"
  | "COPY_HANDOFF"
  | "NONE";

export type FunctionRecord = Readonly<{
  id: string;
  group: FunctionGroup;
  inventory: FunctionInventory;
  title: string;
  state: FunctionState;
  authority: FunctionAuthority;
  maturity: FunctionMaturity;
  summary: string;
  interface: string;
  boundary: string;
  requires: readonly string[];
  action: FunctionAction;
  actionLabel: string;
  sourceLabel: string;
  sourcePath?: string;
}>;

const freezeRecord = (record: FunctionRecord): FunctionRecord => Object.freeze({
  ...record,
  requires: Object.freeze([...record.requires]),
});

const mapFunction = (
  record: Omit<FunctionRecord, "group" | "inventory" | "sourceLabel" | "sourcePath">,
): FunctionRecord => freezeRecord({
  ...record,
  group: "PUBLIC_INTERFACE",
  inventory: "MAP FUNCTION MATRIX",
  sourceLabel: "Draft MapLibre function matrix",
  sourcePath: "docs/Master_MapLibre_Components-Functions-Features_v2.1_FULL.md",
});

const siteExtension = (
  record: Omit<FunctionRecord, "group" | "inventory">,
): FunctionRecord => freezeRecord({
  ...record,
  group: "PUBLIC_INTERFACE",
  inventory: "SITE EXTENSION",
});

const operationalHandoff = (
  record: Omit<FunctionRecord, "group" | "inventory" | "state" | "authority" | "maturity" | "action">,
): FunctionRecord => freezeRecord({
  ...record,
  group: "OPERATIONAL_HANDOFF",
  inventory: "OPERATIONAL RUNBOOK",
  state: "DOCUMENTED",
  authority: "DOCUMENTED",
  maturity: "HANDOFF ONLY",
  action: "COPY_HANDOFF",
});

/**
 * One-to-one projection of the repository's twenty-row draft map function
 * matrix. Each Site state and maturity is assessed separately from the draft.
 */
export const MAP_FUNCTIONS: readonly FunctionRecord[] = Object.freeze([
  mapFunction({
    id: "map-navigation",
    title: "Pan / zoom / bearing / pitch",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Navigate Kansas spatial context with pointer, keyboard, camera, and reset controls.",
    interface: "Map canvas and Navigate workbench",
    boundary: "Camera movement supplies context only and makes no trust claim by itself.",
    requires: ["Finite camera state", "Keyboard alternative", "Safe reset"],
    action: "OPEN_MAP",
    actionLabel: "Open map",
  }),
  mapFunction({
    id: "layer-search",
    title: "Layer search",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Find available public-safe demonstration layers by name, domain, category, or dataset.",
    interface: "Searchable Layer Catalog",
    boundary: "Search results list only Site registry records; discovery does not release a layer.",
    requires: ["Bounded layer registry", "Visible release posture", "Released or explicitly scoped preview layers"],
    action: "OPEN_LAYERS",
    actionLabel: "Search layers",
  }),
  mapFunction({
    id: "layer-toggle",
    title: "Layer toggle",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Show or hide a registered demonstration layer without changing its lifecycle state.",
    interface: "Layer visibility controls",
    boundary: "Visibility is local UI state; a toggle is never publication or withdrawal.",
    requires: ["Registered layer", "Visible state cue", "Deterministic restore"],
    action: "OPEN_LAYERS",
    actionLabel: "Manage visibility",
  }),
  mapFunction({
    id: "layer-opacity",
    title: "Layer opacity",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Adjust a visible layer for visual comparison while retaining its trust metadata.",
    interface: "Per-layer opacity control",
    boundary: "Opacity cannot weaken sensitivity rules, reveal withheld geometry, or change evidence posture.",
    requires: ["Public-safe geometry", "Persistent trust labels", "Independent layer identity"],
    action: "OPEN_LAYERS",
    actionLabel: "Adjust opacity",
  }),
  mapFunction({
    id: "feature-click",
    title: "Feature click",
    state: "BOUNDED",
    authority: "SITE PROOF",
    maturity: "PARTIAL",
    summary: "Select a map feature and translate it to a stable Site-local evidence projection.",
    interface: "Map selection to Evidence Drawer",
    boundary: "A renderer hit is a candidate selection, not governed API evidence.",
    requires: ["Stable feature identity", "EvidenceRef lookup", "Finite negative state"],
    action: "OPEN_DOSSIER",
    actionLabel: "Inspect selection",
  }),
  mapFunction({
    id: "hover-summary",
    title: "Hover summary",
    state: "GATED",
    authority: "DOCUMENTED",
    maturity: "NOT IMPLEMENTED",
    summary: "Offer lightweight orientation without presenting a consequential claim.",
    interface: "Highlight only; summary is withheld",
    boundary: "The Site highlights hover candidates but does not yet project an evidence-backed hover summary.",
    requires: ["Evidence-backed copy", "Keyboard equivalent", "No protected detail"],
    action: "NONE",
    actionLabel: "Await safe summary",
  }),
  mapFunction({
    id: "evidence-drawer",
    title: "Evidence Drawer",
    state: "BOUNDED",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Inspect evidence state, source context, time, limitations, release posture, and correction state.",
    interface: "Evidence Drawer",
    boundary: "Drawer content remains subordinate to its Site-local fixture EvidenceRef and cannot widen source scope.",
    requires: ["Selected registry feature", "Evidence state", "Public-safe projection"],
    action: "OPEN_DOSSIER",
    actionLabel: "Open selected dossier",
  }),
  mapFunction({
    id: "timeline-scrub",
    title: "Timeline scrub",
    state: "BOUNDED",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Explore available demonstration years while preserving each layer's time semantics.",
    interface: "Timeline and temporal controls",
    boundary: "The timeline never fabricates continuity or collapse valid, source, release, and correction time.",
    requires: ["Explicit time kind", "No-data state", "Layer-specific availability"],
    action: "OPEN_TIMELINE",
    actionLabel: "Open timeline",
  }),
  mapFunction({
    id: "compare-releases",
    title: "Compare releases",
    state: "GATED",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Inspect change only when both sides retain independent evidence, time, rights, and release identity.",
    interface: "Eligibility view only",
    boundary: "No aligned, rights-cleared comparison pair or rendering path is implemented in this Site.",
    requires: ["Compatible A/B pair", "Independent evidence", "Accessible text alternative"],
    action: "NONE",
    actionLabel: "Await compatible pair",
  }),
  mapFunction({
    id: "filter-domain",
    title: "Filter by domain",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Narrow the layer catalog by Kansas knowledge domain.",
    interface: "Layer Catalog domain filter",
    boundary: "A domain filter changes visible choices only; it is not a truth or policy decision.",
    requires: ["Domain-tagged registry", "Clear filter state", "Reset path"],
    action: "OPEN_LAYERS",
    actionLabel: "Filter layers",
  }),
  mapFunction({
    id: "filter-source-role",
    title: "Filter by source role",
    state: "GATED",
    authority: "DOCUMENTED",
    maturity: "NOT IMPLEMENTED",
    summary: "Separate observed, modeled, regulatory, and other source roles without collapsing them.",
    interface: "Catalog requirement only",
    boundary: "The Site shows source metadata but does not yet offer a source-role filter.",
    requires: ["Normalized source roles", "Role anti-collapse", "Coverage tests"],
    action: "NONE",
    actionLabel: "Await role inventory",
  }),
  mapFunction({
    id: "filter-policy-status",
    title: "Filter by policy status",
    state: "GATED",
    authority: "DOCUMENTED",
    maturity: "NOT IMPLEMENTED",
    summary: "Narrow availability by public, restricted, generalized, or denied posture.",
    interface: "Catalog requirement only",
    boundary: "A filter must never reveal restricted coordinates or imply a policy decision that was not evaluated.",
    requires: ["Separate access taxonomy", "Safe negative labels", "No hidden-detail counts"],
    action: "NONE",
    actionLabel: "Await policy taxonomy",
  }),
  mapFunction({
    id: "legend-view",
    title: "Legend view",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Interpret each demonstration layer's colors, symbols, units, and scale context.",
    interface: "Layer Catalog and Evidence Drawer legends",
    boundary: "A legend explains styling; it does not turn the rendered map into proof.",
    requires: ["Layer-bound legend", "Non-color labels", "Scale and unit context"],
    action: "OPEN_LAYERS",
    actionLabel: "View legends",
  }),
  mapFunction({
    id: "attribution-view",
    title: "Attribution view",
    state: "BOUNDED",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Show source terms and attribution for every registered demonstration layer.",
    interface: "Layer metadata and export preflight",
    boundary: "Missing attribution blocks export; visible text does not prove external source admission.",
    requires: ["Attribution text", "Rights context", "Export block on omission"],
    action: "OPEN_DOSSIER",
    actionLabel: "Review attribution",
  }),
  mapFunction({
    id: "download-export",
    title: "Download / export",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Preview and download a public-safe JSON artifact with time, attribution, trust, and redaction metadata.",
    interface: "Export Review",
    boundary: "A download has no evidence, policy, review, release, deployment, promotion, or publication effect.",
    requires: ["Artifact identity", "Attribution", "Redaction preflight"],
    action: "OPEN_EXPORT",
    actionLabel: "Review export",
  }),
  mapFunction({
    id: "focus-mode-answer",
    title: "Focus Mode answer",
    state: "BOUNDED",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Resolve selected context into one deterministic ANSWER, ABSTAIN, DENY, or ERROR demonstration outcome.",
    interface: "Focus Workbench",
    boundary: "No live AI, free-form truth authority, direct model path, or silent map action exists in this Site.",
    requires: ["Selected feature", "Finite outcome", "Visible closure checks"],
    action: "OPEN_FOCUS",
    actionLabel: "Open Focus Workbench",
  }),
  mapFunction({
    id: "story-node",
    title: "Story Node",
    state: "BOUNDED",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Compose already-governed public-safe story projections with explicit temporal and evidence context.",
    interface: "Repository fixture slice; no Site route",
    boundary: "Parser, view-model, mount code, and tests do not establish a live narrative route or released story package.",
    requires: ["Evidence-bound story nodes", "Citation continuity", "Route and release proof"],
    action: "NONE",
    actionLabel: "Await Site route",
  }),
  mapFunction({
    id: "offline-package",
    title: "Offline package",
    state: "GATED",
    authority: "REPOSITORY PROOF",
    maturity: "NOT IMPLEMENTED",
    summary: "Use a released map offline only with a versioned manifest, hashes, policy, citations, expiry, and correction path.",
    interface: "Display-only readiness status",
    boundary: "No admitted archive, range proof, release-scoped cache manifest, expiry, or revocation path is available.",
    requires: ["Released archive", "Integrity manifest", "Update and revocation model"],
    action: "NONE",
    actionLabel: "Held for closure",
  }),
  mapFunction({
    id: "accessibility-navigation",
    title: "Accessibility navigation",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Use keyboard paths, focus handling, text labels, and non-map alternatives across core demonstration journeys.",
    interface: "Keyboard map, catalog, timeline, and evidence alternatives",
    boundary: "This describes implemented Site paths; it is not an independent conformance certification.",
    requires: ["Keyboard parity", "Focus restoration", "Screen-reader labels"],
    action: "OPEN_MAP",
    actionLabel: "Open keyboard map",
  }),
  mapFunction({
    id: "debug-proof-view",
    title: "Debug / proof view",
    state: "ACTIVE",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Inspect redacted runtime state, source health, capability gates, and safe recovery actions.",
    interface: "Map Workbench Diagnostics",
    boundary: "Diagnostics exclude secrets and protected internals and cannot become a raw-data backdoor.",
    requires: ["Redacted runtime state", "Source status", "Repository/runtime separation"],
    action: "OPEN_DIAGNOSTICS",
    actionLabel: "Open diagnostics",
  }),
]);

export const SITE_EXTENSION_FUNCTIONS: readonly FunctionRecord[] = Object.freeze([
  siteExtension({
    id: "explore",
    title: "Explore",
    state: "ACTIVE",
    authority: "REPOSITORY PROOF",
    maturity: "IMPLEMENTED",
    summary: "Navigate, search, filter, switch time, manage layers, and select public-safe Site fixtures as one composed workflow.",
    interface: "Persistent MapLibre shell",
    boundary: "Map state supplies context only; it cannot create evidence or publication authority.",
    requires: ["Site-local registry", "Explicit time semantics", "Visible attribution"],
    action: "OPEN_MAP",
    actionLabel: "Open map",
    sourceLabel: "Unified Workspace architecture",
    sourcePath: "docs/architecture/ui/unified-workspace.md",
  }),
  siteExtension({
    id: "dossier",
    title: "Dossier",
    state: "BOUNDED",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Inspect one selected object across evidence, metadata, time, lineage, policy-safe state, and correction posture.",
    interface: "Evidence Drawer",
    boundary: "A drawer record remains subordinate to its EvidenceRef and cannot widen the source scope.",
    requires: ["Selected registry feature", "Evidence state", "Public-safe projection"],
    action: "OPEN_DOSSIER",
    actionLabel: "Open selected dossier",
    sourceLabel: "Unified Workspace architecture",
    sourcePath: "docs/architecture/ui/unified-workspace.md",
  }),
  siteExtension({
    id: "focus",
    title: "Focus Mode",
    state: "BOUNDED",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Bring finite outcome resolution, closure checks, and explicit map-action proposals into one bounded workbench.",
    interface: "Focus Workbench",
    boundary: "No live AI, free-form truth authority, direct model path, or silent map action exists in this Site.",
    requires: ["Selected feature", "Finite outcome", "Visible closure checks"],
    action: "OPEN_FOCUS",
    actionLabel: "Open Focus Workbench",
    sourceLabel: "Focus transition index",
    sourcePath: "docs/focus-mode/state/transitions/README.md",
  }),
  siteExtension({
    id: "export",
    title: "Export",
    state: "ACTIVE",
    authority: "SITE PROOF",
    maturity: "IMPLEMENTED",
    summary: "Review trust metadata, redactions, time, attribution, release posture, and correction state before downloading.",
    interface: "Export Review",
    boundary: "Downloads have no evidence, policy, review, release, deployment, promotion, or publication effect.",
    requires: ["Artifact identity", "Attribution", "Redaction preflight"],
    action: "OPEN_EXPORT",
    actionLabel: "Review export",
    sourceLabel: "Master MapLibre outward artifact rule",
    sourcePath: "docs/Master_MapLibre_Components-Functions-Features_v2.1_FULL.md",
  }),
  siteExtension({
    id: "diagnostics",
    title: "Diagnostics",
    state: "ACTIVE",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Inspect renderer state, source health, capability gates, repository boundary, and safe recovery actions.",
    interface: "Map Workbench Diagnostics",
    boundary: "Diagnostics are redacted and cannot become a raw or canonical data backdoor.",
    requires: ["Runtime state", "Source status", "Repository/runtime separation"],
    action: "OPEN_DIAGNOSTICS",
    actionLabel: "Open diagnostics",
    sourceLabel: "ADR-0006 renderer boundary",
    sourcePath: "docs/adr/ADR-0006-maplibre-boundary--only-maplibreadapter-imports-maplibre.md",
  }),
  siteExtension({
    id: "story",
    title: "Story",
    state: "BOUNDED",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Validate and project an already-governed public-safe StoryManifest into finite 2D playback nodes.",
    interface: "Repository fixture-first Story Player projection",
    boundary: "The repository proves a bounded consumer, but this Site has no mounted Story route, live transport, map playback surface, or release authority.",
    requires: ["Public-safe READY StoryManifest", "Evidence and citation closure", "Policy, review, release, and correction continuity"],
    action: "NONE",
    actionLabel: "Repository slice only",
    sourceLabel: "Explorer Story Player",
    sourcePath: "apps/explorer-web/src/features/story_player/index.tsx",
  }),
  siteExtension({
    id: "compare",
    title: "Compare",
    state: "GATED",
    authority: "REPOSITORY PROOF",
    maturity: "PARTIAL",
    summary: "Inspect side-by-side or before/after context where each side retains separate source, release, and time identity.",
    interface: "Eligibility view only",
    boundary: "The repository serializes compare context, but no aligned, rights-cleared pair or rendering path is implemented.",
    requires: ["Compatible A/B pair", "Independent evidence", "Accessible text alternative"],
    action: "NONE",
    actionLabel: "Await compatible pair",
    sourceLabel: "Public workspace context spine",
    sourcePath: "apps/explorer-web/src/site/workspace-context.ts",
  }),
  siteExtension({
    id: "source-intake",
    title: "Source intake",
    state: "BOUNDED",
    authority: "DOCUMENTED",
    maturity: "PARTIAL",
    summary: "Explore candidate source families, known gaps, and bounded intake-draft structure.",
    interface: "Source Observatory",
    boundary: "Discovery and a copied draft do not admit, activate, release, or publish a source.",
    requires: ["Stable source identity", "Rights and sensitivity review", "Accountable disposition"],
    action: "OPEN_SOURCES",
    actionLabel: "Open source observatory",
    sourceLabel: "Runbook index · source intake boundary",
    sourcePath: "docs/runbooks/README.md",
  }),
  siteExtension({
    id: "review",
    title: "Review",
    state: "GATED",
    authority: "DOCUMENTED",
    maturity: "NOT IMPLEMENTED",
    summary: "Role-gated steward or reviewer work over the same context spine.",
    interface: "Boundary card only",
    boundary: "The public Site has no reviewer authentication, assignment, decision, or release authority.",
    requires: ["Authenticated role", "Scoped assignment", "Audit and separation of duties"],
    action: "NONE",
    actionLabel: "Requires authorized surface",
    sourceLabel: "Review Console read-only contract",
    sourcePath: "apps/explorer-web/src/features/review_console_readonly/README.md",
  }),
]);

export const OPERATIONAL_HANDOFFS: readonly FunctionRecord[] = Object.freeze([
  operationalHandoff({
    id: "source-refresh",
    title: "Source refresh",
    summary: "Prepare a bounded refresh against an already admitted source without silently widening scope.",
    interface: "Copyable no-effect handoff",
    boundary: "Refresh is not admission, promotion, release, or publication.",
    requires: ["Accepted descriptor", "Pinned prior and candidate identity", "Correction and rollback path"],
    actionLabel: "Copy refresh handoff",
    sourceLabel: "Source refresh runbook",
    sourcePath: "docs/runbooks/SOURCE_REFRESH_RUNBOOK.md",
  }),
  operationalHandoff({
    id: "no-network-validation",
    title: "No-network validation",
    summary: "Rehearse deterministic fixtures and negative states without retrieving a live payload.",
    interface: "Copyable fixture handoff",
    boundary: "A fixture pass does not establish a live source, production policy, or public release.",
    requires: ["Exact fixture identity", "Expected finite outcomes", "No-write/no-network proof"],
    actionLabel: "Copy validation handoff",
    sourceLabel: "No-network test runbook",
    sourcePath: "docs/runbooks/NO_NETWORK_TEST_RUNBOOK.md",
  }),
  operationalHandoff({
    id: "promotion",
    title: "Promotion preparation",
    summary: "Assemble the evidence, policy, review, receipt, and rollback questions required before a lifecycle decision.",
    interface: "Copyable preparation handoff",
    boundary: "The handoff cannot approve or apply a lifecycle transition.",
    requires: ["Evidence closure", "Policy decision", "Accountable review", "Rollback target"],
    actionLabel: "Copy promotion handoff",
    sourceLabel: "Promotion runbook",
    sourcePath: "docs/runbooks/PROMOTION_RUNBOOK.md",
  }),
  operationalHandoff({
    id: "release-dry-run",
    title: "Release rehearsal",
    summary: "Plan a non-public release gate rehearsal with exact-revision evidence and explicit non-effects.",
    interface: "Copyable rehearsal handoff",
    boundary: "Dry-run success is not review, release, deployment, promotion, or publication.",
    requires: ["Candidate identity", "Manifest closure", "Correction and rollback evidence"],
    actionLabel: "Copy rehearsal handoff",
    sourceLabel: "Release dry-run",
    sourcePath: "docs/runbooks/RELEASE_DRY_RUN.md",
  }),
  operationalHandoff({
    id: "correction",
    title: "Correction",
    summary: "Preserve immutable history while planning supersession, affected consumers, notices, and revalidation.",
    interface: "Copyable correction handoff",
    boundary: "A copied plan changes no canonical record, carrier, cache, release, or public state.",
    requires: ["Affected identity", "Correction reason", "Consumer inventory", "Successor posture"],
    actionLabel: "Copy correction handoff",
    sourceLabel: "Evidence correction runbook",
    sourcePath: "docs/runbooks/EVIDENCE_CORRECTION.md",
  }),
  operationalHandoff({
    id: "rollback",
    title: "Rollback",
    summary: "Plan restoration to a named prior safe state with consumer invalidation and accountable review.",
    interface: "Copyable rollback handoff",
    boundary: "The Site cannot execute rollback or mutate a release state.",
    requires: ["Prior safe target", "Rollback card", "Affected consumers", "Verification plan"],
    actionLabel: "Copy rollback handoff",
    sourceLabel: "Rollback runbook",
    sourcePath: "docs/runbooks/ROLLBACK_RUNBOOK.md",
  }),
]);

export const FUNCTION_REGISTRY: readonly FunctionRecord[] = Object.freeze([
  ...MAP_FUNCTIONS,
  ...SITE_EXTENSION_FUNCTIONS,
  ...OPERATIONAL_HANDOFFS,
]);

export const functionsForGroup = (group: FunctionGroup): readonly FunctionRecord[] =>
  FUNCTION_REGISTRY.filter((record) => record.group === group);
