import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { validateReceipt } from "../scripts/validate-sites-deployment-receipt.mjs";
const url = new URL("../fixtures/sites-deployment-receipt/repository-rehearsal.json", import.meta.url);
const load = async () => JSON.parse(await readFile(url, "utf8"));
const mutate = async (fn) => { const r = await load(); fn(r); return r; };
test("repository rehearsal is valid and mutation-free", async () => assert.deepEqual(validateReceipt(await load()), { outcome: "PASS", errors: [] }));
for (const [name, fn] of [["wrong project", r => r.site.project_id = "replacement"], ["second Site", r => r.authority.second_site_created = true], ["Vercel mutation", r => r.authority.vercel_mutated = true], ["live rehearsal mutation", r => r.authority.live_transition_performed = true], ["invented deployed result", r => r.outcome = "DEPLOYED"], ["missing digest", r => r.source.artifact_sha256 = ""], ["short revision", r => r.source.revision = "ec203a9"], ["missing evidence", r => r.checks.build.evidence = ""]]) test(`fails closed on ${name}`, async () => assert.equal(validateReceipt(await mutate(fn)).outcome, "DENY"));
test("live success requires version IDs, restore proof, and smoke passes", async () => { const r = await mutate(x => { x.mode = "OPERATOR_READBACK"; x.outcome = "DEPLOYED"; x.authority.live_transition_performed = true; }); const result = validateReceipt(r); assert.equal(result.outcome, "DENY"); assert.ok(result.errors.some(e => e.includes("previous_version_id"))); assert.ok(result.errors.some(e => e.includes("desktop_smoke"))); assert.ok(result.errors.some(e => e.includes("operator_restore_confirmed"))); });
