from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT))
from tools.quality.flora.usda_common import canonical_hash,validate,write_json,sha256_file
p=argparse.ArgumentParser();p.add_argument('--join-plan',type=Path,required=True);p.add_argument('--county-geojson',type=Path,required=True);p.add_argument('--county-presence',type=Path,required=True);p.add_argument('--geometry-approval',type=Path,required=True);p.add_argument('--out-root',type=Path,required=True);p.add_argument('--snapshot-date',required=True);p.add_argument('--generated-at',required=True);a=p.parse_args()
if json.loads(a.geometry_approval.read_text()).get('decision')!='approved': raise SystemExit('USDA_PLANTS_GEOMETRY_APPROVAL_REQUIRED')
geom=json.loads(a.county_geojson.read_text());presence=json.loads(a.county_presence.read_text())
gf={f['properties']['fips']:f['geometry'] for f in geom['features']}
features=[]
for r in sorted(presence.get('records',[]),key=lambda x:(x['plants_symbol'],x['fips'])):
 if r['fips'] in gf: features.append({"type":"Feature","id":f"{r['plants_symbol']}:{r['fips']}","properties":{"fips":r['fips'],"plants_symbol":r['plants_symbol'],"presence":r.get('presence','present'),"spec_hash":r['spec_hash'],"source_id":"usda_plants","geometry_source_id":f"kfm.geometry_source.flora.usda_plants.counties.{a.snapshot_date}"},"geometry":gf[r['fips']]})
out=a.out_root/f'published/flora/usda_plants/{a.snapshot_date}/map'; out.mkdir(parents=True,exist_ok=True)
fc={"type":"FeatureCollection","metadata":{"object_type":"usda_plants_published_county_presence_geojson","schema_version":"1.0.0","domain":"flora","source_id":"usda_plants","snapshot_date":a.snapshot_date,"generated_at":a.generated_at,"join_key":"fips","geometry_authority":"U.S. Census Bureau Cartographic Boundary Files","publication_state":"published","contains_county_boundary_geometry":True,"contains_occurrence_coordinates":False,"contains_vector_tiles":False,"citation_text":"USDA PLANTS Database and U.S. Census Bureau county cartographic boundaries."},"features":features}
fc['metadata']['geojson_hash']=canonical_hash(fc['metadata'],'geojson_hash'); validate(ROOT/'schemas/flora/usda_plants_published_county_presence_geojson.schema.json',fc); write_json(out/'county_presence.geojson',fc)
style={"schema_version":"1.0.0","object_type":"usda_plants_published_geojson_map_style","style_id":f"kfm.map_style.flora.usda_plants.county_presence_geojson.{a.snapshot_date}","domain":"flora","source_id":"usda_plants","snapshot_date":a.snapshot_date,"generated_at":a.generated_at,"maplibre_style":{"version":8,"name":"KFM USDA PLANTS County Presence","metadata":{"kfm:domain":"flora","kfm:source_id":"usda_plants","kfm:snapshot_date":a.snapshot_date},"sources":{"flora_usda_plants_county_presence":{"type":"geojson","data":f"published/flora/usda_plants/{a.snapshot_date}/map/county_presence.geojson","attribution":"USDA PLANTS Database; U.S. Census Bureau county boundaries."}},"layers":[{"id":"flora_usda_plants_county_presence_fill","type":"fill","source":"flora_usda_plants_county_presence","paint":{"fill-opacity":0.55}}]},"safety":{"contains_occurrence_coordinates":False,"contains_vector_tiles":False,"uses_geojson_source":True}}
style['style_hash']=canonical_hash(style,'style_hash');write_json(out/'map_style.json',style)
r={"schema_version":"1.0.0","object_type":"usda_plants_geometry_publication_receipt","geometry_publication_receipt_id":f"kfm.geometry_publication_receipt.flora.usda_plants.{a.snapshot_date}","domain":"flora","source_id":"usda_plants","snapshot_date":a.snapshot_date,"generated_at":a.generated_at,"join_plan_ref":str(a.join_plan),"published_items":[{"role":"county_presence_geojson","target_ref":f"published/flora/usda_plants/{a.snapshot_date}/map/county_presence.geojson","sha256":sha256_file(out/'county_presence.geojson'),"status":"published"}],"publication_state":"published","status":"pass","reason_codes":[]}
r['receipt_hash']=canonical_hash(r,'receipt_hash');write_json(a.out_root/f'geometry/flora/usda_plants/{a.snapshot_date}/geometry_publication_receipt.json',r)
