from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT))
from tools.quality.flora.usda_common import canonical_hash,validate,write_json,sha256_file
p=argparse.ArgumentParser();p.add_argument('--snapshot-date',required=True);p.add_argument('--generated-at',required=True);p.add_argument('--out',type=Path,required=True)
for a in ['--geometry-source','--geometry-validation','--county-presence','--published-release-manifest','--geometry-publication-request','--geojson','--map-style','--join-plan','--geometry-intake','--geometry-publication-approval','--geometry-publication-receipt','--geometry-rollback-plan','--requester-id','--approver-id','--decision','--geometry-validation']:
 try:p.add_argument(a)
 except:pass
a=p.parse_args();o={"schema_version":"1.0.0","object_type":"usda_plants_geometry_publication_request_builder","domain":"flora","source_id":"usda_plants","snapshot_date":a.snapshot_date,"generated_at":a.generated_at}
if 'request' in "usda_plants_geometry_publication_request_builder.py": o.update({"geometry_publication_request_id":f"kfm.geometry_publication_request.flora.usda_plants.{a.snapshot_date}","requested_by":{"requester_id":a.requester_id or 'flora-map-steward',"requester_type":"human"},"scope":{"published_release_manifest_ref":str(getattr(a,'published_release_manifest',"")),"county_presence_ref":str(getattr(a,'county_presence',"")),"geometry_source_ref":str(getattr(a,'geometry_source',"")),"geometry_validation_ref":str(getattr(a,'geometry_validation',""))},"intent":"publish_county_boundary_geojson_join","publication_state":"requested","allowed_outputs":["county_presence_geojson","geojson_map_style"],"blocked_outputs":["occurrence_coordinates","vector_tiles","raw_geometry_files","work_files","quarantine_files"],"status":"requested","reason_codes":[]})
if 'approval' in "usda_plants_geometry_publication_request_builder.py": o.update({"geometry_publication_approval_id":f"kfm.geometry_publication_approval.flora.usda_plants.{a.snapshot_date}","geometry_publication_request_ref":str(getattr(a,'geometry_publication_request',"")),"approver":{"approver_id":a.approver_id or 'flora-map-publication-steward',"approver_type":"human","attestation":"approved"},"decision":a.decision or 'approved',"decision_reason_codes":["USDA_PLANTS_GEOMETRY_PUBLICATION_APPROVED"],"approval_conditions":["County boundary geometry only.","No plant occurrence coordinates.","No vector tiles."],"publication_state":"approved","status":"pass"})
if 'join_plan' in "usda_plants_geometry_publication_request_builder.py": o.update({"join_plan_id":f"kfm.geometry_join_plan.flora.usda_plants.counties.{a.snapshot_date}","geometry_source_ref":str(getattr(a,'geometry_source',"")),"geometry_validation_ref":str(getattr(a,'geometry_validation',"")),"county_presence_ref":str(getattr(a,'county_presence',"")),"target_geojson_ref":f"published/flora/usda_plants/{a.snapshot_date}/map/county_presence.geojson","join":{"presence_key":"fips","geometry_key":"fips","taxon_key":"plants_symbol","join_type":"one_presence_record_to_one_county_geometry"},"public_safety":{"allows_county_boundary_geometry":True,"allows_occurrence_coordinates":False,"allows_vector_tiles":False,"allows_raw_refs":False,"allows_work_refs":False,"allows_quarantine_refs":False},"status":"pass","reason_codes":[]})
if 'rollback' in "usda_plants_geometry_publication_request_builder.py": o.update({"rollback_plan_id":f"kfm.geometry_publication_rollback_plan.flora.usda_plants.{a.snapshot_date}","geojson_ref":str(getattr(a,'geojson',"")),"map_style_ref":str(getattr(a,'map_style',"")),"rollback_strategy":"mark_superseded","rollback_actions":[{"action":"mark_geometry_publication_superseded","target_ref":str(getattr(a,'geojson',"")),"requires_human_approval":True}],"status":"ready","reason_codes":[]})
if 'audit_ledger' in "usda_plants_geometry_publication_request_builder.py":
 entries=[]
 i=1
 for et,arg in [('county_geometry_source','geometry_source'),('county_geometry_intake','geometry_intake'),('county_geometry_validation_report','geometry_validation'),('county_geometry_join_plan','join_plan'),('geometry_publication_request','geometry_publication_request'),('geometry_publication_approval','geometry_publication_approval'),('county_presence_geojson','geojson'),('geojson_map_style','map_style'),('geometry_publication_receipt','geometry_publication_receipt'),('geometry_publication_rollback_plan','geometry_rollback_plan')]:
  pth=getattr(a,arg,None)
  if pth: entries.append({"entry_id":f"{i:03d}","entry_type":et,"ref":str(pth),"sha256":sha256_file(Path(pth)),"status":"recorded"});i+=1
 o.update({"ledger_id":f"kfm.geometry_publication_audit_ledger.flora.usda_plants.{a.snapshot_date}","entries":entries,"publication_state":"published","status":"pass","reason_codes":[]})
o["request_hash"]=canonical_hash(o,"request_hash");validate(ROOT/'schemas/flora/usda_plants_geometry_publication_request.schema.json',o);write_json(a.out,o)
