#!/usr/bin/env python3
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


MARKERS = ("TODO", "UNKNOWN", "NEEDS VERIFICATION")


@dataclass(frozen=True)
class FileDebt:
    path: str
    total: int
    todo: int
    unknown: int
    needs_verification: int


def scan_markdown_debt(root: Path) -> list[FileDebt]:
    rows: list[FileDebt] = []
    for path in sorted(root.rglob("*.md")):
        if ".git" in path.parts:
            continue
        text = path.read_text(encoding="utf-8")
        todo = text.count("TODO")
        unknown = text.count("UNKNOWN")
        needs_verification = text.count("NEEDS VERIFICATION")
        total = todo + unknown + needs_verification
        if total == 0:
            continue
        rows.append(
            FileDebt(
                path=str(path.relative_to(root)),
                total=total,
                todo=todo,
                unknown=unknown,
                needs_verification=needs_verification,
            )
        )
    rows.sort(key=lambda item: (-item.total, item.path))
    return rows


def render_backlog(rows: list[FileDebt], top: int) -> str:
    selected = rows[:top]
    total_files = len(rows)
    total_markers = sum(item.total for item in rows)
    total_todo = sum(item.todo for item in rows)
    total_unknown = sum(item.unknown for item in rows)
    total_needs_verification = sum(item.needs_verification for item in rows)

    lines = [
        "# Markdown Debt Backlog",
        "",
        "Autogenerated by `tools/ci/generate_markdown_debt_backlog.py`.",
        "",
        "## Snapshot",
        "",
        f"- Files with markers: **{total_files}**",
        f"- Marker totals: **{total_markers}** (`TODO`={total_todo}, `UNKNOWN`={total_unknown}, `NEEDS VERIFICATION`={total_needs_verification})",
        f"- Backlog focus (top {top}): highest marker density markdown files",
        "",
        "## Priority queue",
        "",
        "| Rank | File | Total | TODO | UNKNOWN | NEEDS VERIFICATION |",
        "| --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for idx, item in enumerate(selected, start=1):
        lines.append(
            f"| {idx} | `{item.path}` | {item.total} | {item.todo} | {item.unknown} | {item.needs_verification} |"
        )

    lines.extend(
        [
            "",
            "## Next move",
            "",
            "Resolve markers in rank order, starting with the top 3 files, and re-run this generator each cycle.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate markdown debt backlog report.")
    parser.add_argument("--root", default=".", help="Repository root path")
    parser.add_argument("--top", default=10, type=int, help="Number of high-priority files to include")
    parser.add_argument(
        "--output",
        default="artifacts/observability/markdown_debt_backlog.md",
        help="Path to output markdown file",
    )
    args = parser.parse_args()

    root = Path(args.root)
    if not root.is_dir():
        raise SystemExit(f"generate_markdown_debt_backlog: invalid root path: {root}")

    if args.top <= 0:
        raise SystemExit("generate_markdown_debt_backlog: --top must be > 0")

    rows = scan_markdown_debt(root)
    content = render_backlog(rows, args.top)

    output_path = root / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"generate_markdown_debt_backlog: wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
