#!/usr/bin/env bash
set -euo pipefail

# Targeted move rollback
git mv 'docs/domains/atmosphere-air/AIR_CANDIDATE_REENTRY_SLICE.md' 'docs/domains/atmosphere/AIR_CANDIDATE_REENTRY_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_CLIENT_DELIVERY_SLICE.md' 'docs/domains/atmosphere/AIR_CLIENT_DELIVERY_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_CONTINUOUS_ASSURANCE_SLICE.md' 'docs/domains/atmosphere/AIR_CONTINUOUS_ASSURANCE_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_CUTOVER_OBSERVATION_RELEASE_LEDGER_SLICE.md' 'docs/domains/atmosphere/AIR_CUTOVER_OBSERVATION_RELEASE_LEDGER_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_DELIVERY_DEPLOYMENT_READINESS_SLICE.md' 'docs/domains/atmosphere/AIR_DELIVERY_DEPLOYMENT_READINESS_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_DEPLOYMENT_AUTHORIZATION_SLICE.md' 'docs/domains/atmosphere/AIR_DEPLOYMENT_AUTHORIZATION_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_MAINTENANCE_REMEDIATION_SLICE.md' 'docs/domains/atmosphere/AIR_MAINTENANCE_REMEDIATION_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_MAINTENANCE_ROLLFORWARD_SLICE.md' 'docs/domains/atmosphere/AIR_MAINTENANCE_ROLLFORWARD_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_OPERATIONAL_HANDOFF_RELEASE_CLOSURE_SLICE.md' 'docs/domains/atmosphere/AIR_OPERATIONAL_HANDOFF_RELEASE_CLOSURE_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_PUBLICATION_BOUNDARY_SLICE.md' 'docs/domains/atmosphere/AIR_PUBLICATION_BOUNDARY_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_PUBLIC_OPS_SLICE.md' 'docs/domains/atmosphere/AIR_PUBLIC_OPS_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_PUBLIC_READ_MODEL_SLICE.md' 'docs/domains/atmosphere/AIR_PUBLIC_READ_MODEL_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_QA_PROMOTION_SLICE.md' 'docs/domains/atmosphere/AIR_QA_PROMOTION_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_READ_MODEL_REBUILD_SLICE.md' 'docs/domains/atmosphere/AIR_READ_MODEL_REBUILD_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_CONTINUOUS_ASSURANCE_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_CONTINUOUS_ASSURANCE_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_CUTOVER_OBSERVATION_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_CUTOVER_OBSERVATION_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_DEPLOYMENT_AUTHORIZATION_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_DEPLOYMENT_AUTHORIZATION_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_DEPLOYMENT_READINESS_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_DEPLOYMENT_READINESS_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_MAINTENANCE_REMEDIATION_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_MAINTENANCE_REMEDIATION_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_MAINTENANCE_ROLLFORWARD_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_MAINTENANCE_ROLLFORWARD_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_OPERATIONAL_HANDOFF_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_OPERATIONAL_HANDOFF_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_PUBLICATION_BOUNDARY_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_PUBLICATION_BOUNDARY_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_PUBLICATION_BOUNDARY_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_PUBLICATION_BOUNDARY_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_PUBLICATION_MATERIALIZATION_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_PUBLICATION_MATERIALIZATION_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_READ_MODEL_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_READ_MODEL_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_RELEASE_CANDIDATE_REFRESH_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_RELEASE_CANDIDATE_REFRESH_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_REENTRY_RELEASE_CANDIDATE_SLICE.md' 'docs/domains/atmosphere/AIR_REENTRY_RELEASE_CANDIDATE_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_RELEASE_CANDIDATE_SLICE.md' 'docs/domains/atmosphere/AIR_RELEASE_CANDIDATE_SLICE.md'
git mv 'docs/domains/atmosphere-air/AIR_STEWARDSHIP_REMEDIATION_SLICE.md' 'docs/domains/atmosphere/AIR_STEWARDSHIP_REMEDIATION_SLICE.md'
git mv 'docs/domains/geology/CHANGE_IMPACT_MATRIX.md' 'docs/domains/geology-natural-resources/CHANGE_IMPACT_MATRIX.md'
git mv 'docs/domains/geology/CROSS_LANE_RELATIONS.md' 'docs/domains/geology-natural-resources/CROSS_LANE_RELATIONS.md'
git mv 'docs/domains/geology/DATASET_OR_LAYER_INDEX.md' 'docs/domains/geology-natural-resources/DATASET_OR_LAYER_INDEX.md'
git mv 'docs/domains/geology/DOMAIN_INDEX.md' 'docs/domains/geology-natural-resources/DOMAIN_INDEX.md'
git mv 'docs/domains/geology/EVOLUTION_LOG.md' 'docs/domains/geology-natural-resources/EVOLUTION_LOG.md'
git mv 'docs/domains/geology/FILE_MANIFEST.md' 'docs/domains/geology-natural-resources/FILE_MANIFEST.md'
git mv 'docs/domains/geology/OPEN_QUESTIONS.md' 'docs/domains/geology-natural-resources/OPEN_QUESTIONS.md'
git mv 'docs/domains/geology/README.md' 'docs/domains/geology-natural-resources/README.md'
git mv 'docs/domains/geology/SCHEMA_INDEX.md' 'docs/domains/geology-natural-resources/SCHEMA_INDEX.md'
git mv 'docs/domains/geology/SOURCE_INDEX.md' 'docs/domains/geology-natural-resources/SOURCE_INDEX.md'
git mv 'docs/domains/geology/VERIFICATION_BACKLOG.md' 'docs/domains/geology-natural-resources/VERIFICATION_BACKLOG.md'
git mv 'docs/domains/hydrology/HUC12_COMID_CROSSWALK_MANIFEST_LEGACY.md' 'docs/hydrology/huc12-comid-crosswalk-manifest.md'
git mv 'docs/domains/hydrology/LEGACY_README_LINEAGE.md' 'docs/hydrology/README.md'
git mv 'docs/domains/ui-maplibre/README_LAYER11_SNIPPET.md' 'docs/layers/README_LAYER11_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER12_SNIPPET.md' 'docs/layers/README_LAYER12_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER14_SNIPPET.md' 'docs/layers/README_LAYER14_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER15_SNIPPET.md' 'docs/layers/README_LAYER15_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER18_SNIPPET.md' 'docs/layers/README_LAYER18_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER19_SNIPPET.md' 'docs/layers/README_LAYER19_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER20_SNIPPET.md' 'docs/layers/README_LAYER20_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/README_LAYER8_SNIPPET.md' 'docs/layers/README_LAYER8_SNIPPET.md'
git mv 'docs/domains/ui-maplibre/browser-sigstore-verify-before-render.md' 'docs/maps/browser-sigstore-verify-before-render.md'

# Remove new reorg tooling/docs
rm -f tools/repo_inventory/classify_paths.py tools/repo_inventory/check_reorg_manifest.py tools/repo_inventory/check_doc_orphans.py tools/repo_inventory/check_public_path_boundaries.py
rm -rf tests/repo_inventory
rm -rf docs/registers/reorg
