#!/usr/bin/env python3
import argparse, json
from pathlib import Path
from datetime import datetime, timezone
now=lambda: datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00','Z')

if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--refresh-plan',required=True);p.add_argument('--materialization-dir',action='append',default=[]);p.add_argument('--out-dir',required=True);p.add_argument('--source-read-model-dir');p.add_argument('--as-of');p.add_argument('--fixture-only',action='store_true');p.add_argument('--dry-run',action='store_true');a=p.parse_args()
 plan=json.loads(Path(a.refresh_plan).read_text());out=Path(a.out_dir)
 (out/'public_api_record_refresh_candidates').mkdir(parents=True,exist_ok=True);(out/'public_provenance_trace_refresh_candidates').mkdir(parents=True,exist_ok=True);(out/'client_invalidation_notice_refresh_candidates').mkdir(parents=True,exist_ok=True)
 asof=a.as_of or now()
 files={
 out/'reentry_public_index_refresh_candidate.json':{'schema_version':'v1','domain':'atmosphere.air','index_id':'idx1','generated_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'entries':[{'entry_id':'e1','publication_candidate_ref':plan['publication_receipt_candidate_ref'],'artifact_refs':[],'catalog_refs':[],'provenance_ref':'prov1','qa_summary_ref':'qa1','measurement_summary':{'pm25_units':'ug_m3','nowcast_is_operational':True,'nowcast_is_validated_aqs_truth':False},'visibility':'candidate_only','retraction_state':'none','candidate_only':True}],'status':'fixture_index_refresh_candidate'},
 out/'public_api_record_refresh_candidates/rec1.json':{'schema_version':'v1','domain':'atmosphere.air','record_id':'rec1','generated_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'public_index_refresh_candidate_ref':str(out/'reentry_public_index_refresh_candidate.json'),'publication_candidate_ref':plan['publication_receipt_candidate_ref'],'source_classes':['fixture','airnow_nowcast','epa_aqs_validated'],'status':'fixture_record_candidate'},
 out/'reentry_public_status_refresh_candidate.json':{'schema_version':'v1','domain':'atmosphere.air','status_id':'st1','generated_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'public_index_refresh_candidate_ref':str(out/'reentry_public_index_refresh_candidate.json'),'fixture_candidate_count':1,'blocked_count':0,'retracted_count':0,'warnings':[],'status':'fixture_only'},
 out/'public_provenance_trace_refresh_candidates/prov1.json':{'schema_version':'v1','domain':'atmosphere.air','trace_id':'prov1','generated_at':now(),'as_of':asof,'status':'fixture_trace_candidate','public_safe_refs':[],'chain':['QA Summary','EvidenceBundle']},
 out/'reentry_public_delta_feed_refresh_candidate.json':{'schema_version':'v1','domain':'atmosphere.air','delta_feed_id':'d1','generated_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'publication_delta_seed_ref':plan['publication_delta_seed_ref'],'changes':[{'change_id':'c1','change_type':'candidate_publication_added','publication_candidate_id':'pc1','record_id':'rec1','before_visibility':'blocked','after_visibility':'candidate_only','reason':'fixture','effective_at':asof,'candidate_only':True}],'public_safe_refs':[],'status':'fixture_delta_candidate'},
 out/'client_invalidation_notice_refresh_candidates/n1.json':{'schema_version':'v1','domain':'atmosphere.air','notice_id':'n1','created_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'status':'fixture_notice_candidate','visibility_change':'candidate_added','public_safe_refs':[]},
 out/'reentry_read_model_version_candidate.json':{'schema_version':'v1','domain':'atmosphere.air','version_candidate_id':'v1','generated_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'source_version_refs':[],'candidate_version_refs':[{'version_id':'v1','public_index_candidate_ref':str(out/'reentry_public_index_refresh_candidate.json'),'created_at':asof,'visibility':'candidate_only','fixture_backed':True,'sha256':'x'}],'active_version_ref':'v1','superseded_version_refs':[],'blocked_version_refs':[],'status':'fixture_version_candidate'},
 out/'reentry_read_model_refresh_manifest.json':{'schema_version':'v1','domain':'atmosphere.air','refresh_manifest_id':'m1','generated_at':now(),'as_of':asof,'refresh_plan_ref':a.refresh_plan,'public_index_refresh_candidate_ref':str(out/'reentry_public_index_refresh_candidate.json'),'public_api_record_refresh_candidate_refs':[str(out/'public_api_record_refresh_candidates/rec1.json')],'public_status_refresh_candidate_ref':str(out/'reentry_public_status_refresh_candidate.json'),'public_provenance_trace_refresh_candidate_refs':[str(out/'public_provenance_trace_refresh_candidates/prov1.json')],'public_delta_feed_refresh_candidate_ref':str(out/'reentry_public_delta_feed_refresh_candidate.json'),'client_invalidation_notice_refresh_candidate_refs':[str(out/'client_invalidation_notice_refresh_candidates/n1.json')],'read_model_version_candidate_ref':str(out/'reentry_read_model_version_candidate.json'),'artifact_refs':[],'source_chain_refs':[],'next_lifecycle_target':'fixture_client_delivery_refresh_review','safety_checks':{},'status':'fixture_read_model_refresh_manifest'}
 }
 for pth,obj in files.items(): pth.write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
 print('PASS')
