name: "PR Auto-Merge"

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
  pull_request_review:
    types: [submitted, dismissed]
  check_suite:
    types: [completed]
  status: {}
  issue_comment:
    types: [created]
  workflow_dispatch: {}

permissions:
  contents: write       # needed to merge & delete branches
  pull-requests: write  # needed to update PRs / labels
  checks: read
  statuses: read

concurrency:
  group: automerge-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  automerge:
    name: Auto-merge if policy satisfied
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: >
      github.event_name != 'pull_request_target' ||
      (github.event.pull_request.user.login != 'dependabot[bot]' &&
       github.event.pull_request.user.login != 'github-actions[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run AutoMerge Action
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .github/automerge.yml
