name: "Hygiene — Close Stale Issues and PRs"

on:
  schedule:
    - cron: "0 3 * * *"   # Daily at 03:00 UTC
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: read

concurrency:
  group: close-stale
  cancel-in-progress: false

jobs:
  stale:
    name: Mark & close stale threads
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      - name: Run stale bot
        id: stale
        uses: actions/stale@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # --- Timing windows ---
          days-before-stale: 60            # issues go stale after 60d of inactivity
          days-before-close: 14            # close 14d after being marked stale
          days-before-pr-stale: 30         # PRs go stale after 30d of inactivity
          days-before-pr-close: 14

          # --- Stale labels & behavior ---
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          remove-stale-when-updated: true
          exempt-draft-prs: true
          enable-statistics: true

          # --- Exemptions (labels keep items from going stale) ---
          exempt-issue-labels: >
            pinned,security,good first issue,help wanted,roadmap,needs-triage,
            on-hold,milestone,discussion
          exempt-pr-labels: >
            wip,no-automerge,security,roadmap,needs-triage,on-hold,discussion

          # --- Extra safety: don't touch items with milestones or assignees ---
          exempt-all-assignees: true
          exempt-milestones: true

          # --- Limits & noise control ---
          operations-per-run: 200
          ascending: false
          only-labels: ""      # process all unless exempted
          labels-to-remove-when-unstale: "stale"

          # --- Messages (keep concise & actionable) ---
          stale-issue-message: |
            This issue has been automatically marked **stale** after 60 days of inactivity.
            If this is still relevant, please comment or add an exempt label
            (e.g., `help wanted`, `roadmap`, `on-hold`) to keep it open. It will be
            closed in 14 days if no further activity occurs.

            _Note: issues with assignees, milestones, or exempt labels are not marked stale._

          close-issue-message: |
            Closing this issue due to prolonged inactivity after being marked stale.
            If you’d like to revisit it, please reopen with an update or add an exempt label.

          stale-pr-message: |
            This pull request has been marked **stale** after 30 days without activity.
            Please push updates, comment, or add an exempt label (e.g., `wip`, `no-automerge`)
            to keep it open. It will be closed in 14 days if no activity occurs.

            _Draft PRs or items with assignees/milestones/exempt labels are not marked stale._

          close-pr-message: |
            Closing this pull request due to prolonged inactivity after being marked stale.
            Please reopen or open a new PR when you’re ready to continue. Thank you!

      - name: Job summary
        if: always()
        shell: bash
        run: |
          {
            echo "## Hygiene — Close Stale Issues and PRs"
            echo "- Ran at: **$(date -u +"%Y-%m-%d %H:%M:%S UTC")**"
            echo "- Issue stale/close: **60d / 14d**"
            echo "- PR stale/close: **30d / 14d**"
            echo "- Exempt issue labels: \`pinned, security, good first issue, help wanted, roadmap, needs-triage, on-hold, milestone, discussion\`"
            echo "- Exempt PR labels: \`wip, no-automerge, security, roadmap, needs-triage, on-hold, discussion\`"
            echo
            echo "_See step logs for statistics and which threads were touched._"
          } >> "$GITHUB_STEP_SUMMARY"
