version: 2

updates:
  # ────────────────────────────────────────────────────────────────────────────
  # 1) GitHub Actions (repo root)
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: "04:05"
      timezone: America/Chicago
    rebase-strategy: auto
    open-pull-requests-limit: 5
    labels: [deps, "deps:actions"]
    commit-message:
      prefix: "deps(actions)"
      include: scope
    groups:
      actions-all:
        patterns: ["*"] # group all GH Actions into a single PR

  # ────────────────────────────────────────────────────────────────────────────
  # 2) Python (pip) — repo root (requirements*.txt)
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: pip
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: "04:10"
      timezone: America/Chicago
    rebase-strategy: auto
    allow:
      - dependency-type: direct    # keep noise down; only direct deps
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 8
    labels: [deps, "deps:pip"]
    commit-message:
      prefix: "deps(pip)"
      include: scope
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
      tooling:
        patterns:
          - "pytest*"
          - "pytest-*"
          - "ruff*"
          - "black"
          - "mypy*"
          - "sphinx*"
          - "mkdocs*"
      minor-and-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: gdal
        update-types: ["version-update:semver-major"]
      - dependency-name: rasterio
        update-types: ["version-update:semver-major"]
      - dependency-name: geopandas
        update-types: ["version-update:semver-major"]

  # ────────────────────────────────────────────────────────────────────────────
  # 3) Node (npm) — web app
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: npm
    directory: /web
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: "04:20"
      timezone: America/Chicago
    rebase-strategy: auto
    open-pull-requests-limit: 8
    versioning-strategy: increase   # keep lockfile fresh even without manifest changes
    labels: [deps, "deps:npm", "area:web"]
    commit-message:
      prefix: "deps(npm)"
      include: scope
    groups:
      dev-deps:
        dependency-type: development
        patterns: ["*"]
      runtime:
        dependency-type: production
        patterns: ["*"]
      # Optional: group map libs together (uncomment if desired)
      # map-stack:
      #   patterns:
      #     - "maplibre*"
      #     - "mapbox-gl*"
      #     - "@mapbox/*"
      #     - "ol"
      #     - "ol-*"
    # Tame churny major bumps for build tooling; opt-in later if needed
    ignore:
      - dependency-name: vite
        update-types: ["version-update:semver-major"]
      - dependency-name: webpack
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]

  # ────────────────────────────────────────────────────────────────────────────
  # 4) Dockerfiles — root or /docker
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: docker
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: "04:30"
      timezone: America/Chicago
    rebase-strategy: auto
    open-pull-requests-limit: 3
    labels: [deps, "deps:docker"]
    commit-message:
      prefix: "deps(docker)"
      include: scope
    groups:
      base-image:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /docker
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: "04:30"
      timezone: America/Chicago
    rebase-strategy: auto
    open-pull-requests-limit: 3
    labels: [deps, "deps:docker"]
    commit-message:
      prefix: "deps(docker)"
      include: scope
    groups:
      base-image:
        patterns: ["*"]