name: docker-build

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
    paths:
      - "docker/**"
      - "docker-compose.yml"
      - "requirements.txt"
      - "constraints.txt"
      - "pyproject.toml"
      - "src/**"
      - "stac/**"
      - "Makefile"
      - ".github/workflows/docker.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "docker/**"
      - "docker-compose.yml"
      - "requirements.txt"
      - "constraints.txt"
      - "pyproject.toml"
      - "src/**"
      - "stac/**"
      - "Makefile"
      - ".github/workflows/docker.yml"
  workflow_dispatch: {}  # manual runs

env:
  # image name must be lowercase for GHCR
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DOCKERFILE: docker/Dockerfile
  CONTEXT: .

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (and push on main/tag)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # required to push to GHCR
      id-token: write          # for provenance attestations (BuildKit)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # metadata-action semver + tags needs full history

      - name: Lowercase image name
        id: img
        run: |
          set -euo pipefail
          echo "name=${IMAGE_NAME,,}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Slightly larger inline cache; helps PRs reuse main branch cache
          buildkitd-flags: --debug

      # Login only when we intend to push (never on PRs from forks)
      - name: Login to GHCR
        if: >
          github.event_name == 'push' &&
          (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Produce tags/labels from branch, tag, and SHA
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.img.outputs.name }}
          # Add `latest` on default branch, semver tags on tag pushes, branch & sha always
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=sha,format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=kansas-geo-timeline
            org.opencontainers.image.description=Time · Terrain · History mapping system for Kansas (Earth + Web)
            org.opencontainers.image.licenses=MIT

      # Build for PRs; Build & Push for main/tags
      - name: Build (PR) / Build & Push (main/tag)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # BuildKit cache: scoped by repo+ref for better reuse and isolation
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}
          # Build args your Dockerfile can consume
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            GDAL_IMAGE=ghcr.io/osgeo/gdal:ubuntu-small-latest
          # Supply SBOM + provenance (BuildKit native)
          provenance: mode=max
          sbom: true

      # Optional: attest after push (separate attestation subject)
      - name: Attest (provenance+sbom)
        if: >
          steps.build.outputs.digest &&
          github.event_name == 'push' &&
          (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/'))
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ steps.img.outputs.name }}@${{ steps.build.outputs.digest }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
