name: "Hygiene — Sync GitHub Labels"

on:
  push:
    branches: [ "main" ]
    paths: [ ".github/labels.yml" ]
  pull_request:
    paths: [ ".github/labels.yml" ]
  workflow_dispatch:

permissions:
  contents: read
  issues: write         # needed to create/update labels
  metadata: read
  pull-requests: read   # for PR validation context

concurrency:
  group: labels-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Validate label config on PRs without making changes
  validate:
    name: Validate labels (dry-run on PR)
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional lint (kept minimal; skip if you don't want this step)
      - name: Lint .github/labels.yml
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/labels.yml
        continue-on-error: true

      - name: Dry-run label sync (no writes)
        id: dryrun
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
          dry-run: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: PR summary
        if: always()
        run: |
          echo "## Labels config validation" >> "$GITHUB_STEP_SUMMARY"
          echo "- Repository: \`${{ github.repository }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- Dry-run completed. If checks above passed, merging will apply changes on main." >> "$GITHUB_STEP_SUMMARY"

  # Apply label changes on main (push) or manual dispatch
  sync:
    name: Sync labels
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels from .github/labels.yml
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false   # set to true for strict sync (will delete extras)
          dry-run: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Job summary
        if: always()
        run: |
          echo "## Label sync applied" >> "$GITHUB_STEP_SUMMARY"
          echo "- Source: \`.github/labels.yml\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- delete-other-labels: \`false\`" >> "$GITHUB_STEP_SUMMARY"
