name: Link Check (docs)
on:
  push:
    branches: [ main ]
    paths: [ "README.md", "web/**", ".github/workflows/link-check.yml" ]
  pull_request:
    paths: [ "README.md", "web/**", ".github/workflows/link-check.yml" ]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose --no-progress
            --exclude "mailto:*"
            README.md web/**/*.html web/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
