# .github/workflows/link-check.yml
name: Link Check (docs)

on:
  push:
    branches: [ main ]
    paths:
      - "README.md"
      - "docs/**"
      - "web/**"
      - ".lychee.toml"
      - ".github/workflows/link-check.yml"
  pull_request:
    paths:
      - "README.md"
      - "docs/**"
      - "web/**"
      - ".lychee.toml"
      - ".github/workflows/link-check.yml"
  workflow_dispatch:
  schedule:
    # Weekly sweep (Sunday 04:05 UTC)
    - cron: "5 4 * * 0"

permissions:
  contents: read

concurrency:
  group: link-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lychee:
    name: Lychee link check
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for PR diff mode

      # Build args dynamically:
      # - PRs: check only changed Markdown/HTML files
      # - Push/Schedule/Dispatch: scan README + docs + web
      # - If .lychee.toml exists, defer to it
      - name: Compute lychee args
        id: args
        shell: bash
        run: |
          set -euo pipefail

          collect_targets() {
            local mode="$1"
            local -a files=()
            if [[ "$mode" == "pr" ]]; then
              # Ensure base is available (esp. for fork PRs)
              git fetch -q origin "${{ github.base_ref }}" || true
              while IFS= read -r f; do
                [[ -z "$f" ]] && continue
                [[ "$f" =~ \.(md|html)$ ]] || continue
                files+=("$f")
              done < <(git --no-pager diff --name-only "origin/${{ github.base_ref }}..." | tr -d '\r')
            else
              [[ -f README.md ]] && files+=("README.md")
              [[ -d docs ]] && while IFS= read -r -d '' f; do files+=("$f"); done < <(find docs -type f \( -name '*.md' -o -name '*.html' \) -print0)
              [[ -d web  ]] && while IFS= read -r -d '' f; do files+=("$f"); done < <(find web  -type f \( -name '*.md' -o -name '*.html' \) -print0)
            fi
            printf '%s\n' "${files[@]}" | sort -u
          }

          MODE="full"
          [[ "${{ github.event_name }}" == "pull_request" ]] && MODE="pr"

          mapfile -t TARGETS < <(collect_targets "$MODE")

          # If no targets, check README.md to avoid no-op
          if [[ ${#TARGETS[@]} -eq 0 ]]; then
            [[ -f README.md ]] && TARGETS=("README.md")
          fi

          # Prefer repo config if present
          if [[ -f .lychee.toml ]]; then
            echo "args=--config .lychee.toml ${TARGETS[*]}" >> "$GITHUB_OUTPUT"
            echo "mode=$MODE" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          mkdir -p lychee

          BASE_ARGS=(--no-progress --verbose --max-retries 3 --retry-wait-time 2 --require-https)
          # Emit both JSON and Markdown reports
          OUT_ARGS=(--format json --output lychee/results.json --format markdown --output lychee.md)

          # Reasonable excludes for CI (flaky/rate-limited endpoints)
          EXCLUDES=(
            'mailto:*' 'tel:*'
            'http://localhost*' 'http://127.0.0.1*' 'https://localhost*' 'https://127.0.0.1*'
            'https://*.tile.openstreetmap.org/*'
            'https://*.googleapis.com/*'
            'https://*.arcgis.com/*'
            'https://api.mapbox.com/*'
          )

          ARGS=( "${BASE_ARGS[@]}" "${OUT_ARGS[@]}" )
          for e in "${EXCLUDES[@]}"; do ARGS+=( --exclude "$e" ); done
          ARGS+=( "${TARGETS[@]}" )

          printf "args=%s\n" "${ARGS[*]}" >> "$GITHUB_OUTPUT"
          echo "mode=$MODE" >> "$GITHUB_OUTPUT"

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: ${{ steps.args.outputs.args }}
        env:
          # Token improves rate limits for links to github.com (raw, releases, etc.)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report-${{ github.run_id }}
          path: |
            lychee.md
            lychee/results.json
          if-no-files-found: warn
          retention-days: 7

      - name: Job Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## Link Check (Lychee)"
            echo
            echo "- Mode: **${{ steps.args.outputs.mode || 'full' }}**"
            if [ -f lychee.md ]; then
              echo
              echo "### Report excerpt"
              echo
              echo '```markdown'
              sed -n '1,200p' lychee.md
              echo '```'
            else
              echo "_No lychee.md report generated (likely used repo .lychee.toml with different outputs)._"
            fi
          } >> "$GITHUB_STEP_SUMMARY"