name: Sync Roadmap → Issues & Milestones

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/roadmap/roadmap.yaml"
      - "scripts/sync-roadmap.js"
      - "package.json"
      - "package-lock.json"
      # add this file so edits to the workflow can retrigger if needed
      - ".github/workflows/roadmap.yml"

permissions:
  issues: write      # create/update issues & milestones
  contents: read

concurrency:
  group: "roadmap-sync-${{ github.ref }}"
  cancel-in-progress: true

env:
  # If you ever move the Node project under a subfolder (e.g. tools/roadmap-sync),
  # set ROADMAP_WORKDIR to that folder and this workflow will still work.
  ROADMAP_WORKDIR: .
  NODE_VERSION: "20"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify roadmap files exist
        run: |
          set -euo pipefail
          test -f .github/roadmap/roadmap.yaml || { echo "::error::.github/roadmap/roadmap.yaml not found"; exit 1; }
          test -f scripts/sync-roadmap.js || { echo "::error::scripts/sync-roadmap.js not found"; exit 1; }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            ${{ env.ROADMAP_WORKDIR }}/package-lock.json

      - name: Install deps (npm ci with fallback)
        working-directory: ${{ env.ROADMAP_WORKDIR }}
        run: |
          set -euo pipefail
          if [ ! -f package.json ]; then
            echo "::error::package.json not found in $PWD (ROADMAP_WORKDIR='${{ env.ROADMAP_WORKDIR }}')"
            exit 1
          fi
          npm ci || { echo "npm ci failed; attempting to (re)create lockfile..."; npm i --package-lock-only && npm ci; }

      - name: Sync roadmap (labels, milestones, issues)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euo pipefail
          node scripts/sync-roadmap.js

      - name: Summary
        if: ${{ success() }}
        run: |
          echo "✅ Roadmap sync completed for ${{ github.repository }}"
