name: Sync Roadmap → Issues & Milestones

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Parse roadmap and simulate changes (no writes)"
        type: boolean
        default: false
  push:
    branches: [ main ]
    paths:
      - ".github/roadmap/roadmap.yaml"
      - "scripts/sync-roadmap.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/roadmap.yml"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/roadmap/roadmap.yaml"
      - "scripts/sync-roadmap.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/roadmap.yml"

permissions:
  issues: write          # create/update issues, milestones, and labels
  contents: read
  metadata: read

concurrency:
  group: "roadmap-sync-${{ github.ref }}"
  cancel-in-progress: true

env:
  # If you move the Node project under a subfolder (e.g. tools/roadmap-sync),
  # set ROADMAP_WORKDIR to that folder and this workflow will still work.
  ROADMAP_WORKDIR: .
  NODE_VERSION: "20"
  ROADMAP_FILE: ".github/roadmap/roadmap.yaml"

jobs:
  sync:
    runs-on: ubuntu-latest

    # Compute DRY_RUN once, safely, for all event types:
    # - pull_request  → true
    # - workflow_dispatch → uses input
    # - push          → false
    env:
      DRY_RUN: ${{ github.event_name == 'pull_request'
                   && 'true'
                   || (github.event_name == 'workflow_dispatch'
                       && github.event.inputs.dry_run == 'true'
                       && 'true'
                       || 'false') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify roadmap files exist
        shell: bash
        run: |
          set -euo pipefail
          test -f "$ROADMAP_FILE" || { echo "::error::$ROADMAP_FILE not found"; exit 1; }
          test -f "scripts/sync-roadmap.js" || { echo "::error::scripts/sync-roadmap.js not found"; exit 1; }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: |
            ${{ env.ROADMAP_WORKDIR }}/package-lock.json

      - name: Install deps (npm ci with fallback)
        working-directory: ${{ env.ROADMAP_WORKDIR }}
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f package.json ]; then
            echo "::error::package.json not found in $PWD (ROADMAP_WORKDIR='${{ env.ROADMAP_WORKDIR }}')"
            exit 1
          fi
          npm ci || { echo "npm ci failed; attempting to (re)create lockfile..."; npm i --package-lock-only && npm ci; }

      - name: Sync roadmap (labels, milestones, issues)
        id: sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ROADMAP_FILE: ${{ env.ROADMAP_FILE }}
          DRY_RUN: ${{ env.DRY_RUN }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p build
          echo "Event: ${{ github.event_name }} | DRY_RUN=${DRY_RUN}"
          # The script should read DRY_RUN (true/false) from env and avoid writes when true.
          node scripts/sync-roadmap.js 2>&1 | tee build/roadmap-sync.log

      - name: Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## Roadmap sync"
            echo ""
            echo "- Repository: **${{ github.repository }}**"
            if [ "${{ env.DRY_RUN }}" = "true" ]; then
              echo "- Mode: **DRY RUN** (no writes)"
            else
              echo "- Mode: **APPLY**"
            fi
            echo "- Roadmap file: \`${{ env.ROADMAP_FILE }}\`"
            echo "- Event: \`${{ github.event_name }}\`"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-sync-logs
          path: build/roadmap-sync.log
          if-no-files-found: warn
          retention-days: 7
