# .github/workflows/sbom.yml
name: SBOM

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.svg"
  pull_request:
    branches: [ main ]
  schedule:
    # Weekly refresh (Sunday 03:15 UTC)
    - cron: "15 3 * * 0"

permissions:
  contents: read

jobs:
  repo-sbom:
    name: Generate SBOM (repo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Syft
        uses: anchore/syft-action/setup-syft@v1

      - name: Create CycloneDX (repo)
        run: |
          syft dir:. -o cyclonedx-json=sbom.cdx.json

      - name: Create SPDX (repo)
        run: |
          syft dir:. -o spdx-json=sbom.spdx.json

      - name: Upload SBOM artifacts (repo)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-repo-${{ github.sha }}
          path: |
            sbom.cdx.json
            sbom.spdx.json
          if-no-files-found: error
          retention-days: 14

  image-sbom:
    name: Generate SBOM (image)
    runs-on: ubuntu-latest
    needs: repo-sbom
    if: |
      hashFiles('Dockerfile') != '' || hashFiles('docker/Dockerfile') != ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Dockerfile path
        id: df
        run: |
          if [ -f Dockerfile ]; then
            echo "path=Dockerfile" >> $GITHUB_OUTPUT
          elif [ -f docker/Dockerfile ]; then
            echo "path=docker/Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "No Dockerfile found" >&2
            exit 1
          fi

      - name: Build image (local)
        run: |
          IMAGE_NAME=kfm-sbom:${{ github.sha }}
          docker build -f "${{ steps.df.outputs.path }}" -t "${IMAGE_NAME}" .

      - name: Set up Syft
        uses: anchore/syft-action/setup-syft@v1

      - name: Create CycloneDX (image)
        run: |
          IMAGE_NAME=kfm-sbom:${{ github.sha }}
          syft "${IMAGE_NAME}" -o cyclonedx-json=sbom.image.cdx.json

      - name: Create SPDX (image)
        run: |
          IMAGE_NAME=kfm-sbom:${{ github.sha }}
          syft "${IMAGE_NAME}" -o spdx-json=sbom.image.spdx.json

      - name: Upload SBOM artifacts (image)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-image-${{ github.sha }}
          path: |
            sbom.image.cdx.json
            sbom.image.spdx.json
          if-no-files-found: error
          retention-days: 14
