name: STAC Badges (Live)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron:  "17 3 * * *"   # daily at 03:17 UTC

permissions:
  contents: read
  pages: write        # to deploy GitHub Pages
  id-token: write     # required by actions/deploy-pages

concurrency:
  group: "stac-badges"
  cancel-in-progress: false

jobs:
  build-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate badge endpoints (Shields JSON)
        run: |
          python scripts/update_badges.py
        shell: bash

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build-badges
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
